### ISSUE TITLE
Availability of CLI via Homebrew

### ISSUE THREAD

**Issue by andrepoleza** [apache/incubator-openwhisk#1064]
Hello!

I've read the documentation and became (more) interested in OpenWhisk, but I've notice that the CLI isn't published on Homebrew... Is there a reason to not be there?

**Comment by csantanapr** [comment]
Hi @andrepoleza for your interest in OpenWhisk.
We have no specific reason why the CLI is not available thru Homebrew.
I think homebrew is a good way of installing dev tools, and it could be a good vehicle to distribute the CLI.

Like anything it would take effort to get it done and also maintain it current (automation CI/CD).

We also need to do some bit of research on how to handle, nightly publish vs. a stable build with the current situation that the CLI doesn't have a semantic version only a hash or build id (i.e. date stamp)

I think after we figured out this we could also potentially offer the CLI thru other package manager (i.e. npm install -g whisk-cli)

I will keep the issue open to keep this a a enhancement request.

**Comment by andrepoleza** [comment]
Good to know! I've never thought about the semantic version and its impact on availability on Homebrew. I just think that distributing the CLI through a broader package manager would benefit OpenWhisk in several ways, because although npm and pip are stable/popular not every (potential) developer uses them.

Anyway, I'll be happy when OpenWhisk reaches Homebrew. 😃

**Comment by jthomas** [comment]
I did an experiment with exposing the CLI through Homebrew recently.
https://github.com/jthomas/homebrew-tools/blob/master/wsk.rb

It worked perfectly although this file now fails the checksum test because the Go CLI has been updated. 

If we could work out how to trigger building this file when the Go CLI changes, you can just drop that repo in the OpenWhisk org and it'll work.

**Comment by dubeejw** [comment]
@jthomas, we could create the needed file during the CLI build, and add the required checksum during that process as well.

**Comment by jthomas** [comment]
That would be awesome.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #153](https://github.com/apache/incubator-openwhisk-cli/issues/153) via [**ZenHub**](https://www.zenhub.com/)
