### ISSUE TITLE
bashauto sdk go-cli autocomplete doesn't work for me

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#1086]
## Environment details:
- Mac El Capitan 10.11.6
- iTerm2 3.0.7
- bash terminal

```
$ wsk property get
whisk API host      openwhisk.ng.bluemix.net
whisk API version       v1
whisk namespace     csantana@us.ibm.com_openwhisk
whisk CLI version       2016-08-10T15:49:14+00:00
whisk API build     2016-08-12T07:58:09Z
whisk API build number  whisk-build-172
```
## Steps to reproduce the issue:

🚀  $ `wsk sdk install bashauto`
The bash auto-completion script (wsk_cli_bash_completion.sh) is installed in the curent directory.
To enable command line completion of wsk commands, source the auto completion script into your bash environment
🚀  $ `source wsk_cli_bash_completion.sh`
Type `wsk action` and type the TAB key you see the message "_get_comp_words_by_ref: command not found " and new line
🚀  $ wsk action -bash: _get_comp_words_by_ref: command not found  

Here are my environment variables in case is useful for troubleshooting

```
$ env
MANPATH=/Users/csantanapr/.nvm/versions/node/v6.4.0/share/man:/usr/local/share/man:/usr/share/man:/opt/X11/share/man:/usr/local/MacGPG2/share/man:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man
TERM_PROGRAM=iTerm.app
WSK_HELLO=action invoke /whisk.system/samples/echo -p message hello --blocking --result
ANDROID_HOME=/Users/csantanapr/Library/Android/sdk
NVM_CD_FLAGS=
TERM=xterm-256color
SHELL=/bin/bash
CLICOLOR=1
TMPDIR=/var/folders/dx/cb6bdd2s5375fgpgzjrjc69h0000gn/T/
DOCKER_HOST=tcp://192.168.99.100:4243
NVM_PATH=/Users/csantanapr/.nvm/versions/node/v6.4.0/lib/node
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.2a1OetX74N/Render
TERM_PROGRAM_VERSION=3.0.7
OLDPWD=/var/folders/dx/cb6bdd2s5375fgpgzjrjc69h0000gn/T/tmp.0AlGsbvg
TERM_SESSION_ID=w1t0p1:2308A59F-B9AB-4B9E-B73D-ED93EDA075BE
ANT_HOME=/Applications/apache-ant-1.9.6
NVM_DIR=/Users/csantanapr/.nvm
USER=csantanapr
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.uVmpkvZZWb/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/Users/csantanapr/bin:/Users/csantanapr/.nvm/versions/node/v6.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Applications/IBM/MobileFirst-CLI:/Applications/apache-ant-1.9.6/bin:/Users/csantanapr/Library/Android/sdk/platform-tools:/Users/csantanapr/Library/Android/sdk/tools:/Users/csantanapr/dev/cordova/cordova-coho
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
PWD=/Users/csantanapr
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
LANG=en_US.UTF-8
ITERM_PROFILE=Default
XPC_FLAGS=0x0
ITERM_ORIG_PS1=\[\033[1;35m\]\w\[\033[0;32m\]$(git_branch)\[\033[1;37m\]\n🚀  $
PS1=\[\033[1;35m\]\w\[\033[0;32m\]$(git_branch)\[\033[1;37m\]\n🚀  $
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/csantanapr
STUDIO_JDK=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk
ITERM_PREV_PS1=\[
\]\[\033[1;35m\]\w\[\033[0;32m\]$(git_branch)\[\033[1;37m\]\n🚀  $ \[\]
ITERM_SESSION_ID=w1t0p1:2308A59F-B9AB-4B9E-B73D-ED93EDA075BE
LOGNAME=csantanapr
NVM_BIN=/Users/csantanapr/.nvm/versions/node/v6.4.0/bin
GOPATH=/Users/csantanapr/go
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
OPENWHISK_HOME=/Users/csantanapr/dev/whisk/git/openwhisk
DISPLAY=/private/tmp/com.apple.launchd.ff1RHSG7da/org.macosforge.xquartz:0
WSK_LIST=package list /whisk.system
_=/usr/bin/env
```

PS: By the way I not trilled with the current UX of `bashauto` install, we should improve on it by having a way to put the content of wsk_cli_bash_completion.sh into STDOUT this way doesn't generate files for the user and easier to script (i.e. `source $(wsk sdk install bashauto)`)

**Comment by csantanapr** [comment]
@dubeejw @mdeuser any ideas what's could be wrong here?

**Comment by rabbah** [comment]
+1 to generating bash auto conf to stdout. Could add -o  to write it to a file.

**Comment by csantanapr** [comment]
personal preference is by default to do STDOUT always, to have an option to output to a file, not necessary, user can always redirect the output to a file.

**Comment by csantanapr** [comment]
I suspect (i.e. Goole and StackOverFlow 😸 ) I need to install `bash-completion` but I don't see it in the help as a requirement, maybe script can be smart enough to tell me when I source it

**Comment by csantanapr** [comment]
Workaround at least for Mac is install `bash-completion`, don't know for Linux this is something that has a good chance to be already installed
```
🍔  $ brew install bash-completion
==> Downloading https://homebrew.bintray.com/bottles/bash-completion-1.3_1.el_capitan.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring bash-completion-1.3_1.el_capitan.bottle.1.tar.gz
==> Caveats
Add the following lines to your ~/.bash_profile:
  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
  fi

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/bash-completion/1.3_1: 188 files, 605.9K
🍔  $   if [ -f $(brew --prefix)/etc/bash_completion ]; then
>     . $(brew --prefix)/etc/bash_completion
>   fi
🍔  $ cd
🍔  $ source wsk_cli_bash_completion.sh
🍔  $ wsk action
create  delete  get     invoke  list    update
```

**Comment by mdeuser** [comment]
Apparently, bash must be at version >= 4.1 for bash-completion to work.  Docker CLI uses Cobra to generate it's bash-completion script as well.  For Mac, they recommend installing manually installing bash-completion as you mentioned above via `brew install bash-completion` since Mac currently ships bash version 3.2
https://docs.docker.com/compose/completion/

Most recent Linux distributions should have the correct version of bash.

**Comment by csantanapr** [comment]
Thanks @mdeuser 
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```
It looks Mac El Capitan version is 3.2 lower than 4.1

**Comment by csantanapr** [comment]
For those that want to edit their `~/profile` and `~/bashrc`
He is the workaround that I have for now
```
pushd $(mktemp -d) > /dev/null && wsk sdk install bashauto > /dev/null && source wsk_cli_bash_completion.sh && popd > /dev/null
```

**Comment by csantanapr** [comment]
labeling documentation to use issue to document the feature and requirements
1. document the usage of `wsk install sdk bashauto`
2. document for Linux to use bash 4.1 or higher
3. document for Mac if using bash less than 4.1 to install bash-completion via brew `brew install bash-completion`

**Comment by csantanapr** [comment]
This is now fixed
