### ISSUE TITLE
wsk activation poll <id>

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#1201]
We currently implement `wsk activation poll` as a console view that shows all new activations. It is sometimes useful to implement `wsk activation poll <id>` to wait for a particular activation and retrieve its result.

This could be useful as a standalone command or as part of `wsk action invoke --blocking` to retrieve the action result for long actions (more than 1 minute).

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #152](https://github.com/apache/incubator-openwhisk-cli/issues/152) via [**ZenHub**](https://www.zenhub.com/)
