### ISSUE TITLE
Improve UX to install/setup CLI autocomplete

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#1221]
Today to setup autocomplete the command `wsk sdk install bashauto`

```
$ wsk sdk install bashauto
The bash auto-completion script (wsk_cli_bash_completion.sh) is installed in the curent directory.
To enable command line completion of wsk commands, source the auto completion script into your bash environment
```

creates a file that user will need to source/execute.

This doesn't seem like a good UX in IMHO.
To setup using .bashrc or .profile shell configurations it becomes cumbersome like

```
pushd $(mktemp -d) > /dev/null && wsk sdk install bashauto > /dev/null && source wsk_cli_bash_completion.sh && popd > /dev/null
```

A better approach is to print to STDOUT the content of this file
Then the setup in .bashrc or .profile becomes

```
eval "$(wsk sdk install bashauto)"
```

This issue is a requirement to STOP creating the file wsk_cli_bash_completion.sh, and instead the command `wsk sdk install bashauto` should print to STDOUT the content.

AFTER the wsk CLI is updated then a command like `eval "$(wsk sdk install bashauto)"` will work

**Comment by dubeejw** [comment]
Your command to setup auto-completion isn't working for me.

**Comment by dubeejw** [comment]
@csantanapr, when I try to do tab completion with your above command, I get this error: ```-bash: _get_comp_words_by_ref: command not found```.

**Comment by dubeejw** [comment]
@csantanapr, it works after installing bash completion which is outlined here: http://davidalger.com/development/bash-completion-on-os-x-with-brew/.

**Comment by dubeejw** [comment]
@csantanapr, it works after installing bash completion, and restarting the terminal. I followed these directions: http://davidalger.com/development/bash-completion-on-os-x-with-brew/.

**Comment by dubeejw** [comment]
After closing the terminal, auto-complete is gone.

**Comment by csantanapr** [comment]
@dubeejw yes I and @mdeuser are already aware about the requirement to install bash-completion on mac see here: https://github.com/openwhisk/openwhisk/issues/1086#issuecomment-245281821

If you close your terminal will not persist, this is why you need to put in your init scripts, so every time you open a new terminal window the autocomplete lines and it get's setup

**Comment by dubeejw** [comment]
After installing bash-completion I can just run ```source wsk_cli_bash_completion.sh``` to get auto completion to work. I'm not sure i understand what the command you posted does.

**Comment by csantanapr** [comment]
@dubeejw I think there is disconnect in communication, I updated the original comment at the top of the issue to make the requirement. clear.

We need to change the wsk cli first.

>This issue is a requirement to STOP creating the file wsk_cli_bash_completion.sh, and instead the command `wsk sdk install bashauto` should print to STDOUT the content.
AFTER the wsk CLI is updated then a command like `eval "$(wsk sdk install bashauto)"` will work

**Comment by rabbah** [comment]
Should document in docs/cli.md.
Also need to remove this:

**Comment by mdeuser** [comment]
@csantanapr - so that the cli does not break it's existing syntax, what do you think about adding a flag to the command to redirect the output to stdout (ie. `wsk sdk install bashauto --stdout`) ?

**Comment by csantanapr** [comment]
@rabbah that reminded me, that [this](https://github.com/apache/incubator-openwhisk/blob/master/tools/vagrant/Vagrantfile#L158) also needs to be updated.

**Comment by csantanapr** [comment]
@mdeuser since is currently not mentioned in the docs, I think is low risk if we change the API on the syntax

**Comment by mdeuser** [comment]
yes, it's probably lightly used.  would like some way to notify downstream folks of the change though. :-)

**Comment by bpoole16** [comment]
@mdeuser @csantanapr Is the consensus that we should replace existing functionality or implement the `--stdout` along side of existing functionality?

**Comment by mdeuser** [comment]
replace - but need to make sure there's doc somewhere to describe this behavior change.. certainly in the command help
