### ISSUE TITLE
Consider supporting third-party identity providers

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk#1247]
Without too much effort, OpenWhisk could support third-party identity management providers, such as github, google, etc. The architecture, in sketch, for this would be:

`wsk login --provider github`

The CLI then asks the user to identify with github, and acquires an oauth `code`. The CLI passes this `code` to the backend, which then asks github to exchange it for an `access_token`. The backend next uses this token to acquire the user's immortal profile identifier (e.g. "starpit" for me, on github). Finally, the backend passes this identified user's auth_key back to the CLI client.

The attached gif illustrates an implementation of this, where the backend has been stubbed to only do the relevant bits, and the CLI has been mocked to only do the login bit.

![whisk github cli login](https://cloud.githubusercontent.com/assets/4741620/18455942/294a6a8c-791b-11e6-9dd4-2f91b8f35d61.gif)

**Comment by starpit** [comment]
![whisk gmail cli login](https://cloud.githubusercontent.com/assets/4741620/18457505/6d83b4a4-7927-11e6-9f3a-03e49bf17bb8.gif)

**Comment by starpit** [comment]
google login, too

![whisk gmail cli login](https://cloud.githubusercontent.com/assets/4741620/18457506/7300d36c-7927-11e6-80f9-3f10c23cf99c.gif)

**Comment by starpit** [comment]
here is my code: https://github.com/starpit/openwhisk-oauth-login

i think only the fake_backend and fake_wsk are throwaways. the two files under lib/ service the client and server sides of this support. written in node.js, sorry, but it's not a huge amount of code to port over to go and scala.

the conf/ needs to be updated, according to the README, to install your own client_id and client_secrets for the identity providers.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #151](https://github.com/apache/incubator-openwhisk-cli/issues/151) via [**ZenHub**](https://www.zenhub.com/)
