### ISSUE TITLE
Include CLI Build Information in content.json

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk#1309]
In order to supply CLI build/version information to consumers of the packaged CLI, the content.json file generated in the build process should contain the following information: 

```
"cli": {
  "version": "1.0.0",
  "build": "whisk-build-531"
  "date": "2016-09-21T07:55:05Z"
}
```

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #149](https://github.com/apache/incubator-openwhisk-cli/issues/149) via [**ZenHub**](https://www.zenhub.com/)
