### ISSUE TITLE
CLI bash auto complete should add space at the end of a completed command

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#1323]
The CLI provides a bash auto completion profile but the completion does not add a space at the end of a completed command. This is not consistent with usually shell completion.

**Comment by dubeejw** [comment]
The Bash auto-completion script is generated by a third-party package called Cobra. We may have to contribute this change to Cobra, and get legal clearance for the latest version.

**Comment by rabbah** [comment]
Linking to feature request https://github.com/spf13/cobra/issues/371.

**Comment by rabbah** [comment]
@dubeejw do you have any input on this comment? https://github.com/spf13/cobra/issues/371#issuecomment-267333345 Since you and @mdeuser did this you might be better than me.

**Comment by csantanapr** [comment]
This works fine on Linux/Unix, the problem of no inserting a space is on Mac from what I can tell

On Mac the `[ $(type -t compopt) = "builtin" ]` will be false in [1]
and will run `complete` with `-o nospace`

I remove the `-o nospace` and re ran the script, and spaces problems is now fix.

[1] https://github.com/spf13/cobra/blob/master/bash_completions.go#L285
