### ISSUE TITLE
Run OpenWhisk on Kubernetes

### ISSUE THREAD

**Issue by 486** [apache/incubator-openwhisk#1402]
Hi,

Are there any plans to run the whole OpenWhisk stack on a container orchestrator, i.e. Kubernetes? I would love that.

**Comment by animeshsingh** [comment]
No concrete plans yet, but its one of those items which we have started investigating as something we want to be done

**Comment by krook** [comment]
I've heard this question asked by several members of the community when they hear about OpenWhisk. Sounds like a good way to run the underlying services across a fabric of resources in what's becoming the industry standard way to orchestrate containers of services.

**Comment by 486** [comment]
Exactly my thoughts. We move all our current applications to OpenShift (which is Kubernetes-based). For future developments it would be desirable to have a Serverless framework like OpenWhisk available. This would require OpenWhisk to run all its core components in containers (you cannot install anything on the underlying hosts) and then have access to the Kubernetes API to schedule additional containers as needed.

I researched Serverless frameworks for Kubernetes but there is nothing that looks like it has enough features and long-term support. Meanwhile DC/OS offers the Gestalt framework as an emerging, first-class plugin for Serverless computing.

**Comment by animeshsingh** [comment]
"This would require OpenWhisk to run all its core components in containers (you cannot install anything on the underlying hosts) and then have access to the Kubernetes API to schedule additional containers as needed." - Exactly, this is going to be a shift in the current design and we are definitely investigating it. We have initially looked at container orchestrators last year, but the milliseconds response time which we needed wasn't being satisfied at the time, and we are revisiting them again. 

As and when we plan it, it will roll out as part of the Multi-cloud Whisk umbrella
https://developer.ibm.com/openwhisk/2016/08/08/multicloud-openwhisk-build-a-distributed-openwhisk-deployment-on-openstack

**Comment by baldwinSPC** [comment]
@animeshsingh we ([stackpoint.io](https://stackpoint.io)) would be interested in chatting about how we can help enable a multi-cloud openwhisk story. happy to chat via DM on twitter ([@baldwinmathew](https://twitter.com/baldwinmathew))

**Comment by baldwinSPC** [comment]
@krook we, too, consistently hear this across our 6K+ community of Kubernetes users. I imagine K8S support would drive heavy adoption.

**Comment by animeshsingh** [comment]
@baldwinSPC Sure. I will reach out on twitter

**Comment by mrutkows** [comment]
@baldwinSPC Looks like k8s is getting started... see Apache OW "dev" list for discussion...
https://lists.apache.org/thread.html/66b2111f8edb4a44466728d697c735f549971909600a02f1b585a9e7@%3Cdev.openwhisk.apache.org%3E

This issue was cited by Rodric.  Feel free to jump in on the "dev" list conversation and add your thoughts there. Anyone can post (and subscribe) its an open forum.

**Comment by krook** [comment]
@486 @mrutkows @animeshsingh @baldwinSPC I created a [proposal page on the Apache wiki](https://cwiki.apache.org/confluence/display/OPENWHISK/OpenWhisk+on+Kubernetes) to help create a formalized design around this. There's also now [a Slack channel](https://openwhisk-team.slack.com/messages/kubernetes/) to discuss.

**Comment by baldwinSPC** [comment]
@krook Great. Could I get an invite to the Slack channel, too, please?

**Comment by rabbah** [comment]
It's self-serve: http://slack.openwhisk.org

**Comment by baldwinSPC** [comment]
@rabbah awesome. thanks.

**Comment by rabbah** [comment]
See https://github.com/apache/incubator-openwhisk-deploy-kube.
