### ISSUE TITLE
CLI to provide a way to distinguish parameters when using a feed action

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#1406]
Currently the `--param` behaves differently when using a feed `--feed` when creating a trigger using `wsk trigger create ...`

For example today user use the parameter trigger_payload to set the default parameters to be pass to the rules and actions when the trigger fire. But user can't see what the values are set or update them.

Proposed 
1. we use `--param` always to mean the parameters saved in the trigger document. 
2. we introduce new argument flag `--paramFeed`  to mean a parameter to be pass to the feed action

This way user can create a trigger using a feed action like

```
wsk trigger create periodic --feed /whisk.system/alarms/alarm —paramFeed cron '*/20 * * * * *' --param name Odin --param place Asgard
```

In this case the parameters `name` and `place` will be saved on the trigger  where user can see them via `wsk trigger get` and updated them or add to them via `wsk trigger update`

And cron would be a parameter for the feedaction to configure the feed provider.

**Comment by cfjedimaster** [comment]
Query - would this cover getting details for a cron trigger?

**Comment by csantanapr** [comment]
@cfjedimaster or there could a different design implementation, on having the CLI query the backend service provider for the current configuration.

Either way, CLI user can retrieve the cron syntax that was originally used to create the trigger.

**Comment by csantanapr** [comment]
no longer applicable
