### ISSUE TITLE
Runtimes may accept different parameter lengths

### ISSUE THREAD

**Issue by paulcastro** [apache/incubator-openwhisk#1426]
JS and Swift runtimes have different behaviors when passed "large" parameters like a Base64 encoded string.  We need to understand the behavior and the causes of the limitations.  For example, in Python the subprocess module has limits on argument size.

**Comment by rabbah** [comment]
There is a canonical test on that all the runtimes pass today for ensuring consistent behavior. There is indeed a limit when passing the JSON input via the command line which should be addressed in the runtime directly.
