### ISSUE TITLE
Feature request: get partial action information

### ISSUE THREAD

**Issue by psuter** [apache/incubator-openwhisk#1454]
Our current endpoint for retrieving action information is:  `/namespaces/{namespace}/actions/{actionName}`

and [according to the OpenAPI specification](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/openwhisk/openwhisk/master/core/controller/src/main/resources/whiskswagger.json#!/Actions/getActionByName) offers no filtering.

We have been supporting larger action bodies, first for Java, then for NodeJS. In the current situation, a user with a 10M NodeJS action cannot retrieve the annotations attached to the action without downloading the entire action, which is problematic.

There are at least three viable solutions:
1. Do not reflect binary/large `exec` bodies in the returned payload unless requested explicitly (e.g. add a `fullExec` flag defaulting to `false`). This breaks backwards compatibility very slightly, but I think it's still safe to assume no one is relying on the current behavior (for binary `exec.code` values).
2. Add a flag to mark that `exec` is not required in the response (e.g. `meta`, defaults to `false`). Fully backwards-compatible.
3. Embrace annotations as entities on their own, add an endpoint:  `/namespaces/{namespace}/actions/{actionName}/annotations` which only supports `GET` as a first step.

There are of course many variations of the above. Thoughts?

**Comment by starpit** [comment]
i can see wanting to fetch exec.code only if !exec.binary. some sort of execUnlessBinary. editors would behave in this fashion.

**Comment by rabbah** [comment]
once exec is an attachment then i envision fetching it explicitly.

**Comment by rabbah** [comment]
This is now possible - the "code" is excluded from the action response unless explicitly requested.
