### ISSUE TITLE
Renaming entities

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#1461]
The ability to rename entities is a fairly standard user expectation that we want to be able to accommodate, in the UI and elsewhere.

With current API this is performed via a `get`, `put` and `delete` to essentially copy and delete - partly because of the underlying data store model. The CLI does not offer `renaming` but does offer copy and delete.

This was a requested feature once and opening the issue to record the request for future potential enhancements to the CLI or API.

**Comment by csantanapr** [comment]
API should offer an API to rename entity, without the need of copy, fetch, or delete

**Comment by rabbah** [comment]
Handling these on the client has been the case for some time and lets the client deal with error scenarios. Closing as won't fix.
