### ISSUE TITLE
CLI should not encode API response schema

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#1489]
I've experience several instances where a schema change in the controller must be reflected in the CLI to properly render the expected output on the command line because the current CLI implementation encodes the types too strictly and *unnecessarily* - in every case I've encountered so far where I've made a schema change to add or remove a field, the CLI would have been just fine if it treated the response from the controller opaquely.

We should refactor the API respond handling in the CLI so that it uses more generic JSON object interface rather than strict types that just get in the way.

I've also found several instances where the CLI is not in sync with the controller (Evidenced by several defects I've opened for these in recent days) and the CLI injects properties that should not exist (and hence confusing).

**Comment by ioana-blue** [comment]
I was bit by this as well and it's not fun. In fact, if I hadn't checked with RR, I would have wasted a lot of time on chasing a "bug" in my code, while it was really a schema change for activations which is not reflected in the cli.

**Comment by dubeejw** [comment]
@ioana-blue, see https://github.com/openwhisk/openwhisk/pull/1566 for the PR that will address your issue.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #148](https://github.com/apache/incubator-openwhisk-cli/issues/148) via [**ZenHub**](https://www.zenhub.com/)
