### ISSUE TITLE
CLI sugar for "the last activation"

### ISSUE THREAD

**Issue by sjfink** [apache/incubator-openwhisk#1498]
Feature request:   in the CLI, introduce the sugar "--last" to mean "the most recent activation id", to reduce the copy-paste of activation ids when developing.

So, for example, ``wsk activation get --last`` and ``wsk activation log --last`` would suffice.

**Comment by rabbah** [comment]
my sugar: `alias lget="list|head -n 2|tail -n 1|awk -F\" \" '{print \$1}'|xargs wsk activation -i get"`

:rofl:

**Comment by rabbah** [comment]
we should do this - it's such a pain on the experience and users have resorted to their own aliases.
this feature should also allow for projection so that one can do `wsk activation get --last duration` to see the duration of the last activation for example.
