### ISSUE TITLE
Support user-defined dependencies for Python actions

### ISSUE THREAD

**Issue by psuter** [apache/incubator-openwhisk#1505]
We need a way to support user-defined dependencies (e.g. `pip` modules) for Python actions.

Potentially, we could at the same time make it possible to upload Python actions built with more than one file.

Experienced Python users should chime in with their desiderata.

**Comment by csantanapr** [comment]
What about choosing between python 2.x and 3.x ?
Would this be something that can be done declarative using one single runtime, meaning create a container with both versions of python an let user choose which one to use.

**Comment by rabbah** [comment]
Related to https://github.com/openwhisk/openwhisk/issues/1184.

**Comment by cclauss** [comment]
https://github.com/openwhisk/openwhisk/pull/1940 seems like a great solution.
