### ISSUE TITLE
Provide ability to pass parameters as a JSON object on the command line

### ISSUE THREAD

**Issue by l2fprod** [apache/incubator-openwhisk#1513]
Just like I can pass the JSON body of a request on the command line with cURL, I'd like to be able to pass the parameters the same way with the OpenWhisk CLI

```
curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' http://localhost:3000/api/login
```

as example:

```
wsk action invoke --body '{"key1": "value1", "object1": { "object1Prop": "anotherValue" }}'
```

**Comment by mbehrendt** [comment]
good point.

should we even allow piping it in, sth like `echo <json> | wsk action invoke myAction'` ?

**Comment by dubeejw** [comment]
You can put the JSON in a file, and pass that filename to the -P flag.

**Comment by l2fprod** [comment]
true but here I don't want to have to create a temp file.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #147](https://github.com/apache/incubator-openwhisk-cli/issues/147) via [**ZenHub**](https://www.zenhub.com/)
