### ISSUE TITLE
create invite to slack button to invite users to openwhisk slack community

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#1538]
serve a form to enter email and send openwhisk slack community link to recipient, of course bootstraping openwhisk.

**Comment by csantanapr** [comment]
I'm a bit lost on what your proposing, people can't go directly to a slack community and ask to be signup or signup directly. Slack only allows to send invitations, so most people what they use is [slackin](https://github.com/rauchg/slackin)  where it's a form, give some stats and basically is an automation of calling the Slack API to send the invite to the person.

I created a Slack team a while back https://openwsk.slack.com should we start using it? and use [slackin](https://github.com/rauchg/slackin) to handle the invites?

We can deploy it and hosted out of url: http://slack.openwhisk.org

slackin it's what we use for the Apache Cordova project http://slack.cordova.io

I think having a Slack Team for OpenWhisk, would be beneficial as it would allows to have multiple channels

We can even create a channel for bluemix, or any other operator that wants a channel.

The current one about #openwhisk on bluemix is in dwopen can still remain
http://slackindwo.mybluemix.net/

**Comment by rabbah** [comment]
slackin requires deployment hence servers. I am suggesting a "serverless " solution. Have an action call the slack API to send invite to interested parties wanting to join the community.

I was not suggesting a new slack community since we already have one - that is orthogonal to this feature proposal.

**Comment by csantanapr** [comment]
OK that's why I was kind of confuse, this website http://slackindwo.mybluemix.net/ do this today for our Slack community.

Are you talking about an implementation like a sample that is generic that people can use serverless instead of slackin to invite people to their Slack team?
For this we need to get to a point that ow can serve html thru the controller or apigw

**Comment by rabbah** [comment]
@csantanapr did this already.
