### ISSUE TITLE
Update CLI to query namespace from API now that is not configured.

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#1586]
Currently user configures the CLI with explicit namespace.
```
wsk property set --auth uuuu:pppp --namespace "csantanapr@cool.com_openwhisk" --apihost openwhisk.ng.bluemix.net 
```
The explicit value of `namespace`  is required for certain use cases and can't be `_`
1. Printing current settings `wsk property get`
  `whisk namespace		csantanapr@cool.com_openwhisk`
2. Managing Trigger Feeds (i.e. Create, Delete a trigger like alarm, cloudant, etc..)
3. APIGW Managements (i.e. Create API, Delete API, List, etc..)

With the new design on API Keys, the `namespace` will not longer be required to be configured since the API Key belongs to a unique and single namespace.
```
wsk property set --auth uuuu:pppp  --apihost openwhisk.ng.bluemix.net 
```

The CLI now for the use cases stated above, will need to do a REST API call to OW, with the auth value and the API should return the namespace value.

This API doesn't exist today and will block this use cases if the user doesn't have a namespace configured locally.

cc @markusthoemmes @dubeejw  @sjfink 

This a proposal alternatives or modifications are welcome

**Comment by markusthoemmes** [comment]
Why is this needed for "Managing trigger feeds"? Which use-case do you have in mind specifically?

**Comment by csantanapr** [comment]
When creating a trigger using a feed like cloudant. The namespace is passed today to the feedaction when it's invoke.
That info is used to identify the trigger, to id the doc in DB, etc..

**Comment by csantanapr** [comment]
Well to identify the trigger, we might not need it anymore, but we use it to make the entry in DB unique and at the same time flexible, by not making the authkey part of the _id

**Comment by markusthoemmes** [comment]
https://github.com/openwhisk/openwhisk/blob/master/tests/src/whisk/core/cli/test/WskBasicUsageTests.scala#L475

This test reads like the CLI does not need provide the namespace to the action, cause its done by the invoker directly. The feeds might be using old legacy which we could update and thus move this use-case of the critical path of this issue?

**Comment by csantanapr** [comment]
@markusthoemmes like you suggested now we could use process.env['__OW_NAMESPACE'] to get the in context namespace value, and do a transition.
Also using the `spaceGuid` from the authkey `spaceGuid:randomKey`

But I think we still need it for use case 1, 3

**Comment by rabbah** [comment]
we can provide `GET /api/v1/namespaces/_/info` to yield the name of the namespace and in the future as suggested by @markusthoemmes include quotas, current throttle limits (there may be more useful info to surface).

**Comment by csantanapr** [comment]
Closing as
1. is cover by issue in cli repo https://github.com/apache/incubator-openwhisk-cli/issues/137
2 and 3 are already resolved by process.env['__OW_NAMESPACE']
