### ISSUE TITLE
Bring Vagrant box on par wrt kernel and security requirements

### ISSUE THREAD

**Issue by domdom82** [apache/incubator-openwhisk#1614]
We tried to delay this step for as long as possible but with the latest merges in security features like

- user namespaces
- pid-limits (needs at least 4.3)
- memory and swap limits (requires cgroup swap limit kernel setting in grub)
- overlay fs with overlay2 on the horizon (overlay2 needs at least 4.0)

we can no longer avoid to change the way we provision the vagrant machine. Main reason for this is that tests for those features would break otherwise.

The current vagrant setup immediately builds and deploys OpenWhisk on `vagrant up`.
However bringing the kernel from 3.13.0-92 (default) to 4.4.0-45 requires a VM restart to load the new kernel before we can deploy. So it can no longer be done with a simple `vagrant up`

There is some hacks going on here: https://www.exratione.com/2014/06/how-to-reboot-a-vagrant-guest-vm-during-provisioning/ but it all looks really ugly.

Alternative approaches:

1. Try another distribution (I tried ubuntu xenial, did not work very well the last time). This has a lot of ramifications:
 - most notably the shift from upstart to systemd
 - vagrant user removed. user "ubuntu" used instead
 - all apt sources need to change from trusty to xenial

2. During provision, add a patch of the kernel and reboot at the end and push the build, deploy and test to a one-off task that runs after reboot. This will require some init script juggling but retain the "vagrant up" - only approach.

3. Leave everything as-is, but don't run tests (which would fail) in the vagrant file. Provide a script to patch the kernel and reboot the VM. Tests must work afterwards. This would break the "vagrant up" - only approach.

**Comment by domdom82** [comment]
@csantanapr @jeremiaswerner @sjfink please provide your input as to how we shall proceed here.

**Comment by csantanapr** [comment]
@domdom82 I propose we go for now with option 3, it will not break `vagrant up`

Add a script that user can run to patch the kernel. And then he will be able to run all the tests.
`vagrant up` doesn't run the tests automatically, only does a build and deploy, no tests.

user can run a single test, a set of tests if they want. 
We can update the doc README to tell them to run the kernel patch script reboot, it will be one time.

Later we there is an image we can use with no problems and new kernel we remove the instructions and the patch script.

**Comment by csantanapr** [comment]
vagrant these days use ubuntu 16 and uses new kernel
```
vagrant@ubuntu-xenial:~/openwhisk$ uname -a
Linux ubuntu-xenial 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
