### ISSUE TITLE
Turn off Kafka topic-auto-create

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk#1625]
I did a change to create all topics needed in Kafka explicitly. The missing bit now is to turn off topic-auto-creation to actually be sure about the topics in Kafka.

Some tests will need reconfiguration due to this.

**Comment by rabbah** [comment]
@dgrove-oss i think your work will close this?

**Comment by dgrove-oss** [comment]
Yes.  I think once #2948 goes in, we should be able to disable topic-auto-create.

**Comment by dgrove-oss** [comment]
Correction, I missed Markus's comment about the test cases.  #2948 will give us the API to create the topics.  We may still have to extend some unit tests to create the synthetic topics they are using.  Shouldn't be that hard to do however.

**Comment by dgrove-oss** [comment]
assign this to me.  I'll take a look after we merge #2991.  I think if we turn off topic auto creation, then we can also avoid needing to pass KAFKA_DEFAULT_REPLICATION_FACTOR and  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR in roles/kafka/tasks/deploy.yml, which will let us kill kafka_replicationFactor from the group_vars/all (as long as we have a definition there, the default value in application.conf will never be used).

**Comment by markusthoemmes** [comment]
This done I believe.
