### ISSUE TITLE
allow wsk activation list with in-package name filters

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk#1635]
right now, the activation list API supports a `name=` filter, but this filter does not allow me to select in-package actions.

```
{ error: 'The query parameter \'name\' was malformed:\nrequirement failed: name [foo/inpackagetest] is not allowed',
code: 75253 }
```

with
```
href: 'https://openwhisk.ng.bluemix.net/api/v1/namespaces/_/activations?name=foo%2Finpackagetest&limit=1&docs=true&since=1481571776281'
```

**Comment by rabbah** [comment]
See https://github.com/apache/incubator-openwhisk/pull/2760#issuecomment-333138595 for a possible solution.

**Comment by rabbah** [comment]
Fixed by #2760.

**Comment by csantanapr** [comment]
Can I do this from CLI now with the new view? 
wsk activation list mypackage/myaction

**Comment by csantanapr** [comment]
Already review #2760 wanted to double check that there no go CLI changes in another PR for this

**Comment by rabbah** [comment]
No cli changes needed.
