### ISSUE TITLE
api-experimental - confusing "delete" step

### ISSUE THREAD

**Issue by jthomas** [apache/incubator-openwhisk#1654]
## Environment details:

[09:28:12 ~]$ wsk property get
whisk auth		xxx
whisk API host		openwhisk.ng.bluemix.net
whisk API version	v1
whisk namespace		_
whisk CLI version	2016-12-13T10:40:19+00:00
whisk API build		2016-12-13T10:49:44Z
whisk API build number	whisk-build-2366

## Steps to reproduce the issue:

Here's a command to create an API route:
```
wsk api-experimental create /api/weather GET weather
```

I would expect to be able to issue the same parameters to remove the route.

```
$ wsk api-experimental delete /api/weather GET
error: 'GET' must begin with '/'.
Run 'wsk --help' for usage.
```

It appears I need to use the following commands. 
```
wsk api-experimental delete / /api/weather GET
```

Can we change the `delete` command to be consistent with `create`?

**Comment by mdeuser** [comment]
@joachimvaldez - this should only affect the CLI.

**Comment by rabbah** [comment]
experimental is gone.
