### ISSUE TITLE
Add a command to return the version of the CLI

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk#1677]
There is no available command to `wsk` that returns the version of the CLI installed.

**Comment by rabbah** [comment]
Try: `wsk property get -h`

**Comment by cfjedimaster** [comment]
Confirmed this works: wsk property get --cliversion

However, this should be exposed on the top level help screen. It is a pretty common feature (imo) should be made more evident.

**Comment by rabbah** [comment]
Sure `wsk --version` makes sense.

**Comment by daisy-ycguo** [comment]
@lzbj I tested your PR. Yet `wskdeploy version` didn't response what I expected.
`openwhisk-wskdeploy version is unset--unset`

Let's look at it together tomorrow. Thank you for your PR.

**Comment by dubeejw** [comment]
Looks like there is two different converstations going on here. One about the wsk CLI and the other about wskdeploy.

**Comment by rabbah** [comment]
This issue should address `wsk` not `wsk deploy`.

**Comment by daisy-ycguo** [comment]
Sorry, comment wrong place.

**Comment by lzbj** [comment]
@rabbah, is this one we need fix or not?

**Comment by rabbah** [comment]
We should add wsk --version and it wild be great to also add an auto update feature as well or at least notify the user there is a newer version.

**Comment by markusthoemmes** [comment]
We'll need to improve our build processes to not create a new CLI version if no code has changes, as the CLI is currently versioned by date and you don't want to notify users everytime a new OpenWhisk is deployed.

**Comment by rabbah** [comment]
Agree - the date was more intended to show the build date, not the actual version. We could adopt semantic versioning and do it manually to get going.

**Comment by lzbj** [comment]
manually you mean we pass in build number as arguments everytime we updated code?

**Comment by dubeejw** [comment]
A new CLI is not created if the code has not been changed as long as there is already a Docker container of the built CLI in the cache.

**Comment by lzbj** [comment]
Ok, got it.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #146](https://github.com/apache/incubator-openwhisk-cli/issues/146) via [**ZenHub**](https://www.zenhub.com/)
