### ISSUE TITLE
better error message for authorization failure

### ISSUE THREAD

**Issue by sjfink** [apache/incubator-openwhisk#1684]
```wsk action create --sequence cats /whisk.system/utils/echo,/someNamespace/list-documents -p dbname cats
error: Unable to create action: The supplied authentication is not authorized to access this resource. (code 6035175) 
```

Whenever we report an error message about "this resource",  we should instead explicitly name the resource that caused the problem in the error message.

Additionally, if "this resource" does not exist, we should produce an error message saying so explicitly.

**Comment by jthomas** [comment]
This also happens when creating actions with the same name as a trigger or rule and vice-versa.
