### ISSUE TITLE
cannot use node-rdkafka - missing sasl libs

### ISSUE THREAD

**Issue by jberstler** [apache/incubator-openwhisk#1687]
In trying to use the NPM package [node-rdkafka](https://github.com/Blizzard/node-rdkafka) to post messages to a Message Hub instance from a NodeJS action, user @glikson was unable to successfully authenticate, likely due to the sasl system libraries not being available in the NodeJS runtime.

The next most reasonable course of action was to use [message-hub-rest](https://www.npmjs.com/package/message-hub-rest) which relies on a soon-to-be-deprecated REST interface.

Please consider adding the appropriate sasl libraries to the NodeJS runtime in order to support this scenario.

**Comment by rabbah** [comment]
Issue moved to [apache/incubator-openwhisk-runtime-nodejs #11](https://github.com/apache/incubator-openwhisk-runtime-nodejs/issues/11) via [**ZenHub**](https://www.zenhub.com/)
