### ISSUE TITLE
Instrument API GW action logs for log parser consumption

### ISSUE THREAD

**Issue by mdeuser** [apache/incubator-openwhisk#1695]
- Instrument the log entries to conform to the other OpenWhisk log entries that are commonly consumable by log parsers such as stashd.

**Comment by rabbah** [comment]
We dont deploy ELK in openwhisk. Can you clarify what the second bullet item means?

**Comment by mdeuser** [comment]
oh yeah.. that's correct.  in openwhisk we just needs to support the common stashd log parsing format that the rest of the openwhisk logs follow.  I'll update description.

**Comment by rabbah** [comment]
@mdeuser @csantanapr done?

**Comment by mdeuser** [comment]
OpenWhisk is moving towards providing a logging SPI.  actions can leverage this forthcoming feature to publish the action logs into the desire log store.  as such, this issue is no longer needed as-is.
