### ISSUE TITLE
Update watson-developer-cloud

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk#1699]
OpenWhisk is using a 1.* version of the watson-developer-cloud package, which is now at 2.*. Please see if you can upgrade to that version.

**Comment by rabbah** [comment]
Issue moved to [apache/incubator-openwhisk-runtime-nodejs #10](https://github.com/apache/incubator-openwhisk-runtime-nodejs/issues/10) via [**ZenHub**](https://www.zenhub.com/)
