### ISSUE TITLE
wsk command error after Mac installation

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk#1709]
This happened lately when I install openwhisk on mac, based on the instruction at https://github.com/openwhisk/openwhisk/blob/master/tools/macos/README.md.
I keep on receiving the following error message when I run any wsk command:
```Get https://192.168.99.100/api/v1/namespaces: x509: cannot validate certificate for 192.168.99.100 because it doesn't contain any IP SANs```
I tried to run the scripts ./tools/macos/tweak-dockermachine.sh and ./tools/macos/tweak-dockerhost.sh, but they did not resolve it.

**Comment by rabbah** [comment]
Are you passing `-i`?

**Comment by houshengbo** [comment]
No, I directly use wsk. Should that behave this way without -i?

**Comment by rabbah** [comment]
Yes. Your local certificate is not trusted if you used the open generated by openwhisk.

**Comment by domdom82** [comment]
Even if it were trusted you can't create certs for IPs. So the part `doesn't contain any IP SANs` alludes to that. So in any case you have to use `-i` for dev envs.

**Comment by domdom82** [comment]
@csantanapr I think that should already be documented, right?

**Comment by csantanapr** [comment]
Don't think is documented for mac use case. 

I know it's documented and already handle for Vagrant as the wsk in the path points to a wrapper that already includes the -i

**Comment by rabbah** [comment]
The documentation for how to use the CLI shouldn't be tied to Vagrant. Is this a better place for it  https://github.com/openwhisk/openwhisk/tree/master/tools/cli?

**Comment by csantanapr** [comment]
I was not implying that this was covered by Vagrant already. 

Was pointing out that mac points to the general setup CLI and that section doesn't mentioned the insecure (-i) yes that the place to documented for all use cases

**Comment by rabbah** [comment]
(More generally there are other bits of the Vagrant doc that should be pulled out, like these two sections: SSL certificate configuration and Adding OpenWhisk users.)

**Comment by csantanapr** [comment]
As always I'm more than happy to review and merge if someone wants to submit a PR. 

This can be tag with a label "easy for noob"
The type of issues that are good for first time contributors or folks trying to get involved

**Comment by rabbah** [comment]
Cross linking for future reference https://github.com/openwhisk/openwhisk/issues/1032.

**Comment by rabbah** [comment]
Now that top level CLI doc exists, should document `-i` there https://github.com/openwhisk/openwhisk/blob/master/docs/cli.md @romankhar FYI.

**Comment by lolstarz** [comment]
I think this issue can be closed as of: https://github.com/apache/incubator-openwhisk/commit/af6b00306f5060cf6abfca2a09ab91c482e8cc1a
