### ISSUE TITLE
Vagrant doc may need update for cloudant setup

### ISSUE THREAD

**Issue by nwspeete-ibm** [apache/incubator-openwhisk#1719]
# Provide credentials for cloudant database with admin permissions
OW_DB=cloudant OW_DB_USERNAME=xxxxx OW_DB_PASSWORD=yyyyyy ./hello

https://github.com/openwhisk/openwhisk/blob/master/tools/vagrant/README.md

should cloudant be Cloudant here? @mdeuser @csantanapr

**Comment by rabbah** [comment]
@nwspeete-ibm yes.

**Comment by csantanapr** [comment]
There was something weird with how to read env variables in Vagrant that I had to use lower case `cloudant` and then exported as upper case `Cloudant` in Vagrant script
```
        if [[ $OW_DB == "cloudant" ]]; then
          export OW_DB="Cloudant"
          export OW_DB_PROTOCOL="https"
          export OW_DB_HOST="$OW_DB_USERNAME.cloudant.com"
          export OW_DB_PORT="443"
        else
          export OW_DB="CouchDB"
          export OW_DB_PROTOCOL=#{ENV['OW_DB_PROTOCOL']}
          export OW_DB_HOST=#{ENV['OW_DB_HOST']}
          export OW_DB_PORT=#{ENV['OW_DB_PORT']}
        fi
```

The docs are correct.
