### ISSUE TITLE
update doc reference.md with redundant digit and alphanumeric

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#1736]
We got feedback from folks trying to translate our docs, questioning about he use of `digit`, since the sentence already contains alphanumeric

https://github.com/openwhisk/openwhisk/blob/master/docs/reference.md#entity-names

So it will go from:
- The first character must be an alphanumeric character, a digit, or an underscore.
- The subsequent characters can be alphanumeric, digits, spaces, or any of the following: _, @, ., -.
The new bullets would look like this:
- The first character must be an alphanumeric character, or an underscore.
- The subsequent characters can be alphanumeric, spaces, or any of the following: _, @, ., -

**Comment by rabbah** [comment]
I checked the doc, I see no references to digit.
