### ISSUE TITLE
LoadBalancer Invoker list should be sorted

### ISSUE THREAD

**Issue by domdom82** [apache/incubator-openwhisk#1784]
Currently, controller shows LB "in flight" list in unordered list:
e.g.

```
[LoadBalancerService] In flight: 64 = [0 -> 12, 5 -> 0, 1 -> 2, 6 -> 0, 9 -> 0, 2 -> 1, 7 -> 2, 3 -> 2, 8 -> 40, 4 -> 5]
```

With more than a couple invokers this gets hard to read. The invoker list should be sorted like this:

```
[LoadBalancerService] In flight: 64 = [0 -> 12, 1 -> 2, 2 -> 1, 3 -> 2, 4 -> 5, 5 -> 0, 6 -> 0, 7 -> 2, 8 -> 40, 9 -> 0]
```

Should be an easy one.

**Comment by rabbah** [comment]
@markusthoemmes i think you're doing this as part of the new health monitor hence assigning to you.

**Comment by rabbah** [comment]
@markusthoemmes close?

**Comment by markusthoemmes** [comment]
Done.
