### ISSUE TITLE
CLI should show progress of uploading files

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk#1823]
When uploading a large zip file (and we support up to 48 Megabyte) I get no indication of the progress of my upload. It would be a nice feature to have to show progress like `wget`.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #144](https://github.com/apache/incubator-openwhisk-cli/issues/144) via [**ZenHub**](https://www.zenhub.com/)
