### ISSUE TITLE
Scheduled trigger never stops firing

### ISSUE THREAD

**Issue by andreasnauerz** [apache/incubator-openwhisk#1828]
When following this example here https://github.com/openwhisk/openwhisk/blob/master/docs/packages.md#creating-and-using-trigger-feeds the scheduled trigger never stops firing.

We should add a one-liner to show how to disable the alarm-based trigger again.

**Comment by rabbah** [comment]
@csantanapr @jasonpet move to alarms package?

**Comment by csantanapr** [comment]
Yes move, alarm docs are in it's repo. 

We can add note but it's trivial just delete the trigger to stop it.

**Comment by csantanapr** [comment]
Needs to move to alarms and then update the example doc to use a stopDate when we get that implemented

**Comment by csantanapr** [comment]
In addition to add just a section now on how to stop trigger with using delete and make obvious

**Comment by jasonpet** [comment]
it sounds like the pause lifecycle event is what is wanted here.
