### ISSUE TITLE
Updating a rule changes its status to inactive

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk#1840]
If you edit a rule, it becomes disabled in OpenWhisk. It should not change the status of the rule.

**Comment by dubeejw** [comment]
The behavior described here seems to be originating from the backend not the CLI.

**Comment by rabbah** [comment]
@dubeejw thanks for checking.

**Comment by rabbah** [comment]
This is the location of the inactive state setting for the update https://github.com/openwhisk/openwhisk/blob/master/core/controller/src/main/scala/whisk/core/controller/Rules.scala#L303.

**Comment by markusthoemmes** [comment]
I believe this is leftover from the "locks" we had in place, where you couldn't do anything with a rule if its active.

**Comment by rabbah** [comment]
Indeed. Should updating a rule always put it in active state? (Would be consistent with create/activate.)

**Comment by cfjedimaster** [comment]
I would argue that the status shouldn't change - period. However if you decide to activate it, please make the CLI report this with a message. If a dev forgets the updating will also turn it on, a warning will be helpful.

**Comment by csantanapr** [comment]
I would argue that it's useful for staging or swapping deploying if an user wants to use rules that a rule's active state remains unchange when it's being updated.

**Comment by csantanapr** [comment]
@markusthoemmes @rabbah is this a good candidate for one of you to write some sudo code, for someone to pick up and drive it?

**Comment by jthomas** [comment]
This has hit users using the framework.
https://github.com/serverless/serverless-openwhisk/issues/55

**Comment by zachschultz** [comment]
Running `wsk rule update <ruleName> <trigger> <action> -v` shows a PUT request with the body: `{{"name":"<rule>","status":"","trigger":"/_/<trigger>","action":"/_/<action>"}}`

Even after changing the CLI to send `status: active`, Scala will still return a response that contains an "active" status rule

It looks like here: https://github.com/apache/incubator-openwhisk/blob/master/core/controller/src/main/scala/whisk/core/controller/Rules.scala#L85
that no matter what the status actually is, we just send back an active status in the response, even though that may not be the actual status of the rule.

**Comment by zachschultz** [comment]
Running wsk rule update <ruleName> <trigger> <action> -v shows a PUT request with the body: {{"name":"<rule>","status":"","trigger":"/_/<trigger>","action":"/_/<action>"}}

Even after changing the CLI to send `status: active`, Scala will still return a response that contains an "active" status rule, even though GETing the rule shows that it is still inactive, which pretty much confirms @dubeejw thoughts.

It looks like here: https://github.com/apache/incubator-openwhisk/blob/master/core/controller/src/main/scala/whisk/core/controller/Rules.scala#L85
that no matter what the status actually is, we just send back an active status in the response, even though that may not be the actual status of the rule.

**Comment by rabbah** [comment]
To update the status you must POST to the rule.
