### ISSUE TITLE
Would it be possible to create a release?

### ISSUE THREAD

**Issue by cclauss** [apache/incubator-openwhisk#1880]
https://github.com/openwhisk/openwhisk/releases is empty.  The Mac OSX installer Homebrew will not accept [an installation formula](https://github.com/Homebrew/homebrew-core/pull/9879) on a project that has no releases.  Even if it is release V0.0.1 ;-)

**Comment by rabbah** [comment]
yes we should do that. 

@jeremiaswerner @csantanapr what do you think?

**Comment by rabbah** [comment]
also FYI https://github.com/shaftoe/homebrew-wsk.

**Comment by csantanapr** [comment]
Yes this is good to have in place some time in the future.

Here are some thoughts:
- End user of homebrew should NOT need to compile the `wsk` CLI on their computer
- We should move the CLI to it's own Repository
- We should configure a jenkins server in Apache Infra (OpenWhisk server with alarm) to do nightly releases
  - Create git Tag/Release with something like 1.0.0-dev_$timestamp
  - Compile `wsk` and attached to github release page or add link and host binary some where
- To cut release version, we need to go thru Apache process, cut the version `1.0.0`, vote, create source zip for source release, publish binary and create tag/release github page.
- nightly are easy and schedule and always gives you latest and fresh copy
- voted release take some more effort so they will be release in cadence that allows time for the release cutting process.
- Submit formula to homebrew that relies on the binaries

Looking forward for someone to work on this in some time in the future.

**Comment by csantanapr** [comment]
Hi @cclauss team is working on this CLI source code will be moved out from this repo and binary releases will be posted on another repo openwhisk-cli https://github.com/openwhisk/openwhisk-cli/releases
Once we have more automation then a brew entry can be created
