### ISSUE TITLE
the payload for web-exported invocations are sporadically squashed

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk#1905]
i don't have a lot of helpful data here, yet, but about 1 of every 100 invocations of web-exported actions have their payload disappear. it is unrelated to the size of the payload, even a hundred bytes can fail to make it through.

this is a sporadic problem, as retrying with the same input results in success

it may be even less frequent than the "1 of 100" i quoted above.

**Comment by csantanapr** [comment]
I suspect Cookie Monster 🍪 🍪

**Comment by csantanapr** [comment]
Going to be tricky to find who is eating those bytes. 

Any possible clashing with query parameters?

**Comment by starpit** [comment]
i've already verified that the squashing is unrelated to the size of the normal or cookie payloads. it's pretty weird, and a complete mystery to be, so far.

**Comment by rabbah** [comment]
Does it reproduce with API gw?
Any test cases to try?

**Comment by rabbah** [comment]
Closing as not-actionable.
