### ISSUE TITLE
action containers should also be GC'ed on failed pause()

### ISSUE THREAD

**Issue by bjustin-ibm** [apache/incubator-openwhisk#1915]
#1898 Introduced a change which causes containers which fail an unpause operation (for example, crashed containers) to be immediately GC'ed. However, a similar feature was not added for containers that fail a pause operation.

While you could argue that it shouldn't matter unless/until the container is unpaused, @rabbah pointed out that if the container failed pause, it may actually still be running and could cause unexpected errors. Additionally, GC'ing the container immediately frees a slot in the ContainerPool to make room for a healthy new container.

**Comment by rabbah** [comment]
@markusthoemmes @sven-lange-last is this fixed by the new reactive pool?

**Comment by markusthoemmes** [comment]
Yes, the new pool collects containers on any failure.

**Comment by rabbah** [comment]
Going to close then since we are close to switching implants.
