### ISSUE TITLE
wsk activation poll remove the [ ] 

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#1921]
wsk activation poll formats its output in a way that might be confusing:

```
Activation: hello (ce78012710e04ba79b3881d2575c7e0f)
[
    "2017-02-28T14:47:56.993327423Z stdout: hello world!",
    "2017-02-28T14:47:56.993327523Z stdout: hello again!",
]
```

why show the `[]`?

Further it might be nice to add back the `--strip` option to remove the `date`/`std[out,err]` prefix.
Lastly in the summary, should show/color-code in the header if the activation was a success or not.

**Comment by rabbah** [comment]
`--strip` is now available again.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #143](https://github.com/apache/incubator-openwhisk-cli/issues/143) via [**ZenHub**](https://www.zenhub.com/)
