### ISSUE TITLE
Extend Feed Provider API to include update & status operations?

### ISSUE THREAD

**Issue by jthomas** [apache/incubator-openwhisk#1925]
Once you have registered a trigger with a feed provider, there's no way to retrieve any details about the current trigger feed state. 

For example, with the alarm package, it would be useful to be query the trigger feed to recover the cron value. It would also be nice to have a way to modify feed parameters without having to delete & re-create as this might introduce missed events between the delete finishing and create registered. 

Feed Actions currently supported two operations: `CREATE` and `DELETE`. Could we add `RETRIEVE` and `UPDATE`? 

I could see that you could handle `UPDATE` by issuing another create, without the delete, and expecting providers to handle create requests for existing triggers.

**Comment by bjustin-ibm** [comment]
One proposal is that each feed package could include a "health" or "status" action which, when invoked, returns the kind of information you are asking for.

**Comment by rabbah** [comment]
@csantanapr done?

**Comment by csantanapr** [comment]
Yes done
