### ISSUE TITLE
Async Swift Action and Promise/Future

### ISSUE THREAD

**Issue by JacopoMangiavacchi** [apache/incubator-openwhisk#193]
Current Swift support is limited to synchronous action.  It should be nice to support GCD queue capabilities and implement a Whisk Swift API based on Promise/Future pattern such as BrightFutures https://github.com/Thomvis/BrightFutures

**Comment by markusthoemmes** [comment]
Issue moved to [apache/incubator-openwhisk-runtime-swift #76](https://github.com/apache/incubator-openwhisk-runtime-swift/issues/76) via [**ZenHub**](https://www.zenhub.com/)
