### ISSUE TITLE
Relationship between namespace and user

### ISSUE THREAD

**Issue by pjdurai** [apache/incubator-openwhisk#1931]
Greetings,

Could someone please explain (or point to existing docs) the relationship between namespace and user?

How the authentication key relates these two?
Visibility of entities like actions, triggers etc. ?

Thanks
pj

**Comment by markusthoemmes** [comment]
Hi @pjdurai,
a user is merely a container for API keys at this point. In the system itself it has almost no meaning.

All entitlement/visibility concerns are attached to namespaces. Each user can have access to N namespaces and in the same namespace, different users can see entities from each other.

Consequently API keys are related to namespace access, not the user. For each namespace a user has access to, she also has an API key to access this namespace.

**Comment by pjdurai** [comment]
Thanks for the clarification.

>Each user can have access to N namespaces and in the same namespace, different users can see entities from each other

For the life of me I couldn't figure out how to do this using 'wsk'.
How do I make a AuthKey ('user') work with more than on openwhisk namespace?

thanks
pj

**Comment by rabbah** [comment]
See this https://github.com/openwhisk/openwhisk/issues/1107#issuecomment-280810166 - does that help?

**Comment by markusthoemmes** [comment]
@pjdurai an AuthKey precisely is *not* equal to a user.

One user has multiple AuthKeys, each of which have access to exactly one namespace.
