### ISSUE TITLE
how to ignore some runtimes during travis build?

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#1968]
I'm working on configuring travis integration into [openwhisk-apigateway](https://github.com/openwhisk/openwhisk-apigateway)

I only need the nodejs6 runtime, I want to make builds very fast by ignoring some runtimes like swift3, java, python, 

I have the following line in my `tools/travis/build.sh`
```
./gradlew distDocker -x :core:swift3Action:distDocker -x :core:pythonAction:distDocker -x :core:javaAction:distDocker -x :core:nodejsAction:distDocker
```

This seems to ignore the image build, but then later when I run the ansible deployment
```
$ANSIBLE_CMD wipe.yml
$ANSIBLE_CMD openwhisk.yml
```
It builds the images, so I'm not saving any time.

I'm following same pattern as travis on this repo [tools/travis/build.sh](https://github.com/openwhisk/openwhisk/blob/master/tools/travis/build.sh)

What's the magic bit I'm missing to tell the deployment to ignore these images?

**Comment by markusthoemmes** [comment]
@csantanapr The ansible commands shouldn't build the images. Do you have corresponding log output?

**Comment by csantanapr** [comment]
@markusthoemmes thanks for confirming that there no build during ansible. 
Then it must be the gradlew command, maybe the -x are not working as expected?
Take a look at this log output from my PR
https://travis-ci.org/openwhisk/openwhisk-apigateway/builds/208480259

I can see swift3 images being built

Maybe it's the gradle test command running distDocker as a dependency?

**Comment by markusthoemmes** [comment]
Yes, it's the gradle test command.

**Comment by csantanapr** [comment]
@markusthoemmes ah OK, I think I understand now.

Can I specify from gradle test command to only compile and run the 3 classes that I need for apigw, and nothing else?
Or I'm force to create a gradle task with some includes like this?

```
task testLeanAPIGW(type: Test) {
    include 'whisk.core.cli.test.ApiGwTests'
    include 'whisk.core.apigw.actions.test.*'
    include 'apigw.healthtests.*'
}
```

By the way this will temporary, until we move out all apigw related things out of the core repo.
