### ISSUE TITLE
What does sharing a package actually mean?

### ISSUE THREAD

**Issue by g12megha** [apache/incubator-openwhisk#1996]
What i understood from trying the cli, sharing a package means all users under that namespace have access to it. It doesn't mean that  it is available to all namespaces which are created under that server/host . Please correct me if this is not the case.

**Comment by rabbah** [comment]
that's correct for a private package.
for a public package, it is available to all authenticated users (read and invoke only).

you may want to ask these questions on http://slack.openwhisk.org/.
