### ISSUE TITLE
web actions projecting errors incorrectly when using .json

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#2003]
web action `routemgmt/deleteApi` fails with a promise and result is error message string
```
function main(args){
return Promise.reject("Oh no this is an error, you are our only hope!")
}
```

invoke web action
```
/web/whisk.system/routemgmt/deleteApi.json
```

It returns "application error" and success "false"

```
   "namespace": "whisk.system",
    "name": "deleteApi",
    "version": "0.0.39",
    "subject": "whisk.system",
    "activationId": "12345",
    "start": 1489177986998,
    "end": 1489177987074,
    "duration": 76,
    "response": {
        "status": "application error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": "Oh no this is an error, you are our only hope!"
        }
    },
```

cc @mdeuser

**Comment by rabbah** [comment]
This is working as designed - when an action errors, the expectation is that there's a nested object in the `error` property. We could change the semantics to return the `error` object itself, but it's nuanced: for JSON that will work, for other extensions, it would not. 

Closing as invalid. Reopen if you want to revisit the error handling.
