### ISSUE TITLE
support specifying both image and code in wsk CLI

### ISSUE THREAD

**Issue by glikson** [apache/incubator-openwhisk#2011]
In some cases it is useful to augment the standard runtime image (e.g., openwhisk/nodejs6action) with additional binaries (e.g., installation of a certain library, such as `opencv`). In order to do so and still take advantage of 'standard' lifecycle management of the action code itself, it is possible today to use the REST API, specifying `kind=blackbox` with custom `image` as well as `code` (plain text or 'binary' -- base64-encoded zip).
It would be great to enable this option in the CLI too, e.g.:
```
$ wsk action create --image mydockerhubaccount/mynodejsactionimage myaction.zip
```
(Note: can consider reusing the "--docker" flag)

related to #1927

**Comment by rabbah** [comment]
Closed by https://github.com/apache/incubator-openwhisk/commit/9c1f77fdb1e4a7339634434dc90c45026d6a43d2.
