### ISSUE TITLE
HTTP Fails to connect on Vagrant install

### ISSUE THREAD

**Issue by mcdan** [apache/incubator-openwhisk#2041]
## Environment details:

* local deployment: vagrant
Following the directions in the [Vagrant setup](https://github.com/openwhisk/openwhisk/tree/master/tools/vagrant)

## Steps to reproduce the issue:
Trying to setup non ssl connection to the nginx frontend:

1. `git clone https://github.com/openwhisk/openwhisk.git`
2. `cd openwhisk/tools/vagrant`
3. `./hello`
4. ``../../bin/wsk property set --apihost 192.168.33.13 --auth `vagrant ssh -- cat openwhisk/ansible/files/auth.guest` ``
5. `../../bin/wsk action -i invoke /whisk.system/utils/echo -p message hello --blocking --result`
6. ``../../bin/wsk property set --apihost http://192.168.33.13 --auth `vagrant ssh -- cat openwhisk/ansible/files/auth.guest` ``
5. `../../bin/wsk action invoke /whisk.system/utils/echo -p message hello --blocking --result`

## Provide the expected results and outputs:
```
{
    "message": "hello"
}
```

## Provide the actual results and outputs:
```
error: Unable to invoke action 'utils/echo': Post http://192.168.33.13/api/v1/namespaces/whisk.system/actions/utils/echo?blocking=true&result=true: dial tcp 192.168.33.13:80: getsockopt: connection refused
Run 'wsk --help' for usage.
```

## Additional information you deem important:
* In vagrant ( not sure if this needs to be controlled in other deployments ) it's helpful to be able to see the HTTP requests that wsk makes. So having a non-ssl connection is quite helpful. Not sure if this was an oversight or a security decision. If it was a security decision perhaps hiding it behind a setting in ansible is more appropriate than the PR that claims to fix this.

**Comment by rabbah** [comment]
`http://192.168.33.13` should be `http://192.168.33.13:10001` - the nginx conf (as you found) doesn't listen to port 80.

**Comment by rabbah** [comment]
We've debated this in the past: should nginx support http as well; if we enable this but don't test it, it will break. If we enable it and test it, how much test coverage do we apply?

**Comment by mcdan** [comment]
Ah, so the PR is wrong then, I added nginx listening on 80 so that everything was still going through there. So all the requests should be the same to the downstream systems. Directly hitting the controller would change things much more.

**Comment by csantanapr** [comment]
Works for me with recent vagrant changes
```
vagrant@ubuntu-xenial:~/openwhisk$ ifconfig | grep 192
          inet addr:192.168.33.16  Bcast:192.168.33.255  Mask:255.255.255.0
vagrant@ubuntu-xenial:~/openwhisk$ exit
logout
Shared connection to 127.0.0.1 closed.
⛄  $ ../../bin/openwhisk-cli/build/darwin-amd64/wsk property set --apihost 192.168.33.16 --auth `vagrant ssh -- cat openwhisk/ansible/files/auth.guest`
ok: whisk auth set. Run 'wsk property get --auth' to see the new value.
ok: whisk API host set to 192.168.33.16

⛄  $ ../../bin/openwhisk-cli/build/darwin-amd64/wsk -i action invoke /whisk.system/utils/echo -p message hello --blocking --result
{
    "message": "hello"
}
⛄  $ date
Thu Apr 19 13:00:11 EDT 2018
```
