### ISSUE TITLE
Refactor Printing and Formatting of Messages in CLI

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk#2062]
CLI code is hard to read as the externalized string package being used requires a map of keys and values. This process should be abstracted to make the code more readable.

**Comment by dubeejw** [comment]
@csantanapr, @mdeuser, this is technical debt, and should be fixed ASAP.

**Comment by csantanapr** [comment]
Looking forward to a PR :)

**Comment by rabbah** [comment]
As part of doing this, consider: adding quiet mode which omits "ok:" and "error:" lines so that raw Json responses are more amenable to post processing.

**Comment by markusthoemmes** [comment]
Alternatively: `--json` or `--raw` to explicitly make the output machine-readable?

**Comment by dubeejw** [comment]
@markusthoemmes, a flag like `--raw` would be accomplished through this issue: https://github.com/openwhisk/openwhisk/issues/2064.

**Comment by akrabat** [comment]
A quiet mode would be handy for property get too. That way I wouldn't need to do this:

    wsk property get --cliversion | rev | cut -f1 | rev

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #142](https://github.com/apache/incubator-openwhisk-cli/issues/142) via [**ZenHub**](https://www.zenhub.com/)
