### ISSUE TITLE
Refactor Error Processing in CLI

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk#2063]
The error type in the CLI should be refactored as a linked list. This will eliminate the need to manually concatenate error messages whenever an error occurs.

**Comment by dubeejw** [comment]
@csantanapr, @mdeuser, this is technical debt, and should be fixed ASAP.

**Comment by mdeuser** [comment]
@dubeejw - is there a particular failure that you are seeing?

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #141](https://github.com/apache/incubator-openwhisk-cli/issues/141) via [**ZenHub**](https://www.zenhub.com/)
