### ISSUE TITLE
CLI HTTP Client Should Return HTTP Body to Commands

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk#2064]
As values returned from Whisk backend can get out of sync with the CLI, the HTTP body of a response should be returned to each command. This way the HTTP body can be directly printed. This allows fields to be added/removed from the backend responses without the CLI needing to be updated unless the modified fields are critical to the functionality of the CLI.

**Comment by dubeejw** [comment]
@csantanapr, @mdeuser, this is technical debt, and should be fixed ASAP.

**Comment by dubeejw** [comment]
All of the commands currently receive the HTTP response from each request, but the response body is not accessible as the connection has already been closed.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #140](https://github.com/apache/incubator-openwhisk-cli/issues/140) via [**ZenHub**](https://www.zenhub.com/)
