### ISSUE TITLE
Deployment of Go CLI from the separate repo openwhisk-client-go

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk#2101]
Since the Go CLI will be moved under a separate repo openwhisk-client-go, openwhisk needs to change the current deployment for Go CLI to install it from openwhisk-client-go repo.

After the movement is done for Go CLI, the Go CLI code under openwhisk will be removed.

**Comment by pritidesai** [comment]
I have the PR at https://github.com/openwhisk/openwhisk-cli/pull/4

This PR can generate wsk CLI under openwhisk-cli/bin.

**Comment by dubeejw** [comment]
Please create a repo that preserves the Git history of the existing CLI, before continuing this work.

**Comment by houshengbo** [comment]
@pritidesai Could you start to work on the script for openwhisk to innstall Go CLI in the new repo?
I think the build part is ready in Go CLI repo.

**Comment by csantanapr** [comment]
I'm happy to close this now 🎉
