### ISSUE TITLE
controller should slow poll the DB for activations

### ISSUE THREAD

**Issue by bjustin-ibm** [apache/incubator-openwhisk#2118]
Today there was an issue where an active ack message could not be produced because the result of the activation was too large. Even though the action finished quickly, the invoker still waited the (newly increased) 60s active ack timeout period. In the meantime, the controller converted this activation to non-blocking for having exceeded the 60 second blocking threshold (because polling throws `BlockingInvokeTimeout`). However, even though the action completed rather quickly, and the activation was written to the DB even before the active ack time expired, the user still had to wait 60 seconds just to find out that their activation was converted to non-blocking (when really it was already completed).

One solution is to have the controller simultaneously poll the DB for the activation, even during the initial active ack period. In this way, the controller can fail over to getting the activation from the DB without necessarily waiting the entire active ack expiration period.

Because this is more of a failover procedure (rather than a performance optimization) the polling could be done relatively slowly (500ms - 1000ms) to limit the amount of load placed on the DB.

**Comment by markusthoemmes** [comment]
The proper fix in this case would be to properly measure the size of the activation and deny a result which is too large? I suspect this is an error because we allow up to 1MB of response size (and 1MB in Kafka) but the activation JSON is response size + metadata, which can grow > 1MB?

**Comment by rabbah** [comment]
The issue was caused by exactly what you pointed out: the result is 1MB but with metadata added it's over the Kafka limit. That's the system's fault.

**Comment by rabbah** [comment]
Note however that by increasing the active ack to 60s we basically dropped the recovery for a failed Kafka consumer on the controller side.

**Comment by mdeuser** [comment]
> the invoker still waited the (newly increased) 60s active ack timeout period

Is it the invoker that's waiting for the active-ack message or the controller, or both?

**Comment by rabbah** [comment]
The invoker sends the active ack. The controller receives it.

**Comment by mdeuser** [comment]
Is the invoker waiting for anything once it issues the active-ack completion message?  i.e. positive indication that the controller (or kafka) actually received the message?

**Comment by markusthoemmes** [comment]
@mdeuser no, there is no guarantee that active acks are received by the controller, hence we have the database polling fallback.
