### ISSUE TITLE
wsk property get --namespace should give explicit name of namespace

### ISSUE THREAD

**Issue by sjfink** [apache/incubator-openwhisk#2150]
```
$ wsk property get --namespace
whisk namespace	      _
```

I propose `wsk property get --namespace` should always return the explicit name of the default namespace, and not `_` or `default`.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #137](https://github.com/apache/incubator-openwhisk-cli/issues/137) via [**ZenHub**](https://www.zenhub.com/)
