### ISSUE TITLE
wsk CLI needs a flag to query its version

### ISSUE THREAD

**Issue by uwefassnacht** [apache/incubator-openwhisk#2178]
How do I know which version of the CLI I have installed? And whether it's the latest & greatest one? How do I know when to update (re-install) the CLI?

It would be good to provide a `-v` flag (similar to the cloud foundry CLI) that outputs the version. I realize that `-v`is already taken (verbose option).

At the very least, the CLI "splash screen" (displayed when using `wsk` without any options) should display a version number.

It's also not clear from the CLI repo at https://openwhisk.ng.bluemix.net/cli/go/download what the current version is and whether it's time to update.

**Comment by sjfink** [comment]
`wsk property get --cliversion`

**Comment by rabbah** [comment]
@houshengbo @pritidesai as part of making the JSON object available advertising the CLIs versions, it would be nice to address the comment above: the link to a binary should carry version information.

Of course, we don't have a proper version yet or release tag (#1880).
@csantanapr I think we need one epic to track all the related CLI issues for versioning, the download page, etc.

**Comment by eweiter** [comment]
It would also be nice if we could try to expose this info through the CLI page on the download button or near it. 

I opened the issue for it here: https://github.ibm.com/BlueMix-Fabric/Bluemix-Whisk-UI/issues/1805

**Comment by dubeejw** [comment]
@eweiter, @houshengbo, we should be able to expose the CLI version to the UI via the content.json file.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #136](https://github.com/apache/incubator-openwhisk-cli/issues/136) via [**ZenHub**](https://www.zenhub.com/)
