### ISSUE TITLE
Add experimental Swift 4 runtime

### ISSUE THREAD

**Issue by paulcastro** [apache/incubator-openwhisk#2200]
Provide access to a Swift 4 container for developers who need early access.

**Comment by csantanapr** [comment]
@paulcastro now your trying to :trollface: me?

**Comment by paulcastro** [comment]
This train keeps rolling.  No stopping.

**Comment by jthomas** [comment]
@csantanapr has created new issues in the runtime repo for this: 
https://github.com/apache/incubator-openwhisk-runtime-swift/issues/3

should this issue be closed?

**Comment by csantanapr** [comment]
It looks we are going to skip swift 4.0 and go straight to swift 4.1
People can play with swift 4.1 and Codable in the swift runtime today. 
https://github.com/apache/incubator-openwhisk-runtime-swift

I will open a new Issue to track the inclusion of swift 4.1 into core repo to make it part of the default runtimes deploy in ansible.
