### ISSUE TITLE
Update web action and annotations docs to reflect that bound actions can't be web actions

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#2204]
We need to update the docs to make this point clear. In addition would be good to document a pattern of using sequences to create web actions that can leverage bound actions.

User can't enable certain actions as web actions.
The user needs to own the action to be able to enable it as web action by adding the annotation, or using the CLI `--web true`

Type of actions 
- User can't add annotation `web-export` true to an action inside a bound package. for example `/gues/mySlackBinding/post` if `mySlackBinding` if it's a bound package 
- User In addition can't enable web actions on shared packages for example `/whisk.system/utls` like the action `/whisk.system/utls/echo`

**Comment by sjfink** [comment]
I can't recall -- is there a good reason we can't support bound actions as web actions?

**Comment by csantanapr** [comment]
@sjfink 
>I can't recall -- is there a good reason we can't support bound actions as web actions?

I can't recall, I vaguely remember something that user can't write the annotation `web-export` to the action, since it doesn't own the action to attached the annotation.
Also about the annotation needs to be on the action not on a package as it would make all the actions a web action.

I bet @rabbah and @dubeejw can clarify since they worked on that code.

**Comment by rabbah** [comment]
The restriction follows from design choices that I made:

- web annotation is attached to an action
- an action in a public package cannot be amended by a subject unless they own it

So if a packaged action is made into a web action, we’d force all bindings to inherit the annotation for the action. And we don’t have a mechanism that allows a binding to override and modify an action from the base package.

**Comment by rabbah** [comment]
We now allow web actions from bindings.
