### ISSUE TITLE
Openwhisk on Prem setup on Ubuntu 16.04

### ISSUE THREAD

**Issue by Katiyman** [apache/incubator-openwhisk#2212]
## Environment details:

•Ubuntu 16.04
•Docker version 17.04.0-ce, build 4845c56
•output of `docker ps` 
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                  NAMES
fbe91a7a9930        whisk/nodejs6action:latest   "/bin/sh -c 'node ..."   6 minutes ago       Up 6 minutes                                                                                                                                                               wsk0_34_warmJsContainer_20170504T105404209Z
446dcc06a86c        whisk/nodejs6action:latest   "/bin/sh -c 'node ..."   6 minutes ago       Up 6 minutes                                                                                                                                                               wsk0_33_warmJsContainer_20170504T105403237Z
99c1bbf6eef5        nginx:1.11                   "nginx -g 'daemon ..."   3 hours ago         Up 3 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8443->8443/tcp                                                                                       nginx
13143067f46f        whisk/invoker:latest         "/bin/sh -c 'exec ..."   3 hours ago         Up 3 hours          0.0.0.0:12001->8080/tcp                                                                                                                                invoker0
2071c3f59aa0        whisk/controller:latest      "/bin/sh -c 'contr..."   3 hours ago         Up 3 hours          0.0.0.0:10001->8080/tcp                                                                                                                                controller
a3c0715720bf        ches/kafka:0.10.0.1          "/start.sh"              3 hours ago         Up 3 hours          7203/tcp, 0.0.0.0:9092->9092/tcp                                                                                                                       kafka
893a669e96e2        zookeeper:3.4                "/docker-entrypoin..."   3 hours ago         Up 3 hours          2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp                                                                                                             zookeeper
b523aade16af        gliderlabs/registrator       "/bin/registrator ..."   3 hours ago         Up 3 hours                                                                                                                                                                 registrator
02656b311243        consul:0.7.1                 "docker-entrypoint..."   3 hours ago         Up 3 hours          0.0.0.0:8300-8302->8300-8302/tcp, 0.0.0.0:8400->8400/tcp, 0.0.0.0:8301-8302->8301-8302/udp, 0.0.0.0:8500->8500/tcp, 0.0.0.0:8600->8600/udp, 8600/tcp   consul
4d63c71da851        couchdb:1.6                  "tini -- /docker-e..."   2 days ago          Up 6 hours          0.0.0.0:5984->5984/tcp                                                                                                                                 couchdb

## Steps to reproduce the issue:

1.   Build the openwhisk setup
2.   run ansible-playbook -i environments/local openwhisk.yml from ansible dir 

## Provide the expected results and outputs:

```
Successful deployement
```

## Provide the actual results and outputs:

```
fatal: [ansible]: FAILED! => {"changed": true, "cmd": "./installRouteMgmt.sh /home/nokia/openwhisk/ansible/../ansible/files/auth.whisk.system 172.17.0.1 /whisk.system /home/nokia/openwhisk/ansible/../bin/wsk", "delta": "0:00:00.821997", "end": "2017-05-04 10:57:24.666063", "failed": true, "rc": 247, "start": "2017-05-04 10:57:23.844066", "stderr": "+ '[' 4 -eq 0 ']'\n+ AUTH=/home/nokia/openwhisk/ansible/../ansible/files/auth.whisk.system\n+ APIHOST=172.17.0.1\n+ NAMESPACE=/whisk.system\n+ WSK_CLI=/home/nokia/openwhisk/ansible/../bin/wsk\n+ WHISKPROPS_FILE=/home/nokia/openwhisk/ansible/../whisk.properties\n++ fgrep apigw.auth.user= /home/nokia/openwhisk/ansible/../whisk.properties\n++ cut -d= -f2\n+ GW_USER=\n++ cut -d= -f2-\n++ fgrep apigw.auth.pwd= /home/nokia/openwhisk/ansible/../whisk.properties\n+ GW_PWD=\n++ cut -d= -f2\n++ fgrep apigw.host= /home/nokia/openwhisk/ansible/../whisk.properties\n+ GW_HOST=http://172.17.0.1:9000/v1\n++ fgrep apigw.host.v2= /home/nokia/openwhisk/ansible/../whisk.properties\n++ cut -d= -f2\n+ GW_HOST_V2=http://172.17.0.1:9000/v2\n+ '[' -f /home/nokia/openwhisk/ansible/../ansible/files/auth.whisk.system ']'\n++ cat /home/nokia/openwhisk/ansible/../ansible/files/auth.whisk.system\n+ AUTH=789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP\n+ export WSK_CONFIG_FILE=\n+ WSK_CONFIG_FILE=\n+ echo Installing routemgmt package.\n+ /home/nokia/openwhisk/ansible/../bin/wsk -i --apihost 172.17.0.1 package update --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP --shared no /whisk.system/routemgmt -a description 'This experimental package manages the gateway API configuration.' -p gwUser '' -p gwPwd '' -p gwUrl http://172.17.0.1:9000/v1 -p gwUrlV2 http://172.17.0.1:9000/v2\nerror: Package update failed: The server is currently unavailable (because it is overloaded or down for maintenance). (code 6)", "stdout": "Installing routemgmt package.", "stdout_lines": ["Installing routemgmt package."], "warnings": []}
[FAILED]
> ./installRouteMgmt.sh /home/nokia/openwhisk/ansible/../ansible/files/auth.whisk.system 172.17.0.1 /whisk.system /home/nokia/openwhisk/ansible/../bin/wsk
Installing routemgmt package.
.
.
.
/home/nokia/openwhisk/ansible/../bin/wsk -i --apihost 172.17.0.1 package update --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP --shared no /whisk.system/routemgmt -a description 'This experimental package manages the gateway API configuration.' -p gwUser '' -p gwPwd '' -p gwUrl http://172.17.0.1:9000/v1 -p gwUrlV2 http://172.17.0.1:9000/v2
error: Package update failed: The server is currently unavailable (because it is overloaded or down for maintenance). (code 6)

```
```
Using verbose option

Response body size is 117 bytes
Response body received:
{
  "error": "The server is currently unavailable (because it is overloaded or down for maintenance).",
  "code": 6
}
```
## Additional information you deem important:
* The line which is giving error is $WSK_CLI -i --apihost "$APIHOST" package update --auth "$AUTH"  --shared no "$NAMESPACE/routemgmt" \
-a description "This experimental package manages the gateway API configuration." \
-p gwUser "$GW_USER" \
-p gwPwd "$GW_PWD" \
-p gwUrl "$GW_HOST" \
-p gwUrlV2 "$GW_HOST_V2"
* file name is installRouteMgmt.sh in /openwhisk/ansible/roles/routemgmt/files
* please let me know if some other info is required
* resp header info 
Resp Headers
{
  "Connection": [
    "keep-alive"
  ],
  "Content-Length": [
    "117"
  ],
  "Content-Type": [
    "application/json; charset=UTF-8"
  ],
  "Date": [
    "Thu, 04 May 2017 08:14:09 GMT"
  ],
  "Server": [
    **"nginx/1.11.13"**
  ]
}

**Comment by rabbah** [comment]
The error you report is almost always related to either a missing database instance or a badly configured out. I see in your docker ps output there is a couchdb instance (from "3 days" ago). Perhaps you need to rerun the couch playbooks including `initdb` and `wipedb`?

A good tip is to use `bin/wskdev` as in `wskdev couchdb initdb wipedb` to bring up a properly configured db.

You can check that the db is online with `tools/admin/wskadmin`, as in `wskadmin db get whisks`.

**Comment by Katiyman** [comment]
This issue was because the required databases were not created in the couchdb. once the Db were created fine with initdb and wipedb yml. This issue did not occur.
