### ISSUE TITLE
Query Controller for Default, Minimum, and Maximum Parameter Values (CLI)

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk#2219]
When displaying help information, the CLI should make an API call to the backend requesting information about default, min, and max values for parameters. These values will then be displayed to the user in the help dialog. We should think about querying the backend for default values that should be used when invoking non-help commands as well. Perhaps always query for value information when the CLI starts. This will eliminate the need to manually sync such values up between the controller and the CLI. 

Part of the controller implementation needed to achieve this task can been seen here: 
https://github.com/openwhisk/openwhisk/pull/1980

**Comment by rabbah** [comment]
Issue moved to [apache/incubator-openwhisk-cli #168](https://github.com/apache/incubator-openwhisk-cli/issues/168) via [**ZenHub**](https://www.zenhub.com/)
