### ISSUE TITLE
Add golint to scanCode.py

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk#2222]
the openwhisk-cli repo. added "golint" to its specific travis (see https://github.com/apache/incubator-openwhisk-cli/pull/41/files)...  

Would be better to catch any formatting/syntax-related errors or warnings for .go files uniformly in scanCode.py so it is uniformly applied to all .go in all repos. (and configurable).

example Travis inclusion:
before_test:
+  - go get -u github.com/golang/lint/golint
+  - go get -d -t ./...

**Comment by markusthoemmes** [comment]
Is this still relevant once the CLI moves out of this repository?

**Comment by rabbah** [comment]
@mrutkows seems like this can move to the new utils repo?

**Comment by rabbah** [comment]
Issue moved to [apache/incubator-openwhisk-utilities #20](https://github.com/apache/incubator-openwhisk-utilities/issues/20) via [**ZenHub**](https://www.zenhub.com/)
