### ISSUE TITLE
cli.md instruction "To verify your CLI setup, try <link>" has invalid link

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk#2226]
Coming from a native (mac) install, but applies any native setup...

CLI.md section "Setting up the OpenWhisk CLI"

ends with advice to:

> Tip: The OpenWhisk CLI stores the properties set in ~/.wskprops by default. The location of this file can be altered by setting the WSK_CONFIG_FILE environment variable.
> 
> To verify your CLI setup, try creating and running an action.

however the link provided for the text "creating and running an action" does nothing.

It attempts to take you to:

> https://github.com/openwhisk/openwhisk/blob/master/docs/cli.md#**openwhisk-hello-world-example**

which is circular reference to a page-relative link (section) that does not exist.

**Comment by timboldt** [comment]
It appears this is fixed now. The verify link now points to https://github.com/apache/incubator-openwhisk/blob/master/docs/samples.md, which is valid.
