### ISSUE TITLE
OPTIONS verb does not reach web actions

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2234]
The API path routing in the controller prevents a web action from responding to an OPTIONS verb directly. Instead the controller responds automatically with

```
Access-Control-Allow-Headers → Authorization, Content-Type
Access-Control-Allow-Origin → *
```

This allows a pre-flighted request to then proceed and invoke the intended web action. In general, this turns out out to be the common case and desired behavior. But it could also mean a false response to a pre-flight request. For example if the intended call restricts the methods as in:

```
function main(params) {
   var headers = {
       'Access-Control-Allow-Methods': 'POST'
   };

   return ({statusCode:200, headers: headers, body: new Buffer('Ok').toString('base64')})
}
```

Removing the standard respond from the controller will mean pre-flight requests _may_ end up invoking a web action twice: once with the OPTIONS verb and subsequently with the action request.

**Comment by csantanapr** [comment]
I think this important to fix and allow the web action handle OPTIONS http verbs, CORS is one use case, but there are other use cases not related to CORS that the web action needs to handle web actions if the programmer is let's say migrating a web servers application to serverless.

**Comment by carlosgalveias** [comment]
I think that even the default behaviour is incorrect as it **does not** send the default ''Access-Control-Allow-Methods' that web actions support.

This breaks implementations of, for example, a serverless api compatible with a popular framework like Emberjs that uses ajax requests expects OPTIONS to declare the supported methods and when its none, all the verbs except GET will fail because it will assume its not supported.

So i think 2 things are necessary:
1) OPTIONS ''Access-Control-Allow-Methods' should be part of the response and declare the methods that supports by default.
2) Nevertheless i think all headers should be able to be overriden if desired giving total flexibility.

**Comment by rabbah** [comment]
> parameter could be provided for the openwhisk action that would override the supported methods

might be a nice feature - also avoids running actions only to have them reject the method.

agree on your point - the current solution is neither here or there.

**Comment by csantanapr** [comment]
In terms of avoiding an invocation for the default case on options CORS we could use annotations

The controller can see the annotation if the verb is options and if there is a set of annotations then skip the invocation and response to the request with the cors headers using the info from the annotation

**Comment by carlosgalveias** [comment]
Hi Rodric/Carlos,

Seems there is agreement, do you guys have a ETA , i have a IBM project where the frontend is going to be in Ember and using Ember data and so this is a blocker for me.

Thanks,

Carlos Galveias

**Comment by csantanapr** [comment]
@dubeejw would be this something you can handle?

**Comment by rabbah** [comment]
@csantanapr what is the proposal? Two annotations: one for options and for methods to accept? I think we need to spell out exactly what we want the UX to be.

**Comment by csantanapr** [comment]
I'm having seconds thoughts on making the controller do more for every OPTIONS request, it would need to do a DB call to fetch the annotations. 
I proposed we table this one in a new issue to mull on it. 
I think one area to investigate is to see if the recommended way is to handle this before it reaches the controller like using apigateway 

For this issue we have two problems to fix pronto:
1. Add the explicit verbs to the response
2. Web actions should be able to receive OPTIONS http requests and be able to respond how ever it wants

What you think

**Comment by rabbah** [comment]
The action is already fetched - so access to the annotation will not incur additional overhead.

**Comment by rabbah** [comment]
For example we can add annotations: 

* default-options: true or false, and 
* accept-methods: {set of verbs}

Where default-options is true automatically (common case also preserves today's behavior) and further Options may appear in accept-methods and if so overrides default-options (to false).

**Comment by csantanapr** [comment]
I propose (P3)

By default controller response to OPTIONS with web actions
```
Access-Control-Allow-Origin: * (all origins)
Access-Control-Allow-Methods: get, delete, post, put, head, options, patch
```

If user wants to handle the http requests for method OPTIONS then he can add an annotation
`web-options=true`

There might be other use cases to cover, but let's handle in a different issue.

**Comment by rabbah** [comment]
P3 decouples the conflation of method-based routing and options response - good idea. I suggest `web-custom-options`: true or false, with false being the default (if missing).

**Comment by csantanapr** [comment]
Ok fine you picky :D let's go with "web-custom-options"

I thought I was clear false or not present is the default. 

Do we are on the same page to stop the bleed on this issue.

**Comment by dubeejw** [comment]
Sounds good to me.
