### ISSUE TITLE
For how long does an action result is stored in CouchDB?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [apache/incubator-openwhisk#2238]
As far as I understand, every action result is stored in CouchDB. Suppose I hane an action to retrive documents from MongoDB... hundreds of users retrieving data from the database... everything is "re-stored" in CouchDB? Won't  it blow up pretty fast? Are there any mechanism to delete old actions to save space?

Thanks!

**Comment by rabbah** [comment]
You can use this script to delete activations older than `N` days:
https://github.com/apache/incubator-openwhisk/blob/master/tools/db/cleanUpActivations.py

**Comment by rabbah** [comment]
@DanielFerreiraJorge does the script address your question?

**Comment by DanielFerreiraJorge** [comment]
@rabbah Yes thank you very much! Sorry I forgot to follow up!
