### ISSUE TITLE
Add the ability to fetch the total number of activations

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk#2242]
Currently the OW CLI does not provide a way to fetch the total number of activations for an action. You can fetch activations and paginate by using skip, but you don't know how many *total* you have.

**Comment by rabbah** [comment]
duplicate of https://github.com/apache/incubator-openwhisk/issues/1414?

**Comment by cfjedimaster** [comment]
Agreed - thank you!
