### ISSUE TITLE
new ContainerPool aggressively restarts containers under load

### ISSUE THREAD

**Issue by tysonnorris** [apache/incubator-openwhisk#2245]
## Environment details:

* local deployment, Mac OS
* docker 17.03 (server 17.05 on docker-machine) 

## Steps to reproduce the issue:

1.   use [https://github.com/markusthoemmes/openwhisk-performance] to run throughput test (tests/throughput.sh)
2.   run throughput test: 
```./throughput.sh https://192.168.99.100  "$(cat ~/git/forks/tysonnorris/openwhisk/ansible/files/auth.guest)" 10 1000```
3.   in a separate terminal check for nodesjsaction containers - notice they are constantly recreated
```docker ps | grep nodejs```

## Provide the expected results and outputs:

Expected: Don't restart containers when scheduling activation for an action that already has max warm containers that are all busy. Instead, requeue the activation for later.

## Provide the actual results and outputs:

1. Per above, notice the containers are restarting constantly, even though there is only a single action being exercised

2. Notice throughput latency is way up, compared to 4 concurrent users. 
```
[Mon May 15 2017 20:24:41 GMT+0000 (UTC)] INFO Requests: 0 (0%), requests per second: 0, mean latency: 0 ms
[Mon May 15 2017 20:24:46 GMT+0000 (UTC)] INFO Requests: 10 (1%), requests per second: 2, mean latency: 2904.3 ms
[Mon May 15 2017 20:24:51 GMT+0000 (UTC)] INFO Requests: 20 (2%), requests per second: 2, mean latency: 4631.8 ms
[Mon May 15 2017 20:24:56 GMT+0000 (UTC)] INFO Requests: 28 (3%), requests per second: 2, mean latency: 4242.9 ms
[Mon May 15 2017 20:25:01 GMT+0000 (UTC)] INFO Requests: 36 (4%), requests per second: 2, mean latency: 5887.2 ms
[Mon May 15 2017 20:25:06 GMT+0000 (UTC)] INFO Requests: 50 (5%), requests per second: 3, mean latency: 5270.4 ms
[Mon May 15 2017 20:25:11 GMT+0000 (UTC)] INFO Requests: 60 (6%), requests per second: 2, mean latency: 4091.2 ms
[Mon May 15 2017 20:25:16 GMT+0000 (UTC)] INFO Requests: 70 (7%), requests per second: 2, mean latency: 4556.8 ms
[Mon May 15 2017 20:25:21 GMT+0000 (UTC)] INFO Requests: 84 (8%), requests per second: 3, mean latency: 4444.2 ms
[Mon May 15 2017 20:25:26 GMT+0000 (UTC)] INFO Requests: 94 (9%), requests per second: 2, mean latency: 4195.4 ms
```

## Additional information you deem important:
n/a

**Comment by markusthoemmes** [comment]
Regression confirmed! Thank you very much for catching this.

As already discussed, one simple fix is to exclude identical actions from being scheduled for removal (we should do this anyway).

**Comment by rabbah** [comment]
nice find @tysonnorris.
can we add a performance regression test?

**Comment by tysonnorris** [comment]
@rabbah "performance regression test" - do you mean using https://github.com/markusthoemmes/openwhisk-performance? I'm not sure this is possible currently. In the meantime I'm trying to fix up the ContainerPoolTests to at least verify proper functionality with regards to removals when pool is full.

**Comment by tysonnorris** [comment]
One note - with #2246 , for a load of:
* varied actions OR
* varied invocation namespaces
the expected behavior is:
Once the pool is maxed out, additional activations with either different action OR different invocation namespace will be queued until are containers in Free state

This still leaves the potential for "hogging the container pool" by specific actions+invocation namespaces. 

To better handle that, some options to add may be:
* track the number of requeues a Run message goes through via ContainerPool.receive  
* log data on requeue metrics (are internal metrics available in other mechanisms? jmx, etc?)
* limit the number of same-action( and same user) Runs a ContainerProxy may process IFF there are requeues occurring for other Runs that have different actions/users. 

This would increase container "thrashing", but would prevent low traffic actions from being starved while being submitted alongside higher traffic actions. Any thresholds used should be tunable, via whisk properties.

**Comment by markusthoemmes** [comment]
I would only force queue the messages if the container is **really** maxed out. That means: No containers available and each namespace has exactly 1 container (that's an overload scenario basically).

As commented in the PR, I would always schedule a container of the most consuming resource for removal, even if it's in `Busy` state. That action would still finish, but the other action can go on and no starvation happens. This scheme induces a bit of overcommit, which I tend to think we can live with.
