### ISSUE TITLE
[Feature request] Make Invoker be scaled-out

### ISSUE THREAD

**Issue by style95** [apache/incubator-openwhisk#2247]
## Feature details

Currently user cannot scale out running invokers.
It would be great if user can scale out running invokers by ansible.

With this feature, user can add new hosts in inventory file and just re-run the ansible deployment.
It won`t make any changes on running invoker and will start new invoker for new hosts.

**Comment by markusthoemmes** [comment]
This already works. If you add multiple hosts to the invoker list, you'll get multiple invokers deployed. That doesn't work locally though, because ansible deduplicates that list.

**Comment by style95** [comment]
Is it possible to scale out of running invokers?
For example, I have a invoker deployed and want to deploy 2 more invokers.
In this case, could I deploy more invokers without any changes on running invoker?

**Comment by markusthoemmes** [comment]
I see, let's discuss on the pull-request
