### ISSUE TITLE
wsk trigger create/delete with a feed shows the result of the feed activation

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2249]
create a trigger with a feed
```
> wsk trigger create t --feed cloudant/changes 
ok: invoked /_/cloudant/changes with id xyz
{
    "activationId": "xyz",
    "response": {
        "result": {},
        "status": "success",
        "success": true
    },...
}
ok: created trigger myCloudantTrigger
```

then delete it:
```
> wsk trigger delete t
ok: invoked /.../changes with id xyz
{
    "activationId": "xyz",
    "response": {
        "result": {},
        "status": "success",
        "success": true
    }, ...
}
ok: deleted trigger t
```

is it intentional to show the feed action activation?

**Comment by mdeuser** [comment]
@dubeejw - was this the desired behavior?  this additional output comes from invoking the action invoke cli command method under the covers.  calling the lower level action invoke method would avoid displaying the action invocation output.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #134](https://github.com/apache/incubator-openwhisk-cli/issues/134) via [**ZenHub**](https://www.zenhub.com/)
