### ISSUE TITLE
Reevaluate the need of Consul in our deployment

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk#2254]
Consul is supposed to help with service-discovery, service-monitoring, DNS and thelike. We use none of it.

Today we store our configuration in Consul. The Controller also writes a couple of statistics to Consul which can be used to monitor the internals of the system. The fact that we store configuration in Consul has two major drawbacks:

1. The deployment tool (ansible) cannot know, that configuration for Controller/Invoker have changed. It therefore cannot automatically determine they need a redeployment.
2. Other tools like Kubernetes or Docker Compose have a hard time keeping up with changes in the main repository.

I therefore propose to remove Consul from our deployment completely. We should pass configuration via environment. Monitoring can be done via an internal API on the Controller.

Steps to do:

- [ ] Configure Controller/Invoker through environment variables. That is possible today, even with `WhiskConfig`.
- [ ] Create a `/queue` route in the Controller, just like `/invokers` to monitor the Controller's view of the queue.

**Comment by rabbah** [comment]
@markusthoemmes consider a consolidated /admin route prefix where we might add other details in the future or perform administrative tasks as well; this could serve a single authenticated route for operators.

**Comment by tysonnorris** [comment]
Can registrator go away with consul?

**Comment by rabbah** [comment]
indeed. Two for one (pull request).

**Comment by ddragosd** [comment]
how about `whisk.properties` vs ENV VARS ?

**Comment by markusthoemmes** [comment]
`whisk.properties` have no benefit ansible wise! We need something ansible is aware of, which is only env vars if you ask me.

**Comment by markusthoemmes** [comment]
Done.

**Comment by imesh** [comment]
@markusthoemmes As I see still the architecture diagram on [about.md](https://github.com/apache/incubator-openwhisk/blob/master/docs/about.md) has Consul. Should we remove it from that as well?

**Comment by rabbah** [comment]
yes we should but we need the sources; related to #3208.
