### ISSUE TITLE
wsk activation poll needs more robust name matching

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk#2274]
I filed a bug report on "wsk activation poll -h" not making it clear that it can match by name as well, but I want to expand on the feature in general. It feels like the name matching isn't very robust. It's also possible I'm not doing this right, but this is where better docs would help.

I've got an action called makeresult that lives in the serverless_superman package. The only way I can see to poll for it is to poll JUST for 'makeresult'. If I try /serverless_superman/makeresult, it will not match. If I've got 10 packages with makeresult in it, then I'll get a lot of noise back.

If I need to also provide a namespace, than I'd consider that a bug as well. It would work, but the CLI should just default to my namespace anyway. (And again, it should be documented.)

Also, there seems to be no way to get everything called within one package. (Again, unless I'm running it wrong.)

**Comment by rabbah** [comment]
confirmed bug - you can name an action in the default package but not an action in a named package.

it may be possible to support polling on all actions in a package as part of the same fix.

**Comment by dubeejw** [comment]
I had a PR open to update the activation poll usage, but was informed that activation IDs may bot apply to rules and triggers in the future. I can update the usage to just mention actions though. See: https://github.com/apache/incubator-openwhisk/pull/2398

**Comment by dubeejw** [comment]
Linked the PR to the proper issue.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #133](https://github.com/apache/incubator-openwhisk-cli/issues/133) via [**ZenHub**](https://www.zenhub.com/)
