### ISSUE TITLE
Return Nicer Errors when Non-Integer Values are Passed as Integer Arguments (CLI)

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk#2279]
`$ wsk action create actionName hello.js --timeout 30303030300303030303003`

`invalid argument "30303030300303030303003" for --timeout: strconv.ParseInt: parsing "30303030300303030303003": value out of range`

`$ wsk action create actionName hello.js --timeout asdf`

`invalid argument "asdf" for --timeout: strconv.ParseInt: parsing "asdf": invalid syntax`

**Comment by lzbj** [comment]
@dubeejw , I think this kind of error is throw by cobra package, right? can we control it?

**Comment by dubeejw** [comment]
I believe we can control the error message if we surround the `strconv.ParseInt` method calls in a try/catch, @lzbj.

**Comment by dubeejw** [comment]
If the issue is with Cobra we should open an issue with them.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #132](https://github.com/apache/incubator-openwhisk-cli/issues/132) via [**ZenHub**](https://www.zenhub.com/)
