### ISSUE TITLE
Invoker with reactive pool does no more process activations if pause grace expires too often

### ISSUE THREAD

**Issue by sven-lange-last** [apache/incubator-openwhisk#2285]
In tests on virtual systems with one CPU (=at most 4 containers on the invoker) with light workload (=more than 40 activations per invoker with >> 1 sec pause between activations), activation feed book-keeping breaks and the invoker no more pulls activation requests from Kafka. For this reason, the invoker stops processing activations but still sends health pings to the controller so that the problem is not detected.

Invoker log lines like the following indicate that the problem occurred:
```
[ActivationFeed] waiting for activation pipeline to drain: 5 > 4
```
If the problem occurs, the invoker is still running but no more log entries are appended.

Found that the `ContainerProxy` sends `NeedWork(WarmedData())` twice to the `ContainerPool`:
- when entering state `Running` with `WarmedData`, i.e. after having processed an activation successfully
- when being in state `Ready` and the `pauseGrace` timeout expires, we transition to `Pausing` sending `NeedWork`.
The `ContainerPool` sends `ContainerReleased` to the `ActivationFeed` when receiving `NeedWork(WarmedData())`.

In addition, the new container pool does NOT send `FailedActivation()` to the `ActivationFeed`.

Need to understand the book-keeping and fix it.

**Comment by markusthoemmes** [comment]
Good find! Just a quick note: Failed activation being sent is irrelevant here.

**Comment by sven-lange-last** [comment]
I agree - in the scenario that raised this defect, we had no failed activations. I just wanted to mention that we need a complete picture with regard to `ActivationFeed` book-keeping.
