### ISSUE TITLE
CLI: Zip action install fails with bad error message when --kind is missing

### ISSUE THREAD

**Issue by jasonpet** [apache/incubator-openwhisk#2287]
--kind is required when installing a zip action, but the CLI does not let the user know that the missing --kind is the issue.  Instead it just replies with a message stating "exec: undefined"

**Comment by rabbah** [comment]
Can you provide an example?

```
touch t.zip
wsk action create t t.zip
error: Unable to parse action command arguments: creating an action from a .zip artifact requires specifying the action kind explicitly
```

**Comment by jasonpet** [comment]
strange. I am seeing this error now as well.
