### ISSUE TITLE
remove api-experimental functionality, now replaced by api

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#2288]
Now that `wsk api` replaces `wsk api-experimental` we should remove `api-experimental` command.

Probably give 30 days more to give folks a chance to start using `wsk api`

**Comment by jthomas** [comment]
I will need to coordinate updating the openwhisk-client-js and openwhisk serverless framework plugin when this is released.

**Comment by csantanapr** [comment]
Yep let's coordinate thru this issue 
I would will even start marking it deprecated today in client js today and removed a bit before we remove from here.

**Comment by mdeuser** [comment]
Some development items to consider
- CLI Go code
  - Removal of experimental command, associated help, associated wski18n strings
  - Replacement of `V2` labeled structures and functions.  i.e. `apiCreateCmdV2` becomes just `apiCreateCmd` after removing the existing experimental `apiCreateCmd`.  Look in go-whisk/whisk/api.go and go-whisk-cli/commands/api.go
- Tests
  - ApiGwRoutemgmtActionTests
    - Removal `experimental` functions.
    - Re-label the `V2` items (remove V2) - methods, test labels, etc.
    - Delete the entire `API Gateway routemgmt action parameter validation` test suite
  - ApiGwTests
    - Remove all experimental tests and helper functions
  - ApiGwEndToEndTests
    - Remove api-experimental test suite
- Deployment
  - installRouteMgmt.sh task.  Remove installation of routemgmt package and associated actions

**Comment by rabbah** [comment]
related changes in https://github.com/apache/incubator-openwhisk/pull/2493 feel free to pick it up.

**Comment by drcariel** [comment]
not totally sure what to do about routemgmt, do you want me to remove the entire routemgmt.yml entirely?

**Comment by mdeuser** [comment]
no, the routemgmt.yml stays - along with the entire ansible role `routemgmt`.  the only change to this role is the update to the `installRouteMgmt.sh` file under that role.

**Comment by drcariel** [comment]
PR --> https://github.com/apache/incubator-openwhisk/pull/2547

**Comment by mdeuser** [comment]
@csantanapr - ok to close now?
