### ISSUE TITLE
Add new python kind with pandas and numpy in the environment

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2300]
The ability to add a new runtime per deployment was improved with the introduction of a runtimes manifest. The motivation for this is to add more runtimes that may be of interest based on usage. 

The way I was thinking of doing is is another "blackbox" supported image like the openwhisk skeleton. To enable this, we'd need to programmatically pull the curated docker images to the invoker registries.

**Comment by leetabix** [comment]
Hi Rodric, I was pointed towards this issue by Kailash Peri as a result of a ticket I raised (#5377-13398691) relating to exceeding the size of a Docker environment for a Python action using Pandas (itself dependant on Numpy).  Happy to share any details or collaborate if you need any assistance.  

I believe your comment is referring to adding Numpy/Pandas to the list of packages which can be called without needing to create a Docker environment that includes the extra packages.  If so, then I wholeheartedly support this approach as it'd make Openwhisk far more accessible to these very popular data science packages.

Many thanks,
James Johnson
(fellow IBMer posting on my personal GitHub account)

**Comment by rabbah** [comment]
Closing as this can be a deployment specific image. IBM Cloud Functions will roll out a new python image with additional python packages: https://github.com/ibm-functions/runtime-python/commit/d9bcbddc38da1e33e112ebfa5ba3875d9634ade8

**Comment by rabbah** [comment]
@csantanapr FYI.

**Comment by leetabix** [comment]
Thanks rabbah, that's great news!
