### ISSUE TITLE
Native deployment of openwhisk in vagrant vm. nginx is not present in docker ps.

### ISSUE THREAD

**Issue by varsha33** [apache/incubator-openwhisk#2304]
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                          PORTS                                        NAMES
67f5b9848e62        ches/kafka:0.10.0.1      "/start.sh"              46 hours ago        Up 26 hours                     7203/tcp, 0.0.0.0:9092->9092/tcp             kafka
82959d1037dc        zookeeper:3.4            "/docker-entrypoin..."   46 hours ago        Up 26 hours                     2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp   zookeeper
308dd2b1b4fd        gliderlabs/registrator   "/bin/registrator ..."   46 hours ago        Restarting (1) 43 seconds ago                                                registrator
c69895255c3a        consul:0.7.0             "docker-entrypoint..."   46 hours ago        Restarting (1) 43 seconds ago                                                consul

**Comment by rabbah** [comment]
Try the fix suggested here: https://github.com/apache/incubator-openwhisk/issues/32

**Comment by varsha33** [comment]
ant can't be used to build the current version I suppose. Used gradle as per the revised version. Steps to be followed are the same ? I cannot do it with ant as there is no build.xml file, so can you please tell how to fix this issue using gradle ?

**Comment by rabbah** [comment]
Do you have /tmp/nginx owned by root?

**Comment by varsha33** [comment]
Sorry for the delayed response. I think it was owned by root. But I deleted it while following some instructions to solve the above problem. Now I can't locate that file. And the problem is still not resolved. Please help.

**Comment by rabbah** [comment]
run `wskdev edge` to redeploy nginx. You. An just recreate the directory (without root /tmp/nginx if necessary).

**Comment by varsha33** [comment]
Thanks a lot. It works :+1:

**Comment by AsmOK** [comment]
I get this when trying 'wskdev edge'
![image](https://user-images.githubusercontent.com/14912966/36054646-3e8f850a-0e00-11e8-8dc6-f56bbcd5d47f.png)

**Comment by AsmOK** [comment]
I get "Destination /tmp/wskconf/nginx not writable" when trying 'wskdev edge': 
![image](https://user-images.githubusercontent.com/14912966/36055466-3dd6db90-0e05-11e8-988c-56d7b1326986.png)

**Comment by rabbah** [comment]
Remove the directory first. It’s likely owned by root and causes the issue you’re seeing.

**Comment by AsmOK** [comment]
Now I get a different error,
![image](https://user-images.githubusercontent.com/14912966/36055710-0aed7688-0e07-11e8-9af4-103bcff5fdd7.png)
sorry for the headache!

**Comment by csantanapr** [comment]
This is now fix with #3269
