### ISSUE TITLE
Native deployment of openwhisk in vagrant vm. Not able to set api host to an IP address for eg 172.17.0.1. 

### ISSUE THREAD

**Issue by varsha33** [apache/incubator-openwhisk#2305]
error: Unable to obtain the list of entities for namespace 'default': Get https://172.17.0.1/api/v1/namespaces/_/: dial tcp 172.17.0.1:443: getsockopt: connection refused

**Comment by rabbah** [comment]
I suspect if your nginx is not up, then this is the reason you can't use the API host.

**Comment by rabbah** [comment]
Duplicate of https://github.com/apache/incubator-openwhisk/issues/2304.
