### ISSUE TITLE
Openwhisk native deployment, not able to invoke action or any functions due to SSL certificate issue.

### ISSUE THREAD

**Issue by varsha33** [apache/incubator-openwhisk#2309]
error: Unable to obtain the list of entities for namespace 'default': Get https://172.17.0.1/api/v1/namespaces/_/: x509: cannot validate certificate for 172.17.0.1 because it doesn't contain any IP SANs

I referred to this fix [https://github.com/apache/incubator-openwhisk/issues/1908] but did not solve my problem.

**Comment by rabbah** [comment]
Use `-i` with your wsk commands.

**Comment by varsha33** [comment]
vagrant@vagrant-ubuntu-trusty-64:~/openwhisk/bin$ ./wsk -i list
error: Unable to obtain the list of entities for namespace 'default': The connection failed, or timed out. (HTTP status code 502).

Still there is connection problem. Is it because I did not use any certificate ?

**Comment by rabbah** [comment]
Since you opened another issue for the last comment I will close this one.

**Comment by pqingshuang** [comment]
> Use `-i` with your wsk commands.

what if for URL invoking action

**Comment by rabbah** [comment]
Use `wsk action get <name> --url` to see the API endpoint for your action.
