### ISSUE TITLE
Failure to execute /whisk.system/utils/sort on an array on Windows 7

### ISSUE THREAD

**Issue by lziosi** [apache/incubator-openwhisk#2312]
## Environment details:

Windows 7, cmd.exe
connected to BlueMix

## Steps to reproduce the issue:

1.   Follow the tutorial at: https://github.com/IBM-Bluemix/openwhisk-workshops/tree/master/bootcamp
2.   at the line that calls /whisk.system/utils/sort
```
D:\OpenWhisk>wsk action invoke -b myAction -p lines \"["c","b","a"]\" --result
{
    "error": "An error has occurred: TypeError: lines.sort is not a function"
}
```

3.   If I execute the above from the Git Bash shell, it works fine

**Comment by lziosi** [comment]
Same issue with another command later on the tutorial:


D:\OpenWhisk>wsk action invoke --blocking --result packageAction --param lines '["and now", "for something completely",
erent"]'
error: Invalid argument(s): for something completely,, different]'. An action name is required.
Run 'wsk --help' for usage.

Again, this worked fine when executed from the Git Bash shell.

**Comment by rabbah** [comment]
I'll guess this is related to #2313; did you try double quotes but escaping the nested ones?
https://github.com/apache/incubator-openwhisk/issues/1291 related.

**Comment by lziosi** [comment]
Using external double quotes and escaping the internal double quotes works using cmd.exe on Windows:

```
D:\OpenWhisk>wsk action invoke --blocking --result packageAction --param lines "[\"and now\", \"for something completely\", \
"different\"]"
{
    "padded": [
        ".......................and now",
        "......for something completely",
        ".....................different"
    ]
}
```

#2313 is related to running the GIT Bash shell on Windows, not cmd.exe.

**Comment by csantanapr** [comment]
This is now fixed by using `wsk action invoke whisk.system/utils/sort` do not use `/` in front of namespace

https://github.com/apache/incubator-openwhisk-cli/commit/9b26034e9a3879a415115f2a01c2dbd582a82bca
