### ISSUE TITLE
Failure to invoke /whisk.system/utils/echo in the Windows Git Bash Shell

### ISSUE THREAD

**Issue by lziosi** [apache/incubator-openwhisk#2313]
## Environment details:

* Windows 7
* Git Bash shell

## Steps to reproduce the issue:

1.   Download the Windows CLI
2.   As directed, on Windows use the Git Bash Shell
3.   $ ./wsk action invoke /whisk.system/utils/echo -p message hello --blocking --result

## Provide the expected results and outputs:

```
{
    "message": "hello"
}

```

## Provide the actual results and outputs:

```
error: Unable to invoke action 'C:/Git/whisk.system/utils/echo': The name of the
 entity contains illegal characters. (code 19303670)
Run 'wsk --help' for usage.
```

## Additional information you deem important:
* This command works fine from the Windows cmd.exe

**Comment by csantanapr** [comment]
I think the shell is interpreting the action name as a local directory/file path. 
Instead try using quotes "/whisk.system/utils/echo" so it gets interpreted as a string

**Comment by lziosi** [comment]
I tried your suggestions, but it did not help:

```
$ ./wsk action invoke "/whisk.system/utils/echo" -p message hello --blocking --result
error: Unable to invoke action 'C:/Git/whisk.system/utils/echo': The name of the
 entity contains illegal characters. (code 21582166)
Run 'wsk --help' for usage.
```

and also with single quotes:

```
$ ./wsk action invoke '/whisk.system/utils/echo' -p message hello --blocking --result
error: Unable to invoke action 'C:/Git/whisk.system/utils/echo': The name of the
 entity contains illegal characters. (code 21583022)
Run 'wsk --help' for usage.
```

**Comment by lziosi** [comment]
```
$ ./wsk action invoke \/whisk.system\/utils\/echo -p message hello --blocking -
-result
error: Unable to invoke action 'C:/Git/whisk.system/utils/echo': The name of the
 entity contains illegal characters. (code 21706817)
Run 'wsk --help' for usage.
```
```
$ ./wsk action invoke //whisk.system//utils//echo -p message hello --blocking -
-result
error: '//whisk.system//utils//echo' is not a valid qualified name: A valid qual
ified name must be specified.
Run 'wsk --help' for usage.
```
```
$ ./wsk action invoke \whisk.system\utils\echo -p message hello --blocking --re
sult
error: Unable to invoke action 'whisk.systemutilsecho': The requested resource d
oes not exist. (code 21710430)
Run 'wsk --help' for usage.
```
```
$ ./wsk action invoke \\whisk.system\\utils\\echo -p message hello --blocking -
-result
error: Unable to invoke action '\whisk.system\utils\echo': The name of the entit
y contains illegal characters. (code 21711129)
Run 'wsk --help' for usage.
```
If wsk could accept the \ as a separator, this last form could work in this shell on Windows. On the other hand, using this shell on Windows is rather unnatural, so fixing the issues that happen with cmd.exe may be the preferred choice.

**Comment by rabbah** [comment]
@cfjedimaster @mdeuser can you help?

**Comment by cfjedimaster** [comment]
First, while you *can* run Windows executables from WSL, why are you doing so? Why not use the Linux binary instead? I'd consider (and to be clear, I do *not* speak for IBM here) using the Windows .exe in WSL as unsupported.

**Comment by lziosi** [comment]
I would say that the user experience today is confusing. 
I read that I should use the GIT Bash shell on Windows. 
But when I logged into the BlueMix UI, it directly prompted me to download the CLI for Windows (based on my Browser user-agent?) 
That's how I came to try the above combination. If the intent is to make the Windows users utilize the Linux binaries with the Git Bash shell, then I think that the docs should point that out. 
But that also raises the question of why you would have the Windows CLI in the first place?

**Comment by cfjedimaster** [comment]
Oh my goodness, I apologize - I saw "Bash shell", not "Git Bash Shell"! I apologize!

**Comment by cfjedimaster** [comment]
To add more to my last comment, I'm on Windows, but I use the Windows Linux subsystem bash shell, hence me saying I'd use the *Linux* CLI for that and not the Windows one.

**Comment by rabbah** [comment]
Thanks for the feedback @lziosi.

**Comment by cfjedimaster** [comment]
I can definitely confirm this bug. However, if you use Powershell (and I assume cmd.exe), it works well. So it's either a bug in wsk.exe, or something wonky in Git Bash.

Hope this helps!

**Comment by lziosi** [comment]
yes, this works for me in cmd.exe. It's just that the docs suggest to use Git Bash on Windows.

**Comment by mdeuser** [comment]
The Windows `wsk` CLI also works for me inside cygwin bash on Windows

**Comment by cfjedimaster** [comment]
Fair enough - @rabbah - could we quickly remove that from the docs for the time being?

**Comment by mdeuser** [comment]
@lziosi - Just to be sure the doc pages are more clear, could you paste the link to the page describing the git bash shell requirement.  Thanks!

**Comment by csantanapr** [comment]
>I read that I should use the GIT Bash shell on Windows.
The docs don't have this information.

For Windows users they should always download windows binaries:
They should use cmd.exe or powershell.
I tested latest windows build today and both seem to work.

I like to use Github Shell, which get's installed when you install the Github Windows App.
Github shell to my understanding runs on top of Windows Power Shell.
I also tested today with latest build.

I just tested Git-bash (https://git-for-windows.github.io/) which is different from Git Shell from Github. And it seems to have a problem with entities full qualified names like describe in the original comment on this Issue.
```
$ wsk action invoke /whisk.system/utils/echo -p hello windows
error: Unable to invoke action 'C:/Program Files/Git/whisk.system/utils/echo': The name of the entity contains illegal characters. (code 454638)
Run 'wsk --help' for usage.
```
I tested multiple combinations of trying to make this shell happy to take the string as type but is getting converted.
The git-bash is based on mingw and according to this http://www.mingw.org/wiki/Posix_path_conversion I should be able to type `//whisk.system\utils\echo` with no success.

You should not use the wsk linux binaries from cmd.exe, powershell, or git-bash if you do you should see the following error
```
 cannot execute binary file: Exec format error
```

As far of Bash on Ubuntu for Windows, I have not tried yet since my current Windows VM, is outdated, and out of space. So I will delegate to folks like @cfjedimaster to comment on how it get's setup and use.

**Comment by csantanapr** [comment]
One idea to workaround the issue with mingw interpretation on windows with shells like git-bash is to add a paramter to compose full qualified names like with an extra parameter to compose the entity name with an extra flag to specify the namespace

```
wsk action invoke --namespace whisk.system utils/echo -p hello windows
```

**Comment by cfjedimaster** [comment]
wsk on WSL (Windows Subsystem for Linux) works perfectly as far as I can tell. I no longer use wsk.exe.

**Comment by csantanapr** [comment]
@cfjedimaster  
You did a linux steps to set it up?

Did you downloaded 32bit or 64bit linux binary? 
Here is a 64bit: https://openwhisk.ng.bluemix.net/cli/go/download/linux/amd64/OpenWhisk_CLI-linux.tgz

Extracted and then copy this to some place in your Linux Path? Like `/usr/local/bin/wsk`

**Comment by cfjedimaster** [comment]
@csantanapr it wasn't "setup" - I just got the binary, downloaded it, and put it in /usr/bin. I didn't extract anything. Basically just downloaded this: https://openwhisk.ng.bluemix.net/cli/go/download/linux/amd64/wsk

**Comment by lziosi** [comment]
My apology, it was not the official docs that suggested using the GIT Bash on Windows, it was this tutorial:
https://github.com/IBM-Bluemix/openwhisk-workshops/tree/master/bootcamp

**Comment by csantanapr** [comment]
Hi @lziosi 
I opened an issue for them to address the doc in the bootcamp workshop
https://github.com/IBM-Bluemix/openwhisk-workshops/issues/4

**Comment by rabbah** [comment]
@csantanapr should we close this issue since the defect is elsewhere?

**Comment by saulimus** [comment]
This workaround seems to work: https://stackoverflow.com/a/34386471
Example:
`MSYS_NO_PATHCONV=1  wsk action invoke /whisk.system/utils/echo -p message hello --blocking --result`

**Comment by csantanapr** [comment]
@saulimus that's great workaround we should doc it. 
Also there is a fix to not require the first /
