### ISSUE TITLE
Openwhisk native deployment, API host connection issue 

### ISSUE THREAD

**Issue by varsha33** [apache/incubator-openwhisk#2314]
vagrant@vagrant-ubuntu-trusty-64:~/openwhisk/bin$ ./wsk -i list
error: Unable to obtain the list of entities for namespace 'default': The connection failed, or timed out. (HTTP status code 502).

**Comment by rabbah** [comment]
Can you try with `-v`: `wsk -i -v list`. Also consider joining http://slack.openwhisk.org (you're welcome to direct message me for help).

**Comment by varsha33** [comment]
Sure. Thank you
