### ISSUE TITLE
Openwhisk deployment fail locally

### ISSUE THREAD

**Issue by anasanjaria** [apache/incubator-openwhisk#2330]
## Environment details:

* local deployment, ubuntu VM (16.04 LTS - 64 bit Memory 3.8 GB , Disk 14.7 GB)
* version of docker 
`Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 116
Server Version: 17.03.1-ce
Storage Driver: aufs
..`

## Deploying Using CouchDB

The command `ansible-playbook -i environments/<environment> openwhisk..yml` produces error.

## Provide the actual results and outputs:

```
TASK [invoker : determine docker root dir] *************************************
Sunday 04 June 2017  18:00:25 +0000 (0:00:00.329)       0:04:19.028 *********** 
fatal: [172.17.0.1]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:4243/info"}

PLAY RECAP *********************************************************************
172.17.0.1                 : ok=25   changed=18   unreachable=0    failed=1   
ansible                    : ok=2    changed=1    unreachable=0    failed=0   

Sunday 04 June 2017  18:00:26 +0000 (0:00:00.918)       0:04:19.947 *********** 
=============================================================================== 
kafka : pull the ches/kafka:0.10.0.1 image ----------------------------- 98.14s
controller : wait until the Controller in this host is up and running -- 39.38s
kafka : pull the zookeeper:3.4 image ----------------------------------- 38.62s
kafka : wait until the kafka server started up ------------------------- 11.44s
kafka : create the active-ack and health topic -------------------------- 9.38s
kafka : wait until the Zookeeper in this host is up and running --------- 8.43s
consul : start registrator using docker cli ----------------------------- 7.34s
consul : pull the consul:0.7.0 image ------------------------------------ 6.89s
consul : wait until the Consul Server/Agent in this host is up and running --- 6.44s
kafka : create the invoker topics --------------------------------------- 4.76s
consul : fill consul kv ------------------------------------------------- 4.66s
consul : (re)start consul server/agent ---------------------------------- 2.32s
kafka : (re)start zookeeper --------------------------------------------- 2.10s
controller : (re)start controller --------------------------------------- 1.99s
write whisk.properties template to openwhisk_home ----------------------- 1.85s
Gathering Facts --------------------------------------------------------- 1.81s
kafka : (re)start kafka ------------------------------------------------- 1.79s
Gathering Facts --------------------------------------------------------- 1.78s
Gathering Facts --------------------------------------------------------- 1.74s
Gathering Facts --------------------------------------------------------- 1.39s

```
`ansible-playbook -i environments/<environment> postdeploy.yml` produces 

`dial tcp 172.17.0.1:443: getsockopt: connection refused`

## Additional information you deem important:
* The command `docker ps --format "{{.Names}} - {{.Image}}"` provide the following output.
`controller - whisk/controller:latest
kafka - ches/kafka:0.10.0.1
zookeeper - zookeeper:3.4
registrator - gliderlabs/registrator
consul - consul:0.7.0
couchdb - couchdb:1.6
`
* There is no nginx and invoker.

**Comment by markusthoemmes** [comment]
Have you setup docker according to our scripts? Seems like ansible cannot reach its REST API.

**Comment by anasanjaria** [comment]
Actually that script produces following error.
`docker-engine : Depends: libsystemd-journal0 (>= 201) but it is not installable` [1]
So, I followed official docker installation guide [here](https://docs.docker.com/engine/installation/linux/ubuntu/#install-docker). However, I managed to solve the above mentioned issue[1] by following the instruction mentioned [here](https://github.com/moby/moby/issues/20698#issuecomment-192606903). 

Even using the docker setup according to your script, I am still facing the same issue.

**Comment by csantanapr** [comment]
Need to setup docker engine to listen on tcp port 4243
See ubunutu helper script here: https://github.com/apache/incubator-openwhisk/blob/master/tools/ubuntu-setup/docker.sh

```

```

**Comment by csantanapr** [comment]
I'm looking into removing this requirement, I need to setup Jenkins in Apache nodes, and these nodes don't allow me to be root and don't allow me to change the way default docker engine is installed.

Everything should be able to use docker engine using docker CLI via socket file and no REST API connection

**Comment by markusthoemmes** [comment]
@csantanapr Why should we use the CLI for everything? Using the REST API (which also works through the socket) is convenient in this case.

Note that we not only change the socket options but also enable user namespaces etc. for our CI.

**Comment by csantanapr** [comment]
Well I mean at least for development or minimum deployment I think we should try to use the default docker Installation 

Hum using the REST API thru the socket didn't know that was possible.

**Comment by csantanapr** [comment]
Yes having certain custom config setup for production is necessary like storage driver and namespaces

**Comment by anasanjaria** [comment]
I have used a completely new Virtual machine and follow the steps mentioned in the [setup guide](https://github.com/apache/incubator-openwhisk/blob/master/tools/ubuntu-setup/README.md). Now there is a different error.

`TASK [controller : wait until the Controller in this host is up and running] ***
Tuesday 06 June 2017  13:50:43 +0000 (0:00:04.160)       0:09:09.466 ********** 
FAILED - RETRYING: wait until the Controller in this host is up and running (12 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (11 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (10 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (9 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (8 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (7 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (6 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (5 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (4 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (3 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (2 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (1 retries left).
fatal: [172.17.0.1]: FAILED! => {"attempts": 12, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:10001/ping"}

PLAY RECAP *********************************************************************
172.17.0.1                 : ok=23   changed=18   unreachable=0    failed=1   
ansible                    : ok=2    changed=1    unreachable=0    failed=0   

`

**Further Details**

I have used the same setup docker script provided with installation guide.
`$ echo $DOCKER_HOST`
`tcp://0.0.0.0:4243`

`$ telnet 172.17.0.1 4243`
`Trying 172.17.0.1...
telnet: Unable to connect to remote host: Connection refused`

`$ telnet 172.17.0.1 10001`
`Trying 172.17.0.1...
telnet: Unable to connect to remote host: Connection refused`

**Comment by anasanjaria** [comment]
@csantanapr I have setup docker engine to listen on tcp port 4243

`telnet 172.17.0.1 4243`
`Trying 172.17.0.1...
Connected to 172.17.0.1.
Escape character is '^]'.`

I am still getting this error
`TASK [controller : wait until the Controller in this host is up and running]`
`...`
`fatal: [172.17.0.1]: FAILED! => {"attempts": 12, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:10001/ping"}
`
Can you please help me what am I missing?

**Comment by csantanapr** [comment]
To really check if docker engine is running with the configuration to listen on port 4243 try the following:

See if there process is running and with the config
```
vagrant@vagrant-ubuntu-trusty-64:~$ ps -xa | grep tcp://0.0.0.0:4243
19590 ?        Ssl    4:27 /usr/bin/dockerd -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock --storage-driver=aufs --raw-logs
```
Then try to check the by doing a curl
```
vagrant@vagrant-ubuntu-trusty-64:~$ curl http://0.0.0.0:4243/info
{"ID":"TDMN:WKUT:DB2S:ULXV:VSNF:MVUW:AGY2:2OS6:GRZT:2BUS:XMNL:ZHW2","Containers":12,"ContainersRunning":12,"ContainersPaused":0,"ContainersStopped":0,"Images":30,"Driver":"aufs","DriverStatus":[["Root Dir","/var/lib/docker/aufs"],["Backing Filesystem","extfs"],["Dirs","124"],["Dirperm1 Supported","false"]],"SystemStatus":null,"Plugins":{"Volume":["local"],"Network":["null","host","bridge","overlay"],"Authorization":null},"MemoryLimit":true,"SwapLimit":false,"KernelMemory":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":65,"OomKillDisable":true,"NGoroutines":100,"SystemTime":"2017-06-07T22:29:05.214821599Z","ExecutionDriver":"","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","NEventsListener":1,"KernelVersion":"3.13.0-92-generic","OperatingSystem":"Ubuntu 14.04.4 LTS","OSType":"linux","Architecture":"x86_64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":null,"Secure":true,"Official":true}},"Mirrors":null},"NCPU":4,"MemTotal":4145131520,"DockerRootDir":"/var/lib/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"vagrant-ubuntu-trusty-64","Labels":null,"ExperimentalBuild":false,"ServerVersion":"1.12.0","ClusterStore":"","ClusterAdvertise":"","SecurityOptions":["apparmor"],"Runtimes":{"runc":{"path":"docker-runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null,"Nodes":0,"Managers":0,"Cluster":{"ID":"","Version":{},"CreatedAt":"0001-01-01T00:00:00Z","UpdatedAt":"0001-01-01T00:00:00Z","Spec":{"Orchestration":{},"Raft":{},"Dispatcher":{},"CAConfig":{},"TaskDefaults":{}}}},"LiveRestoreEnabled":false}
```

**Comment by anasanjaria** [comment]
@csantanapr I am able to create/update/invoke actions but I need to stop the docker service and have to run the following command explicitly (although the `DOCKER_OPTS` has been set in the provided Docker script).

`sudo dockerd -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock`

Is it fine? Also, I am receiving this error now.

`TASK [invoker : wait until Invoker is up and running] ******************************************************************************************************************************************************
Thursday 08 June 2017  18:55:22 +0000 (0:00:02.183)       0:02:24.276 ********* `
`.....`
`fatal: [172.17.0.1]: FAILED! => {"attempts": 12, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:12001/ping"}
`

**Comment by csantanapr** [comment]
Look at the line in setup docker to see full config for docker engine
https://github.com/apache/incubator-openwhisk/blob/master/tools/ubuntu-setup/docker.sh#L20

The error means that ansible is trying to check if invoker is up and functional by doing a curl on 
`http://172.17.0.1:12001/ping`

**Comment by nicschreiber** [comment]
@csantanapr I am having the same problem as anasanjaria. I set it up the exact way it is described in "Setting it up in Ubuntu"

I see in https://github.com/apache/incubator-openwhisk/blob/master/ansible/roles/controller/tasks/deploy.yml that it indeed tries to curl  http://172.17.0.1:10001/ping . Doing this manually the connection gets still refused. The question now is if it fails to start the controller or if it fails to curl the right address.

**Comment by csantanapr** [comment]
Hum this now sounds suspicious 
Did you setup the Ubuntu VM using the all.sh script meaning that all the software dependencies are the specified version as stated on these set of scripts. 

With that said could you run a few docker commands to debug ?

docker ps
docker info
docker inspect controller

**Comment by nicschreiber** [comment]
Maybe additional knowledge:
I used a locally hosted couchdb instance that was simply installed with apt and a administrator was added. Of course i adjusted the db_local.ini accordingly.

```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                  NAMES
bdf9ed7e67fe        whisk/controller:latest   "/bin/sh -c 'controll"   32 minutes ago      Up 32 minutes       0.0.0.0:10001->8080/tcp                                                                                                                                controller
ec506d8e2e2a        ches/kafka:0.10.0.1       "/start.sh"              32 minutes ago      Up 32 minutes       7203/tcp, 0.0.0.0:9092->9092/tcp                                                                                                                       kafka
aa33a70b9cc1        zookeeper:3.4             "/docker-entrypoint.s"   32 minutes ago      Up 32 minutes       2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp                                                                                                             zookeeper
1d631cf5485f        gliderlabs/registrator    "/bin/registrator -ip"   33 minutes ago      Up 33 minutes                                                                                                                                                              registrator
a1c813e1250a        consul:0.7.0              "docker-entrypoint.sh"   33 minutes ago      Up 33 minutes       0.0.0.0:8300-8302->8300-8302/tcp, 0.0.0.0:8400->8400/tcp, 0.0.0.0:8301-8302->8301-8302/udp, 0.0.0.0:8500->8500/tcp, 0.0.0.0:8600->8600/udp, 8600/tcp   consul
7816d5319d0a        couchdb:1.6               "tini -- /docker-entr"   34 minutes ago      Up 34 minutes       0.0.0.0:5984->5984/tcp                                                                                                                                 couchdb
```

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 116
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 137
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-79-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.503 GiB
Name: testing
ID: 2ZHI:4KIN:3YKI:VT7E:YTEO:H372:FFKS:WQSI:4S7C:72EB:TSER:RV5B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

```
[
    {
        "Id": "bdf9ed7e67fe763bea8e8c21449b732c94102d6e694d146b1ef4d73def784a56",
        "Created": "2017-06-09T22:25:51.908049996Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "controller/bin/controller \u003e\u003e /logs/${COMPONENT_NAME}_logs.log 2\u003e\u00261"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 31245,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-06-09T22:25:52.207727743Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:68130ff1489231653431e40368a046bd11e093f40d1de2cdf27143bcb05046fd",
        "ResolvConfPath": "/var/lib/docker/containers/bdf9ed7e67fe763bea8e8c21449b732c94102d6e694d146b1ef4d73def784a56/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/bdf9ed7e67fe763bea8e8c21449b732c94102d6e694d146b1ef4d73def784a56/hostname",
        "HostsPath": "/var/lib/docker/containers/bdf9ed7e67fe763bea8e8c21449b732c94102d6e694d146b1ef4d73def784a56/hosts",
        "LogPath": "/var/lib/docker/containers/bdf9ed7e67fe763bea8e8c21449b732c94102d6e694d146b1ef4d73def784a56/bdf9ed7e67fe763bea8e8c21449b732c94102d6e694d146b1ef4d73def784a56-json.log",
        "Name": "/controller",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/tmp/wsklogs/controller:/logs:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "10001"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Source": "/tmp/wsklogs/controller",
                "Destination": "/logs",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "controller",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SERVICE_CHECK_HTTP=/ping",
                "WHISK_VERSION_NAME=local",
                "CONTROLLER_OPTS=",
                "JAVA_OPTS=-Xmx2g",
                "KAFKA_NUMPARTITIONS=2",
                "CONSULSERVER_HOST=172.17.0.1",
                "WHISK_VERSION_BUILDNO=latest",
                "CONSUL_HOST_PORT4=8500",
                "SERVICE_CHECK_TIMEOUT=2s",
                "SERVICE_CHECK_INTERVAL=15s",
                "PORT=8080",
                "WHISK_VERSION_DATE=2017-06-09T22:25:51Z",
                "COMPONENT_NAME=controller",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8",
                "VERSION=8",
                "UPDATE=131",
                "BUILD=11",
                "JAVA_HOME=/usr/lib/jvm/java-8-oracle",
                "JRE_HOME=/usr/lib/jvm/java-8-oracle/jre"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "controller/bin/controller \u003e\u003e /logs/${COMPONENT_NAME}_logs.log 2\u003e\u00261"
            ],
            "Image": "whisk/controller:latest",
            "Volumes": {
                "/logs": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "8916515a0ded3bfc3a1b56a60f65a2ce1b0351ff945fdc4a480fd9a22fa474b0",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "10001"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/8916515a0ded",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "e17c7700c1e4a165b2486e9c533e110947848a72f39bf9abd35c340896b69e47",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.7",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:07",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "2ec89508de94eb15271e65208a0610b2a0e7495bbb5d81c26c0f7ab7d6b82c92",
                    "EndpointID": "e17c7700c1e4a165b2486e9c533e110947848a72f39bf9abd35c340896b69e47",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.7",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:07"
                }
            }
        }
    }
]
```

**Comment by csantanapr** [comment]
If you are running couchdb locally then stop the docker container for couchdb. 
If you have the db_local.ini info with information that controller can reach the run the ansible wipe.yml to create the DBs
Then redeploy the openwhisk.yml

**Comment by nicschreiber** [comment]
I run couchdb.yml, initdb.yml, wipe.yml everything without errors. Only when i run openwhisk.yml (after the others) i get:
```
FAILED - RETRYING: wait until the Controller in this host is up and running (1 retries left).
fatal: [172.17.0.1]: FAILED! => {"attempts": 12, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:10001/ping"}
```

**Comment by csantanapr** [comment]
No need to run couchdb.yml
Is the other couchdb running on the same port?

I'm suspecting controller having trouble connecting to couchdb or not finding the dbs and tables on the couchdb

You can try get the logs from controller and maybe it has some error messages that can give us a clue

**Comment by anasanjaria** [comment]
@nicschreiber As I mentioned in my previous [comment](https://github.com/apache/incubator-openwhisk/issues/2330) that I resolved this issue by stopping the docker service using this command

`sudo service docker stop`

and then running the docker deamon on specific port 

`sudo dockerd -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock`

It help me to overcome the error `http://172.17.0.1:10001/ping` . But now I am facing the same error with different port number. that is `http://172.17.0.1:12001/ping`

I thought that I don't have to explicitly run this docker daemon on specific port as I followed the provided installation script which sets the DOCKER_OPT.

@csantanapr docker ps 

`CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                  NAMES
5ba4b7ae1260        whisk/nodejs6action:latest   "/bin/sh -c 'node --e"   3 minutes ago       Up 3 minutes                                                                                                                                                               wsk0_12_warmJsContainer_20170609T182109025Z
1e836f7cee27        whisk/nodejs6action:latest   "/bin/sh -c 'node --e"   3 minutes ago       Up 3 minutes                                                                                                                                                               wsk0_11_warmJsContainer_20170609T182103066Z
724498701e9c        whisk/invoker:latest         "/bin/sh -c 'exec /in"   23 hours ago        Up 23 hours         0.0.0.0:12001->8080/tcp                                                                                                                                invoker0
6129d8e0191b        whisk/controller:latest      "/bin/sh -c 'controll"   23 hours ago        Up 23 hours         0.0.0.0:10001->8080/tcp                                                                                                                                controller
a6b925722b6c        ches/kafka:0.10.0.1          "/start.sh"              23 hours ago        Up 23 hours         7203/tcp, 0.0.0.0:9092->9092/tcp                                                                                                                       kafka
a6f8589c6183        zookeeper:3.4                "/docker-entrypoint.s"   23 hours ago        Up 23 hours         2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp                                                                                                             zookeeper
5fb111fa500b        gliderlabs/registrator       "/bin/registrator -ip"   23 hours ago        Up 23 hours                                                                                                                                                                registrator
4f4ea7beb45c        consul:0.7.0                 "docker-entrypoint.sh"   23 hours ago        Up 23 hours         0.0.0.0:8300-8302->8300-8302/tcp, 0.0.0.0:8400->8400/tcp, 0.0.0.0:8301-8302->8301-8302/udp, 0.0.0.0:8500->8500/tcp, 0.0.0.0:8600->8600/udp, 8600/tcp   consul
1702bbd95d41        couchdb:1.6                  "tini -- /docker-entr"   24 hours ago        Up 23 hours         0.0.0.0:5984->5984/tcp`

the output of the other two command is more or less similar

**Comment by nicschreiber** [comment]
@anasanjaria 
I understand that you found a solution for the first issue but my opinion is that it should not be necessary to do manual actions from outside. For me this is still a mistake in the deployment script.

**Comment by theharshbhatia** [comment]
@anasanjaria I am also facing the same problem, are you able to go past that step ?
Please if anyone has solve please explain the process.

**Comment by anasanjaria** [comment]
@theharshbhatia no, I am waiting for openwhisk developer's response.

**Comment by csantanapr** [comment]
@anasanjaria what are you waiting on ?

Configuring the docker deamon, follow by a restart it's what the script does today
https://github.com/apache/incubator-openwhisk/blob/master/tools/ubuntu-setup/docker.sh#L27
```
sudo service docker restart
```
I recently merge a change that to all.sh that all script run sequentially no more async, hope this helps with some of the inconsistencies

**Comment by uzdry** [comment]
Well, i am still having the same issue. And another problem for me is that i have to run gradlew with sudo because it does not get access to docker. (My user is in the docker group and i restarted)

**Comment by uzdry** [comment]
@anasanjaria @theharshbhatia Was the problem solved for you?
@csantanapr It is not solved for me

**Comment by anasanjaria** [comment]
I am not sure about the deployment failure. After failure of this below command 

`ansible-playbook -i environments/<environment> openwhisk.yml`

I hit this URL `http://172.17.0.1:12001/ping` in my browser and it returns `pong` as a response. Here is my output of the command `docker ps`

![selection_002](https://user-images.githubusercontent.com/499739/27287428-e38b5d7e-5503-11e7-880f-ffe395187dda.png)

Please note that for `Ubuntu 16.04 LTS`, we need to set the following options to start Docker daemon on a specific port.

```
# cat /etc/systemd/system/docker.service.d/docker.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock --storage-driver=aufs
```
Source: [https://sreeninet.wordpress.com/2017/01/27/docker-1-13-experimental-features/](https://sreeninet.wordpress.com/2017/01/27/docker-1-13-experimental-features/)

And this is not [working](https://github.com/apache/incubator-openwhisk/blob/master/tools/ubuntu-setup/docker.sh#L20) for me.

@csantanapr 

- Can you please let me know if it's a successful deployment as I think the invoker is up? I have explicitly run `./bin/wskdev edge` to run nginx. 

- Is it possible if I can use the latest version of Docker (docker-ce) for openwhisk deployment? I wanted to use live container migration feature of docker-ce in openwhisk.

**Comment by csantanapr** [comment]
@anasanjaria 
In ubuntu I have seing docker config in `/etc/default/docker` and `/etc/systemd/system/docker.service.d/docker.conf `

For ubuntu 14, the effective one is the first one.
For ubuntu 16 I have not tried yet.

you can verify which one is running by seeing the process `ps -ax | grep dockerd`

About the ping if you can ping from curl or browser, then it could be something going on with ansible client doing the curl
Check that you have the correct version of ansible 
https://github.com/apache/incubator-openwhisk/blob/master/tools/ubuntu-setup/ansible.sh

If the system is not critical and your setting for development try to treardown all and deply fresh
```
wskdev teardown
rm ansible/db_local.ini
wskdev fresh
```
If you want to know if its a successful deploy deployment you can try invoking a simple action

I have not try docker 1.13 or the community edition of docker, I will suggest you use docker 1.12 since it's the version we are using today in OpenWhisk.

**Comment by uzdry** [comment]
@csantanapr Well, my docker config is here: /lib/systemd/system/docker.service

**Comment by Anuraag-Advani** [comment]
Hi, I was able to deploy wsk but I also got this error `docker-engine : Depends: libsystemd-journal0 (>= 201) but it is not installable`. I was thinking that we should not encounter it if we run all.sh as it calls docker.sh, but we still do. All of the other errors are related to it.

**Comment by uzdry** [comment]
@Anuraag-Advani This is easily solved by adding ```deb http://cz.archive.ubuntu.com/ubuntu trusty main in /etc/apt/sources.list``` (Or the one to your country) to your sources.list
Maybe using a bit of Google might have helped with that.

**Comment by Anuraag-Advani** [comment]
I got it working, I was saying that using the script without any external action to be done by a user

**Comment by uzdry** [comment]
It is a script for Ubuntu 14.04. That part works with 14.04

**Comment by Anuraag-Advani** [comment]
What is the issue you are facing?

**Comment by uzdry** [comment]
The same thing as @anasanjaria @theharshbhatia and @nicschreiber, Basically the main thing this issue is about.

**Comment by Anuraag-Advani** [comment]
ok sorry but I was getting the same error but I resolved it by adding deb `http://cz.archive.ubuntu.com/ubuntu trusty main in /etc/apt/sources.list`, so I thought it was something else.

**Comment by saurabh1284** [comment]
@anasanjaria , I am also getting same issue both with local as well as distributed env deployments. Are you to fix it ? I tried all above mentioned steps.. But same error ""http://172.17.0.1:10001/ping' waiting for this to reply "pong" ?

**Comment by zhanghuanhao** [comment]
@anasanjaria I have the same issus on Ubuntu 18.04. And I followed the same steps to setup the openwhisk. Then I met the problem. Now I solved by setting up **db_local.ini** . I checked the controller logs and found that it couldn't connect to `127.0.0.1:5984`  so it threw an error. Try to configure the **db_local.ini** and set `db_host=172.17.0.1`. Hope that it would help you.
