### ISSUE TITLE
introduce a 'binary' kind to distinguish from 'docker' kind

### ISSUE THREAD

**Issue by sjfink** [apache/incubator-openwhisk#2331]
I think the "modern" way to do arbitrary actions (https://www.ibm.com/blogs/bluemix/2017/01/docker-bluemix-openwhisk/), which injects a binary into a container, is fundamentally different from the original "docker" actions which download a docker image from dockerhub.

I propose calling the new ones "binary -- this issue will entail introducing the new 'kind' and documenting.

**Comment by rabbah** [comment]
This PR should address it: https://github.com/apache/incubator-openwhisk/pull/2112

**Comment by csantanapr** [comment]
Would this let me specify both a zip that get's send in /init, and also specify the docker image ?

Meaning let's say I have a few npm packages that are not included in the nodejs runtime, and the the npm packages go above the 48MB, let's say 80MB.

Can I create a nodejs zip action call it nodejsaction.zip small without the npm pakcages.
Then create a new docker image that extends from openwhisk/nodejs6action with the only modification that I add more npm packages (80MB) to the image

Then do something in the cli like:
`wsk action create --kind native --docker csantanapr/fatnodejs myaction nodejsaction.zip`

**Comment by rabbah** [comment]
Yes. There is an separate issue/feature request for that. The pr does both. I used native as the kind name rather than binary.

**Comment by csantanapr** [comment]
Yes I review the code, I was just double checking my understanding 👍

**Comment by rabbah** [comment]
Related to https://github.com/apache/incubator-openwhisk/issues/2011

**Comment by rabbah** [comment]
@sjfink I called the option `--native` in the proposed pr. Do you have a strong position on `--binary` vs `--native`? I opted for the latter because the executable need not be an actual binary (it could be a shell script) but I admit this is a little nuance.

**Comment by sjfink** [comment]
@rabbah native is fine

**Comment by rabbah** [comment]
Closed by https://github.com/apache/incubator-openwhisk/commit/9c1f77fdb1e4a7339634434dc90c45026d6a43d2.
