### ISSUE TITLE
document how to add swift dependencies via Package.swift

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#2351]
We document how to compile swift and create a zip action using the swift docker container.
https://github.com/apache/incubator-openwhisk/blob/master/docs/actions.md#packaging-an-action-as-a-swift-executable

The steps are missing how an user would add a dependency by using Package.swift

This is one way I got it to work
I tried this today and the steps missing are:
Before running `/swift3Action/spm-build/swiftbuildandlink.sh`

Delete the file `swiftbuildandlink.sh`
 `rm /swift3Action/spm-build/swiftbuildandlink.sh`

Delete the build folder `spm-build/.build/`
`rm -rf /swift3Action/spm-build/.build/`
Edit for example using vim, or replacing the file `spm-build/Package.swift`
`cp -f /owexec/Package.swift /swift3Action/spm-build/Package.swift`
For example I tried adding a package used in swift.org examples `https://github.com/apple/example-package-deckofplayingcards.git`

```
import PackageDescription

let package = Package(
    name: "Action",
        dependencies: [
            .Package(url: "https://github.com/IBM-Swift/Kitura-net.git", "1.0.1"),
            .Package(url: "https://github.com/IBM-Swift/SwiftyJSON.git", "14.2.0"),
            .Package(url: "https://github.com/IBM-Swift/swift-watson-sdk.git", "0.4.1"),
            .Package(url: "https://github.com/apple/example-package-deckofplayingcards.git", majorVersion: 3)
        ]
)

```
Make sure at minimum you include `Kitura-net.git` and `SwiftyJSON.git`

Recreate `swiftbuildandlink.sh`
`python /swift3Action/buildandrecord.py`

Then continue with current docs
```
/swift3Action/spm-build/swiftbuildandlink.sh
cd /swift3Action/spm-build
zip /owexec/hello.zip .build/release/Action
exit
```

**Comment by csantanapr** [comment]
@paulcastro @bjustin-ibm any feedback on my experiments ?

Also I see that the directory `spm-build`  contains `_Whisk.swift` and `_WhiskJSONUtils.swift`

```
root@a979d6047b1d:/# ls /swift3Action/spm-build/
Package.swift  Packages  _Whisk.swift  _WhiskJSONUtils.swift  main.swift  swiftbuildandlink.sh
```

If the user wants to split the code instead of having one single swift file it might have a few secondary files, they can be copied over to `spm-build/` and they would be pickup by the `swift build` right?

**Comment by csantanapr** [comment]
In terms of build/init action, user can create a zip or git url with a contract that minimum at the root has `Action.swift` and `Package.swift` and any other swift files, then it's a matter of going thru the process to compile a zip with the compile code.

**Comment by jthomas** [comment]
If you run `swift build -v -c release` rather than the existing shell script it should handle downloading and compiling the packages automatically.

**Comment by paulcastro** [comment]
For pre-compiled binaries, we can skip the `swiftbuildandlink.sh` and just use `swift build -c release` directly.

**Comment by csantanapr** [comment]
This is already documented https://github.com/apache/incubator-openwhisk/blob/master/docs/actions.md#creating-swift-actions
