### ISSUE TITLE
dynamic per-user throttling limits

### ISSUE THREAD

**Issue by sjfink** [apache/incubator-openwhisk#2352]
Implement a feature which allows changing the throttling limits dynamically per user.

Two use cases:
    1)  In emergencies, be able to restrict or shut off attackers
    2)  Allow the possibility of supporting higher workloads for a limited set of "special" users

**Comment by rabbah** [comment]
Related to https://github.com/apache/incubator-openwhisk/issues/1041#issuecomment-239466028.

**Comment by markusthoemmes** [comment]
Implemented.
