### ISSUE TITLE
wsk property get does not work if api host is not set

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2358]
```
> WSK_CONFIG_FILE= wsk property get --all
error: The API host is not valid: An API host must be provided.
Run 'wsk --help' for usage.
```

If I'm trying to get all the properties, I think the CLI should just show what is set and what isn't.

Trying to override this:

```
> WSK_CONFIG_FILE= wsk property get --all --apihost xxx
whisk auth		
whisk API host		
whisk API version	v1
whisk namespace		_
whisk CLI version	2017-06-09T21:18:47+00:00
whisk API build		Unknown
whisk API build number	Unknown
error: Unable to obtain API build information: Get openwhisk.ng.bluemix.net/v1: unsupported protocol scheme ""
```

Seems to show there's a baked in reference to bluemix somewhere: https://github.com/apache/incubator-openwhisk/blob/master/tools/cli/go-whisk/whisk/client.go#L36 which should not be present, and looks like a bug since the default does not seem to hold if that was intended.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #131](https://github.com/apache/incubator-openwhisk-cli/issues/131) via [**ZenHub**](https://www.zenhub.com/)
