### ISSUE TITLE
While following Mac host setup, docker ps shows an error, also causes failure on ./gradlew distDocker

### ISSUE THREAD

**Issue by zachschultz** [apache/incubator-openwhisk#2368]
## Environment details:

Mac OS local deployment
Docker: Docker version 1.12.0, build 8eab29e
Mac OS: Sierra 10.12.5 (16F73)
Vagrant: N/A

## Steps to reproduce the issue:

1.   Follow Mac OS guide (https://github.com/apache/incubator-openwhisk/blob/master/tools/macos/README.md)
2.   Get to `docker ps` step
3.   Error

## Provide the expected results and outputs:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
```

## Provide the actual results and outputs:

```
docker ps
An error occurred trying to connect: Get https://192.168.99.100:4243/v1.24/containers/json: http: server gave HTTP response to HTTPS client
```

## Additional information you deem important:
* After trying to finish the guide and run `./gradlew distDocker`, I get the same 2 failures as this issue: https://github.com/apache/incubator-openwhisk/issues/2290 however, I notice the error: `http: server gave HTTP response to HTTPS client` everywhere as well, which leads me to believe that the root of the problem is here

**Comment by rabbah** [comment]
Did you disable tls?

**Comment by zachschultz** [comment]
@rabbah Yes, I did run `./tools/macos/tweak-dockermachine.sh`. Is that the step you're referring to?

**Comment by rabbah** [comment]
Yes - can you verify the TLS setting stuck?

That is check `/var/lib/boot2docker/profile` inside your [docker-machine](https://github.com/apache/incubator-openwhisk/blob/master/tools/macos/tweak-dockermachine.sh#L10) and confirm 
`DOCKER_TLS=no` appears there.

**Comment by zachschultz** [comment]
Hm..., running `docker-machine ssh whisk "echo $DOCKER_TLS"` just returns a blank line. Am I wrong in thinking that would work?

**Comment by zachschultz** [comment]
Here is what I see:
```
docker@whisk:~$ sudo cat /var/lib/boot2docker/profile

EXTRA_ARGS='
--label provider=virtualbox

'
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem


DOCKER_TLS=no
DOCKER_HOST='-H tcp://0.0.0.0:4243'
EXTRA_ARGS='--userns-remap=default'
DOCKER_TLS=no
DOCKER_HOST='-H tcp://0.0.0.0:4243'
EXTRA_ARGS='--userns-remap=default'
DOCKER_TLS=no
```

**Comment by zachschultz** [comment]
It seems the issue is resolved...restarting the process and initially SSH-ing into the machine (after running `./tools/macos/tweak-dockermachine.sh` then deleting the line `DOCKER_TLS=auto` made my `docker ps` run fine, and so far, `./gradlew distDocker` run fine as well. Because `DOCKER_TLS=no` gets appended to `/var/lib/boot2docker/profile` after the `auto` line, it should override it, and this shouldn't be the reason `gradlew` works for me now...but it does.

**Comment by rabbah** [comment]
Glad you got it working. Do you think I should close this issue or is there something for us to fix (in which case, might you be interested in contributing a patch)?

**Comment by zachschultz** [comment]
Thanks for showing me the profile file! Regarding fixing it, I really have no idea why it decided to work, so I'm not sure what I would patch. For now I think it can be closed, but I can try to recreate it in a new setup and see if changing the `./tools/macos/tweak-dockermachine.sh` script to remove the `DOCKER_TLS=auto` solves the issue from the start.
