### ISSUE TITLE
dead code in CLI command line parsing

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2380]
I think these lines are currently deadcode:
* https://github.com/apache/incubator-openwhisk/blob/master/tools/cli/go-whisk-cli/commands/action.go#L884-L887
* https://github.com/apache/incubator-openwhisk/blob/master/tools/cli/go-whisk-cli/commands/action.go#L898-L901
* https://github.com/apache/incubator-openwhisk/blob/master/tools/cli/go-whisk-cli/commands/action.go#L904-L905

because the parameter and annotation parsing is happening here instead:
https://github.com/apache/incubator-openwhisk/blob/master/tools/cli/go-whisk-cli/commands/commands.go#L132

I only checked `actions.go` but suspect since this code is common to triggers and packages, the same will apply there.

Should this code be removed? 
Also, I code in `commands.go` for parsing annotations and parameters could be refactored for reuse.

So my understanding is that they exist in the parameter list strictly for usage generation.

**Comment by dubeejw** [comment]
@rabbah, your second link points to the below lines. Please explain why you think they should be removed.

```
actionCreateCmd.Flags().BoolVar(&flags.action.sequence, "sequence", false, wski18n.T("treat ACTION as comma separated sequence of actions to invoke"))
    actionCreateCmd.Flags().StringVar(&flags.action.kind, "kind", "", wski18n.T("the `KIND` of the action runtime (example: swift:default, nodejs:default)"))
    actionCreateCmd.Flags().StringVar(&flags.action.main, "main", "", wski18n.T("the name of the action entry point (function or fully-qualified method name when applicable)"))
    actionCreateCmd.Flags().IntVarP(&flags.action.timeout, "timeout", "t", TIMEOUT_LIMIT, wski18n.T("the timeout `LIMIT` in milliseconds after which the action is terminated"))
```

**Comment by rabbah** [comment]
That's because we just merged a CLI change. I'll update the links. I'm preferring to the parameter and annotation parameters which are not parsed by cobra. My understanding is that these exist here only because of the help/usage generation.

**Comment by rabbah** [comment]
https://github.com/apache/incubator-openwhisk/blob/master/tools/cli/go-whisk-cli/commands/action.go#L904-L907 for example.

**Comment by dubeejw** [comment]
@rabbah, you're right that those flags are only there for displaying usage information. Cobra doesn't actually process those flags as we do it manually.

**Comment by rabbah** [comment]
Thanks for confirming. We should add a comment in the source to this effect. I'll close this issue.
