### ISSUE TITLE
custom parameter parsing in CLI ignores command separators

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2381]
The parameter parsing that's going on in `commands.go` can lead to surprising results. It ignores `-` and `--` as command separators. For example:

```
> wsk action create echo tests/dat/actions/echo.js
ok: created action echo

> wsk action invoke echo -p -b -r
ok: invoked /_/echo with id 9172aa2c35c34e0eacd031b641e850ee
```

`-b` and `-r` are both CLI parameters for blocking invoke with results projection. They are interpreted however as parameters for the action:

```
> wsk activation result 9172aa2c35c34e0eacd031b641e850ee
{
    "-b": "-r"
}
```

This affects both parameters and annotations.
```
> wsk action update echo -p -p -a -a -a -p
ok: updated action echo

> wsk action get echo annotations
ok: got action echo, displaying field annotations
[
    {
        "key": "-a",
        "value": "-p"
    }
]

> wsk action get echo parameters
ok: got action echo, displaying field parameters
[
    {
        "key": "-p",
        "value": "-a"
    }
]
```

This is related to #2380.

**Comment by mdeuser** [comment]
On the surface, I'd say this is working as expected.  When a `-p` or `-a` flag is specified, the next two space-separated arguments are taken as the parameter key and value, respectively.  If they are valid JSON (object or string), then the command will not consider this an error.  In the examples above -b, -r, -p, and -a are all valid JSON strings and the command consumes them as such.

**Comment by rabbah** [comment]
Sure but usually parameter parsing treats - and -- and as options; wsk action invoke x -p p -b where I intended to do a blocking invoke but forgot the parameter value seems like a bug in the parameter parsing to me. I'm willing to accept this as a feature just find it to be surprising behavior.
