### ISSUE TITLE
JVM heap size is not set correctly for Java actions

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2389]
Java actions run with no heap settings, regardless of the container's memory limit: https://github.com/apache/incubator-openwhisk/blob/master/core/javaAction/Dockerfile#L38

This will cause a reused Java action to eventually be killed because the GC may not get a chance to run.

```bash
>  docker run -m 64M -it javaaction bash
# java -XX:+PrintFlagsFinal -version 2>&1 | grep MaxHeapSize
    uintx MaxHeapSize                              := 1035993088                          {product}
```

That's ~1GB even though memory limit for container is 64M.

**Comment by jsanda** [comment]
Is something like [this|https://github.com/fabric8io-images/java/tree/master/images/jboss/openjdk8/jdk] along the lines of what you have in mind? run-java.sh is the default command for the image. Among other things it sets the JVM heap size based on container limits.

**Comment by rabbah** [comment]
Issue moved to [apache/incubator-openwhisk-runtime-java #5](https://github.com/apache/incubator-openwhisk-runtime-java/issues/5) via [**ZenHub**](https://www.zenhub.com/)
