### ISSUE TITLE
Refactor Swift Whisk object to use URLSession

### ISSUE THREAD

**Issue by paulcastro** [apache/incubator-openwhisk#2392]
URLSession seems stable enough to use to make network calls for the Whisk Object.   There already exists a function `postUrlSession` in `_Whisk.swift` that can invoke an action.  Using this function instead of the `post` function in `_Whisk.swift` based on KituraNet would move us to using the standard networking class in Foundation.

This is orthogonally related to PR #2391

**Comment by rabbah** [comment]
@paulcastro is this still relevant? If so, should this move to the runtime or client repo?

**Comment by paulcastro** [comment]
No longer relevant.  I'll close this.
