### ISSUE TITLE
Unable to set the api host

### ISSUE THREAD

**Issue by Katiyman** [apache/incubator-openwhisk#2411]
## Environment details:

* Ubuntu 16.04 
* Docker version 1.12.0, build 8eab29e

## Steps to reproduce the issue:

1.   try setting apihost like below
2.   ./wsk property set --apihost 10.xxx.11.xx:5009
3.   since the api host is having port no it will throw error 

## Provide the expected results and outputs:

```
ok: whisk API host set to 10.xxx.11.xx:5009
```

## Provide the actual results and outputs:

```
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
```

## Additional information you deem important:
* i have distributed OW setup with    
* i am using HAProxy as LB. 
* i wanted to add LB ip and port as api host

**Comment by dubeejw** [comment]
@Katiyman, as a work-around, try appending `http://` in front of the apihost when you set it. Ex: `./wsk property set --apihost http://10.xxx.11.xx:5009`

**Comment by Katiyman** [comment]
@dubeej thanks James .. will do and let you know...

**Comment by lzbj** [comment]
I submitted a pr just start the discussion, @dubeejw @rabbah , should we consider add a port flag or we just need to parse the possible integer settings like 10.xxx.11.xx:5009?

**Comment by dubeejw** [comment]
I think there is another issue here regarding not being able to provide a port, @lzbj.

**Comment by dubeejw** [comment]
```
wsk property set --apihost 192.168.99.100:80
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
```

**Comment by dubeejw** [comment]
@Katiyman, did that help solve your issue?

**Comment by Katiyman** [comment]
@dubeejw yups that seemed to have worked.. thanks

**Comment by vikashsahu4** [comment]
@Katiyman How do we select the api for apihost?
