### ISSUE TITLE
wsk action update fails with --web true

### ISSUE THREAD

**Issue by akrabat** [apache/incubator-openwhisk#2428]
## Environment details:

* Local Vagrant installation of OpenWhisk, commit `db21c089dac0e7bf87fbf648a83d50ef974cf673` (current tip of `master`).
* `wsk` client from Bluemix, version `2017-06-17T19:12:56+00:00`.

## Steps to reproduce the issue:

```
$ wsk action update hello hello.js --web true --kind nodejs:default
error: Invalid argument(s). Unable to get action 'hello': The requested resource does not exist. (code 173)
Run 'wsk --help' for usage.
$ wsk action update hello hello.js --kind nodejs:default
ok: updated action hello
```

## Provide the expected results and outputs:

I expected the action to be created when I use `--web true`.

**Comment by rabbah** [comment]
Confirmed this is a bug. The CLI on update is fetching the action first to merge annotations. When it cannot find the action it is aborting incorrectly in this case. This will happen when enabling web actions.
