### ISSUE TITLE
Is it possible to replace kafka with other messaging

### ISSUE THREAD

**Issue by JanakiRubicon** [apache/incubator-openwhisk#2470]
Is it possible to replace kafka 

1. If yes, how to implement this
2. How to map ngnix (80) port to apigateway call from 9001 ( wsk api create action)
3. How to verify the up and downtime of the call in console (http://host/8500/ui/#/dc1/services)

Thanks in advance

**Comment by rabbah** [comment]
The "lean" loadbalancer is one example of replacing kafka. See https://github.com/apache/incubator-openwhisk/pull/4216 for an example.
