### ISSUE TITLE
Move field filter to a flag 

### ISSUE THREAD

**Issue by bpoole16** [apache/incubator-openwhisk#2472]
Currently, field filter is an argument that can be sent along side of activation id; i.e. `wsk activation get ACTIVATION_ID FIELD_FILTER`. Because there are two arguments sent in, there is no way to distinguish the activation id from the field filter. I suggest that we make field filter a flag instead to allow for the distinction of the activation id. See example below.
```
wsk activation get cc5ea085c7824846959269f4a4c14e6f --fieldFilter response
```
I'm currently working on adding the flag `--last` to `wsk activation get` and this would allow for more precise error handling. #2334

**Comment by dubeejw** [comment]
@bjustin-ibm, can you label this as cli and enhancement.........
