### ISSUE TITLE
invoker doesn't work propertly in case of heavy load

### ISSUE THREAD

**Issue by keunseob** [apache/incubator-openwhisk#2481]
## Environment details:

* Openwhisk on Kubernetes based on AWS EC2
* ubuntu 14.04, Kube 1.5.6

## Steps to reproduce the issue:

1.   setup Environment Openwhisk on K8s
2.   set 3 invokers pod
2.   create a action (similiar to helloword)
3.   try to requst lots of trigger action as **blocking mode**

## Provide the expected results and outputs:
after lots of request consistently (about 3~4000), invoker can't return proper response. 
it returned only activation id, i already knew about it is normal.. but after invokers consumed all of requests, it has to be return proper response.
but It will not be .... even waiting for a long time.
once invoker can't return response propertly, invoker didn't work properly anymore
so, i tried to check invoker log as below

> [2017-07-11T05:54:55.453Z] [WARN] [#tid_113086] [ContainerPool] getContainer has been waiting about 10000 ms: position = 7872 completed = 7869 slack = 1 maxActive = 4 activeCount = 3 startingCounter = 0
> [2017-07-11T05:54:55.453Z] [WARN] [#tid_113086] [ContainerPool] getContainer has been waiting about 10000 ms: position = 7872 completed = 7869 slack = 1 maxActive = 4 activeCount = 3 startingCounter = 0
> [2017-07-11T05:54:55.453Z] [WARN] [#tid_113086] [ContainerPool] getContainer has been waiting about 10000 ms: position = 7872 completed = 7869 slack = 1 maxActive = 4 activeCount = 3 startingCounter = 0

in this case, invoker not able to handle requests.
however controller log shows it is healthy...

it need to be fixed... current healthy checker mechanism is used only for checking invoker creation..

**Comment by markusthoemmes** [comment]
Those logs inform you of long internal queue times. @rabbah has a PR (#2425) which is going in very soon which at least makes up for a proper backpressure mechanism, these logs should go away.

Nonetheless the invoker should eventually handle all the load you hammer at it. Was this not the case? Are you deploying only on a single invoker?

**Comment by keunseob** [comment]
Thanks for your information. I already know about the poll when i received the activationId from OW.
however i'm afraid that it would be not right result user want.
and @rabbah 's PR also looks great. however regarding health checking is not little different approach of me. I give it a try to suggest another PR that i tried and tested recently.

**Comment by rabbah** [comment]
Referencing https://github.com/apache/incubator-openwhisk/issues/2506 as the underlying issue.
