### ISSUE TITLE
Specifying the --shared Flag in CLI with Package List does not Work as Expected

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk#2485]
The following command should list only public packages, but instead shows all packages.
```
wsk package list --shared true
```

In additon, the following call should show only private packages.
```
wsk package list --shared false
```

The request from the CLI to the controller seems not to return the proper result
`https://{deployment_address}/api/v1/namespaces/_/packages?limit=30&public=true&skip=0`

**Comment by rabbah** [comment]
This is explicitly disabled today.

**Comment by dubeejw** [comment]
Okay, sounds like we should hide the option from the CLI then.

**Comment by rabbah** [comment]
https://github.com/apache/incubator-openwhisk/blob/master/tests/src/test/scala/whisk/core/controller/test/PackagesApiTests.scala#L157
