### ISSUE TITLE
Condition "'environments/docker-machine' in inventory_dir" dows not work correctly in ansible/roles/cli/tasks/download_cli.yml

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk#2487]
Since we have changed from "environments/mac' in inventory_dir" to "environments/docker-machine' in inventory_dir" in ansible/roles/cli/tasks/download_cli.yml, we run into the error that mac environment still downloads the Linux binary into the path openwhisk_home/bin, which leads to binary wsk not working.

Here is the log when install openwhisk on mac:
```
TASK [cli : download cli (linux) to openwhisk home at /Users/vincent/workspace/openwhisk] ******************************
Thursday 13 July 2017  11:56:30 -0400 (0:00:00.463)       0:01:20.946 ********* 
changed: [172.17.0.1 -> localhost]

TASK [cli : download cli (docker-machine) to openwhisk home at /Users/vincent/workspace/openwhisk] *********************
Thursday 13 July 2017  11:56:31 -0400 (0:00:01.030)       0:01:21.976 ********* 
skipping: [172.17.0.1]
```

**Comment by rabbah** [comment]
https://github.com/apache/incubator-openwhisk/pull/2455?

**Comment by houshengbo** [comment]
@rabbah That fix is on the correct direction, but I added my comments regarding my concern.
