### ISSUE TITLE
Revisit Kafka ConsumerGroup strategy

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk#2498]
As of today, all invokers are part of one consumer-group, `invokers` (but each invoker has its own topic). This is very useful to monitor the state of all consumers at once, but it also implies a danger. When one invoker disconnects due to failure, Kafka rebalances the whole group, resulting in a huge delay of message polling for **all** invokers.

Since each invoker has its own topic anyway, the rebalancing is entirely useless. We should revisit this.

**Comment by cbickel** [comment]
https://github.com/apache/incubator-openwhisk/pull/3067

**Comment by markusthoemmes** [comment]
Done!
