### ISSUE TITLE
Missing active acks are not factored into invoker health

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2506]
As part of https://github.com/apache/incubator-openwhisk/pull/2482 it's suspected that the health actions which may end up queued are not properly registering an unhealthy invoker.

Need to investigate, confirm and address. I'm fairly sure it's broken (need a test as well for added coverage).

FYI @cbickel

**Comment by keunseob** [comment]
@rabbah thanks good! i'm investigaing more and making a patch in different way

**Comment by rabbah** [comment]
Addressed by 8e7c8e5bc7f2cd672c2314d13e56ef8f94cb96f6.
