### ISSUE TITLE
Set a User-Agent header in wsk cli requests

### ISSUE THREAD

**Issue by mdeuser** [apache/incubator-openwhisk#2568]
The `wsk` CLI currently does not set a User-Agent header when sending requests to the OpenWhisk backend.  Setting this can help distinguish between various clients' access to the backend.

**Comment by drcariel** [comment]
Do we have a preferred value for the User-Agent Header? Keep it simple?

```User-Agent: CLI```

or more complicated?

```User-Agent: <product> / <product-version> <comment>```

**Comment by mdeuser** [comment]
i like the latter.  we'll want the cli version included to distinguish between various builds..

**Comment by drcariel** [comment]
Got some code @ https://github.com/apache/incubator-openwhisk/pull/2591 if you wanna check it out

**Comment by drcariel** [comment]
os.Setenv/os.Getenv was the easiest way for me to get access to the build version since it was intentionally excluded from the available Config

**Comment by rabbah** [comment]
@drcariel this is complete no? closing as I believe so, reopen otherwise.
