### ISSUE TITLE
Add user agent header for CLI http client

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#2571]
#It will be useful for operators to distinguish http clients, this way we can see how many % of users/usage is using the CLI vs other type of http clients.

This is more useful for deployment and crud operations, to see the usage of the tools.

Set a default value something like "OpenWhisk-cli...", and allow to override this thru env variables in ansible for example, for operators compiling the code with modifications and be able to override it.

cc @mdeuser

**Comment by markusthoemmes** [comment]
duplicate of #2568?

**Comment by csantanapr** [comment]
closed by #2951
