### ISSUE TITLE
CLI should note the requirement of the bluemix CLI

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk#2574]
## Environment details:

* local deployment, vagrant, native ubuntu, Mac OS, Bluemix, ...   
Ubuntu on Windows

## Steps to reproduce the issue:

I was trying to get a list of my APIs, but needed to wsk bluemix login first. I have to use the --sso option, and when I did, I got:

 Unable to authenticate with Bluemix: Error reading config file '/home/ray/.bluemix/.cf/config.json'

When I installed the bluemix CLI itself (and logged in), I was then able to successfully login with wsk as well. 

I believe the wsk CLI should provide a quick message stating the folks need to install the bluemix CLI first (only for API stuff of course).

**Comment by rabbah** [comment]
This seems like an issue for the bluemix CLI wrapper and hence I'm inclined to close this issue as invalid for this repo.

**Comment by rabbah** [comment]
we could use this issue as a way of consolidating thoughts around `wsk login <provider>` support that's being discussed in slack.

FYI @tysonnorris
