### ISSUE TITLE
compile failed  with "./gradlew distDocker"

### ISSUE THREAD

**Issue by zhy989** [apache/incubator-openwhisk#2579]
when I run CLI "./gradlew distDocker",
there is an error about swift-3.0.2-RELEASE-ubuntu14.04.tar.gz not found

- https://swift.org/builds/swift-3.0.2-release/ubuntu1404/swift-3.0.2-RELEASE/swift-3.0.2-RELEASE-ubuntu14.04.tar.gz:
2017-08-07 06:56:48 ERROR 404: Not Found.

**Comment by markusthoemmes** [comment]
We know about this issue, will try to mitigate until Swift brings the binaries back.

**Comment by DQvsRA** [comment]
I have this problem when 
**Executing**:
/openwhisk# ./gradlew distDocker

**Problem**:
/root/.sdkman/candidates/java/current/bin/java: 1: /root/.sdkman/candidates/java/current/bin/java: Syntax error: end of file unexpected (expecting ")")
