### ISSUE TITLE
Difference in output for successful/unsuccessful blocking activations

### ISSUE THREAD

**Issue by ioana-blue** [apache/incubator-openwhisk#258]
I've noticed that the output for successful/unsuccessful blocking activations is quite different. In the case of successful activations, the return object is printed. In the case of unsuccessful activations, there is more information provided, including the start/end times for the activation and the logs. 

I found the logs very useful when playing around and experimenting with actions/activations and I was wondering whether we should include them for the output of `invoke` when the activation is successful.

**Comment by rabbah** [comment]
The result of an activation is an activation record - always - if the response code is `200`. Can you give more details on what you mean by "successful/unsuccessful" and how you are invoke the action?

**Comment by ioana-blue** [comment]
`wsk invoke --blocking <action-name>` if the response code is 200, the result of the activation is printed, but not its logs. if the response code is different than 200, the start/end timestamps + the logs get printed. what I care about is logs when the response code is 200. 

I have to note that this is cod run by a new python action that I'm adding. If I need to do anything special to get the logs printed, let me know, I thought that part of the code is language-agnostic.

**Comment by rabbah** [comment]
The API response is the same. The CLI, when you run with `--blocking`, in addition to printing the activation id as with non-blocking activations, will also project the result. If you want the full activation record or just the logs, of course you can get it by its id.

**Comment by rabbah** [comment]
I don't think this is still valid:

```
> wsk action invoke /whisk.system/samples/echo --blocking
ok: invoked /whisk.system/samples/echo with id 646457dbaadd49a5b9b4ddbaa39223a9
{
    "activationId": "646457dbaadd49a5b9b4ddbaa39223a9",
    "annotations": [],
    "end": 1470901383752,
    "logs": [],
    "name": "echo",
    "namespace": "guest",
    "publish": false,
    "response": {
        "result": {},
        "status": "success",
        "success": true
    },
    "start": 1470901383745,
    "subject": "guest",
    "version": "0.0.1"
}

> bin/go-cli/wsk action invoke /whisk.system/samples/echo --blocking -i
ok: invoked /whisk.system/samples/echo with id 851664d8294946b38155d74b18e01cc8
{
    "namespace": "guest",
    "name": "echo",
    "version": "0.0.1",
    "subject": "guest",
    "activationId": "851664d8294946b38155d74b18e01cc8",
    "start": 1470901393743,
    "end": 1470901393748,
    "response": {
        "status": "success",
        "success": true
    }
}
```

**Comment by rabbah** [comment]
(accidentally closed.)

@mdeuser @dubeejw why is the go CLI output different for the activation record?

**Comment by markusthoemmes** [comment]
Is this solved by dropping the schemas @dubeejw ?

**Comment by dubeejw** [comment]
This issue can be closed. Currently displayed from blocking actions:
```
ok: invoked /_/e with id a3e945a273dd41fda00409b8ee98bf5f
{
    "activationId": "a3e945a273dd41fda00409b8ee98bf5f",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": ".../e"
        }
    ],
    "duration": 2559,
    "end": 1489158351081,
    "logs": [],
    "name": "e",
    "namespace": "...",
    "publish": false,
    "response": {
        "result": {
            "key": "vale"
        },
        "status": "success",
        "success": true
    },
    "start": 1489158348522,
    "subject": "...",
    "version": "0.0.1"
}
```
