### ISSUE TITLE
Feature request: Allow java action entrypoint method name to be configurable

### ISSUE THREAD

**Issue by misl** [apache/incubator-openwhisk#2590]
Looking at the 'wsk' I initially expected the entrypoint method name for java actions already to be configurable:

      --main string            the name of the action entry point (function or fully-qualified method name when applicable)

It mentions fully qualified method name. So I tried using:

    $> wsk action create ... --main my.package.path.ActionClass#methodName

Even though this command is accepted. Invoking the action result in an error. 
After a quick look at the source code https://github.com/apache/incubator-openwhisk/blob/master/core/javaAction/proxy/src/main/java/openwhisk/java/action/JarLoader.java line 61 . I noticed the method name 'main' is hardcoded.

**Comment by misl** [comment]
I was able to add support, but since I am new to openwhisk. I have not yet been able to test it locally. Once confirmed locally I will issue a pull request.

**Comment by rabbah** [comment]
We had envisioned that the "main" should be called `main` and you control the class name - I suppose this would make java actions more in line with other kinds.

**Comment by misl** [comment]
Having the option to control the entrypoint name allows me to have multiple entrypoints in the same class. For instance a create and an update action on the same model are very similar, why should I be **forced** to separate them over 2 classes.

I did a small test to see the impact of a separate class on jar size:

- Add same entrypoint to different class increased jar file by 700 bytes
- Duplicating the entrypoint in the same class (with different name) increases jar file by 27 bytes

This was done with a plain hello world action.

I know that if I was really concerned about jar size I should only include only a single action in the jar file and remove everything not used by that single action. But from a coding perspective (sourcecode readability) this separation seems like additional complexity to me, making it harder to understand. I like to see it more like a REST resource, where I would put the various operations on that resource close together as well.

**Comment by rabbah** [comment]
Thanks for the added explanation. 👍

**Comment by misl** [comment]
Yay, seems my changes have been accepted and committed. Am I allowed to close this issue now?
