### ISSUE TITLE
Inconsistent entity name printed in CLI for invoke/fire versus other commands

### ISSUE THREAD

**Issue by underwoodb-sd-ibm** [apache/incubator-openwhisk#2597]
The confirmation messages for `wsk action invoke` and `wsk trigger fire` list the entity by its full qualified name (including a namespace), while all other confirmation messages list the entity without the namespace. 

For example:

```
$ wsk action invoke testPack/testAction
ok: invoked /guest/testPack/testAction with id 4edd1e1efafe439bb2a43656859943b3

$ wsk trigger fire testTrigger
ok: triggered /guest/testTrigger with id 849e5a8773c64e8c8af4c35567f18492
```

Compared to:

```
$ wsk action create testPack/testAction test.js
ok: created action testPack/testAction

$ wsk action get testPack/testAction
ok: got action testPack/testAction
...

$ wsk trigger create testTrigger
ok: created trigger testTrigger

etc...
```

I propose an update which will make these confirmations uniform in how they display entity names, either all including the namespace, or none including the namespace. Which direction to go would be up for discussion here.

**Comment by rabbah** [comment]
Issue moved to [apache/incubator-openwhisk-cli #166](https://github.com/apache/incubator-openwhisk-cli/issues/166) via [**ZenHub**](https://www.zenhub.com/)
