### ISSUE TITLE
Invoking action via CLI with the -b and -r options gives non-zero exit code 

### ISSUE THREAD

**Issue by mdeuser** [apache/incubator-openwhisk#2617]
## Environment details:

* Bluemix

## Steps to reproduce the issue:

1.   Create an action (normal action or web action) that returns a promise that's resolved with a JSON object
```
function main(args) {
   return new Promise((resolve, reject) => {
       resolve({"response":{"SomeField":1}});
   });
}
```
2.  Invoke the action via CLI using the `-b` and `-r` options
3.  Compare results to invoking action with just the `-b` option

## Provide the expected results and outputs:
Exit code of 0 and output:
```
{
  "response": {
    "SomeField": 1
  }
}
```

## Provide the actual results and outputs:
Exit code of -56 and output:
```
error: Unable to invoke action 'YOUR-ACTION': The connection failed, or timed out. (HTTP status code 200)
Run 'wsk --help' for usage.
```

**Comment by cfjedimaster** [comment]
To add a bit more context, it seems to revolve around the name of the key and the value. When I change "response" to anything else, it works. If I change the value to a simple string, it works. If I change the value to an array, it works. As soon as I use: "reponse":{ ...} it fails via the CLI. The code runs 100% fine though. In my original code, I was using Twitter's API to send out a tweet and it ran fine, it's just the error in the CLI.

**Comment by rabbah** [comment]
I'll guess this has to do with the cli searching for "response" which is also part of the schema for an activation.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #129](https://github.com/apache/incubator-openwhisk-cli/issues/129) via [**ZenHub**](https://www.zenhub.com/)
