### ISSUE TITLE
How can I restart OpenWhisk?

### ISSUE THREAD

**Issue by cmdhema** [apache/incubator-openwhisk#2673]
Hello

I write codes on controller and invoker and others. And then, I did rebuild and deploy and successfully.

After that, I invoke action with wsk cli command, but it did not apply my codes.
For example, I write logging code on src/main/scala/whisk/core/container/ContainerUtils.scala
runDockerCmd function 'logging.info(this, "Run Docker Command")

and rebuild, deploy, wsk action invoke

FInally I checked log files(tmp/wsklogs/invoker0_logs.log

but the log codes not working.

How can I apply my codes?

thanks

**Comment by rabbah** [comment]
openwhisk/bin/wskdev controller0 invoker0

This will rebuild and redeploy both. 
You can see what wskdev is doing with -n.

**Comment by cmdhema** [comment]
@rabbah Thanks for your reply. What are controller0, invoker0? 
I try ./wskdev controller0 but I got message that "unknown component controller0"

I using ubuntu16

Thanks

**Comment by rabbah** [comment]
Indeed it's just controller and invoker. No instance number.

**Comment by cmdhema** [comment]
@rabbah Thank you very much! I can't find about that.

Thank you

**Comment by cmdhema** [comment]
@rabbah Hello, I still have that problem.

I done wskdev controller invoker. But my code still not apply.
I wrote logging code on core/invoker/src/main/scala/whisk/core/container/ContainerUtils.scala
runDockerCmd function 'logging.info(this, "Run Docker Command")

Is it right check tmp/wsklogs/invoker or controller?

Thanks

**Comment by rabbah** [comment]
Are you up to date? That code is not active an was recently removed.

**Comment by rabbah** [comment]
You can check logs with `wskdev syslog get controller0` or `invoker0`.

**Comment by cmdhema** [comment]
@rabbah Oh, I pull latest code and I can check my applying codes. Thank you.
