### ISSUE TITLE
Non-blocking web action

### ISSUE THREAD

**Issue by feliu** [apache/incubator-openwhisk#2687]
Is there any way of using a web action using an HTTP request in a non-blocking manner? I understand that the result should be the activation code in this case.
Thanks!

**Comment by rabbah** [comment]
You can programmatically invoke an action from the webaction and return immediately thereafter. If that's not clear I can provide a sample.

**Comment by feliu** [comment]
An example will be very helpful. Thanks

**Comment by feliu** [comment]
any updates?

**Comment by rabbah** [comment]
oops - sorry, slipped off my todos.

here's an example:

```js
> cat delegate.js 
var openwhisk = require('openwhisk')

function main(args) {
   const wsk = openwhisk()

   return wsk.actions.invoke({
          actionName: '/whisk.system/utils/echo',
          params: {args: 'some arg'},
          blocking: false
      }).then(_ => ({ body: 'this is the webaction result' }))
}
```

create the web action:
```bash
> wsk action create delegate delegate.js --web true
> curl `wsk action get delegate --url | tail -1`
this is the webaction result
```

now you can curl this action and it will return as soon as the action is invoked (here i'm using `whisk.system/utils/echo` as an example).

you can use this action in a sequence if your web action handler requires more logic, and use it at the end of the sequence in particular.

does that help?
