### ISSUE TITLE
Curious about Docker Client path

### ISSUE THREAD

**Issue by cmdhema** [apache/incubator-openwhisk#2703]
Hello, I have some curious about Docker client path. 

As I saw source code on 'core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala', there is variable that 'dockerCmd' and this is initialized val alternatives = List("/usr/bin/docker", "/usr/local/bin/docker").

Then, Is it the path( "/usr/bin/docker" or "/usr/local/bin/docker" ) is my host environment docker client path? or other environment docker client path? (For example, In Invoker container)

This is because, I want to change my own Docker for running containers to action invoke.
Thanks.

**Comment by bbrowning** [comment]
That is the path the `docker` binary is expected to be in the Invoker container. The Invoker shells out to that binary for some operations.

**Comment by cmdhema** [comment]
@bbrowning Thanks for your reply. So If I want to use my own docker, am I editing 'core/invoker/Dockerfile' and rebuild and deploy?

**Comment by bbrowning** [comment]
@cmdhema You can either edit that Dockerfile directly or make your own Docker image based off of the default Invoker image. And you'll need to make sure the new Invoker Docker image is picked up by however you're deploying OpenWhisk.

**Comment by cmdhema** [comment]
@bbrowning  Thanks your reply.
