### ISSUE TITLE
Add "icon" attribute for packages

### ISSUE THREAD

**Issue by joachimvaldez** [apache/incubator-openwhisk#271]
@starpit: There should be an "icon" attribute at the package-level for packages Watson, cloudant, git, weather, etc. This will help the UI quite a bit.
I think this can be done by adding an href icon attribute we can link to when we install the packages in installWatson.sh, installWeather.sh, etc.

**Comment by starpit** [comment]
at some point, we may also want to consider per-action icons. e.g. Watson seems to have a TTS icon: http://www.ibm.com/cloud-computing/bluemix/watson/

**Comment by starpit** [comment]
i suggest that we start with hrefs to externally hosted icons. later, we may consider that these are part of the package bundle itself, i.e. hosted by openwhisk, though still presented as hrefs to clients.

**Comment by starpit** [comment]
@joachimvaldez has suggested this icon for Watson
![](https://developer.ibm.com/bluemix/wp-content/uploads/sites/20/2014/10/watsonLogo.png)

**Comment by starpit** [comment]
we also may want to distinguish "icons" into two separate fields:

1. branding: large-scale iconography, that may e.g. include the company trademark
2. inline icons: small-scale iconography that can be used alongside entity listings, etc.

for example, for cloudant, a "branding" attribute might be data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAdEAAABsCAMAAAACPni2AAAA3lBMVEX///8ALHdyx+b///4ALHYAKnZyx+UAKXYBLHlyx+gAH3IAJHMAGXDl6vEAM35/kbfw8vYrSYfZ4OoADW0AG3HO1uUAEm4cPIBSbJ6ksMizwNb1+Ptea5i/yt1UZ5gAJnRSmcYAAGxMkL3j8/ne4+sPNX1Wn8iOnLu84/JleaR0hq4COYMACWwpX5mx3/F0xumW1Ow+WpLN6vYhRIdHY5eQ0uw0UY5kttqeqcOCi6wAAGOpuM9FhrVcqtFgdqUiUZE1cKXJzNiOn73b8PhAfK2GlLC54fQnP36Jwd13gKUd8Li1AAAeMElEQVR4nO1dCWPauLa28S6ZBIhxCg5xGZIhkDRsgTI3bWaa3M68/P8/9HS0WfLC1vY1fcOZKUmwLcv6dPYj2TAOJcsyrIMvPtLbIktAeYT016QCblbCSBw5AvtrEYhX+s8wBi8399NaELi1gP23nN7PXwZWxrVH+kWIYJbMp0s3CCYTgiQh+sF/LO9fEnrOz+7mkbaRhGhwswwCwI9xJyfXJX8GtQl8TG+S7JojtG+WKDSDG8KbVNLWMjQpg5LvXZciHYAInidHMN8+WYNpDUBzBZpBBqpLv6UKFRAH8ZsI2XuUwW+NwBgioAymbjBR5Kz2Q4pe/gtB1r1POJhHQN8cWYDnhADq6kxZRXAIxDPF9Mijb41oROg+oArSDYJqHDW9Sq2noDa3jv7MmyMCyMsSeA6E6gbGzEE6IZBO3Ml0wAJLR1TfBlGBmRAGdZl1uyuLUky56XRz1KZviUCDLiln7oElR1Tw8zSxrGMw/62QZcxp3KBW213g5mniDo7m0RshAoKQuIcRZW53EsyPgL4NsowpMXEOkLgqqPTiv6lTe4T1pxKw1XQfj6WCIGhIXFPmBR0h/WkELJVMQeJ+G541GtQnk+Le4tGnI/0MYqO/3AfMzYYTMa/umVf6gzE9TplyojpvOqH5su02rpv7mb/ErRHjqBbc/PjxPuJZQRTQ+2A765Ued4tfQwzRDeZHofuTiAYE5juF/Fj41qW6knieAU22BRW2lDv4IXF7S6hny3p7ivrNGIPWINiSX+GIsvCDANaFv2tuyWWM4ZMfMehy0N5EYEp/vrfQI0bJsrZTEDfgdWMBjeMHEwZtlYEcTHeO8O5iRgnOlOe9gYxAfsb+7P5wsoz7iYgNbOZQyIIGtAqQUDIYvMzvp4RDJ1UXzFnzh3ar/Nt6K6NDH/l7EcEzUbrTeitqYA51Q1WwUPkpfrmfD+gVlsIrg7+XtdIiB8K8gx/wiON+fEbprn9d/+6t70fk6br/ORN0Fzd+cn84Jdxp2aBGJ647qU1fkooWoISF4qnwOW1tuVMHWJ6cYl9vdcbvZiugh6fTbgsgYwaWsIeMU+SbjLzmz0aUdKcXmoKck/8jRLepp3tmyVSKXYgN1ibTQXUhvWW9wKyY5JogV73sqEZZanY9Og9DhFIgL8Uojhajx8QQoLJTT5H5dhA1fgqilcQGaVDpf2ScGyxfNhtyVjKdBCVs7laxda4jhHqjfogcx/NN3zdtkzCi7ZseDvujL5qr8q9H1DIa7YySIizTKlGbwRPcJ1vcEIvay3mjl/Ds39s0qcXs1/ZDigBD2wYgyU/yB/kdvkLeQ0tZRfWvR5TobnQt6KStHyKj9FIV/MtUK6RSCoZ6rhnLGJSVsQRbmZQ2mowx9nzHNAFRwp428KjvwC8EWwejUz4VraPUJUPQjR1OntdWeZRWj1SyaEBza0Q3stzY9jstdceUrZIJ7q3NjiMc6aWRmZFtqn/Qv7zwumXwYpd/O6KEutk9/Xb+4KDSDeUrJNxguWMo5O+SpkgDxtZYyjP2mOKsJhv7j1zyHhEtIKqN7v3G2B+tCZzvGHCbF2NH8MV8Y+6bHPh6Z/t+jjV1ZrUpmz4zZv+eiO4Spdpywo9B1Np4fwVRJ69Hkw2hIrriZTnNlrRsuj8tUtJMI7Y4xiU+6SYb2TLGdwQyx3Sge2AVEfzYfwr5YCX9p0uZ9Jfj0X2DLNvZpxtXSl1rXspWLPy+nM4HSWLtVlNNulErlrRAHVltYGzSw18RwAcGkM6kjiP6zD/QiBlZuyO641B+W6x9Rx61rI2jUN6bsqNwXOFRL69Hl0HRhWTl1/cve8wu6O58otu64vfgvnJCgNnWp54KcCb5CeZuisLw7CwOo9TzmTtDsUYzPlxbEZWRkGpxLxfS5Q+rBn3uoGWogMu2tyHKC67Yjx2SUaJAi2s6y9LShhzR2NYQVc5I8g4Hy6gEy/leqQ1o8CUICv4ob7NqcpKv29jxGX8S6BzygeLZ10631ep2vj6giGDKxLGPVwK9SkQFFyj/Khgjgzq3TidnMGh/8nHma/fklTsgqg5kuUmi3oVvlaBLDnWaZlLXB0Qt7SlvijKXGjMlgYiNRJezBdytzXO9+1JxEfn3gIlRxKxc4EV8MmrJUUmuhk3k0INOeiLzLJt5lOcQkgalxKoaw1w/qo5Y2mm0wI41nRh8GDcjWnLvPFwlt+VXNcSdLIknOyCkri31qGxyGuTz1YRJpwm/6c7pauYpDu6hvqhoOkPJUelVhrGObK4pfduxnXjWEkcYJZ2I4uehnrysGlFxWW/9Ors9IbSYva7beouMWr2M9DYayhHNeWfD2l5frPyTE39xOeQ9KkdUubDeWw+/jih9fX5s5Q+z59TvSmdOZ9SEZ1g9PbcVFjXgFDkEjuOs2TX8eFLT6jldGly/US7fmZg0GpTVEwbg0JZTI/TAuOU2UYrWRqb+OEvUR6Fjm9FjNr02SF0448s4DCOUeo7tOV6KovBkXEyjjvthxCjsd7Qmev1I0NlDxhx0ytaffdDunk2axlGI1g1jS+6l9fiEY9IUQhgIkfuhd72kMLytkzDkPTq7hCP10zjC5Faek+IoXvXk89U9ch5WrEho8+ydEO6DQGUpWpxQu9/f3M6shmQaFBPgQa2K14eRnXmdjvNYetIap/GzIr6qEKVSpX3pIYfpXtKww/jbf2pLBSXbEKZ02NHu1sscA/zOEGNBr1w3Q0cehNbDVXeT1E06F9ch9uBONtd65BwPI7hMiaqSH61zbtrbNr4gX3XPkSPkKrkQ45GYsPVrz3SUTsAfDn4SHb0JtDIhgHd6cI6aXpgsJwU2dYNBeZv1haOEEcJ1hQXVw2MRAQSqQBTOqI9ibNtyJNgQkZFE8WlDjp7exjZERetG/V3s2aqDRRrGd89ViFrW2gc4s6HPCMcXOWZunXviPED0+c7jFzg0Y+E7IbH06RSoXztmgQBRRlPdOoWKoW/ZdYoq02LIIpjMy1vsxPJJbTP8WtluPVHtm3JEodM9jDgnKNEmFrOIzntqrmEfRJn4b10j088ilXzeOPFTN2tK59HTkJ1EEVBDnMRkwFFLG2aJqAmInka2OneIF0Am5SyRPLoB0aWaGaW1fcs97KEiwaVuSdnRfcmp5N8M+7Lj6SKpunPORqtEdJh6pu/7mWLmY28DEinqqqO9L4+2zlPT10Mg1Di301XGMzqi7TPH98WZ/FqaHoQIGT6/MgqI0qP44vGMxc3kU8DFDhpuRRRSmoEWtaN5swPCJtnIG2A+axKXsv609OTWiXhkMujosfq20ummf5UiSg4NzxyQsMRmNoXgVSHwzhSpvh+iROSeU2NEYurIzIKjDHBOj956NGhi8kxv1hnigttolZTyqG9eX7MUsU2lC7uKjJPTpw8LiOozi5wnER3U9MxoANz0rXtjTHX3hW5OtiwmSck9HpF4TN9PVzvfoIAo07FDKcIJm9Isq+1nwssGC+mxpI2tiFJPYoX13BCwPUwdnXKIDiMW36QxTuiK6B/l2XCoTGFF6son8G0zs4HIxWhM59a1p8sK8pgcUQuS3WKHKU6T2v9sjVNtg/tjcdFERW3KGMlR8qP1lmYzKvIo9LiXMkeIMoTNRaI+lz1UEqXYSY8+R1lTNIvg81D0JkStHnYYfr7IPKjKwEmVk3OIUqb0tfSib3vn5GktsIy0G4MQR9zWtV5yKWrXDT7VD3Fe5EOQvv1WKE0hDQ/KTm16juh0enK1801KpK5lNCKPDbVDhZWDwvjsLCZuaQYrMSNnSaGNXbyXOvZURWji6K7f74fIy0l2DVGi1M4hME3MIES8Yuoka5BFw+xkBVHWpJcS99WTd6T1OjFYAnUPnFs+bsDtpHXE/VHLuqEMmq0xmwTupyfj2+jyfa7EhWrSIqKEFEsXX+xUYUaplEdHkSkycEQcRovxut1u94aXCMsRJ5jIQdxPj55GvmlLIweHF506mUPd8QnSPYl8hGGMfA+F57PX0+HjY2f4ukJY4gY2VXa2xqNESUf+w+j18jbzfwmgPjilRjIk9ISzs8fk769Cn9wUtnB0fwtPjYrsmbUlIUQPrfvvi+F6twRRy7i6k72y0R+bMNSpBFGjHZoir0q8xOuhsJiSLzMkc62+6V1f5dvYyqNEdS08RaOhlQxIXj0hTfDmEf3S95rjL1fyy8aXh8iRTOfgLBGmIEomXuqfwkXJVecaK+IebA2Lx3VFdzyRH2UHbvJ5F4IoikaJTDEUYajSsvzrYYTeFwLFlEet/PnEupcPAdGFnYV9GaKXXA6B0EUrLep3GoogCzmFMCl9gn0sI3CbJfnhSJUmz9msLEG08awmLy2186AMwrX4Vpe63vUX4XFcLbAvJZn3T4PHR7P8qKNnvAuZF4JoaqJFpyFSOmL0xf9lhrDI/5BJdRqa0fuSqogij4KpK/gKEN3gu+SpRI+2TU+oOR+vEtEf9rlGInZMrAuU5KrPdtCjs1SMtemjS33qnSryr4CoJcKjyhdP/M7E7iFSVIynQBRu4cQ9PqYw7T1PGkge+LD0/KrKMasMUWz6aTh7rms9YR1T0jpFgMiB9ozcCL0vKecu1aOdUHCOacaFirZqKkH0ayQtCMdsS4+aa4+xKDQktwLrYj9ErSSVEtdng6o8dzJT5GLO1jUEYFpM3pfcqHhsHFEassQPhshXkP+fhBUEcQnxaJW1gDfFFfe/YXDT06g/Gz62MvnSaHfXD/0nKc7UPvLfe+/6KUQK3pelXyoR5SH1uP1NPCp9NMLtQ6ECLNG7hIdZwN9gTt1ellEvO9c86xi5md4OS2NGlfopuRBcbTvnMhamWkZRj88DKmLaWX8cW9T9VSNKN0dxdURNNt1ThE7O/1k9ADXPz20UYQeZY46yEGvi+a46TYxp2L2gR1m0uOTZOmHm0nHW2YnyiBLTpS8dWw83DCPfVkcoL4LSqmHspUctIrXF4JneoqFPZhCjmdzN8SiHK6lf0ZWIV3U6dl+z7l/LBISCqHeu8A2xH7MjFFFuGVUgOi+sAwYe5VebULCd0rRe6jBhTlxZ7+L5Kj/32sMLP0w9GqjJI8qbL+pRi4wdeNE0421HnfwJ1VTk0W4svE7Kg/lbGXVlVJjjuw+ifyDpEuI/9LkCgHSy4nEt98IEZPI4vlyd03jz7epivK7zJD87vV7gUeHUWOIGjZmcMYxH6QNXIfoS5BYfuYxH86RY0B6O/oMfhp3HLqXO86h5d4ZQFhDL8yjbWa4snda+Y2Vh9KqvfBgOQnSIhLvoR8UcKxm0h+ypYlhCs5fUHWE+1jYYcEonGWibMt5f3sUhwp7jOyZhDwej8G41E2EVx8mWvypx3fRBG4bkUsYldkB0QPfRVbm0HFHpjfk0nuWkKIwgI48i8tPj1Zd+OaLQaFAW17WSvi0yXzLCsAukRan7h0iiEZ+txMSyAHIxJcGq3gvRRJi6ZETjzOoSTW9AtHWJMQ3SwWTweSVyKuNkwKPyVC2bphJBVPL0NkQta1DLLxCsQlRWzdq0Z4y3bJEdYl/7eyFKBuM2yyLQmOWOVORRiajtmYVooiUcJUbRek/LSCAKj3xWz5v7lTxKnEYf+UwK+TRvTR/W920VUdGWwqMFRHeWuhZdIKhFdoMNiMpmWTtKTkNm/aoQFVts5OmJ2NXi8c6622v2KhEdYZGAZNHswiUSUdtmAO6HqMzpxPl5Z1VL3Q7KggaOyVeB2LYSfqdSV9WjPD+q3YHwqBjsrYgadGtHbeOEWm0roqYSsTb13HwFom7NLcl4G1AIKB6UCKPZBl9Xx6hM6tq84sa0W0VALZVHD0GUPTFRN3FhvlQi2vYcpeIBXFkHErd+FgIyi3oUDhFEdT26j2Vk3Odt3WA7oluoxHuha6GKMBk9oaBsmwU5d/NfyqSunPppz8jtqg6/PGf2KPGTVKlr78ijNuW0XCDE2mAZKcYYrH+FYkBidwizg31dZhkV9eheiM51u4iM/fvvgWjO2p0EFYmVf+Tj+Sae7ZqVLbN1pRIoukEWDbzI/mW2Lrf2tnovIxEzLmudXFDqvfTuBIfathc/rNt1iLz31iMPbeBRetdvQjTJL8sOPqs5vEMIvS+o0VpVdedpJB6aiLS4qhQQfHTh3pUgCoZPLEIVPr7kMKqYJk3FH20xHpWsAqaSEt5RBosjOhTn+jZ+1TsGfVqXIvqUifXU7CldaozkkR+CqLaYjG4gpha8HUIlcd2yMiP2HFgpM3BO2kVI6VgnI78usztlPNq6k4j68ZVhaUYWOBgZi+JZw9JsXajoUBcKKRqW+6Od7BvnOh+Kt5QRVxCtN4WTQszvnnI+M8xFa98fUVCkeoSh9hcuVlvsSNRUiz8WFl6wrcfKaISUWswUiRUEauAU0pNReq2gXRLX9R1R9GGjkRi6rIVVNujoD9r+KZd95FmdhYqolTn0WVxXxIyIiD7VA/VEjcqcoIpoG/OAtelpUSwLzDjBMd8DUS+3ItiaT/SKg6D2WSSmDqN04RaXvhSyo/zuRitWr3X8Xl5eWlBeTvQYbmYdL9q6xliaRsTE6uZ9xkflLmc9rQ1ANO0p57cVAcURTRwlFs+3g5BPkPk2porol1i2E6vuhaHx6G4Rhs2I6utHSdcKgd3gL+QLS0Cj0nX1kpj74Hi4UMLgBhs2HnvKVisQTNJ0aOQwbYwieFYfXdcVPco7kgoe7WGxpsDxHSyDDOyC9rWaHWEiYMjLECFaQhynjGY4e+x8fhRukJUqscbHSC0nURHlnrp9l1ubo/Dod0DULCCar64lptKftJIxX0tnO5v2vuAyzEGfXH2dN2w/N68qGKUxdFqQbJpsPXB421EHoDWO6fP7jg+CVyAqquSchTh5hh0pGr2ILSvhY97DitBBzwyKx5DrXbh7+CRQajype7aI6s5umLmRNlqJCQMafhyrKsoDROnDfoml0LhrCT1Cu3SVZVul1LUORNTOahiy8X3Jb2U0cYMP2KGucAagzWYzfaqSZRf0FFidQQDNMyhxj6p2t6LxuUiNi4HaWYwe65S+nF6eIEcWRuJ/uMcqpS6xPbsJWyRKHpFvawVtOONs8o+JByjjx6kINraEVKSH8KpLV2p2VkgVRIJHGytI/IpZhJpdqS0fkCbKnJMraIYi6vOyJ4/WwrPcO3xkGWzT8UT390PUkiuCIT34TAdLydYo+25KXfoJkXlNo8s2B4tyLMHSs4uSl4ZqyBPbKf5Ulu2+r47uke9HkbpQxYfCkfgM1k3GUJsJAwaF90SV+ZgnDiEdxSQIsSNnq1WTiOrkAdtyCkLS77XTrtfbndcUSjBtXiNonvGqYKsuq0B8qntDe7VamXGqaRZZgX0aiuJZuG8ar4bdq3p7/RRj21TLPn2vSZoBId5GohjedM7rkkXBFtR4mpzehD4dgii/b3R3d9c/UUb0pih2iaD89CeKsCeZhyjIFEc+IvJLrwsWORnCHmn44aObnx0T8v/AqJS68PVKfUZWe05mL1184Ms6dChMN+MnOs+/nGXRNS9NvWgMwuwuixHDMKIovjuLQ8RnJjsbvRMrE5ILpZgECthJQ6lDuTyTQRLR5DYVjdPC6DSiG0Ug9uBq7yGhDKN7tcjUayrzQY3uItI4wkm9NB4egGioBBh9Zq/LMU1qOpMG/F2inz99aN6eeIxOzpsf/vv7x/cLVFgZwOath80PvwfFHSMntcnmDVmJKtUghSFjW8jB71kpJPkdz1gBQZ1lyVl+ivygaxGhPkxMW8cUqQ7QzT7f5YGYQJ6wriwoibFN3jzMG9sU0OcRBXqEucyEEb+Arn9glypjC996tzDv1BmT+penvV5vPVohTwgS5tzAhEAHINrWfATb9ySi8OPezW1xwl5tCNuWf/z8O6PPbOmD+/HTSYjSXAbBwTg8+etz6e6CbllMV+FRuo5vgWBtD9OWvmPr9pfNzTQvFAXLyUNqq2vQeOkQGCmOI3W9LS9n/3yHrvwXfUn6ji10IN+L0MybCQJRKD2JfD5P+KoVhj51fiK9y84tnQN3PPFIdwxJURzDmm2TfwN6hGHk04LTfRFt9G2lz76fLrRLYEOM0n3HXICVEoXTpX9//u+f1wjhlBHGCN9++PQ5KNS3CJ28w57JyQyWOChJiYJN7ZtePGbvCQd2jB2RoIX/uAtvPcUmX9BVYr7ZfupLvxM+h5FqzNtiHTFalPGo1ZgVRCztF1E2/zyCvS6OkJ7eMpcHm05u3SPdX9bGEa0f9sVzHsKjhu2ZvmLSeBqi8D7DXV7cA/jAa/Lc4OPn3/77gdFfn37/+JG+LqT0fALzy7aEikV37lSkubQ0ZMbO5p6quMInGt7Pitx5UCYZI4ep+RLzjYjcnmEosikBzzNLFHDY8cNj5r+o60fr59g25VIJEaEiFvh1zxhH6hTkiFKnSTM6aK98POs1PWXOOhxR+Ti7eC8QUlGfLodosnQ37VGfZ1z6PstAvu/H5e++qzh3ujVDRk/o4dARo6QRVYZevNCiSVDknrFLFmZbx1jBJyPHdMKFskUv/dlGmZ8qfsFpvV2+Ipio+9A3bd1Fh8hljy7ptLPbAqI0iBGrWxKwh3Ps8F1iPPZNhXsVRO0tiGZ76bZTdVboiFqsgGy3d3YH8IIC+joQV3zBNkR3y4VuLUi2Isos3mToI2UDT23Sh9dDFQ1wJ87MbI2tRJRYvA9hIXcEJg1iS5gye5CWq5soN4niWb16H4bkNMZOrmW0oHXG7SjNGqJ6lBUJpk5OWqQx1fnDWHnAEqm7MePNBuL5TLXKAVFtoCFwtNebZLUNczbRTbVZpEIKn1enC4RNKk3pjOeaFUfnpzJKwz5gdCPMVakjCzrhaPK4wFiJy4ERkiJz1DZUHcqpPUOpiBzA0i8E22/oiGbTiHz2Zghn5Yu2ifHois2w7jUy2RZ4wjKi7a9Q6tiZGvGiBd9RdkzMS4FpxBG1eb1PulHqimBNMg6VgHJm6/JHTAJ3MinZWmofaEtpaRg7QCpKDhrdd2FM3zsAGwZ5OEXRWfzwqJSvZvS4uCPDBfLUjCSP0tRb991dTCw3j24QTZronw9b+RYsPo9IKxFiLzkI++9oEL+Xveyjn1XK8C72ZtA29lKPXHD20Bbsbly960MVJ73nrbwq6TZJ+3RbIkw6sljzR7GM3jlpx4MNphxm66Z3d+KulzqPzvrZy0fahiU732n2I7ZLEiazXh9QC3bGrbJuDiWI78KStJ13daDDkPSGr7PmNbgmzdXlK1vbVRKggJzM6+wczgN/NNdI94+L2YIcO2k+vD63RAuFflBt+vx62VzBeWwDAPWFPO3cGhc66x5J281m8/KVBqAtMTeM1vASbgmV1pl0J1+vXy9XTfosLdYInwPd8eyWnk6jhNprgPROXilH5L64zBIY/nFxCXTxqiX5qEtA7N1J6Z5+hxN9YeXugIohJoNWvwKqN2QJb0lcGL7hJ15pG6bwM9mxeoMNYmWmgE6Aer3ekCK9eDxrnPejQS5IhDdtyOqKhHdH2QTFEu2zBRL0dHl+g53dauQ7p4KTryW1JKLsnoz0nrNJ8w3vYy8n2OyKoVE2lqWUX/sjB3TneWHx/5Uh5W2WsailAcJXP+kY6n9Y8gYZc2bfaZZ09ptSH8EBtfJFFtrum3n1kJtkqnWntpF/PottLLWbxbsZSWkFL3cvk6/q1i6XbDm+x4wqY1O9rdy5VZxfLuA3HT+sR5svZbtsfONr2RmmTIfCuyoP6spu/aUfm+fzDq0c2MO8cN5ylpWbDXv18+Auwv7mxIMpZE/2JvZm9kltcMAIH+n7EZHK89LNcQ8kyKH9SB490jYCRXvzHUQua2JSe6GN/uyn+tfTnL0D2D2QVV361gLIkk4G1lHm/nQC5T3nb5Y9WPi6NMS7HBzhfCMErxGteC/erpAG7mSZfOtukUf6XkS3Ja960fpuRF99ZxzuGBzpexNsclTYXG4LX7KwAnv1rDu3jlbumyLLeKH7KO9lHUEWPGB7aA9EOO1Ib4JYbKO4F9k2LmX1gxNaJna0ct8aWfT9ShMpTXdgUS6k75MjoG+QGCIvuWRMID9y3JlhuhxYSq7oSG+HOCDzqdjxPBDI6cvB+Q9aYjQJpgN59RHRt0fM/xhMgVFd+jpvKVkz1VmbSMZ17wdHGH8JGtwsgwlLprg16aiK2G2NFwFO57tvSX6kn0ms7uFmSkt0QQRzj4Zt9UerdDmcR3/llyGqFZOXm+kyV2YNANO3Qu9bJ3Ckn0yyLGLwMr+5n06n7nJJPu/nLy9J7qwjvX3K19Wo38iKrCP9oqSX9R3l7P8HkmWvR5fzTdL/AlmNO1vHLXzyAAAAAElFTkSuQmCC

and an inline-icon attribute might be data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOAAAACGCAMAAADzXnaUAAAAyVBMVEX///9yx+cALHdsxeZ0yur0+/0AHnFUmMFntdgAGG4AKnYAKHX6/f5pxOaL0euX1O3u+PwAIXJ/zOnY8PgAJHPo9vuFzurA5fRGgrDP7Pe64/Ot3fDd8vmd1+6arMlsvt+HlbcbTI3q7fPFzd0RQIU7dKdWoMknXZhfrdMybaQANH9Ji7ksZJ0FOIGm2/BHhLIaR4dhsdiVn7zW3Oe5w9Z9udpAW5MAE2yuuM4xS4jAy95ic598jbJogKtkdaGSnLkABWtIZJnh5e5UhvUtAAAFrUlEQVR4nO2ca1fiOBiAKWkLtOmF0Mv0gggiMiiMM7o67jizq///R22L6EiT2utO3p6Txw+KQk8e3yRvbm2vJxAIBAKBQCAQCAQCgaAZyiu8C9I+OA7CaGe9sovCIOZdpvaYRCaRJQkhJB2+kp9kQqwwxrzL1hRs+xYyEh8myJCswO6wpB3siMF2e3NEJAo62ibt0JRyQnfsKFl+BxVxSErpvSiSiHd5K6L4ee0uB4N0qaLiwKqmtw+jNeFd7rIoU7m6X2JIwm50qBOvjt5e0XR5F74YJarY+o4MJZ93+YtQpvX19ooh7L7GtQoSezFTm7fEB8S1m9+7GJpwDWPS3C8x9KDWUrcVvzQjwoyha7bjB9XQrjF6yTXcwUv5yrRx//kOA97gO2ovfnvDgLdQhrj01AgZ78gf9RBYoza7VAJM3iObkT85dCHKJIhMOWfWiKaQkgXelfBDxAonVKntYMf+5yBIw9KAlNDLXXuJI2YUAVVSpTgDGjs3v+fHzBkWmv5BhY/xCzOEVzBbV1hJ1IAyxcdF8UPFMwSX9TkTSLoPCwRL+LEvIsNIhopXFMAygXAZ1RxIqvAL9IxS/b3N6ohlCK2Q2T+8ycnELBcGm/n5CEArjOU8O5SMWoLYLVfNAmZPTADUUXYXgwwSxVU2jnKGM/y7GWaSR5JZcX8zZKdSZP4/pa6Ay/Kzqv7jsZ+zE2Vwb4SMGorCGisOdsAc7/GfF9JJsO40wN6xUiH3qT1dqPrTHJ9RG3g3wjgr2Gi9iLHuwXvSRDVB0mTw4dIVnvd4NDuVb1alWCsDnCf22a6v4SyVrqOcexmcrVPIanQ9OoKc14BtqtGQ5waXe/6LqqGcp0wxNckZfmtwudsBNXLnvK09yQrKQ+229tVuNrSgBE7wfvu95sWel/ddEBzp6ulNnWvd3I3VLlTRUV9zHh6rK54s9T5DEGAE+31NV//dPJ49LxYLnJJ8X5ydPiyfc3v8xe3mXu93RjBFU+/V66dfpylPT9fJK8fRH88WjIsszk4eRnr6IXiCbq5giu6M1ZRE7SC9/fHt7yNHfPP9n1/LkfPyAWYb5LqdTSX6I0EafewsH+5+np688PPH3cN2PNZf/8wS5JvoqaFagWDaPtO4jl4YJ7HV3v2RKch30SI72C4U/BCWIOcpffZoWuuCvKdL2VWG1gV5T3izSxatC/JessCUoNqqIPdFp142EQ63WrFIBcEdb8HsIsPsyqntpzmUIP+F3+wJIHlQP4L69ZoS5O1H7+8Or/RiFXYAtfPskgzyePv1cHZlVF5vaxo68yEVQACngSaZMiWGulOnmjqbGZ0FARwcpc/Zy7OrbWVFvX9BxQ/GFjbjEIKMVufLZJKgvVlquqNu+vn9q6bOL+n4wTiEwDwfIaP16tPFdjzazwdH6mb+ebBez1V269TV7ZchfREJWQC26Hs5u/SyLM0SVoPBYJ3+gJLfzFZzPeF3XJOOM3ntzAcziXmUgXsSPMAq25tnwrtXX8+v5sukso5T+pvt9cXny6HMPqjRcBugRYrOch0LD1eDyy+fUi4HqzXKsUsFQbTAFNssLXiQ/E3+2+AEsNcLKgmWBc6B2B5u+cx9Cqgjzay956Z+wO5+mbR5W0gKgfYoiLZvDAFVQVNww1s/j+G9WMiivZvPuC9n50BvZ9f2A9bBvGKXfrZDgR/cW0BbuIU39QOU4TO0cpOyBdevDUOo7e8V3NAQ4s2tGaJaT+o46JGQd/GLwUGDh3WAmQF+iF3veQ/IiKCmB4oaQURSR8L3ghJWfCoCMn3wvcsxcVRBEXkh5OTHBrs+Mkrdm20Qv3t6e3CQexf5m50kV75NBhRuaHlSzuMAkl97Ux/2wKUEOA6iqZd5wCFKXnvTMOho1cyCFdsNwp3pecQwDOJ51s4PXLszWU8gEAgEAoFAIBAIBAKBQFCN/wA04WdSX0VrWAAAAABJRU5ErkJggg==

**Comment by markusthoemmes** [comment]
This can be solved via annotations. Still valid/needed @starpit ?
