### ISSUE TITLE
go-sdk - wski18n/i18n.go:97: undefined: Asset

### ISSUE THREAD

**Issue by svenwoldt** [apache/incubator-openwhisk#2723]
Hello,
where is the definition of Asset?

error: ../openwhisk/tools/cli/go-whisk/wski18n/i18n.go:97: undefined: Asset
Much thanks

**Comment by rabbah** [comment]
@mdeuser @dubeejw @jessealva can one of you help?

**Comment by mdeuser** [comment]
the function `Asset` is generated during the cli build.  here are the two lines in the dockerfile that generates the i18n_resources.go files - one for the ui and one for the sdk.

https://github.com/apache/incubator-openwhisk/blob/6b0c03725b43d5454dc07ccc51318675b6b0905e/tools/cli/Dockerfile#L26

**Comment by csantanapr** [comment]
answered

**Comment by dimgiagos44** [comment]
So what is the solution???

**Comment by rabbah** [comment]
@dimgiagos44 are you following the go build steps from https://github.com/apache/openwhisk-cli#build-using-go-build?

**Comment by rabbah** [comment]
@dimgiagos44 ill follow up in https://github.com/apache/openwhisk-cli/issues/512.
