### ISSUE TITLE
Have seen your Invoker inplementation, how's its performence and memory cost?

### ISSUE THREAD

**Issue by hykych** [apache/incubator-openwhisk#2733]
I notice that when a request comes, the Invoker Component create a container for the request.

If a function needs a 256mi memory, 400 requests come simultaneously will cost 100Gi memory. 

Don't you think this  a little bit wasted？I am very confused.

**Comment by markusthoemmes** [comment]
In general, you are right: 400 fully parallel requests will need 400 containers, which results in 100 Gigabyte of memory usage.

Most of the times, those requests are not fully parallel though, so container reuse is in action. You can refer to [my article on invoker performance](https://medium.com/openwhisk/squeezing-the-milliseconds-how-to-make-serverless-platforms-blazing-fast-aea0e9951bd0) for more insight.

**Comment by rabbah** [comment]
The number of containers that run concurrently on any single invoker should be equal to VM memory available divided by expected memory requirement for actions running in that invoker. The memory resource is not generally over committed and hence is the limiting factor for the number of concurrent containers allowed by a single invoker.

**Comment by hykych** [comment]
@markusthoemmes @rabbah thanks
