### ISSUE TITLE
deploy only one controller and one invoker locally

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2758]
local deployment now starts up two controllers and two invokers - is this really necessary for local development?

i would like to suggest that for local deployment and development, the default mode should be one controller and invoker each. 

i don't think we need to deploy more than one invoker, and apart from the `ha` test, i don't think we need a second controller either.

that's not to say some development modes wont require redundancy, just that in the default case, it's not necessary. the reason for this: additional resource requirements for the vm.

thoughts @cbickel?

**Comment by markusthoemmes** [comment]
We decided to deploy 2/2 to make HA required for Travis to be able to assert correct funtionality there.

You're right, that this causes more resource requirements locally. An alternative could be to have an own env for Travis.

**Comment by rabbah** [comment]
+1. I forgot the stem cell containers so we'd reduce active containers by 4. 

is it something we can also do with an env var when running the ansible playbooks? mode=ha for example.

**Comment by starpit** [comment]
+1 on this. in travis "container" mode, one is limited to a 4GB heap.

**Comment by rabbah** [comment]
Proposed patch in #3105 adds `-e mode=HA` to the setup playbook to deploy multiple instances. Otherwise only one instance of the core components is deployed. This works with `redo` as well: `-a "-e mode=HA"`.
