### ISSUE TITLE
cli does not tolerate comment on api host in property file

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2770]
```
> cat ~/.wskprops
APIHOST=http://localhost:10001 #http://192.168.99.100:10001
```

```
> wsk property get
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
```

**Comment by GabrielNicolasAvellaneda** [comment]
@rabbah I've found that actually the problem is generated by any trailing white space, not the comment itself. Anyway, I created https://github.com/apache/incubator-openwhisk/pull/2772 to handle comments and cleanup those white spaces.
