### ISSUE TITLE
Split runtimes into individual repos

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#2791]
Take the builds our from the core repo into individual repos.

High level goals for short term
- Core repo will continue to have gradle project with a the same task `distDocker`
  - This is done to allow for transparent transition, alllow for current flows for dev, test, prod to continue to work with no changes.
  - Invoker and Ansible assumes that all runtimes use the same prefix and come from same 
- Each runtime will only have a `Dockerfile` that extends the runtime from a DockerHub image
  - The Dockerfile will have a pinned image 

Repos to be created by runtime type/language
  - incubator-openwhisk-runtime-nodejs
  - incubator-openwhisk-runtime-python
  - incubator-openwhisk-runtime-swift
  - incubator-openwhisk-runtime-java
  - incubator-openwhisk-runtime-php
  - incubator-openwhisk-runtime-docker

Each repo:
 - Will have same process and structure as in the core repo
    - Will use gradle to build and push images and running tests
 - Have tests and Travis enable
    - The actionContainer tests will be kept in both core an runtime for a while
 - Build and Push docker images
 - Will not have a hard dependency against core/main repository
    - Files will be duplicated (i.e. gradle, scala tests, etc..)

The `incubator-openwhisk-runtime-docker` will produce an image that swift and python will extend to get the common python proxy code.

**Comment by markusthoemmes** [comment]
One (important) word of caution: Let's not build a dependency of those repositories against the main repository. They should be completely stand-alone. If we need to copy a file or two for that, I'd rather do that than building a dependency.

**Comment by csantanapr** [comment]
Yes that's a goal, I will added explicitly.

**Comment by ddragosd** [comment]
Also maybe we should zero in a bit into the individual repo structure that
highlights the directory structure for multiple runtime versions of that
language. I.e multiple NodeJS versions.

**Comment by csantanapr** [comment]
@ddragosd that's also a goal.

As the first pass to be able to migrate the git history I would start with initial repo having same directory structure as today.

First pass for example for nodejs
```
core/nodejsActionBase/
core/nodejs6ActionBase/
core/nodejs8ActionBase/
gradle
tests/
gradlew
build.gradle
settings.gradle
```

Second pass
```
6/
8/
gradle
tests/
gradlew
build.gradle
settings.gradle
```

**Comment by csantanapr** [comment]
OK after talking to @markusthoemmes I want to clarify what it means for independent from main/core repo

All the scala code for testing will not have any dependencies from core repo
A deployment of openwhisk is not required to run unit tests
There will be integration tests and those will be simple test for sanity check end to end
