### ISSUE TITLE
CLI: Support Semantic Versioning

### ISSUE THREAD

**Issue by drcariel** [apache/incubator-openwhisk#2794]
v.r.m semantic version format (i.e. 1.0.0) -- an essential initial component for release management and Homebrew support:

 - https://github.com/apache/incubator-openwhisk/issues/420#issuecomment-249195056 
 - https://github.com/apache/incubator-openwhisk/issues/2178
 - https://github.com/apache/incubator-openwhisk/issues/1880
 - https://github.com/apache/incubator-openwhisk/issues/1677

**Comment by rabbah** [comment]
Issue moved to [apache/incubator-openwhisk-cli #163](https://github.com/apache/incubator-openwhisk-cli/issues/163) via [**ZenHub**](https://www.zenhub.com/)
