### ISSUE TITLE
The Load balancer can't schedule the last invoker when exist more than one invokers

### ISSUE THREAD

**Issue by ningyougang** [apache/incubator-openwhisk#2809]
After installed multiple invokers, access `http://controller:10001/invokers`, all the invoker's status is `up`, but when execute `wsk -i action invoke --result <action>` multiple times, the last invoker can't be scheduled by controller's loadbalancer to deal `the action request`.

I do several tests as below(in centos7, memory:16G, cpu:8 physical cpu total, 8 logic cores total)
* test case one: only deploy two invokers
  status for invokers: {"invoker0":"up","invoker1":"up"}
  only `invoker0` deals the request,  `invoker1` seems don't recevie the request

* test case one: deploy three invokers
  status for invokers: {"invoker0":"up","invoker1":"up", "invoker2":"up"}
   only `invoker0` and `invoker1` deal the request, `invoker2` don't recevie the request. 

* test case one: deploy four invokers
  status for invokers: {"invoker0":"up","invoker1":"up", "invoker2":"up","invoker3":"up"}
  only `invoker0` and `invoker1`  and `invoker2` deal the request, `invoker3` don't recevie the request. 

* test case one: deploy five invokers
  status for invokers: {"invoker0":"up","invoker1":"up", "invoker2":"up","invoker3":"up","invoker4":"up"}
  only `invoker0` and `invoker1`  and `invoker2` and `invoker3` deal the request, `invoker4` don't recevie the request. 

So my test conclusion is that: since all invokers's status is ok, may be there has some bug on controller's `load balancer‘s scheduling strategy`, it leads to the last invoker can't be sheduled by `load balancer` to deal the `action request`

**Comment by markusthoemmes** [comment]
The last invoker is per default only used for blackbox actions. The fraction of invokers used for blackbox invocations is configurable but it's always at least one invoker (today). Arguably, we can adjust that logic to be disablable.

**Comment by ningyougang** [comment]
* What's mean for  `The blackbox actions`, i do not know what role he has.
* Where the configuration for the fraction of invokers?
* regarding `Arguably, we can adjust that logic to be disablable.`, you mean `remove the blackbox actions used the last invoker logic`?

**Comment by markusthoemmes** [comment]
Blackbox actions are actions based on user-provided docker images. Configuration is per environment variable and the code you posted.

We can adjust that logic, so you can completely disable that blackbox actions get their own invokers and are rather shared with all the other invokers.

**Comment by rabbah** [comment]
This is working as designed.

**Comment by hsane2001** [comment]
Does the change to make any invoker pick up blackbox image require changes in source to "ShardingContainerPoolBalancer.scala" or is this configurable in the env variable somewhere?

**Comment by rabbah** [comment]
@hsane2001 this PR https://github.com/apache/incubator-openwhisk/pull/3751 makes it possible to use all the invokers (for small N). Otherwise we don't have a way to disable the blackbox isolation when your N is high enougn (10 invokers for a 10% fraction).
