### ISSUE TITLE
Any way to adapt response to Messenger webhook

### ISSUE THREAD

**Issue by allansduarte** [apache/incubator-openwhisk#2816]
Hi there!

I'm looking for help with Facebook Messenger webhook for a serverless technology bot.

The problem that exists today is the impossibility of responding correctly to the messenger webhook, as it does not accept a JSON dictionary as an answer, but only a token.

Error 400 Bad Request:
```
function webhook (params) {
  if (params ['hub.verify_token'] === 'AWESOME_TOKEN') {
    return Promise.resolve (params ['hub.challenge']);
  }
}
```
Answer is not accepted by webhook:
```
function webhook (params) {
  if (params ['hub.verify_token'] === 'AWESOME_TOKEN') {
    var apiResponse = {
      body: params ['hub.challenge'],
      statusCode: 200
    };

    return Promise.resolve (params ['hub.challenge']);
  }
}
```

Is there any way to send a response without a JSON data dictionary? If there is no alternative to this problem?

Thanks for the help.

**Comment by ddragosd** [comment]
Yes, you can use [webactions](https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md)

**Comment by ddragosd** [comment]
For FB in particular, here's a sample code:

```javascript
function main(params) {
  let verify_token = params.verify_token || "token";
  if (params["hub.mode"] == "subscribe" && params["hub.verify_token"] == verify_token) {
    // this request is just a verification request from Facebook
    return {
      headers: {
        'Content-Type': 'text/html'
      },
      body: params["hub.challenge"],
      statusCode: 200
    };
  };
}
```

Use `--web true` when invoking `action create ...` to create  a web action.

**Comment by allansduarte** [comment]
@ddragosd Thanks for the sample code, but if you can continue to guide me ...

Even with the changed headers I'm getting the same problem.

Facebook webhook returns me:
`Response does not match challenge, expected value = "789827496", received = "{\ n \" body \ ": \" 78982 ... "`

And Openwhisk successfully returns me:
`{"body": "789827496", "statusCode": 200, "headers": {"Content-Type": "text / html"}`

Is there any way to openwhisk to return the `hub.challenge` without a JSON body? Or alternative?

**Comment by rabbah** [comment]
What URL are you using for the webhook? It should not have a .json extension.

**Comment by allansduarte** [comment]
@rabbah I am using IBM Openwhisk with IBM API Gateway for url endpoint.
URL: [/chatbot/bot/webhook](https://service.us.apiconnect.ibmcloud.com/gws/apigateway/api/321c788a37912aeded69af2b85a98a3abc4dc268e1cfc3e3e512848d903e0d31/chatbot/bot/webhook)

In APIGateway `Content response type was enabled`: `Use the "Content-type" header of the action`

How can I see the output in the url... It seems that the header is not being respected, or is there something else to work correctly?

**Comment by allansduarte** [comment]
Updating information ...

Using payload:
```
return {
  headers: {
    'Content-Type': 'text / html'
  },
  body: '123456',
    statusCode: 200
  };
```
Created with --response-type HTTP and working properly.
`wsk api create / webhook / test get webhook --response-type http`
Endpoint for test: [/webhook/test](https://service.us.apiconnect.ibmcloud.com/gws/apigateway/api/321c788a37912aeded69af2b85a98a3abc4dc268e1cfc3e3e512848d903e0d31/webhook/test)

Created via Serverless Framework, probably using --response-type json. Not working.
Endpoint for test: [/chatbot/bot/webhook](https://service.us.apiconnect.ibmcloud.com/gws/apigateway/api/321c788a37912aeded69af2b85a98a3abc4dc268e1cfc3e3e512848d903e0d31/chatbot/bot/webhook)

Is there any way to update --response-type? How to `wsk api UPDATE ... --response-type http
`
**The IBM headers change interface does not appear to respond to changes.**

**Comment by rabbah** [comment]
@jthomas @mdeuser can comment on serverless framework and api gw.
I suggest you at least validate the direct web action URL works.
If you use the `wsk` CLI, try `wsk action get --url actionName` and curl the URL.

**Comment by rabbah** [comment]
```bash
> cat t.js 
function main() {
return {
  headers: {
    'content-type': 'text/html'
  },
  body: '123456',
  statusCode: 200
};
}

> wsk action update t.js t.js  --web true
ok: updated action t.js

> curl `wsk action get t.js --url | tail -1`
12345
```

**Comment by rabbah** [comment]
i suggest you delete the link you have in your action for `Content-type` and type it out from scratch.

**Comment by allansduarte** [comment]
Since it is working perfectly when using the `wsk CLI` and regardless of a content-type lowercase or capitalize ... Everything indicates that it is something in the creation of an API when using Serverless in relation to `--response-type` and I am unable to upgrade ...

@ddragosd @rabbah thank you for the prompt and accurate directions.

I will try to get guidance from this issue with the Openwhisk Serverless team.

**Comment by jthomas** [comment]
This issue can be closed as it's an issue with the serverless framework integration: 
https://github.com/serverless/serverless-openwhisk/issues/80
