### ISSUE TITLE
Failed to build swift3Action docker image

### ISSUE THREAD

**Issue by kevhouck** [apache/incubator-openwhisk#2817]
## Environment details:

* local deployment, vagrant, native ubuntu, Mac OS, Bluemix, ...   
* version of docker, vagrant, ubuntu, ...

## Steps to reproduce the issue:
 
1. ./gradlew distDocker -PdockerHost=<registry_vm_ip>:4243 -PdockerRegistry=<registry_vm_ip>:5000

## Provide the expected results and outputs:

Containers should be built and pushed to registry

## Provide the actual results and outputs:

```
Cloning into '/swift3Action/spm-build/Packages/swift-watson-sdk.git'...
fatal: could not read Username for 'https://github.com': No such device or address
swift-build: error: Git 2.0 or higher is required. Please update git and retry
Building action
Traceback (most recent call last):
  File "/swift3Action/buildandrecord.py", line 36, in <module>
    out = check_output(BUILD_COMMAND, cwd=SPM_DIRECTORY)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['swift', 'build', '-v', '-c', 'release']' returned non-zero exit status 1
The command '/bin/sh -c python /swift3Action/buildandrecord.py && rm /swift3Action/spm-build/.build/release/Action' returned a non-zero code: 1
```
   > Task :core:swift3Action:distDocker

## Additional information you deem important:
* Seems to be an outdated version git being installed in the build container...

**Comment by kevhouck** [comment]
Edit: Reopening issue since the [commit on master](https://github.com/apache/incubator-openwhisk/commit/5f4568cdc0d130813544299885448211784f8200) isn't a true fix

**Comment by rabbah** [comment]
We should deprecate and remove swift 3 (in favor of 3.1.1) and also move all the runtimes to their own repos.

**Comment by csantanapr** [comment]
>We should deprecate and remove swift 3 (in favor of 3.1.1) and also move all the runtimes to their own repos.
Already working on this

**Comment by csantanapr** [comment]
We need to give users a heads up notice before we remove swift:3.0

**Comment by rabbah** [comment]
Closing since we've moved to 3.1.1.
