### ISSUE TITLE
Failed to build :core:php7.1Action:distDocker

### ISSUE THREAD

**Issue by Hugh-ifly** [apache/incubator-openwhisk#2824]
## Environment details:

* native ubuntu 14.04LTS
* version of docker 1.12.0 linux/amd64

## Steps to reproduce the issue:

1.   ./gradlew distDocker

## Provide the expected results and outputs:

containers should be built successfully.

## Provide the actual results and outputs:

> Task :core:php7.1Action:distDocker
Sat Sep 30 08:08:26 UTC 2017: Command 'docker build -t action-php-v7.1 /home/hugh/openwhisk/core/php7.1Action' was killed after 840 seconds, 1 retries left, retrying...
Sat Sep 30 08:08:26 UTC 2017: Executing 'docker build -t action-php-v7.1 /home/hugh/openwhisk/core/php7.1Action'

Step 1 : FROM php:7.1-alpine
 ---> c209d835115a
Step 2 : RUN apk update && apk upgrade &&    apk add        postgresql-dev        icu        icu-libs        icu-dev        freetype-dev        libjpeg-turbo-dev        libpng-dev        libxml2-dev    &&    docker-php-ext-install        opcache        mysqli        pdo_mysql        pdo_pgsql        intl        bcmath        zip        gd        soap
 ---> Using cache
 ---> 2b8a56e98ee6
Step 3 : RUN curl -s -f -L -o /tmp/installer.php https://getcomposer.org/installer     && php /tmp/installer.php --no-ansi --install-dir=/usr/bin --filename=composer     && composer --ansi --version --no-interaction
 ---> Using cache
 ---> eb37103cbb23
Step 4 : RUN mkdir -p /action/src
 ---> Using cache
 ---> 0c71edebb4fa
Step 5 : COPY composer.json /action
 ---> Using cache
 ---> 94c690c26acb
Step 6 : RUN cd /action && /usr/bin/composer install --no-plugins --no-scripts --prefer-dist --no-dev -o && rm composer.lock
 ---> Running in 004c9f44422d
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies

Exception in thread "Thread-163" groovy.lang.GroovyRuntimeException: exception while reading process stream
        at org.codehaus.groovy.runtime.ProcessGroovyMethods$TextDumper.run(ProcessGroovyMethods.java:495)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:336)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at org.codehaus.groovy.runtime.ProcessGroovyMethods$TextDumper.run(ProcessGroovyMethods.java:488)
        ... 1 more

> Task :core:php7.1Action:distDocker
Sat Sep 30 08:22:26 UTC 2017: Command 'docker build -t action-php-v7.1 /home/hugh/openwhisk/core/php7.1Action' was killed after 840 seconds, no more retries left, aborting...

Error response from daemon: no such id: action-php-v7.1
Error response from daemon: no such id: action-php-v7.1
Error response from daemon: no such id: action-php-v7.1

> Task :core:php7.1Action:tagImage
Sat Sep 30 08:22:26 UTC 2017: Executing 'docker tag action-php-v7.1 whisk/action-php-v7.1:latest'
Sat Sep 30 08:22:26 UTC 2017: Command 'docker tag action-php-v7.1 whisk/action-php-v7.1:latest' failed with exitCode 1, 2 retries left, retrying...
Sat Sep 30 08:22:26 UTC 2017: Executing 'docker tag action-php-v7.1 whisk/action-php-v7.1:latest'
Sat Sep 30 08:22:26 UTC 2017: Command 'docker tag action-php-v7.1 whisk/action-php-v7.1:latest' failed with exitCode 1, 1 retries left, retrying...
Sat Sep 30 08:22:26 UTC 2017: Executing 'docker tag action-php-v7.1 whisk/action-php-v7.1:latest'
Sat Sep 30 08:22:26 UTC 2017: Command 'docker tag action-php-v7.1 whisk/action-php-v7.1:latest' failed with exitCode 1, no more retries left, aborting...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/home/hugh/openwhisk/gradle/docker.gradle' line: 96

* What went wrong:
Execution failed for task ':core:php7.1Action:distDocker'.
> Sat Sep 30 08:22:26 UTC 2017: Command 'docker build -t action-php-v7.1 /home/hugh/openwhisk/core/php7.1Action' was killed after 840 seconds

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

## Additional information you deem important:
* issue happens always

**Comment by rabbah** [comment]
@Hugh-ifly is this still an issue?

**Comment by Hugh-ifly** [comment]
It was caused by network inaccessibility, and did not happen any more.
