### ISSUE TITLE
Feature Request: Add support for `--result` flag to `activations get`

### ISSUE THREAD

**Issue by Juice10** [apache/incubator-openwhisk#2841]
It would be really great to have support for the `--result` or `-r` flag when calling `wsk activation get`
This would make the cli consistent with the action invoke flags available: `wsk action invoke [action name] --result`.

## Example
Retrieve the result of "my hello world action":
```
$ wsk action invoke my-hello-world-action --blocking --result
{
    "message": "Hello World"
}
```

Retrieve the same result via the activations list:
```
$ wsk activation get --last --result
{
    "message": "Hello World"
}
```
Response I currently get:
```
$ wsk activation get --last --result
unknown flag: --result
```

**Comment by rabbah** [comment]
`wsk activation result --last` doesn't work?

**Comment by dubeejw** [comment]
```
$ wsk activation result --last
{
    "foo": "bar"
}
```

**Comment by Juice10** [comment]
I noticed that one a little later on indeed.
I'm wondering if we'd like to add the flag version for CLI consistency reasons.

**Comment by rabbah** [comment]
i'd rather keep things orthogonal and avoid two of ways of doing the same thing... `--result` and `--logs` on get, or top level commands as today.

the logs command is worth keeping in my view, since the log interface may change based on on going discussions on the dev list.

**Comment by csantanapr** [comment]
answered
