### ISSUE TITLE
How do you limit the concurrent activations with multiple Controller?

### ISSUE THREAD

**Issue by hykych** [apache/incubator-openwhisk#2856]
I noticed that you use the `activationByNamespaceId` in `LoadBalancerData` to count the concurrent activations.  
However, this is invalid with multiple Controller. Is there anything I didn't noticed or I made a mistake on that code snippet?

**Comment by vvraskin** [comment]
Hi @hykych! 

basically there are two ways you deploy controllers: active-passive (one controller is active, another one becomes active if the first one fails), active-active (requests are dispatched for multiple controllers simultaneously). I think you mentioned the second case. 
So for that we use akka cluster to share the number of activations per namespace and activations per invoker across cluster members. You could look it up here:
https://github.com/apache/incubator-openwhisk/blob/master/core/controller/src/main/scala/whisk/core/loadBalancer/DistributedLoadBalancerData.scala

and here is where we enable this class:
https://github.com/apache/incubator-openwhisk/blob/master/core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala#L105

**Comment by tysonnorris** [comment]
@hykych @vvraskin  I just logged #2859 - is this possibly related?

**Comment by hykych** [comment]
@vvraskin thanks
