### ISSUE TITLE
Use configured protocol for API requests

### ISSUE THREAD

**Issue by mdeuser** [apache/incubator-openwhisk#2862]
See https://github.com/apache/incubator-openwhisk/blob/1110c34ef496115aa0f4252bd38ace3ed881a811/tools/cli/go-whisk-cli/commands/api.go#L821

Instead of hardcoding the protocol to `https` use the protocol configured in the apihost

**Comment by jsanda** [comment]
I submitted [PR 2909](

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #125](https://github.com/apache/incubator-openwhisk-cli/issues/125) via [**ZenHub**](https://www.zenhub.com/)
