### ISSUE TITLE
redact information in test log message

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2882]
- [ ] https://github.com/apache/incubator-openwhisk/blob/d86c415a1d9a4eaa2061eac3a6ce99f24ba390f9/tests/src/test/scala/whisk/core/database/test/RemoveLogsTests.scala#L50
- [ ] https://github.com/apache/incubator-openwhisk/blob/d86c415a1d9a4eaa2061eac3a6ce99f24ba390f9/tests/src/test/scala/whisk/core/database/test/CleanUpActivationsTest.scala#L63
- [ ] https://github.com/apache/incubator-openwhisk/blob/418fcd147dc366d61b9bb943a40b203a381b4bce/tests/src/test/scala/whisk/core/database/test/ReplicatorTests.scala#L79
- [ ] https://github.com/apache/incubator-openwhisk/blob/418fcd147dc366d61b9bb943a40b203a381b4bce/tests/src/test/scala/whisk/core/database/test/ReplicatorTests.scala#L113

will leak information to the console.

**Comment by rabbah** [comment]
also here https://github.com/apache/incubator-openwhisk/blob/d86c415a1d9a4eaa2061eac3a6ce99f24ba390f9/tests/src/test/scala/whisk/core/database/test/CleanUpActivationsTest.scala#L63

**Comment by vooolll** [comment]
https://github.com/apache/incubator-openwhisk/pull/3173#issuecomment-356605689

**Comment by rabbah** [comment]
Thanks for the contribution and fix.
