### ISSUE TITLE
Add a quick status utilility

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk#2886]
It would be nice if there was a quick way to get stats about an action. So something like:

    wsk stats ACTIONNAME

Which would report a very brief summary:

    ACTIONNAME has had X invocations in 24h. Average duration is 219ms. Error rate is 2%

Obviously Bluemix's online reporting can show some of this and you can build your own tools to report similar values, but I'm thinking that the CLI could provide a quick summary of your action and that could be pretty useful.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #123](https://github.com/apache/incubator-openwhisk-cli/issues/123) via [**ZenHub**](https://www.zenhub.com/)
