### ISSUE TITLE
List all namespaces associated for a Subject .

### ISSUE THREAD

**Issue by neerajmangal** [apache/incubator-openwhisk#2889]
I am trying to list the namespaces a user (subject) is associated with. As a subject can be associated with multiple namespaces, if I want to list namespaces for a particular using command

> `wsk namespace list`

It only gives one namespace to which uuid:secret matched (either provided in cmd argument using --auth or wskprop file). If I understand it correctly its because the user's uuid:secret are different in each namespace it is associated/part of and when I user "`wsk namespace list -u <auth string>`", it only list the matched one and may be due to this PR (https://github.com/apache/incubator-openwhisk/pull/1914).     

1. Is there any other way I can list the namespaces associated for a particular user (wskadmin user whois <authkey>), or let me know if I am missing something? 
2. One thing I was trying, when adding subject in different namespaces, I gave the same uuid:secret string in wskadmin command (`wskadmin user create -u "uuid:secret" -ns namespace1 user1`), to see if get the list of namespaces but it is failing with below error. 

`error: Unable to obtain the list of available namespaces: The connection failed, or timed out. (HTTP status code 500)
 `
 
## Environment details:

* local deployment    
* docker version = 1.12.0-0~trusty
* ubuntu version = Ubuntu 16.04.2 LTS

## Steps to reproduce the issue:

1.   Create a user1 in demospace1 using below command 

> `/bin/wskadmin user create -u "uuid:secret" -ns demospace1 user1`

2.   Add user1 to demospace2 using below command, make sure to provide the same uuid:secret provided above.

> `/bin/wskadmin user create -u "uuid:secret" -ns demospace2 user1`

3.   List namespaces associated using "wsk namespace list", provide the same uuid:secret as above.  

> `/bin/wsk  -u "uuid:secret" namespace list`

> `error: Unable to obtain the list of available namespaces: The connection failed, or timed out. (HTTP status code 500)`

I can provide debug/verbose output further, if required.
 
I was expecting the "wsk namespace list" should list the all namespaces associated with same Auth Key. This happens every time if I add a user which is already part of a namespace and then added to another namespace with same uuid:secret. 

If user is only part of one namespace then only "wsk namespace list" command works. 

Is there any issue/limitations if a user is created with same uuid:secret in multiple namespaces?

**Comment by rabbah** [comment]
You can't get this information through the API today and it looks like we don't have a command to list the information for a subject via `wskadmin` but this would a useful addition.

**Comment by rabbah** [comment]
here's a proposed patch for `wskadmin` to list the spaces for a subject:

```git
diff --git a/tools/admin/wskadmin b/tools/admin/wskadmin
index 2dcdc7f..c094db2 100755
--- a/tools/admin/wskadmin
+++ b/tools/admin/wskadmin
@@ -269,16 +269,19 @@ def getUserCmd(args, props):
     (doc, res) = getSubjectFromDb(args, props)
 
     if doc is not None:
-        # try default namespace if no namespace provided
-        namespaceName = args.namespace if args.namespace is not None else args.subject
-        namespaces = filter(lambda ns: ns['name'] == namespaceName, doc['namespaces'])
-        if len(namespaces) == 1:
-            ns = namespaces[0]
-            print('%s:%s' % (ns['uuid'], ns['key']))
-            return 0
+        if args.namespace is not None:
+          namespaces = filter(lambda ns: ns['name'] == args.namespace, doc['namespaces'])
+          if len(namespaces) == 1:
+              ns = namespaces[0]
+              print('%s:%s' % (ns['uuid'], ns['key']))
+              return 0
+          else:
+              print('namespace "%s" not found for "%s"' % (args.namespace, args.subject))
+              return 1
         else:
-            print('namespace "%s" not found for "%s"' % (namespaceName, args.subject))
-            return 1
+            for ns in doc['namespaces']:
+              print('%s\t%s:%s' % (ns['name'], ns['uuid'], ns['key']))
+            return 0
```
