### ISSUE TITLE
Deprecate swift:3.0 kind, direct users to use swift:3.1.1 kind instead

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#2897]
I'm proposing that we deprecate swift:3.0 and get everyone using swift:3.1.1 kind

The default kind for swift is already swift:3.1.1 anyway.

What this means if an user opens a bug against swift:3.0 we are going to tell that 3.0 is deprecated and to try in swift:3.1.1 to see if the bug exists in the new runtime, and then look into how to resolve.

To migrate from swift:3.0 to swift:3.1.1 if the action uses a single source file then it's matter of updating the kind.

If the user is pre-compiling then it needs to pre-compile using the new image as described in the docs
https://github.com/apache/incubator-openwhisk/blob/master/docs/actions.md#packaging-an-action-as-a-swift-executable

I have a repo with an example that shows side by side, and some scripts to make it easier to migrate if need it https://github.com/csantanapr/openwhisk-swift-upgrade

**The actions items to get this done are:**
 1. Update the reference docs to tell users to migrate their actions to kind swift:3.1.1
 2. After a period (maybe 4 weeks) update manifest in invoker to mark it deprecated, meaning user can only read, update, and delete actions with swift:3.0 not invoke.

**Comment by rabbah** [comment]
Since deprecation is a deployment based toggle should master just deprecate immediately?

**Comment by csantanapr** [comment]
@rabbah 
>Since deprecation is a deployment based toggle should master just deprecate immediately?

We are not there yet to be 100% deployment only toggle, there is a build step I think downstreams are using `distDocker` build step.

**Comment by csantanapr** [comment]
>After a period (maybe 4 weeks) update manifest in invoker to mark it deprecated, meaning user can only read, update, and delete actions with swift:3.0 not invoke.

Small clarification only can read and delete, (it can't update the kind).

**Comment by akrabat** [comment]
It would be really useful if when a kind was marked as "deprecated", the action would still run, but couldn't be updated and new actions could not be created with that kind.
