### ISSUE TITLE
should we support non-zip node action with exports.main?

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2918]
if you declare a node.js action with a `function foo` and use `exports.main = foo`, the action will fail to run `Initialization has failed due to: ReferenceError: main is not defined`. Currently we're only supporting `exports.main` for zip node.js action. Should we allow it for non-zip actions as well?

The alternative is using `--main` for the CLI or correspondingly from the API.
This could be an issue for the nodejs runtimes library - @csantanapr wdyt?

**Comment by jthomas** [comment]
I would definitely like this. Would be a nice feature for consistency.

**Comment by rabbah** [comment]
Issue moved to [apache/incubator-openwhisk-runtime-nodejs #14](https://github.com/apache/incubator-openwhisk-runtime-nodejs/issues/14) via [**ZenHub**](https://www.zenhub.com/)
