### ISSUE TITLE
REST test client generates many warnings

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2935]
check any local junit suite or travis and you'll see several of these warnings:

`[2017-11-07T10:23:05.145Z] [WARN] Hostname verification failed on hostname 192.168.99.100, but the connection was accepted because ssl-config.loose.disableHostnameVerification is enabled. Please fix the X.509 certificate on the host to remove this warning.`

Can we disable these or properly use the test certificate to validate the connection?

@houshengbo @dubeejw

**Comment by houshengbo** [comment]
@rabbah This should be fixed, since I have got latest PRs merged.
