### ISSUE TITLE
some tests do not make sense as REST tests

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2936]
with the CLI/REST test split, some tests no longer make sense to run in the latter vs the former. In particular, the `wsk console ` tests are already covered by unit tests, are we gaining anything by running such tests again?

of course a code coverage tool would be preferred but I don't think this particular test suite is adding coverage.

@houshengbo @dubeejw how many of the tests have been fully duplicated and are you planning to audit some of these suites for REST validity?

**Comment by houshengbo** [comment]
@rabbah do not worry much about the divergence of wskcli and wskrest. We keep them now because we do not want to lose coverage of tests. (Better checking twice than missing any.)

We'll have either cli or rest for the openwhisk or the cli repo: the convergence stage.
