### ISSUE TITLE
REST API in Vagrant image

### ISSUE THREAD

**Issue by reiz** [apache/incubator-openwhisk#2949]
I just tried the example with the Vagrant image. Everything is up and running and the example action worked fine. I sshed into the Vagrant box with `vagrant ssh`. How can I access the HTTP API directly? I tried `curl http://localhost/api/actions`, but without success.

**Comment by rabbah** [comment]
Try port 10001.

**Comment by reiz** [comment]
I created an action and found out the URL with this command: 

```
wsk action get greetingAction --url
```

The output is: 

```
https://192.168.33.13/api/v1/namespaces/guest/actions/greetingAction
```

The IP address is written into the Vagrantfile.

**Comment by csantanapr** [comment]
Hum it would be good to create a webaction in the vagrant deployment and try with curl and show the those curl like including `-k` and the hostname.
Be part of the hello message at the end.
