### ISSUE TITLE
Add support for Ubuntu 16.04

### ISSUE THREAD

**Issue by andreasnauerz** [apache/incubator-openwhisk#295]
I have been told that we do not yet support Ubuntu 16.04.
If this is really the case this should be fixed as 16.04 is out since quite a while and more and more people will switch over from 14.04 to 16.04.

**Comment by csantanapr** [comment]
For whom ever wants to contribute this, this is the recommended approach.

### 1. Support both ubuntu14 and ubuntu16
Make the following scripts work out of the box on unbuntu14 or unbunt16.
https://github.com/apache/incubator-openwhisk/tree/master/tools/ubuntu-setup/
```
tools/ubuntu-setup/ansible.sh
tools/ubuntu-setup/docker.sh
tools/ubuntu-setup/java8.sh
tools/ubuntu-setup/misc.sh
tools/ubuntu-setup/pip.sh
tools/ubuntu-setup/scala.sh
```

### 2. Have a way to test it
I think there could be 2 options:
1. Setup Travis to run in matrix running in parallel ubunt14 and ubunt16
2. Update Vagrant deployment to use ubunt16
