### ISSUE TITLE
SwaggerUI on Vagrant box

### ISSUE THREAD

**Issue by reiz** [apache/incubator-openwhisk#2950]
How to access the SwaggerUI on the Vagrant box?

**Comment by reiz** [comment]
I can access the API from outside like this `https://192.168.33.13/api/v1/namespaces/guest/actions`. Would be nice to be able to access the swaggerUI interface if it ships with Vagrant.

**Comment by rabbah** [comment]
Tried https://192.168.33.13/api/v1/docs/index.html?url=/api/v1/api-docs?

**Comment by rabbah** [comment]
@csantanapr since you use Vagrant - can you confirm if this is an issue?

**Comment by dubeejw** [comment]
@csantanapr, can you close this if you can verify the above works.
