### ISSUE TITLE
ApiGW tests sometimes fail with return code 429 (too many requests in the last minute)

### ISSUE THREAD

**Issue by RSulzmann** [apache/incubator-openwhisk#2961]
failing testcases:
whisk.core.cli.test.ApiGwRestTests.Wsk api should verify successful creation of a new API using an action name using all allowed characters
whisk.core.cli.test.ApiGwRestTests.Wsk api should verify failed creation with invalid swagger doc as input
whisk.core.cli.test.ApiGwRestTests.Wsk api should verify delete basepath/path
whisk.core.cli.test.ApiGwRestTests.Wsk api should verify delete single operation from existing API basepath/path/operation(s)
whisk.core.cli.test.ApiGwRestTests.Wsk api should verify successful creation with complex swagger doc as input
whisk.core.cli.test.ApiGwRestTests.Wsk api should verify successful creation and deletion with multiple base paths
whisk.core.cli.test.ApiGwRestTests.Wsk api should verify API with http response type
whisk.core.cli.test.ApiGwRestTests.Wsk api should reject deletion of a non-existent api
whisk.core.cli.test.ApiGwRestTests.Wsk api should successfully list an API whose endpoints are not mapped to actions

example error messages:
org.scalatest.exceptions.TestFailedException: 429 was not equal to 200

org.scalatest.exceptions.TestFailedException: "Too many requests in the last minute (count: 63, allowed: 60)." did not include substring "swagger is missing the basePath field."

**Comment by rabbah** [comment]
The tests should use the returned count to properly throttle and remove the guess work out which is going to get harder to do with multiple controllers active soon on master.

**Comment by mdeuser** [comment]
this failure was introduced when running the cli api gw tests followed by the equivalent rest-based api gw tests.  each test suite is action invocation intensive and were implemented prior to having a return count with the 429 error.  leveraging an explicit throttle count from the backend is a strategic approach, although i'm seeing emails regarding the need for translating exposed PII, so maybe parsing a response won't work in all languages.  in either case, a quick tactical fix will be to settle the throttle completely at the end of the test suite so that downstream tests will start with a clean throttle count.

**Comment by mdeuser** [comment]
fixed via https://github.com/apache/incubator-openwhisk/pull/2963

**Comment by ningyougang** [comment]
@mdeuser 
How strange!! after used the new codes(#2963 already merged) to run test cases.
Why this issue sometimes happen?
```
whisk.core.cli.test.ApiGwRestTests > Wsk api should verify delete basepath/path FAILED
    org.scalatest.exceptions.TestFailedException: 429 was not equal to 200

whisk.core.cli.test.ApiGwRestTests STANDARD_OUT

    Finished test Wsk api should verify delete basepath/path at 2017-11-23 15:09:57.163

    Starting test Wsk api should verify delete single operation from existing API basepath/path/operation(s) at 2017-11-23 15:09:57.163

whisk.core.cli.test.ApiGwRestTests > Wsk api should verify delete single operation from existing API basepath/path/operation(s) STANDARD_OUT
    Action invokes within last minute: 51
    Action invokes within last minute: 52

whisk.core.cli.test.ApiGwRestTests > Wsk api should verify delete single operation from existing API basepath/path/operation(s) FAILED
    org.scalatest.exceptions.TestFailedException: 429 was not equal to 200

whisk.core.cli.test.ApiGwRestTests STANDARD_OUT

    Finished test Wsk api should verify delete single operation from existing API basepath/path/operation(s) at 2017-11-23 15:09:57.306

    Starting test Wsk api should verify successful creation with complex swagger doc as input at 2017-11-23 15:09:57.308

whisk.core.cli.test.ApiGwRestTests > Wsk api should verify successful creation with complex swagger doc as input STANDARD_OUT
    Action invokes within last minute: 53
    Action invokes within last minute: 54

whisk.core.cli.test.ApiGwRestTests > Wsk api should verify successful creation with complex swagger doc as input FAILED
    org.scalatest.exceptions.TestFailedException: 429 was not equal to 200

whisk.core.cli.test.ApiGwRestTests STANDARD_OUT

    Finished test Wsk api should verify successful creation with complex swagger doc as input at 2017-11-23 15:09:57.372

    Starting test Wsk api should verify successful creation and deletion with multiple base paths at 2017-11-23 15:09:57.374

whisk.core.cli.test.ApiGwRestTests > Wsk api should verify successful creation and deletion with multiple base paths STANDARD_OUT
    Action invokes within last minute: 55
    Action invokes within last minute: 56
    Action invokes within last minute: 57

whisk.core.cli.test.ApiGwRestTests > Wsk api should verify successful creation and deletion with multiple base paths FAILED
    org.scalatest.exceptions.TestFailedException: 429 was not equal to 200

whisk.core.cli.test.ApiGwRestTests STANDARD_OUT

    Finished test Wsk api should verify successful creation and deletion with multiple base paths at 2017-11-23 15:09:57.547

    Starting test Wsk api should verify API with http response type at 2017-11-23 15:09:57.549

whisk.core.cli.test.ApiGwRestTests > Wsk api should verify API with http response type STANDARD_OUT
    Action invokes within last minute: 58
    Action invokes within last minute: 59

whisk.core.cli.test.ApiGwRestTests > Wsk api should verify API with http response type FAILED
    org.scalatest.exceptions.TestFailedException: 429 was not equal to 200
```

**Comment by ningyougang** [comment]
After checking, in whiks.properties: `limits.actions.invokes.perMinute=60`
It seems the quest doesn't reach `60`

**Comment by mdeuser** [comment]
@ningyougang Looking at #2998, it seems all is working now for you?

**Comment by ningyougang** [comment]
@mdeuser 
Yes, after using this commit : https://github.com/apache/incubator-openwhisk/commit/1a4493f1facd301d34c2beb5dd011c52d3b2953c

It is ok.
