### ISSUE TITLE
OW Controller should be more lenient about the data type of the statusCode value passed to it from the openwhisk action 

### ISSUE THREAD

**Issue by chris-ratcliffe** [apache/incubator-openwhisk#2971]
## Environment details:

* Bluemix

## Steps to reproduce the issue:

1.   Create a raw http ICF that returns the JSON statusCode entry as a string, like "200" or "500" instead of a numeric, like 200 or 500.  
2.   Execute the ICF using an HTTP REST call and you should see an error like:
```
{
  "error": "Response is not valid 'message/http'.",
  "code": 11061494
}
```
3. If you use an explicit .json content extension, it will work ok, and show the statusCode field as the string value. 
4. Modify the code to return the statusCode as an integer.
5. Retest, and you will find that the default http extension will work now.

## Provide the expected results and outputs:

The default http extension type should work regardless of whether the statusCode is a string or a numeric.

## Provide the actual results and outputs:

The default http extension only works if the statusCode value is an integer.

## Additional information you deem important:

I am 95% sure that my code has always provided the statusCode as a string, and it was working fine up until sometime between Nov. 10 and Nov. 15, when I started seeing these errors, so perhaps the code was previously more lenient and it changed.  (?)

**Comment by chris-ratcliffe** [comment]
Not sure if this qualifies as a bug or enhancement.  If it used to allow the statusCode as a string, and then stopped, I would consider that a regression and a bug.  If it never did, and I am crazy, then its an enhancement I guess.

**Comment by rabbah** [comment]
Related code: https://github.com/apache/incubator-openwhisk/blob/master/core/controller/src/main/scala/whisk/core/controller/WebActions.scala#L234-L238

**Comment by rabbah** [comment]
Closed by https://github.com/apache/incubator-openwhisk/pull/3473.
