### ISSUE TITLE
If you specify --kind and --docker, --docker is silently ignored

### ISSUE THREAD

**Issue by sdague** [apache/incubator-openwhisk#2977]
When you set an action using the wsk action update command, and specify both --kind and --docker, the --docker portion is silently ignored. Instead at least a warning should be provided to the users to ensure that they get something consistent.

This tripped me up when moving from a --kind python:3 to --docker <customimage> as I didn't remember to delete the --kind from my script, then my image wasn't used, the base python3action was used instead.

**Comment by csantanapr** [comment]
@jessealva take a look when you have a chance.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #122](https://github.com/apache/incubator-openwhisk-cli/issues/122) via [**ZenHub**](https://www.zenhub.com/)
