### ISSUE TITLE
'Getting Started' guide assumes I have installed the CLI

### ISSUE THREAD

**Issue by ChrisChinchilla** [apache/incubator-openwhisk#2983]
The main OpenWhisk getting started link leads to https://github.com/apache/incubator-openwhisk/blob/master/docs/actions.md

The guide tells you to use the CLI tool to create an action, but if I follow this link I haven't had anything that tells me what the CLI is yet, or how to install it, which isn't massively helpful.

I'm happy to submit a PR if you want me to, once I figure out the solution myself.

**Comment by rabbah** [comment]
Does this help? https://github.com/apache/incubator-openwhisk/blob/master/tools/vagrant/README.md

The cli is also available to download from a rest end point. I can provide a link if you haven’t found it yet.

**Comment by ChrisChinchilla** [comment]
@rabbah Sure, I found that, but do you think the link should be in the document itself?

**Comment by rabbah** [comment]
:100: will you submit a pr to improve the doc?

**Comment by ChrisChinchilla** [comment]
@rabbah https://github.com/apache/incubator-openwhisk/pull/3078

**Comment by dubeejw** [comment]
Closing as fixed.
