### ISSUE TITLE
configuring local deployment with cli binaries should avoid unnecessary binaries

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3000]
When locally building and deploying OpenWhisk, the gradle & ansible scripts omit, by default, the binaries that do not match the host. That is for mac, only the mac cli binary is built and bundled.

With the remote CLI downloads, the builds are all handled externally but the deployment is fetching all the binaries:

```
cli : download cli (linux) amd64 to Nginx directory --------------------- 2.03s
cli : download cli (mac) 386 to Nginx directory ------------------------- 1.99s
cli : download cli (mac) amd64 to Nginx directory ----------------------- 1.88s
cli : unarchive cli for Mac and Windows --------------------------------- 1.69s
cli : download cli (linux) 386 to Nginx directory ----------------------- 1.61s
cli : download cli (windows) 386 to Nginx directory --------------------- 1.58s
cli : download cli (windows) amd64 to Nginx directory ------------------- 1.55s
cli : unarchive cli for Mac and Windows --------------------------------- 1.12s
```
This adds several seconds to the deployment unnecessarily. It is not clear why the binaries are downloaded twice - I have not investigated the redundancy. It would also be nice to restore the previous behavior where only one binary is fetched by default.

@houshengbo @csantanapr

**Comment by csantanapr** [comment]
This is fix now cli role downloads all.tgz once
