### ISSUE TITLE
Minor typo in ansible/README.md

### ISSUE THREAD

**Issue by sungjunyoung** [apache/incubator-openwhisk#3001]
In line 120,
```
This step is not required for local environments since all prerequisites are already installed, and therefore may be skipped.`
```

There is additional punctuation mark, It is presumed to be a typo.

**Comment by jonpspri** [comment]
Hi.  I'm working on a PR for edits to ansible/README.md, so I'll pull this into it.  PR to be filed later today.

**Comment by sungjunyoung** [comment]
thanks @jonpspri :)

**Comment by jonpspri** [comment]
See [Pull Request 3002](https://github.com/apache/incubator-openwhisk/pull/3002).

**Comment by sungjunyoung** [comment]
LGTM 👍
