### ISSUE TITLE
Loglevel should be configurable via ansible 

### ISSUE THREAD

**Issue by mhenke1** [apache/incubator-openwhisk#3034]
The default log level is set to INFO level in logback.xml
To make local debugging easier this level should be adaptable for each environment via Ansible.

**Comment by style95** [comment]
You can change log level by setting it up in `common/scala/src/main/resources/logging.conf`

**Comment by mhenke1** [comment]
PR: https://github.com/apache/incubator-openwhisk/pull/3042

**Comment by dubeejw** [comment]
Closing as fixed.
