### ISSUE TITLE
Fail when execute 'hello' script

### ISSUE THREAD

**Issue by sungjunyoung** [apache/incubator-openwhisk#3049]
## Environment details:

* [Quick start ](https://github.com/apache/incubator-openwhisk#quick-start)
* vagrant 2.0.1

## Steps to reproduce the issue:

1.   `git clone --depth=1 https://github.com/apache/incubator-openwhisk.git openwhisk`
2.   `cd openwhisk/tools/vagrant`
3.   `./hello`

## Provide the expected results and outputs:

Vagrant have to create vm and run hello action

## Provide the actual results and outputs:

```
...
default: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch
default: E
default: :
default: Some index files failed to download. They have been ignored, or old ones used instead.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Additional information you deem important:

The following errors are likely to occur if the network is slow.
In [VagrantFile](https://github.com/apache/incubator-openwhisk/blob/master/tools/vagrant/Vagrantfile#L50), I added command that enable `multiverse` before  `sudo apt-get update`   
```
sudo rm -rfv /var/lib/apt/lists/* && sed -i ’s/# \(.*multiverse$\)/\1/g’ /etc/apt/sources.list
```

Then, It works as expected.
What do you think of adding the following command to the VagrantFile? This will help developers who anywhere in the world to set the development environment.

**Comment by csantanapr** [comment]
Sounds good can you send a PR with the change?

**Comment by csantanapr** [comment]
Close by #3050
