### ISSUE TITLE
Support pagination for actions, activations, ... in API response

### ISSUE THREAD

**Issue by KeonHee** [apache/incubator-openwhisk#3051]
When I implementing a dashboard, the API was inconvenient because it did not support paging.
This issue is similar to #1414, and I would like to discuss the output

### 1. Link Header
If you add `size` and `current page` to request parameters(like `?page=3&size=30`), It return to response `last page`, `first page`, `next page` and `prev page` in link header.

Like a GitHub API: https://developer.github.com/v3/#pagination
This is also specified in the [RFC](https://tools.ietf.org/html/rfc5988)

Since OW using `?limit=30&skip=0`, a lot of changes are needed. :(

### 2. X-TOTAL-COUNT
This is a way to return to response a `total count value` in custom header.
It is easy to implement, because CouchDb view is already returns total count. Just set header.

**Comment by rabbah** [comment]
I think we can provide the counts - note though that it's possible for activations to back fill in time, so it may still be possible to miss activations where we sort them by date corresponding to their start time.

**Comment by rabbah** [comment]
Here's a proposed patch to get counts with an explicit API call: `GET /namespaces/_/activations?count=true` return `{"activations": N}`
`https://github.com/apache/incubator-openwhisk/commit/7bf8ab260f4a71bb6ab1cdf94b0d2291ed551bce`

**Comment by KeonHee** [comment]
Closed by #3155
