### ISSUE TITLE
How do you decide how many active and idle containers in one Invoker?

### ISSUE THREAD

**Issue by hykych** [apache/incubator-openwhisk#3054]
If you allow too many containers on one Invoker, the host may OOM and start killing containers.

If you decide how many containers on one Invoker strictly base on their memory limit,(eg: only allow 8 1G-memory-limit conatiners on a 8G host), it would be too less containers.

Please tell me how do you decide the containers' number.

**Comment by markusthoemmes** [comment]
As of today, the invoker only supports a fixed number of containers. You'd roughly determine the number of containers by the calculation shown by you. You can also very likely overcommit your memory, since not all containers might use memory to its allowed limits.
