### ISSUE TITLE
if invoker id 0 is offline, invoker id 1 is ignored even if it is healthy

### ISSUE THREAD

**Issue by tysonnorris** [apache/incubator-openwhisk#3091]
## Environment details:

* local deployment (all deployments I've tested exhibit the 

## Steps to reproduce the issue:

1.  deploy a single invoker, with id=1  
2.  restart controller+invoker
3.  invoke any action 

## Provide the expected results and outputs:

expected successful use of invoker1

## Provide the actual results and outputs:

```
[2017-12-11T17:41:24.665Z] [ERROR] [#sid_121] [LoadBalancerService] all invokers down
[2017-12-11T17:41:24.668Z] [ERROR] [#tid_14] [ActionsApi] [POST] action activation failed: no invokers available
```

## Additional information you deem important:
probably only happens with single invoker, related to blackbox vs managed reservation

**Comment by dubeejw** [comment]
Seems somewhat related to https://github.com/apache/incubator-openwhisk/issues/3014.

**Comment by rabbah** [comment]
This is working as designed today. The invokers are seen as seperate and non overlapping pools. It’s conceivable another load balancer heuristic treats the invokers as weighted pools instead.
