### ISSUE TITLE
WhiskAction and ExecutableWhiskAction equality ignores DocRevision

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3120]
Two actions are equal modulo their revision using the default case class equality method. The invoker uses action equality when matching actions to warm containers. That means creating an action, invoking it, then deleting/recreating/reinvoking it will reuse the previous container.

I don't think this was intended but is likely harmless since equality will require that code matches exactly between the two versions (parameters, annotations also).

I'm going to suggest a test to enforce this behavior should we keep it. Otherwise, we need to define an explicit equals method.

**Comment by dubeejw** [comment]
@rabbah, can this one be closed?
