### ISSUE TITLE
no src found in actionProxy

### ISSUE THREAD

**Issue by Hugh-ifly** [apache/incubator-openwhisk#3134]
## Provide the expected results and outputs:

In core/actionProxy, there should be some src files that illustrating how the actionProxy is implemented.

## Provide the actual results and outputs:

In core/actionProxy, there are only Dockerfile and build.gradle. After reading README.md, I could not find any implementations corresponding to ActionRunner, init(), run(), build(), epilogue(), verify(), etc. 
I am wondering is this module being used in openwhisk, or obsolated so there are no src files in this directory?  If not, how can I get the detailed information about actionProxy? Thanks a lot.

**Comment by rabbah** [comment]
The source moved to this repo https://github.com/apache/incubator-openwhisk-runtime-docker/blob/master/core/actionProxy/actionproxy.py

**Comment by Hugh-ifly** [comment]
Thanks! I got it.
