### ISSUE TITLE
I wonder how do you assure tasks are executed and the problem of sync tasks may be block

### ISSUE THREAD

**Issue by hykych** [apache/incubator-openwhisk#3135]
If a Invoker is terminated abnormally, the Ongoing tasks in that Invoker will lost, how do you deal with this situation?

Invokers and Controllers communicate through Kafka,  if too many tasks are async tasks, a new sync task will be blocked. It seems like you labeled the Invoker unhealthy and no longer send message to that topic, am i  corrected?  Why don't you distinguish sync tasks and async tasks, send them to different topics.

**Comment by rabbah** [comment]
An activation once pulled from the kafka bus in an invoker may be lost (or executed but an activation record lost) if an invoker fails, or the connection to couch fails. The execution of an action is best effort, at most once.

The idea of having invoker pools for blocking vs non-blocking requests has been discussed in the past. There’s an ongoing work thread to modify the load balancing to allow work redistribution which is difficult to do today. Once in place - along with a fairness policy - it should be easier to have different pools scheduled. 

If you want to do it today, you can follow the model used to segerate docker actions from other actions in the load balancer.

**Comment by hykych** [comment]
@rabbah what is "docker actions"?

**Comment by rabbah** [comment]
When you create an action with wsk action create —docker
