### ISSUE TITLE
add version as an annotation to activations

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk#3166]
The activation records do not preserve the version of the action that was invoked. To facilitate differential analysis across versions of an activation, and to enable filtering out "i already fixed that" and such use cases, I propose that we preserve this information in the activation record.

option 1: extend the path annotation, e.g. /ns/package/action@semver; this will probably break clients, but is probably the easiest change to the backend

option 2: add a new field to the activation records

**Comment by starpit** [comment]
sorry, this feature was already added. my bad

**Comment by rabbah** [comment]
For reference, the `version` of the activation record is the action's semver: https://github.com/apache/incubator-openwhisk/blob/master/core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala#L472
