### ISSUE TITLE
plugable model for adding action language support

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#319]
As we add more language support (pending #16  and #308) - we should re-architect the language support so that it is not necessarily part of the openwhisk core and rather there is a plugable framework that allows others to add their runtime to openwhisk. Most of the language support is self-encapsulated but there are at least two points that should have extensible adapters: 1. the CLI and 2. the `WhiskAction` enumeration and `Exec` serialization. The addition of `--type` goes to the former but we don't have a mechanism to extend the latter from "outside". We should consider doing this so that language support could even be contributed from external repositories.

**Comment by sjfink** [comment]
We should look at Cloud Foundry and Heroku build packs for inspiration.

**Comment by mrutkows** [comment]
This is a subject that intrigues me, a build pack approach was suggested "out-of-the-blue" at the CF meetup last week.  I have a follow scheduled with the person from Altoros, an IBM partner company.

**Comment by mrutkows** [comment]
This is work I think my team would like to champion.

**Comment by csantanapr** [comment]
We should also take inspiration on container definition, packaging and distribution , since at the end of the day main pack is a custom container with an API contract.

**Comment by markusthoemmes** [comment]
This becomes more important as we're constantly hitting CI/CD build time limits and increase our feedback time as we add more and more runtimes. Also impacts local deployments, especially first-time users with a long installation time.

**Comment by markusthoemmes** [comment]
Taken from another issue opened by me:

## Problem statement

Currently we support a fixed number of runtimes in OpenWhisk "natively". That means a user can upload an artifact specific to the language (i.e. a code snipped) and we will treat it as needed by that language (compile it, run it).

While this is all good, the approach doesn't scale from a CI/CD point of view. We're currently hitting the 50 minute mark in Travis repeatedly and even with that off the table, our build times will just increase over time as we add new runtimes. Building the different runtimes, especially Swift currently, has a big impact on our overall build time. It also impacts first-time contributors as the time to "just deploy the system locally" increases.
## Proposed solution

We could add a plugin system for runtimes and only ship OpenWhisk with a default runtime (Node.js for example). We benefit from this in multiple ways:
1. Build and testtime for just the _core_ system decreases. As we only test what's common for every language. I think it makes sense to define at least one language as being the default though, to facilitate end-to-end testing and have a better test-coverage for that core system.
2. It's easier for contributors to add new runtimes, as they likely don't have to touch the core components.
## Thoughts on design

To implement this we could make runtimes part of the configuration. That configuration would then include the different properties of each runtime, included in `Exec.scala` today.

The configuration needs to be able to tell the system which _image_ to use and which properties to expect for each of the runtimes (Node.js for example takes `code`, Java takes a `.jar` file).

**Comment by rabbah** [comment]
The runtimes manifest makes it possible to build runtimes and integrate them with openwhisk without having to change the core. Each of those runtimes is now built and tested in its own repo.

**Comment by imesh** [comment]
@rabbah @markusthoemmes It's nice to see this feature has been added to OpenWhisk for extending the language support. I checked in documentation and other online resources but I couldn't find much information on how to do that. Would you mind pointing me to any resources available for adding a new language to OpenWhisk using this model without using a native action? Thanks!

**Comment by rabbah** [comment]
It looks like you figured it out https://medium.com/@imesh/apache-openwhisk-runtime-for-ballerinalang-3f18be2d556c?source=linkShare-76041f7388eb-1521463545.

@sciabarracom has offered to write it up.

**Comment by imesh** [comment]
Thanks @rabbah for the update and all your help on implementing it!

**Comment by sciabarracom** [comment]
HI Imesh actually the "pluggable" support is already written. It lives in sciabarracom/incubator-openwhisk-runtime-go and it is in the process of being merged with the new runtime. However I am already working to extend it for Swift but it is actually a general implementation of it for arbitrary binaries. Once done for swift and go it will be a matter of documenting it.
