### ISSUE TITLE
In a HA multiple controllers distributed env, apihost has to manually change.

### ISSUE THREAD

**Issue by saurabh1284** [apache/incubator-openwhisk#3200]
## Environment details:
It is a multiple controllers, invokers distributed setup on ubuntu 14.04

## Steps to reproduce the issue:
After successful deployment, I have to set apihost as wsk property. But It did not takes nginx IP address.
It always takes IP address (along with port number) of one of the controllers.
So, If that controller goes down, I have to manually change apihost to point to other up controller's IP 

## Provide the expected results and outputs:
I was having assumption that in case of HA proxy controllers,  apihost should be the IP address of nginx.
Based on heartbeating from nginx, it will forward to respective controllers.

## Provide the actual results and outputs:
If I set apihost as nginx IP, I get following error:

-> wsk property set --auth $(cat files/auth.whisk.system) --apihost http://100.100.100.91:80 -i -v
ok: whisk auth set. Run 'wsk property get --auth' to see the new value.
ok: whisk API host set to http://100.100.100.91:80

-> wsk action list
error: Unable to obtain the list of actions for namespace 'default': Get http://100.100.100.91:80/api/v1/namespaces/_/actions?limit=30&skip=0: dial tcp 100.100.100.91:80: getsockopt: connection refused

However, if I set apihost to one of controllers IPs(with port number), it works fine.
 
## Additional information you deem important:
This deployment is running on 5 VMs as below = 
1> nginx,couchdb,zookeeper,kafka,registry ( all these inside 1 VM)
2> controller0 
3> controller1 
4> invoker0 
5> invoker1

**Comment by markusthoemmes** [comment]
Hi, you're right using nginx to dispatch between all deployed controllers.

Per default, nginx is only configured to use https though, so your host needs to be `https://100.100.100.91:443`. It should then work as expected.

**Comment by saurabh1284** [comment]
thx @markusthoemmes  !

I set it as per above =
-> wsk property set --auth $(cat files/auth.whisk.system) --apihost https://100.100.100.91:443 -i -v
ok: whisk auth set. Run 'wsk property get --auth' to see the new value.
ok: whisk API host set to https://100.100.100.91:443

But now getting a different error -
-> wsk action list
error: Unable to obtain the list of actions for namespace 'default': Get https://100.100.100.91:443/api/v1/namespaces/_/actions?limit=30&skip=0: x509: cannot validate certificate for 100.100.100.91 because it doesn't contain any IP SANs
Run 'wsk --help' for usage.

**Comment by rabbah** [comment]
Use -i consistently. The ssl cert is self signed and hence not trusted, by default.

**Comment by saurabh1284** [comment]
Thx @rabbah @markusthoemmes !
It worked !
Is there any documentation, wherein I can find configuration details regarding HA proxy and invokers cluster autoscaling ?
If not, please update the documentation.
