### ISSUE TITLE
Passing action container ID in response header or body.

### ISSUE THREAD

**Issue by rahulqelfo** [apache/incubator-openwhisk#3210]
Is there a way in which we can pass the action container ID in the response to action invocations.The benefits could be:

1)Better debugging
2)Help in automation
For example, consider a use case for automation:

A user invokes the same action multiple time.Every new action is invoked after successful completion of the previous one.
The expected result should be that the action should be executed in the same action container.
Such case can be automated when we can get the container ID in either header or body of the response.

**Comment by rabbah** [comment]
My first reaction: that really breaks the function/container abstraction and leaks implementation details. You can know if an action ran inside a warn container or a new container by inspecting the annotations in the activation record. The presence of an `initTime` indicates new container.

**Comment by rahulqelfo** [comment]
Not sure how the passing of Container ID will hamper the container abstraction but yes the above solution works well.
Thanks for the answer.
