### ISSUE TITLE
update docs with correct values for open files/sockets and pids

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#3229]
It should 1024 for both according to the code
https://github.com/apache/incubator-openwhisk/blob/master/core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala#L82-L83

In the docs 
https://github.com/apache/incubator-openwhisk/blob/master/docs/reference.md#per-docker-action-open-files-ulimit-fixed-6464

**Comment by rabbah** [comment]
Fixed by #3231.
