### ISSUE TITLE
Collect test code coverage data

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3243]
We should collect test code coverage data for common, controller and invoker module.

For Scala code we would need to use [scoverage][1] which has a [Gradle Plugin][2]. The docs are bit old and samples do not work with current Gradle version out of the box. It would need to be determined how to use for openwhisk project which has a single "test" project and source code is distributed across 3 modules. 

Some reference links

1. [Gradle Scoverage Sample][3]
2. [Gradle Scoverage][4] - Gradle Plugin source
3. [Scoverage Google Group][5]

@michaelmarth  Also suggested to have a look at https://codecov.io/ which has Github integration

[1]: https://github.com/scoverage/scalac-scoverage-plugin
[2]: https://plugins.gradle.org/plugin/org.scoverage
[3]: https://github.com/scoverage/gradle-scoverage-sample
[4]: https://github.com/scoverage/gradle-scoverage
[5]: https://groups.google.com/forum/#!forum/scala-code-coverage-tool

**Comment by csantanapr** [comment]
Yeah I agree with @michaelmarth let’s integrate with codeconv.io we already have a repo that leverages their free service for open source projects. 

We currretly use it for the JavaScript client, and is very nice to have every PR being evaluated with the codecov report

**Comment by markusthoemmes** [comment]
It'd be sooo great to have this! 👍  for Github integration and fancy reports.

**Comment by chetanmeh** [comment]
Just for reference as @csantanapr  suggested we already have codecov integration for js client. See
https://codecov.io/gh/apache/incubator-openwhisk-client-js for the report and [this pr](https://github.com/apache/incubator-openwhisk-client-js/pull/63#issuecomment-320281397) for sample github commit analysis wrt coverage

**Comment by chetanmeh** [comment]
## How scoverage works

Scoverage [gradle plugin][1] configures a [scala compiler plugin][2] which then instruments the source code and generates instrumented classes in `build/classes/scala/scoverage`. 

It also generates a `build/scoverage/scoverage.coverage.xml` which is a db of source code instrumentation mapping

```xml
<statements>
  <statement>
    <source>/absolute/path/of/openwhisk/common/scala/src/main/scala/whisk/core/entity/EntityPath.scala</source>
    <package>whisk.core.entity</package>
    <class>EntityPath</class>
    <classType>Object</classType>
    <fullClassName>whisk.core.entity.EntityPath</fullClassName>
    <method>apply</method>
    <path>/absolute/path/of/openwhisk/common/scala/src/main/scala/whisk/core/entity/EntityPath.scala
    </path>
    <id>3331</id>
    <start>5251</start>
    <end>5309</end>
    <line>149</line>
    <description>scala.this.Predef.require(parts.!=(null).&amp;&amp;(parts.nonEmpty), &quot;path undefined&quot;)
    </description>
    <symbolName>scala.Predef.require</symbolName>
    <treeName>Apply</treeName>
    <branch>false</branch>
    <count>0</count>
    <ignored>false</ignored>
  </statement>
...
</statements>
```

The instrumented source looks like below (post decompile). Here call is being made to `scoverage.Invoker.` with the position id

```java
 public Seq<String> whisk$core$entity$EntityPath$$apply(Seq<String> parts)
    throws IllegalArgumentException
  {
    Invoker..MODULE$.invoked(3331, "/absolute/path/of/openwhisk/openwhisk/common/scala/build/scoverage"); Invoker..MODULE$.invoked(3329, "/absolute/path/of/openwhisk/openwhisk/common/scala/build/scoverage"); Invoker..MODULE$.invoked(3327, "/absolute/path/of/apache/openwhisk/openwhisk/common/scala/build/scoverage"); Object 
```

Now as test execute and the code path gets executed it would record the invocation in `build/scoverage/scoverage.measurements.xxx` files. Post test complete a task is run which consumes the measurement file and scoverage.coverage.xml to produce a `build/reports/scoverage/scoverage.xml` which the coverage file for that module. Then multiple coverage file can be combined to produce the final report

### Runtime classpath implication

For the instrumented code to work we need to include following deps in classpath (current version 1.3.1)

1.  org.scoverage:scalac-scoverage-plugin_2.11
2. org.scoverage:scalac-scoverage-runtime_2.11

This is simpler for unit test or tests where code from common, invoker and controller is run in same vm as test cases as the scoverage gradle plugin adapts the classpaths. However it posses some challenge with Docker setups

[1]: https://plugins.gradle.org/plugin/org.scoverage
[2]: https://github.com/scoverage/scalac-scoverage-plugin

**Comment by chetanmeh** [comment]
### Code coverage and Docker execution

For capturing coverage stats for tests which hit the controller and invoker docker containers we would need following changes

1. Include the scoverage jars in the docker container and launch script classpath
2. Include the instrumented jars for controller and invoker and ensure that they come before in classpath
3. Provide a writable mount to `<openwhisk>/core/controller/build/scoverage` directory (+ for invoker) such that measurement files can be written

This can possibly be done by producing 2 extra containers which extend the main containers and have been customized for coverage. Further the ansible scripts would need to pick these containers

**Comment by chetanmeh** [comment]
Resolving this for now. Collecting coverage stats for code running in controller and invoker can be dealt later

**Comment by chetanmeh** [comment]
With #3685 merged all planned tasks under this issue are done
