### ISSUE TITLE
bypassPullForLocalImages setting no longer overridable

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3245]
As noted on this PR, https://github.com/apache/incubator-openwhisk/pull/3142#pullrequestreview-93706400 factoring out the runtime manifest to a separate file does not in its current form permit overriding any of the values, including `bypassPullForLocalImages` (this value permits docker pull bypass for locally tagged images).

@dgrove-oss, I think we can fix this a couple of ways: mangle the manifest after reading it from file, or read from pureconfig. What do you think?

Reported by @krugazor on slack.

**Comment by rabbah** [comment]
Should move https://github.com/dgrove-oss/openwhisk/blob/a386e72321d6c2f6957ff7fba8df7ce2d4f09275/ansible/group_vars/all#L26-L34 also the runtimes file.

**Comment by dgrove-oss** [comment]
If you want to assign this to me, I can put a fix together on Monday.

**Comment by dgrove-oss** [comment]
Will be fixed by #3259
