### ISSUE TITLE
How do you prevent users' Actions access to Kafka or couchDb?

### ISSUE THREAD

**Issue by hykych** [apache/incubator-openwhisk#3257]
The containers that run Actions are in the same host with Invoker, don't they have access to kafka or couchDb?  How do you guys prevent breach from happening?

**Comment by rabbah** [comment]
@hykych see this post on the Apache dev list https://lists.apache.org/thread.html/e29ed12c5b8e677678dc7ca1cf0d2ac137205bd350844c3473be9143@%3Cdev.openwhisk.apache.org%3E
