### ISSUE TITLE
Is there a way to debug the action containers?

### ISSUE THREAD

**Issue by rahulqelfo** [apache/incubator-openwhisk#3263]
## Environment details:

* local deployment
* Mac

## Steps to reproduce the issue:

1.   Create an action 'Sleep' with the namespace 'guest'.The action sleeps for 50 seconds
2.   Invoke the sleep action twice (simultaneously) and get the activation ID
3.   Get the details using the two activationID's from the above step
4.   The activation details in response should have the 'init' value to display two action containers were spawned up.

I one of the test runs the same action container were used for both the invocations.So the activation details for invocation1 of sleep actions has the 'init' value but invocation2 utilizes the same action container used by invocation1.

How to debug the above scenario and see why same action container was used.

Also, this cases occurred only twice of the 500 runs.

**Comment by rabbah** [comment]
If you have the system logs still you can use

wskadmin syslog get -g activation-id-1

This will yield results from which you can infer the transaction id (tid_nnn). Repeat the wskadmin operation now using the transaction id.

Then do the same for the other activation id.

**Comment by rabbah** [comment]
Can you describe how you invoked the 500 sleep actions? Are they all sequential blocking invokes?

**Comment by rahulqelfo** [comment]
Thanks, @rabbah ,
It seems there is a problem with the setup.I get the following error when I use the command given above:

./wskadmin syslog get -g a7418b688ebe4f6a818b688ebe7f6a65-1
grep: /logs/controller0/controller0_logs.log: No such file or directory
grep: /logs/invoker0/invoker0_logs.log: No such file or directory


Also, the invoked actions are sequential and  non-blocking (blocking=false&result=true')

**Comment by rabbah** [comment]
result=true implies a blocking invoke. So  second invoke will end up reusing a previous container in that case.

As for missing logs - do you know where your logs are stored? Usually they are in /tmp unless the location is changed in the environment files.

**Comment by rahulqelfo** [comment]
Oops my bad.

Thanks for the clarification.Closing this issue.
