### ISSUE TITLE
Use Maven based dependency instead of gradle project based dependency

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3277]
Currently other OpenWhisk repositories refer to OpenWhisk modules like common, core and test via Gradle project dependency. This creates a tight coupling between the repositories and poses problem as seen in #3249 

With #3061 support was added to generate Maven artifacts and install them in local repositories. Other repositories should leverage these artifacts as dependency. This would later allow them to be pulled from Maven repositories.

the plan of action is to  find out all other projects which rely on openwhisk core project via project dependency and then modify them in following way

Switch to Maven based dependency

	repositories {
	    mavenCentral()
	    mavenLocal()
	}
    dependencies {
        compile "org.apache.openwhisk:openwhisk-common:${gradle.openwhisk.version}"    
    }

Modify travis build to perform Maven install

    ./gradlew install distDocker

Based on [this search][1] there are 8 such modules which need to be modified.

[1]: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/apache/incubator-openwhisk*++file:settings.gradle+%22whisktests%22

**Comment by chetanmeh** [comment]
Below is the list of all OpenWhisk projects which need to be checked for dependency on core. We cannot just rely on sourcegraph as it does not list all modules. For e.g. incubator-openwhisk-runtime-swift has a dependency but is not listed in search result. So need to be manually check

Below is the list of various OpenWhisk projects. Those marked as checked are those which have been converted or not need to be converted

- [ ] [incubator-openwhisk-client-js](https://github.com/apache/incubator-openwhisk-client-js)
- [ ] [incubator-openwhisk-client-swift](https://github.com/apache/incubator-openwhisk-client-swift)
- [ ] [incubator-openwhisk-podspecs](https://github.com/apache/incubator-openwhisk-podspecs)
- [ ] [incubator-openwhisk-vscode](https://github.com/apache/incubator-openwhisk-vscode)
- [ ] [incubator-openwhisk-package-pushnotifications](https://github.com/apache/incubator-openwhisk-package-pushnotifications)
- [ ] [incubator-openwhisk-package-jira](https://github.com/apache/incubator-openwhisk-package-jira)
- [ ] [incubator-openwhisk-catalog](https://github.com/apache/incubator-openwhisk-catalog)
- [ ] [incubator-openwhisk-package-template](https://github.com/apache/incubator-openwhisk-package-template)
- [ ] [incubator-openwhisk-website](https://github.com/apache/incubator-openwhisk-website)
- [ ] [incubator-openwhisk-tutorial](https://github.com/apache/incubator-openwhisk-tutorial)
- [ ] [incubator-openwhisk-sample-slackbot](https://github.com/apache/incubator-openwhisk-sample-slackbot)
- [ ] [incubator-openwhisk-package-rss](https://github.com/apache/incubator-openwhisk-package-rss)
- [ ] [incubator-openwhisk-xcode](https://github.com/apache/incubator-openwhisk-xcode)
- [ ] [incubator-openwhisk-client-python](https://github.com/apache/incubator-openwhisk-client-python)
- [ ] [incubator-openwhisk-sample-matos](https://github.com/apache/incubator-openwhisk-sample-matos)
- [ ] [incubator-openwhisk-wskdeploy](https://github.com/apache/incubator-openwhisk-wskdeploy)
- [ ] [incubator-openwhisk-workshop](https://github.com/apache/incubator-openwhisk-workshop)
- [ ] [incubator-openwhisk-package-kafka](https://github.com/apache/incubator-openwhisk-package-kafka)
- [ ] [incubator-openwhisk-external-resources](https://github.com/apache/incubator-openwhisk-external-resources)
- [ ] [incubator-openwhisk-package-cloudant](https://github.com/apache/incubator-openwhisk-package-cloudant)
- [ ] [incubator-openwhisk-package-alarms](https://github.com/apache/incubator-openwhisk-package-alarms)
- [ ] [incubator-openwhisk-debugger](https://github.com/apache/incubator-openwhisk-debugger)
- [ ] [incubator-openwhisk-devtools](https://github.com/apache/incubator-openwhisk-devtools)
- [ ] [incubator-openwhisk-apigateway](https://github.com/apache/incubator-openwhisk-apigateway)
- [ ] [incubator-openwhisk-client-go](https://github.com/apache/incubator-openwhisk-client-go)
- [ ] [incubator-openwhisk-test](https://github.com/apache/incubator-openwhisk-test)
- [ ] [incubator-openwhisk-slackinvite](https://github.com/apache/incubator-openwhisk-slackinvite)
- [ ] [incubator-openwhisk-playground](https://github.com/apache/incubator-openwhisk-playground)
- [ ] [incubator-openwhisk-GitHubSlackBot](https://github.com/apache/incubator-openwhisk-GitHubSlackBot)
- [ ] [incubator-openwhisk-cli](https://github.com/apache/incubator-openwhisk-cli)
- [ ] [incubator-openwhisk-utilities](https://github.com/apache/incubator-openwhisk-utilities)
- [ ] [incubator-openwhisk-deploy-kube](https://github.com/apache/incubator-openwhisk-deploy-kube)
- [ ] [incubator-openwhisk-selfserve-test](https://github.com/apache/incubator-openwhisk-selfserve-test)
- [ ] [incubator-openwhisk-deploy-mesos](https://github.com/apache/incubator-openwhisk-deploy-mesos)
- [ ] [incubator-openwhisk-performance](https://github.com/apache/incubator-openwhisk-performance)
- [ ] [incubator-openwhisk-runtime-java](https://github.com/apache/incubator-openwhisk-runtime-java)
- [ ] [incubator-openwhisk-runtime-swift](https://github.com/apache/incubator-openwhisk-runtime-swift)
- [ ] [incubator-openwhisk-runtime-php](https://github.com/apache/incubator-openwhisk-runtime-php)
- [ ] [incubator-openwhisk-runtime-nodejs](https://github.com/apache/incubator-openwhisk-runtime-nodejs)
- [ ] [incubator-openwhisk-runtime-python](https://github.com/apache/incubator-openwhisk-runtime-python)
- [ ] [incubator-openwhisk-runtime-docker](https://github.com/apache/incubator-openwhisk-runtime-docker)
- [ ] [incubator-openwhisk-package-deploy](https://github.com/apache/incubator-openwhisk-package-deploy)
- [ ] [incubator-openwhisk-release](https://github.com/apache/incubator-openwhisk-release)

**Comment by chetanmeh** [comment]
Opened PR on all 13 repo which need changes. Once those are merged we can make changes in core

**Comment by jasonpet** [comment]
incubator-openwhisk-package-alarms and incubator-openwhisk-package-cloudant can be marked as done in the table above

**Comment by csantanapr** [comment]
@chetanmeh I merged all the PRs Thanks 💯  👍

**Comment by chetanmeh** [comment]
Thanks @csantanapr and @jasonpet . Resolving this as done then
