### ISSUE TITLE
Update pre commit hook doc in wiki

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3295]
Currently the [wiki for contribution][1] says the commit hook should be set like

```
$ cat /path/to/openwhisk/.git/hooks/pre-commit
#!/usr/bin/env bash
python /path/to/incubator-openwhisk-utilities/scancode/scanCode.py .
```

For me this was not stopping commits which changed build.gradle with no EOL. On checking with @csantanapr  he suggested that commit hook should be something like

```
$ cat /path/to/openwhisk/.git/hooks/pre-commit
#!/usr/bin/env bash

# determine openwhisk base directory
root="$(git rev-parse --show-toplevel)"
python /path/to/incubator-openwhisk-utilities/scancode/scanCode.py . --config $root/tools/build/scanCode.cfg
```

As its not possible to open PR for [wiki][2] opening an issue for proposing the change

[1]: https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines
[2]: https://github.com/isaacs/github/issues/333

**Comment by csantanapr** [comment]
Wiki updated https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines
