### ISSUE TITLE
Allow adding a feed on trigger update.

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk#3297]
Today, updating a trigger (even if it has no feed attached) does not allow adding the feed post-creation.

There are scenarios where that would be very helpful though, for instance: Testing!

One can imagine a user creating Trigger -> Rule -> Action, then inserting a testpayload to the trigger to, well, test everything through. Once she's happy with the behaviour, attach the feed to the trigger via an update and 💥 .

It sounds reasonable to limit this only for **adding** feeds first (for simplicity).

**Comment by rabbah** [comment]
+1 allowing an update of a trigger with a feed if one is not attached makes sense. The current restriction was intended to prevent a trigger that is already attached to a feed to participate in another feed which replaces the first - and neglecting to disable the first feed. With a trigger that does not have an attached feed, there is no such concern.

The `wsk` CLI does not offer `--feed` on `wsk trigger update` and will need to also be updated.
