### ISSUE TITLE
Feature Request: config api that specifies supported runtimes and limits

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk#335]
would it be possible to expose a config API that

1) enumerates the supported runtimes
2) specifies the universe of limits, along with their default and hard-limit values

so that the UI doesn’t have to hard-code this info. also, this will allow backend updates to expand or restrict these options without requiring a front-end redeploy

e.g. openwhisk.ng.bluemix.net/api/v1/config

**Comment by starpit** [comment]
Update: the editor v2 UI now exposes timeout and memory quotas to the user. for now, we're (unpleasantly) hard-coding things in the UI: min, max, and default limits.

UI work item: https://github.ibm.com/BlueMix-Fabric/Bluemix-Whisk-UI/issues/150

**Comment by rabbah** [comment]
Linking #547 and #618.

**Comment by rabbah** [comment]
Proposed patch, produces this info subject to input and feedback:

```

```
> curl -k https://dockerhost
{
  "support": "https://github.com/openwhisk/openwhisk/issues",
  "description": "OpenWhisk",
  "build": "2017-03-08T08:06:28Z",
  "api_paths": ["/api/v1"],
  "buildno": "latest",
  "runtimes": {
    "swift:3": {
      "deprecated": false,
      "requireMain": false,
      "default": true,
      "attached": true,
      "kind": "swift:3"
    },
    "nodejs": {
      "deprecated": false,
      "requireMain": false,
      "default": false,
      "attached": false,
      "kind": "nodejs"
    },
    "java": {
      "deprecated": false,
      "requireMain": true,
      "default": false,
      "attached": false,
      "kind": "java"
    },
    "nodejs:6": {
      "deprecated": false,
      "requireMain": false,
      "default": true,
      "attached": true,
      "kind": "nodejs:6"
    },
    "python": {
      "deprecated": false,
      "requireMain": false,
      "default": false,
      "attached": false,
      "kind": "python"
    },
    "swift": {
      "deprecated": true,
      "requireMain": false,
      "default": false,
      "attached": false,
      "kind": "swift"
    }
  },
  "limits": {
    "actions_per_minute": 60,
    "triggers_per_minute": 60,
    "concurrent_actions": 30
  }
}
```

**Comment by rabbah** [comment]
And for the "api" path:

```bash
> curl -k https://dockerhost/api/v1
{
  "min_cli_version": "2017-03-08T08:06:28Z",
  "api_version_path": "v1",
  "description": "OpenWhisk API",
  "min_recommended_cli_version": "2017-03-08T08:06:28Z",
  "swagger_paths": {
    "ui": "/docs",
    "api-docs": "/api-docs"
  },
  "build": "2017-03-08T08:06:28Z",
  "api_version": "1.0.0",
  "buildno": "latest"
}
```

**Comment by csantanapr** [comment]
@rabbah this looks great, this means we need to update the swagger doc to describe this responses to the two endpints `/api/v1`

**Comment by rabbah** [comment]
I don't think we have swagger for `/api/v1` or `/` but can add it once we settle on schema.

**Comment by csantanapr** [comment]
Yeah that's I meant

**Comment by cclauss** [comment]
The file extension might not be the same as language name so it would be helpful if you could add a file_suffix like `.py` for python, `.rb` for ruby, `.pl` for perl, etc.  By parsing this data structure, clients could dynamically support new languages or reject requests for unsupported file extensions.

**Comment by starpit** [comment]
i just realized that #1980 does not enumerate the memory and log min/max system settings.

**Comment by rabbah** [comment]
Yes; this is still open :) 1980 made the general facility available.
