### ISSUE TITLE
Make EntryPoint Optional for Java Kind

### ISSUE THREAD

**Issue by kameshsampath** [apache/incubator-openwhisk#3365]
With the  https://github.com/apache/incubator-openwhisk-runtime-java/issues/12 , its related update in CLI https://github.com/apache/incubator-openwhisk-cli/issues/233 will be making the entrypoint param `--main` as optional, hence during action create we can make the `--main`  parameter check as optional

**Comment by kameshsampath** [comment]
@csantanapr  - I need help here as I never worked on `scala` to make the entrypoint optional in the controller

**Comment by rabbah** [comment]
Closing for https://github.com/apache/incubator-openwhisk-cli/issues/233.
