### ISSUE TITLE
Mock database service for unit testing

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3387]
Many of our unit tests which need to mock a database operation actually use couch and require a deployment of the couchdb playbook. Instead, we should have a mock library to emulate the db contract and eschew the actual datastore service.

As additional SPIs are added for couchbase, mongo, etc, having this canonical library will simplify how we test the other implementations.

FYI @chetanmeh

**Comment by chetanmeh** [comment]
This task is now done with #3517.
