### ISSUE TITLE
Service not running when connecting to Vagrant box running openwhisk - Question

### ISSUE THREAD

**Issue by aganesh-pk** [apache/incubator-openwhisk#3415]
I have started openwhisk using vagrant as mentioned in https://github.com/apache/incubator-openwhisk#quick-start.
And then I have configured Openwhisk CLI, and then tried below commands.

1. After setting apihost and auth, executed the get property command and it give me error.
λ wsk property get
client cert
Client key
whisk auth              23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
whisk API host          172.17.0.1
whisk API version       v1
whisk namespace         _
whisk CLI version       2018-03-02T20:21:44.473+0000
whisk API build         Unknown
whisk API build number  Unknown
error: Unable to obtain API build information: Get https://172.17.0.1/api/v1: dial tcp 172.17.0.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

2. Tried to crate an action 
λ wsk action create hello hello.js
error: Unable to create action 'hello': Put https://172.17.0.1/api/v1/namespaces/_/actions/hello?overwrite=false: dial tcp 172.17.0.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Run 'wsk --help' for usage.

3. ssh into vagrant box, and executed below command
vagrant@ubuntu-xenial:~/openwhisk/ansible$ docker ps --format "{{.Names}} - {{.Image}}"
Cannot connect to the Docker daemon at tcp://0.0.0.0:4243. Is the docker daemon running?

I was hoping to create actions and access database, actions list but none of them is working. Do I'm missing anything?

**Comment by aganesh-pk** [comment]
Able to find a solution.

**Comment by csantanapr** [comment]
Try running the wsk command inside the VM
Do first vagrant ssh

Then once inside run “wsk list” and such
