### ISSUE TITLE
make OW context information available to Action

### ISSUE THREAD

**Issue by ScottChapman** [apache/incubator-openwhisk#3419]
It would be nice to have a __ow_ variable contain information about the action. Like

- Action Name
- Package Name
- runtime kind
- etc...

@csantanapr

**Comment by rabbah** [comment]
The fully qualified name of the action is already available in the context.
https://github.com/apache/incubator-openwhisk/blob/bcf87fe3a26abe899a47bc888e9b5d70ad39d70d/docs/actions.md#accessing-action-metadata-within-the-action-body

**Comment by csantanapr** [comment]
Duh my bad

What about adding a sugar one __OW_PACKAGE_NAME ?

Default to “default” when action not in a package ?

**Comment by ScottChapman** [comment]
Yea, I guess just adding package name to the above would be good.

I threw runtime kind in for completeness.

**Comment by rabbah** [comment]
https://github.com/apache/incubator-openwhisk/blob/91778eb36e2cea98b8cf47c5246e0eceaeef046c/core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala#L349

`/ns/name` or `/ns/package/name`

**Comment by rabbah** [comment]
> Default to “default” when action not in a package ?

no, because we need to do that globally first.

**Comment by rabbah** [comment]
This is tested for all the runtimes. So if you didn’t gave a set value you found a bug. Can you post details to reproduce?

**Comment by ScottChapman** [comment]
nvm. pilot error

**Comment by csantanapr** [comment]
Hum that was on the init or run?

They should be there on the run

On the init not today, but we can think which one could be added to init.

**Comment by rabbah** [comment]
Context is provided on run.
