### ISSUE TITLE
CLI Builds not found in expected location

### ISSUE THREAD

**Issue by lornajane** [apache/incubator-openwhisk#3426]
## Environment details:

* deploying to Ubuntu machine (laptop), but struggling with installation steps
* version of docker: `17.12.1-ce`, ansible `2.3.0`, ubuntu: `17.10`

## Steps to reproduce the issue:

1.   Work through the setup instructions as far as https://github.com/lornajane/incubator-openwhisk/blob/master/ansible/README.md#configuring-the-installation-of-wsk-cli
2.   The documented gradle command doesn't work, but the instructions in the CLI repo itself suggest `./gradlew compile -PnativeCompile` which does build something
3.   However the `ansible-playbook -i environments/<environment> openwhisk.yml -e cli_installation_mode=local -e openwhisk_cli_home=../incubator-openwhisk-cli` still fails

```
TASK [cli : ... or Copy release archive to build directory] ***********************************************************
Friday 09 March 2018  22:09:41 +0000 (0:00:00.045)       0:01:18.569 ********** 
fatal: [172.17.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/home/lorna/projects/incubator-openwhisk-cli/release/OpenWhisk_CLI-latest-all.tgz' in expected paths."}

Unable to find '/home/lorna/projects/incubator-openwhisk-cli/release
/OpenWhisk_CLI-latest-all.tgz' in expected paths.
```

Also if you try to fix something and then repeat the command it will fail until you manually `docker stop` and then `docker rm` the `invoker0` container (this may not be the right fix for the problem but it's allowing my command to run a bit longer!)

## Provide the expected results and outputs:

I expected the CLI to be installed

## Provide the actual results and outputs:

The CLI isn't installed, and I'm not able to proceed further with the installation (suggestions for workarounds are also welcome here)

## Additional information you deem important:

I have the newest code (as of a couple of days ago) and I think this differs from #3329 but could be related to it.

**Comment by dubeejw** [comment]
@lornajane, as a workaround, run `ansible-playbook -i environments/<environment> openwhisk.yml`.

**Comment by lornajane** [comment]
This fails but I think because the playbook isn't designed to be run more than once.  Is there a way of cleaning up what it did on previous runs so I can start again?

**Comment by csantanapr** [comment]
Run the teardown.yml playbook

**Comment by dubeejw** [comment]
@jonpspri, FYI.

**Comment by dubeejw** [comment]
To first clean the environment: `ansible-playbook -i environments/<environment> openwhisk.yml -e mode=clean`.

**Comment by jonpspri** [comment]
For local build of the zip file, we need to execute `./gradlew release -PnativeCompile`.  (Notice the `release`, not compile).  See comments about on cleaning the environment -- I recommend the `wskdev`/`redo` tool (now that I've learned how to use it).

Regarding cleanup and invoker0, see also #3218.

Leave the issue open to address the documentation shortcomings in both `incubator-openwhisk` and `incubator-openwhisk-cli`.  I'll get to add two more PRs to my backlog.

**Comment by lornajane** [comment]
Thanks!  Using the updated instructions in #3435 helped me get further along.

**Comment by lornajane** [comment]
Next I tried to follow https://github.com/apache/incubator-openwhisk/blob/master/docs/cli.md (the next link in the overall Ubuntu installation instructions) which tells me to use `./bin/wsk`  however all the files in this directory have old timestamps from a previous attempt (also unsuccessful) at getting OpenWhisk to work locally.  I can see the files extracted in my `/tmp/wskconf/nginx....` directory but I assume that's not where they're supposed to end up!  Am I looking in the wrong place?
