### ISSUE TITLE
KubernetesContainer doesn't properly track the timestamp, leading to logging problems esp. under load

### ISSUE THREAD

**Issue by bwmcadams** [apache/incubator-openwhisk#3439]
## Environment details:

* OpenWhisk running on Kubernetes
* all versions of Kubernetes

## Steps to reproduce the issue:

1.   Start up OpenWhisk against Kubernetes (or OpenShift, which uses it behind the scenes)
2.   Make a number of repeated requests to an endpoint
3.   Request the activation logs

## Provide the expected results and outputs:

The results should, if it is an endpoint with output, show the output.

```
$ ACTIVATION_ID=$(wsk action -i invoke --blocking hello | tail -n +2 | jq .activationId | sed 's/"//g' ) && sleep 1.50 && wsk activation -i logs $ACTIVATION_ID
2018-03-13T21:06:34.652259951Z stdout: hello, undefined!
```

## Provide the actual results and outputs:

The failure is intermittent, but frequent…
```
$ ACTIVATION_ID=$(wsk action -i invoke --blocking hello | tail -n +2 | jq .activationId | sed 's/"//g' ) && sleep 1.50 && wsk activation -i logs $ACTIVATION_ID
error: Unable to get logs for activation 'f0298257c9a644dda98257c9a674dd09': The requested resource does not exist. (code 18950)
```

## Additional information you deem important:
* There is an additional minor, related issue where if the Kubernetes log handler returns no logs (typically because of the main issue), it may fail to handle that properly and cause more downstream issues. This is also problematic if you manage to request logs before Kubernetes makes them available. The fix is to retry.

**Comment by bwmcadams** [comment]
I have a PR nearly read to address this issue.

**Comment by dgrove-oss** [comment]
PR merged.
