### ISSUE TITLE
Vagrant Dev environment

### ISSUE THREAD

**Issue by theobouwman** [apache/incubator-openwhisk#3448]
## Environment details:

vagrant: 2.0.2

## Question

I've just finished the setup using Vagrant and I was wondering how to develop my application using Vagrant.

Should I create functions and setup triggers in the virtual using `vagrant ssh`? 

And what other options do I have (when using a Vagrant environment)?

**Comment by csantanapr** [comment]
Yeah you can vagrant ssh and deploy your actions, create trigger and rules use the wsk inside the Vagrant VM.

Another alternative is to use the wsk CLI from outside and configure the CLI to use the Vagrant IP address, the doc has more details https://github.com/apache/incubator-openwhisk/blob/master/tools/vagrant/Vagrantfile

But I would recommend to use the wsk and test inside the Vagrant VM, edit your files outside and share the files into the VM with a share folder,
