### ISSUE TITLE
Add better debugging/logging capabilities

### ISSUE THREAD

**Issue by andreasnauerz** [apache/incubator-openwhisk#346]
During the recent labs/user studies many people asked for better debugging/logging capabilities.

Hence, the question is what we can do to ease debugging/logging?
I think that we may partially be able to address this by adding filtering capabilities to the dashboard (as discussed in one of our previous calls); but probably even that isn't sufficient.

**Comment by rabbah** [comment]
Closing as too vague. In general, there is a need for better log visualization and performance analysis. Some ideas are available in the [shell](https://www.npmjs.com/package/@ibm-functions/shell)
![grid](https://user-images.githubusercontent.com/4959922/32898142-5ae7702a-cab5-11e7-8e8e-6219aa4fe4f7.png)
