### ISSUE TITLE
issue about "SSL routines:SSL3_READ_BYTES:sslv3 alert bad"

### ISSUE THREAD

**Issue by z14572** [apache/incubator-openwhisk#3476]
when I run the CLI "ansible-playbook -i environments/local openwhisk.yml",  there is an error as blow:

fatal: [controller0]: FAILED! => {"attempts": 12, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 1] _ssl.c:510: error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate>", "redirected": false, "status": -1, "url": "https://172.17.0.1:10001/ping"}

Status code was not [200]: Request failed: <urlopen error [Errno 1]
_ssl.c:510: error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad
certificate>

**Comment by chetanmeh** [comment]
Issue looks similar to #3431. Try updating the ansible version 2.4.2.0 (see #3430)

**Comment by z14572** [comment]
thanks，update the ansible version to 2.4.2.0， the issue has been fixed
