### ISSUE TITLE
CLI action get should format source code nicely and allow export to file

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#353]
```
wsk action get /whisk.system/samples/helloWorld exec
ok: got action /whisk.system/samples/helloWorld, projecting exec
{
    "code": "/**\n * Hello, world.\n */\nfunction main(params) {\n    console.log('hello', params.payload+'!');\n}\n",
    "kind": "nodejs"
}
```

it would be useful to project code and pretty print it so that it is human readable && allow export to a file.

**Comment by csantanapr** [comment]
This one is big plus in UX.
Be able to export actions source code.

**Comment by rabbah** [comment]
Removed high priority label - we should use that if we're actually going to commit to doing something about the labelled issue.

**Comment by rabbah** [comment]
@dubeejw assigned to you since you have a PR for this.

**Comment by rabbah** [comment]
I think can be closed by https://github.com/apache/incubator-openwhisk/pull/2544.

**Comment by dubeejw** [comment]
I'm fine with closing this one. Not sure how useful it is to extract code manually by copying directly from the terminal.
