### ISSUE TITLE
factor out max code blob size to a deployment configuration

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3530]
From a conversation on slack, it was pointed out by @chetanmeh that we are hardcoding the exec max size https://github.com/apache/incubator-openwhisk/blob/a2dcace3d4cbef737cb5875c758f7e5d2b6d9f3c/common/scala/src/main/scala/whisk/core/entity/Exec.scala#L217

We should factor this out as we've done with other limits (to pureconfig).
A reference PR https://github.com/apache/incubator-openwhisk/pull/3148.

**Comment by tz70s** [comment]
@rabbah , I'm working on this. Is the limit on code size configurable during creating/updating actions or just get fixed after deploying whisk?

**Comment by rabbah** [comment]
Fixed at deployment - It’s possible we want these to be specific to subjects in the future but that will likely apply to a lot of limit.

**Comment by tz70s** [comment]
Got it, thanks!

**Comment by rabbah** [comment]
closing as duplicate https://github.com/apache/incubator-openwhisk/issues/3712.
