### ISSUE TITLE
nginx docker not starting after ubuntu machine restart

### ISSUE THREAD

**Issue by anishvarghese** [apache/incubator-openwhisk#3574]
I have successfully deployed openwhisk  in Ubuntu Native Environment  using the tutorial https://gist.github.com/epiphone/8fe223bbfc375d01f12822e405f6aa54
and all are working fine but after server restart nginx docker is continuously restarting . while checking the dockers logs getting the following error.

root@openwhisk:~# docker logs fdaa4a93b80e 2018/04/16 13:10:45 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (2: No such file or directory) nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory) 2018/04/16 13:10:46 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (2: No such file or directory) nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory) 2018/04/16 13:10:46 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (2: No such file or directory) nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)

**Comment by anishvarghese** [comment]
Fixed the openwhisk nginx restart issue, updated  Fixed the issue created new directory /tmp1 for nginx conf instead of default /tmp directory in the docker configuration file  **environments/local/group_vars/all** 

openwhisk_tmp_dir: "{{ lookup('env', 'OPENWHISK_TMP_DIR')|default('/tmp1', true) }}"

**Comment by csantanapr** [comment]
Maybe /tmp should not be a default ? 🤔

**Comment by anishvarghese** [comment]
Default configuration is
openwhisk_tmp_dir: "{{ lookup('env', 'OPENWHISK_TMP_DIR')|default('/tmp', true) }}"

So nginx conf files are stored inside /tmp. while restart whole data loss.

**Comment by rabbah** [comment]
#32 back again.

**Comment by csantanapr** [comment]
Maybe we should change it to another directory maybe use the same value we use vagrant $HOME/.openwshik/ansible/nginxconf
