### ISSUE TITLE
Build does not correctly set permissions on the nginx conf directories

### ISSUE THREAD

**Issue by mcdan** [apache/incubator-openwhisk#3612]
## Environment details:

* build

## Steps to reproduce the issue:

1.   Try and build not using a root user
2.   Build will fail.

## Provide the expected results and outputs:

```
TASK [nginx : copy template from local to remote in nginx config directory] ****
Thursday 03 May 2018  20:55:55 +0000 (0:00:00.208)       0:01:02.518 ********** 
fatal: [10.50.246.129]: FAILED! => {"changed": false, "checksum": "021bfc3c885e8190fc71f45f0e25238337a68ca9", "failed": true, "msg": "Destination /tmp/wskconf/nginx not writable"}

Destination /tmp/wskconf/nginx not writable
```

## Provide the actual results and outputs:
Build should not fail.
```
Exit 0
```

## Additional information you deem important:
* always if you run as non-root.

**Comment by jonpspri** [comment]
I ran into something similar where I left the nginx container running and then did `sudo rm -rf /tmp/wsk*` in my.  Docker recreated the `wskconf` and `wskconf/nginx` directories, but did so with root ownership and 0744 permissions.  I suspect you may have encountered something similar, and this may not help.

Order of operations to be sure:
1.  'docker kill $(docker ps -q)'
2.  'sudo rm -rf /tmp/wsk*'
3.  Retry the build you were working on.

**Comment by mcdan** [comment]
You're right actually but my problem was slightly different. I was having other issues with the "become" statements with /tmp/whiskconf and I set all the *_dir_become variables for my environment to true assuming non root would always need that and that was creating the incorrectly permissioned directory.
