### ISSUE TITLE
java Actionruntime of  jar confilcts

### ISSUE THREAD

**Issue by xingyunhui** [apache/incubator-openwhisk#3648]
hi,
I use java8 actionRuntime, and have two jars are conflicted.
for example, there is a jar -- base-0.0.1.jar in java8 actionRuntime, my function use a jar -- base-0.0.2.jar, when I run my function in java8 actionRuntime, I find the actionRuntime always use base-0.0.1.jar , and I wanna use base-0.0.2.jar for my funtion

**Comment by csantanapr** [comment]
Hi @xingyunhui 

I don't understand what's the problem.

The java runtime doesn't have any file named `base-0.0.1.jar` 
```
$ docker run --rm -it openwhisk/java8action find / -name base-0.0.1.jar
```

Could you open a new issue in the [runtime-java](https://github.com/apache/incubator-openwhisk-runtime-java/issues) repo, that's the repo that deals with java actions.

And provide more details on step by step on how to reproduce your error

**Comment by rabbah** [comment]
Issue moved to [apache/incubator-openwhisk-runtime-java #52](https://github.com/apache/incubator-openwhisk-runtime-java/issues/52) via [**ZenHub**](https://www.zenhub.com/)

**Comment by csantanapr** [comment]
Ah shoot I wanted to give 24 hours before moving the issue over, so the originator of the issue was not me :-(

**Comment by csantanapr** [comment]
My bad should have being more explicit. 
Will see if we get more information on the issue, do you have any clue?
