### ISSUE TITLE
Is latest NodeJS 10.2.x supported as a runtime?

### ISSUE THREAD

**Issue by idibidiart** [apache/incubator-openwhisk#3730]
Is latest NodeJS 10.2.x supported as a runtime?

**Comment by vvraskin** [comment]
You could look it up in the nodejs runtime repo: https://github.com/apache/incubator-openwhisk-runtime-nodejs
Currently versions 6 and 8 are supported. 

I would have considered asking such kind of questions in our slack: https://openwhisk-team.slack.com
