### ISSUE TITLE
Distributed deployment: export | unreachable

### ISSUE THREAD

**Issue by akharitonov** [apache/incubator-openwhisk#3733]
I'm attempting to deploy a distributed OpenWhisk according to [this guide](https://github.com/apache/incubator-openwhisk/blob/master/ansible/README_DISTRIBUTED.md).
However, right away there is an issue.
Specifically when I run
`ansible all -i environments/distributed -m ping`

All of the hosts specified by me in the` /home/uvlba/openwhisk/ansible/environments/hosts` are reachable but there is one that is not: "export"

`export | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname export: Name or service not known\r\n",
    "unreachable": true
}`

It's not present in any of the configs as far as I can tell for the distributed environment nor I see any mentions of it anywhere in the documentation. Where is it coming from? What is that export host?

`; the first parameter in a host is the inventory_hostname

; used for local actions only
ansible ansible_connection=local

[registry]
192.168.56.21              ansible_host=192.168.56.21

[edge]
192.168.56.21              ansible_host=192.168.56.21

[apigateway:children]
edge

[redis:children]
edge

[controllers]
192.168.56.21              ansible_host=192.168.56.21

[kafkas]
192.168.56.21              ansible_host=192.168.56.21

[zookeepers:children]
kafkas

[invokers]
192.168.56.21              ansible_host=192.168.56.21
192.168.56.22              ansible_host=192.168.56.22

[db]
192.168.56.21               ansible_host=192.168.56.21
`

**Comment by Hugh-ifly** [comment]
The doc has some error. You could use this cmd `ansible -i environments/distributed/hosts all -m ping`.

**Comment by axiqia** [comment]
> -i, --inventory, --inventory-file
> specify inventory host path or comma separated host list. –inventory-file is deprecated


https://docs.ansible.com/ansible/latest/cli/ansible.html#cmdoption-ansible-i

**Comment by rabbah** [comment]
Thanks @axiqia for reporting these --- we haven't maintained these files and there's some rot for sure.

**Comment by rabbah** [comment]
We have removed these playbooks since they aren't tested and maintained. We'll need to rethink the setup infra setup, but for a distribute deployment, adapting the environment in `local` should suffice.
