### ISSUE TITLE
Vagrant installation waits for user accepts java 8 license

### ISSUE THREAD

**Issue by rosogon** [apache/incubator-openwhisk#3765]
## Environment details:

* Ubuntu 16.04.4 LTS
* Vagrant 2.1.1

## Steps to reproduce the issue:

1.   git clone --depth=1 https://github.com/apache/incubator-openwhisk.git openwhisk (commit b46478bfe6b5068fd57f78cea44b2a6326e89f4b)
2.   cd openwhisk/tools/vagrant
3.   ./hello

## Provide the expected results and outputs:

Vagrant machine is installed successfully

## Provide the actual results and outputs:

Vagrant installation is stopped waiting for user accept java8 license.

## Additional information you deem important:

I was able to fix this adding `echo 'oracle-java8-installer shared/accepted-oracle-license-v1-1 boolean true' | sudo debconf-set-selections` to file tools/ubuntu-setup/java8.sh file

I can submit a PR.

**Comment by starpit** [comment]
i can verify that this resolves the issue.

**Comment by rabbah** [comment]
@rosogon that'll be great (if you submit a PR) - do you have a CLA already?

**Comment by rosogon** [comment]
You should also modify https://github.com/apache/incubator-openwhisk/commit/5f9975854fae3f2585f9d1dd93055f33ead6a617#diff-04c6e90faac2675aa89e2176d2eec7d8R88 to say Oracle is default Java installation to reflect the changes introduced by https://github.com/apache/incubator-openwhisk/commit/5aa8fc7fa6a09f219f704d301541b213b9aa07c8#diff-b84d6a391031d6181fa26b3e4ae9d267R90

**Comment by starpit** [comment]
done, via https://github.com/apache/incubator-openwhisk/pull/3783

however, as i noted in the PR comment, i'm not sure why we're modifying tools/ubuntu-setup for a vagrant-specific change?
