### ISSUE TITLE
Invoker id assignment path in zookeeper uses wrong id format

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3856]
`Invoker` supports using zookeeper for id assignment logic. There it constructs the a path like `/invokers/idAssignment/mapping/<invokerName>`. Due to. the way name is constructed its coming out to be like `/invokers/idAssignment/mapping/Some(10.66.20.10)`. Here invoker was launched with ip as the name.

![image](https://user-images.githubusercontent.com/664531/42450212-098db8ce-83a1-11e8-8842-3a372dfc140d.png)

Above is the state as seen via exhibitor. This happens because invokerName below is an `Option`

https://github.com/apache/incubator-openwhisk/blob/9c05de4494d6edbd198fd494d458b908bbc0cd0a/core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala#L133

**Comment by dgrove-oss** [comment]
yep, by the time we get to line 133, we know that the invokerName is a non-empty String.  it should be unwrapped.  @chetanmeh do you want to do a PR with the fix?
