### ISSUE TITLE
Replace legacy kubectl commands with rest-client in kube client.

### ISSUE THREAD

**Issue by tz70s** [apache/incubator-openwhisk#3857]
In the kubernetes client apis, there still exist the legacy `kubectl` commands.
https://github.com/apache/incubator-openwhisk/blob/5b13c4c90e4f8d59156c862c2ffe57ef027e5aee/core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala#L168-L174

It's better to replace this with rest-client based on fabric8.

**Comment by tz70s** [comment]
Currently, the kubernetes client tests are made by mock client with limited number of test cases. After removing `kubectl` commands, we can refactor our tests with more comprehensive test cases by using [mock kubernetes server](https://github.com/fabric8io/kubernetes-client#mocking-kubernetes).

**Comment by dgrove-oss** [comment]
Done 4 months ago in https://github.com/apache/incubator-openwhisk/pull/3963 but I forgot to close this issue.
