### ISSUE TITLE
is WhiskProperties.useCLIDownload deadcode now?

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3861]
I don't think we use this flag anymore:

https://github.com/apache/incubator-openwhisk/blob/f6046721acd801ea1777cb5cb040dfaa6922a18e/tests/src/test/scala/common/WskCliOperations.scala#L962-L966

@houshengbo @dubee might you know if this is dead code now?

**Comment by drcariel** [comment]
If this is dead code what would be the default? To always use `WhiskProperties.getCLIPath` AKA `WHISK_HOME/bin/wsk`?
