### ISSUE TITLE
JUnit test concurrency flag

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3862]
Do we use this anywhere now that all our tests are scala tests?

https://github.com/apache/incubator-openwhisk/blob/37ce9b86048dafb0f369a5a5b05caa0136a26ef4/tests/src/test/scala/common/WhiskProperties.java#L53

@dubee @jasonpet @drcariel can we remove this flag?

**Comment by drcariel** [comment]
I think we can - I see one single lingering java test file upstream that still uses this but might be stale as well. Attempting to confirm with the team right now

**Comment by rabbah** [comment]
Thanks - if it's dead, would you mind sending a PR to remove it and its related slice.

**Comment by drcariel** [comment]
Once I get some confirmation will be sure to open a PR - feel free to assign this to me
