### ISSUE TITLE
Download page should describe how to verify artifacts

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-openwhisk#3900]
The download page mentions that downloads should be verified, but does not give any details of how to do so.

**Comment by rabbah** [comment]
cc @pritidesai @mrutkows

**Comment by dgrove-oss** [comment]
This has been fixed as part of the website updates. Relevant section of Downloads page:
![screen shot 2018-12-19 at 5 02 09 pm](https://user-images.githubusercontent.com/5099100/50250799-e2c17480-03af-11e9-8c81-b8dd6386aa8b.png)
