### ISSUE TITLE
Provide option to support static metric names

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3917]
OpenWhisk currently use dynamic metric names for some of the cases. The dynamic case has 2 variants

1. Finite Bounded options - Some of the metric names have finite states like `openwhisk.counter.invoker_docker.<cmd>_start`
2. Non bounded options - Metric names like those used for Kafka stats `openwhisk.histogram.kafka_invoker0_count` use instance id for the name. As these id can be many the metric names can be many and setup dependent.

Its possible to aggregate such metrics via use of regex or wildcard. However some systems like [Datadog does not support regex][1] which makes it tricky to analyze such metrics. Suggested way is to use Tags which is supported by #3343.

As a solution may be we expose another option for disabling use of dynamic names in unbounded cases and instead use tags.

[1]: https://docs.datadoghq.com/graphing/faq/when-i-query-can-i-use-wildcards-in-metric-names-and-events/

**Comment by andrewryno** [comment]
One workaround for now is to set `kamon.statsd.simple-metric-key-generator.include-hostname` to `false` which will remove the hostname part of the metric name. It doesn't add any tags for the controller/invoker instance ids but for overall metrics it works. This should also be easier to implement in a backwards compatible way if tags are added to the current metrics so it's only additive. Then setting `include-hostname` to `false` will satisfy systems that need static metric names.
