### ISSUE TITLE
Update to latest NodeJS runtime which contains latest Openwhisk package, 3.16.0

### ISSUE THREAD

**Issue by eweiter** [apache/incubator-openwhisk#3938]
The NPM package for 'openwhisk' was recently upgraded from 3.15.0 -> 3.16.0.
The change was done in the NodeJS runtime repository to update the package.  That change can be found here: https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/75/files

This change is to update OpenWhisk to have the latest version of the NodeJS runtime.

**Comment by rabbah** [comment]
https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/75 merged already.
