### ISSUE TITLE
Provide command to update namespace key in wskadmin-next

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3965]
Currently wskadmin (and next) provide way to add a namespace with specific auth key. 

     wskadmin user create -ns foo --auth uuid:key

In some cases we need a way to update the namespace key with a specific auth even if it already exists. One way would be to add a `-f`, `--force` flag to enable this override behaviour

    wskadmin user create -ns foo --auth uuid:key -f

**Comment by rabbah** [comment]
Do you mean to set the uuid and key or just the key?

Can we add a revoke flag to change just the key? This is handy.

**Comment by chetanmeh** [comment]
> Do you mean to set the uuid and key or just the key?

For our case both. Objective here is that credentials for some system namespaces are stored in separate store and deployment logic would ensure that one in db matches the one in credential store used by deployment

> Can we add a revoke flag to change just the key? This is handy.

That would be useful (cc @duynguyen)
