### ISSUE TITLE
Conductor action returns "application error" when continuation function throws an uncaught exception

### ISSUE THREAD

**Issue by mgencur** [apache/incubator-openwhisk#3966]
## Steps to reproduce the issue:

1. Place the following snippet into WskConductorTests
```
it should "invoke a conductor action with an exception in continuation" in withAssetCleaner(wskprops) { (wp, assetHelper) =>
    val conductor = "conductor" // conductor action
    assetHelper.withCleaner(wsk.action, conductor) { (action, _) =>
      action.create(
        conductor,
        Some(TestUtils.getTestActionFilename("conductor.js")),
        annotations = Map("conductor" -> true.toJson))
    }

    val runException = "runexception"
    assetHelper.withCleaner(wsk.action, runException) { (action, _) =>
      action.create(runException, Some(TestUtils.getTestActionFilename(s"$runException.js")))
    }

    // dynamically invoke step action with an uncaught exception
    val uncaughtExceptionRun = wsk.action.invoke(conductor, Map("action" -> runException.toJson))
    withActivation(wsk.activation, uncaughtExceptionRun) { activation =>
      activation.response.status shouldBe "action developer error"
      //^^^^^fails here, it returns application error
      checkConductorLogsAndAnnotations(activation, 3) // conductor, step, conductor
    }
  }
```
2. Run the tests: `./gradlew tests:test --tests system.basic.WskConductorTests`  

## Provide the expected results and outputs:

```
action developer error
```

## Provide the actual results and outputs:

```
application error
```

## Additional information you deem important:
My expectation is that it should return "action developer error" similar to normal actions. However, the docs state that it should be "internal error"? (https://github.com/apache/incubator-openwhisk/blame/master/docs/conductors.md#L253). But actually it throws "application error".

**Comment by dgrove-oss** [comment]
@tardieu is the expert, but is on vacation.

**Comment by tardieu** [comment]
In the current implementation, the conductor action only sees the result of the composed action, not the full response. Application errors and action developer errors are represented in the same ambiguous way: a json dictionary with a single error field. The conductor action therefore cannot propagate the precise status. The "conductor.js" code used here (https://github.com/apache/incubator-openwhisk/blob/master/tests/dat/actions/conductor.js#L9) unconditionally reports an "application error" in all cases. Alternatively, the code `if (args.error) throw args.error` would unconditionally produce an "action developer error".

I am thinking of introducing support for "raw" conductor actions, where the full response would be made available to the conductor action, but the code for this does not exist yet.

In the documentation, "invocation failure" is intended to mean an internal error at invocation time, not an unsuccessful invocation with an "action developer error" or an "application error". I'll update the documentation to be clearer.

**Comment by mgencur** [comment]
@tardieu Thanks
