### ISSUE TITLE
error when following guide for ansible distributed installation with openstack provisioning step using ansible 2.5.2 on an Ubuntu 16 Xenial VM

### ISSUE THREAD

**Issue by SchuhMichael** [apache/incubator-openwhisk#3989]
The provisioning playbook for openstack VMs does not work on a Ubuntu 16 Xenial VM as bootstrapper with 4.4.0-124-generic virtualized on openstack queens
ansible version is 2.5.2
python version is 2.7.12

## Steps to reproduce the issue:

1.  Spawn a Xenial VM on Openstack, clone the openwhisk repo, run the software installer all.sh  following [https://github.com/apache/incubator-openwhisk/blob/master/tools/ubuntu-setup/README.md]() until it says you should continue with [https://github.com/apache/incubator-openwhisk/blob/master/ansible/README_DISTRIBUTED.md]()
2.  populate the openstack.env following the instructions in [https://github.com/apache/incubator-openwhisk/blob/master/ansible/environments/distributed/files/openstack/README_OS.md]()
2.   run it `ansible-playbook -i environments/distributed provision_env_dist.yml`

## Provide the expected results and outputs:
It should use the nova client to provision the Openstack VMs

## actual results and outputs:

Instead it fails to run the playbook:
```
ERROR! You cannot use loops on 'import_tasks' statements. You should use 'include_tasks' instead.
```

**Comment by rabbah** [comment]
This closed PR might be of help for future reference https://github.com/apache/incubator-openwhisk/pull/4107, although we have removed these playbooks since they aren't tested and maintained.
