### ISSUE TITLE
Improve error message when an action source file does not exist

### ISSUE THREAD

**Issue by tareqmamari** [apache/incubator-openwhisk#399]
when I create an action and passed a non-exist file name a not valid file error thrown, I expected " The file action1.js does not exist"

```
$ wsk action create anAction action1.js
the artifact "action1.js" is not a valid file. If this is a docker image, use --docker.
```

**Comment by rabbah** [comment]
update: the message above if from the previous version of the cli. The new version produces this error message which is more informative but could be cleaned up:

```
error: Unable to parse action command arguments: File 'xyz' is not a valid file or it does not exist: stat xyz: no such file or directory
Run 'wsk --help' for usage.
```

**Comment by mdeuser** [comment]
I believe the new message satisfies this issue as described.
@csantanapr - ready for closure.
