### ISSUE TITLE
enhancement: add user-agent to allowed CORS headers, and extend allow-methods

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk#4009]
Right now, we limit accepted headers via CORS to 

```json
{
  "Access-Control-Allow-Headers": [
    "Authorization, Content-Type"
  ]
}
```

to allow for browsers to communicate directly with openwhisk API endpoints, it is helpful to add User-Agent to the list of allowed headers. many popular request libraries tack on default user agents, including our own openwhisk npm.

we also will need to expand the default Access-Control-Allow-Methods, which, by default, limits clients to GET operations.

**Comment by csantanapr** [comment]
The proper fix is to check if request method is OPTIONS AND contains the header Access-Control-Request-Headers then in the response for that request (pre flight) then echo back the same value in Access-Control-Allow-Headers

I just double check what we do in the apigateway for default config for Cors https://github.com/apache/incubator-openwhisk-apigateway/blob/master/scripts/lua/cors.lua

There might be other headers to allow it all depends on the request header value.

**Comment by csantanapr** [comment]
some background info
“This header is required if the request has an Access-Control-Request-Headers header.”

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers
