### ISSUE TITLE
Negative waitTime in wsk action invoke

### ISSUE THREAD

**Issue by handong32** [apache/incubator-openwhisk#4018]
## Environment details:
Two redhat machines, one machine acting as invoker and another for deployment, kafka, nginx, etc.
Red Hat Enterprise Linux Server release 7.1 (Maipo)
Kernel 3.10.0-229.el7.x86_64
Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz - 32 cores
Docker version 18.03.0-ce, build 0520e24
OpenWhisk is forked off https://github.com/apache/incubator-openwhisk/commit/e66945ac2b579b57d3d0698ee97a36fa9b563369
-No changes to underlying OpenWhisk code other than the few parameter changes listed below

## Steps to reproduce the issue:
1.   Changed the following parameters,
incubator-openwhisk/ansible/group_vars/all:
`numcore: "{{ invoker_num_core | default(1) }}"`
`coreshare: "{{ invoker_core_share | default(1) }}"`
incubator-openwhisk/ansible/files/runtimes.json
`"stemCells": [{`
`                    "count": 1,`
`                    "memory": "256 MB"`
`                }]`

2. Deploy OpenWhick
3. Creates a JavaScript function that sleeps for 1 second with number 1235
4. Invoke the function on invoker machine  `wsk -i --apihost http://172.17.0.1:10001 --auth ##### action invoke -b 1235`

## Provide the expected results and outputs:
Should have a positive waitTime

## Provide the actual results and outputs:

First execution has initTime and negative waitTime
```
ok: invoked /_/1235 with id d408f29332ef403288f29332ef203258
{
    "activationId": "d408f29332ef403288f29332ef203258",
    "annotations": [
        {
            "key": "path",
            "value": "guest/1235"
        },
        {
            "key": "waitTime",
            "value": -6404
        },
        {
            "key": "kind",
            "value": "nodejs:6"
        },
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "initTime",
            "value": 1421
        }
    ],
    "duration": 2435,
    "end": 1536695716734,
    "logs": [],
    "name": "1235",
    "namespace": "guest",
    "publish": false,
    "response": {
        "result": {},
        "status": "success",
        "success": true
    },
    "start": 1536695714299,
    "subject": "guest",
    "version": "0.0.1"
}
```
Second execution with negative waitTime

```
ok: invoked /_/1235 with id 5ddd95a7f6104c1b9d95a7f6103c1b04
{
    "activationId": "5ddd95a7f6104c1b9d95a7f6103c1b04",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "guest/1235"
        },
        {
            "key": "kind",
            "value": "nodejs:6"
        },
        {
            "key": "waitTime",
            "value": -6054
        }
    ],
    "duration": 1007,
    "end": 1536695720525,
    "logs": [],
    "name": "1235",
    "namespace": "guest",
    "publish": false,
    "response": {
        "result": {},
        "status": "success",
        "success": true172.17.0.1
    },
    "start": 1536695719518,
    "subject": "guest",
    "version": "0.0.1"
}
```

## Additional information you deem important:
"duration" times seems to indicate function executes correctly
This issue doesn't appear if we do a local deploy on a single machine

**Comment by cbickel** [comment]
Hi,
the wait time is the time between arriving in the controller and initialising the action-container. (Substraction of the two timestamps)
As your invoker is on another machine than the controller, the these two timestamps are taken on different machines.
So my assumption is, that the clocks of your two machines are not in sync.
Greetings.

**Comment by handong32** [comment]
Hey thanks for the reply, fixing the clocks solved the negative waitTime issue but we also found another parameter invoker_heap: 4g that for some reason why causing invocations to fail, we're still figuring out why but thanks a lot!
