### ISSUE TITLE
Add git2slack tutorial

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#403]
It would be good to have a tutorial step by step for someone to implement a scenario to create a **Rule** using the Github **Feed** to create a **Trigger** to _invoke_ a Slack **Action** 

Both Github feed and Slack actions already exist, let's show user how they can use them.

The document should be a markdown in [docs/tutorials/git2slack.md]

Tutorials should have code snippets inside the markdown, no external files. this way has potential to be posted in website or blog and everything is one place kept in sync.

**Comment by sjfink** [comment]
Note: I believe I've seen a git2slack.js which does not follow the pattern described by Carlos above.

Let's make sure that the tutorial uses the github and slack packages in a pipeline, as described by Carlos above.

**Comment by ChrBi** [comment]
I'll open a PR of the file, how it is at the moment.
Maybe someone else, could do a short check, if this tutorial still works.

**Comment by csantanapr** [comment]
Hi @ChrBi can you do that work and take it to completion, to check if the tutorial works, and modify it to match the specifications I describe in https://github.com/openwhisk/openwhisk/issues/403#issue-154506045 ?

**Comment by rabbah** [comment]
@csantanapr is this moved to catalog and shall we therefore close this issue?

**Comment by csantanapr** [comment]
I will take a look, I think maybe is trivial to show the example in the triggers and rules chapter of the docs, or move the issue to catalog and add to the Github docs on how to use the Github webhooks by creating a rule and using the Slack action
