### ISSUE TITLE
The parameter __ow_path is not correct or empty when not using path parameter

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#4055]
When creating an api using response type http, the call path should always be forwarded to the web action.

Duplicate issue opened https://github.com/serverless/serverless-openwhisk/issues/136

To reproduce:
```
$ echo "const main = (p) => {return {body:p}}" >echoweb.js
$ wsk action update echoweb echoweb.js --web true
$ wsk api create /v1 /foo get echoweb --response-type http
ok: created API /v1/foo GET for action /guest/echoweb
http://172.17.0.1:9090/api/23bc46b1-71f6-4ed5-8c54-816aa4f8c502/v1/foo
```
The expected behavior  is that the `__ow_path` always contains the basePath (/v1) plus the API Operation Path (/foo) and any Path appended to endpoint.

```
curl -s http://172.17.0.1:9090/api/23bc46b1-71f6-4ed5-8c54-816aa4f8c502/v1/foo | jq .__ow_path
""
```
Calling the endpoint `/v1/foo` it returns `""` it should be `/v1/foo`

```
$ curl -s http://172.17.0.1:9090/api/23bc46b1-71f6-4ed5-8c54-816aa4f8c502/v1/foo/bar | jq .__ow_path
"/bar"
```
Calling the endpoint `/v1/foo` it returns `""` it should be `/v1/foo/bar`

Inspecting the swagger definition the target url is missing the `$(request.path)` at the end after `echoweb.http`
```
wsk api get /v1 | grep target-url
"target-url": "https://172.17.0.1/api/v1/web/guest/default/echoweb.http",
```

Recreating the API with a modified swagger to fix:
```
wsk api get /v1 > swagger.json
```
Changing the swagger to have end in `echoweb.http$(request.path)`
```
$ wsk api create -c swagger.json
ok: created API /v1/foo get for action /guest/echoweb
http://172.17.0.1:9090/api/23bc46b1-71f6-4ed5-8c54-816aa4f8c502/v1/foo
```
verify target-url:
```
$ wsk api get /v1 | grep target-url
"target-url": "https://172.17.0.1/api/v1/web/guest/default/echoweb.http$(request.path)"
```
Then try the scenario again 😸 and it's fix
```
🍰  $ curl -s http://172.17.0.1:9090/api/23bc46b1-71f6-4ed5-8c54-816aa4f8c502/v1/foo | jq .__ow_path
"/v1/foo"
~/dev/whisk/git/apache/incubator-openwhisk (master)
💋  $ curl -s http://172.17.0.1:9090/api/23bc46b1-71f6-4ed5-8c54-816aa4f8c502/v1/foo/bar | jq .__ow_path
"/v1/foo/bar"
```
If a path parameter syntax is used then this problem doesn't show up
```
$ wsk api create /v2 /foo2/{id}/friends get echoweb --response-type http
ok: created API /v2/foo2/{id}/friends GET for action /guest/echoweb
http://172.17.0.1:9090/api/23bc46b1-71f6-4ed5-8c54-816aa4f8c502/v2/foo2/{id}/friends
 $ curl -s http://172.17.0.1:9090/api/23bc46b1-71f6-4ed5-8c54-816aa4f8c502/v2/foo2/42/friends | jq .__ow_path
"/v2/foo2/42/friends"
$ curl -s http://172.17.0.1:9090/api/23bc46b1-71f6-4ed5-8c54-816aa4f8c502/v2/foo2/42/friends/first | jq .__ow_path
"/v2/foo2/42/friends/first"
```
The swagger json doc is generated correct with the `$(request.path)`
```
$ wsk api get /v2 | grep target-url
"target-url": "https://172.17.0.1/api/v1/web/guest/default/echoweb.http$(request.path)",

```

**Comment by rabbah** [comment]
This is working as expected/documented: The __ow_path (type: string): the unmatched path of the request (matching stops after consuming the action extension).

**Comment by csantanapr** [comment]
@rabbah web actions are working as design/expected nothing wrong with the way web actions work.

The problem specifically only to APIGateway Integration.
And the difference when using path parameters

The code never has access to the swagger definition and incoming request to the gateway for example never be able see the apigateway specific data like basepath `/v1` and `/foo` 

Again nothing wrong with http web actions, is just that info is not being pass to the webaction.http<missing data here>

**Comment by rabbah** [comment]
Thanks for the clarification - I misunderstood.

**Comment by csantanapr** [comment]
Also in production environment the API Gateway like IBM Cloud the user will have a vanity/custom  domain

Making the match of `https://foo.com` to `http://172.17.0.1:9090/api/23bc46b1-71f6-4ed5-8c54-816aa4f8c502`
So the clients final url would be something like `https://foo.com/v1/foo/bar` and as developer I want access to the `/v1/foo/bar`
