### ISSUE TITLE
Docker compose install on Ubuntu 18.04 bare metal : Authenticated user does not have namespace 'guest'

### ISSUE THREAD

**Issue by Franzerfos** [apache/incubator-openwhisk#4060]
Hello,
I am trying a basic install on a bare meta server Ubuntu 18.04 updated.
Docker and Docker compose installed last versions
I follow the OpenWhisk documentation for Docker compose install :

$ git clone https://github.com/apache/incubator-openwhisk-devtools.git
$ cd incubator-openwhisk-devtools/docker-compose
$ make quick-start

The 'make' works until this error occurs :

ok: whisk auth set. Run 'wsk property get --auth' to see the new value.
ok: whisk API host set to https://10.64.232.82
error: Authenticated user does not have namespace 'guest'; set command failed: Get https://10.64.232.82/api/v1/namespaces: dial tcp 10.64.232.82:443: getsockopt: connection refused
Makefile:289: recipe for target 'init-whisk-cli' failed

I looked at the makefile, different mailing lists but no clue on how to fix the problem.
Any idea is welcome.
Thanks
FZ

**Comment by Franzerfos** [comment]
After some more investigation :
- netstat report that the port 443 is open
- It looks that the API web server is not working

**Comment by ddragosd** [comment]
@Franzerfos I'm sorry you're having issues.  Can you check the https://github.com/apache/incubator-openwhisk-devtools/blob/master/docker-compose/README.md#troubleshooting doc and see if it helps ?

**Comment by rabbah** [comment]
@Franzerfos is this still an issue? Please reopen if so.
