### ISSUE TITLE
DockerContainerTests heisenbug

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#4069]
Following failure seen in _DockerContainer should pause and unpause container via docker_

```
:tests:testCoverageLeanwhisk.core.containerpool.docker.test.DockerContainerTests » DockerContainer should pause and unpause container via docker (0.128s)
org.scalatest.exceptions.TestFailedException: 
Unsatisfied expectation:

Expected:
inAnyOrder {
  <stub-12> DockerApiWithFileAccess.pause(ContainerId(id), #tid_sid_testing) once (never called - UNSATISFIED)
  <stub-12> DockerApiWithFileAccess.unpause(ContainerId(id), #tid_sid_testing) once (called once)
}

Actual:
  <stub-12> DockerApiWithFileAccess.unpause(ContainerId(id), #tid_sid_testing)
```

Links
* https://scans.gradle.com/s/4thv2ae4ks6u6/tests/xaqugzlgs2zw6-5dknij2weoq7i
* https://travis-ci.org/apache/incubator-openwhisk/jobs/441855302
* https://openwhisk.app.box.com/v/travis-logs/file/332132464599

**Comment by markusthoemmes** [comment]
I'd propose to just kill the stubbed function and replace it with a `LoggingFunction` (a self-rolled stubbing mechanism). I had nothing but problems with ScalaMock unfortunately.
