### ISSUE TITLE
Add more information about contribution guidelines

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#409]
We need to document some basic instructions when collaborating to the repo

Don't know if this info belongs here [CONTRIBUTING.md](https://github.com/openwhisk/openwhisk/blob/master/CONTRIBUTING.md) or create a new doc here [docs/contributors/README.md]. 

Maybe have some sections
- Setup and fork maintenance
- Preparing Pull requests 
- Reviewing Pull requests
- Merging Pull requests
- (Optional) Configure Git-Duet for sign-off pair programming

Some notes: (notice that most folks can't assigned or label issues only committer)
- Do not merge or push directly to the upstream repo (i.e. this repo)
- Fork the repo and and work on your own fork
- Submit a Pull Request as early as possible with "WIP" (Work in Progress) in title
- Title should have main issue number that is being address #xxx 
- Mention other related issues or PRs in comments
- Please add test cases  to verify your changes
- Always run the tests "ant run" to check your changes
- When you think you reach a point to get your patch in add [review] to the start of the title of the PR, ask someone else for a review, you can find out from file history who might be most appropriately 
- When the reviewer is OK for the PR to be merge, if the reviewer has write access it can merge it, if the reviewer doesn't have write access replace "[review]" with "[ready]" it's also good to mention one of the committer (write access) in a comment to make them aware but we monitor ready PRs

@markusthoemmes @rabbah @jeremiaswerner @sjfink 
Can you comment or edit this

**Comment by rabbah** [comment]
Maybe pull the `Git.md` document from blue here?

**Comment by csantanapr** [comment]
The git.md content is already located in the open in the github wiki. 

Since we have many repos for the Apache OpenWhisk, how about we put this content in the Apache OpenWhisk wiki or website, then on each repo link to it (maybe each CONTRIBUTING.md)

**Comment by rabbah** [comment]
+1.
