### ISSUE TITLE
Error while installing in Ubuntu 16.04

### ISSUE THREAD

**Issue by juanestebanj** [apache/incubator-openwhisk#4095]
## Environment details:

* local deployment, ubuntu 16.04 running on virtualbox in windows 10.   
* version of docker: 10.06.1-ce.

## Steps to reproduce the issue:

1.   I followed the installation process for Ubuntu
2.   I ran the command: make quick-start
3.   After a while, error took place.

## Provide the actual results and outputs:

```
initializing CLI ... 
REQUEST:
[GET]	https://10.0.2.15/api/v1/namespaces
Req Headers
{
  "Authorization": [
    "Basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A="
  ],
  "User-Agent": [
    "OpenWhisk-CLI/1.0 (2018-11-03T00:38:40.372+0000) linux amd64"
  ]
}
RESPONSE:Got response with code 500
Resp Headers
{
  "Connection": [
    "keep-alive"
  ],
  "Content-Length": [
    "35"
  ],
  "Content-Type": [
    "text/plain; charset=UTF-8"
  ],
  "Date": [
    "Sat, 03 Nov 2018 08:02:16 GMT"
  ],
  "Server": [
    "openresty/1.13.6.2"
  ]
}
Response body size is 35 bytes
Response body received:
There was an internal server error.
ok: whisk auth set. Run 'wsk property get --auth' to see the new value.
ok: whisk API host set to https://10.0.2.15
error: Authenticated user does not have namespace 'guest'; set command failed: The connection failed, or timed out. (HTTP status code 500)
Makefile:290: recipe for target 'init-whisk-cli' failed
make: *** [init-whisk-cli] Error 1
```

## Additional information you deem important:
* I searched for other similar issues, but the error was not 500 internal server error.
* For one issue it was, but it appears as resolved as a fix in source code.

Thank you.

**Comment by juanestebanj** [comment]
Hi @csantanapr 
I allocated 12 GB,

**Comment by csantanapr** [comment]
Hmm
Then check the controller logs should have an error for example having trouble connecting the couchdb database

Logs are located in your home directory ~/tmp/openwhisk/...

**Comment by juanestebanj** [comment]
Hello.
I just ran again the command: make quick-start
and it's OK now. Thanks.
