### ISSUE TITLE
Documentation corrections

### ISSUE THREAD

**Issue by atsag** [apache/incubator-openwhisk#4113]
Some minor corrections to the Vagrant README.md file: 

- In the "Using CLI from outside the VM section" (https://github.com/apache/incubator-openwhisk/blob/master/tools/vagrant/README.md#using-cli-from-outside-the-vm), the wsk binary should be downloaded properly from the website of openwhisk (at least for Windows machines), because the folder `../../bin/openwhisk-cli/build/` does not exist.

- In the same section, the first command to set the Openwhisk Authorization Key, 
```
wsk property set --apihost 192.168.33.16 --auth `vagrant ssh -- cat openwhisk/ansible/files/auth.guest`
```
cannot be used in Windows. The relevant command would be
```
wsk property set --apihost 192.168.33.16 --auth $(vagrant ssh -- cat openwhisk/ansible/files/auth.guest)
```

**Comment by vvraskin** [comment]
Hi @atsag , great that you found it! 
Do you mind opening a PR to fix it?

**Comment by atsag** [comment]
Not at all! The changes for the PR are already [done](https://github.com/atsag/incubator-openwhisk/tree/vagrant_documentation_improvement), however I first have to sign the Apache CLA.
