### ISSUE TITLE
tests:testSwaggerCodegen failing

### ISSUE THREAD

**Issue by dgrove-oss** [apache/incubator-openwhisk#4169]
Test currently failing.  Appears to be breakage in upstream dependency.

$ ./gradlew :tests:testSwaggerCodegen
> Task :tests:testSwaggerCodegen FAILED

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':swagger-java-client'.
> > Could not resolve all artifacts for configuration ':swagger-java-client:classpath'.
>    > Could not find any matches for com.android.tools.build:gradle:2.3.+ as no versions of com.android.tools.build:gradle are available.
>      Searched in the following locations:
>        - https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml
>        - https://jcenter.bintray.com/com/android/tools/build/gradle/
>      Required by:
>          project :swagger-java-client

Proposing to disable test case until we have time to find a real fix.

See https://openwhisk-team.slack.com/archives/C3TPCAQG1/p1544514441533000

**Comment by dgrove-oss** [comment]
#4170 disables the failing test.  As people have time, we should do a real fix and re-enable the test.
@bbrowning

**Comment by rabbah** [comment]
We need to re-enable these tests before they rot.

**Comment by bbrowning** [comment]
I'm able to run `./gradlew :tests:testSwaggerCodegen` from latest master as of now and everything worked fine. Am I doing it wrong, or was this fixed some other way?

**Comment by rabbah** [comment]
Thanks Ben - I think they fixed themselves, I'll reverse the PR.
