### ISSUE TITLE
Add PHP 7.3 runtime support to default deployments

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#4174]
Title: Add `php:7.3` runtime support to default deployments

### 1. Add `php:7.3` to core ansible/vagrant deploy
- Add `php:7.3`entry into [ansible/files/runtimes.json](https://github.com/apache/incubator-openwhisk/blob/master/ansible/files/runtimes.json#L209)
- Update and add doc file into [docs/action_node.md](https://github.com/apache/incubator-openwhisk/tree/master/docs)
- Update unicode tests https://github.com/apache/incubator-openwhisk/tree/master/tests/dat/actions/unicode.tests

### 3. Add `php:7.3` to docker-compose deploy
- Add `php:7.3` into runtime manifest
https://github.com/apache/incubator-openwhisk-devtools/blob/master/docker-compose/docker-whisk-controller.env#L64

### 4. Add `php:7.3` to deploy-kube
- Add `nphp:7.3` into runtime manifest
https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/runtimes.json

### 5. Update wskdeploy with `php:7.3`
- Update spec, and tests for `php:7.3`
https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/runtimes/runtimes.go#L267
https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/specification/html/spec_actions.md#valid-runtime-names
https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/tests/src/integration/runtimetests/manifest.yaml#L5

### 6 Update website with `php:7.3`
- Update js action section with `php:7.3`
https://github.com/apache/incubator-openwhisk-website/blob/master/_layouts/documentation.html
https://github.com/apache/incubator-openwhisk-website/tree/master/_includes/code

**Comment by csantanapr** [comment]
@akrabat will be working on this

**Comment by akrabat** [comment]
All required PRs opened I believe.

**Comment by csantanapr** [comment]
All PRs have being merged, Thanks ❤️ @akrabat  👍
