### ISSUE TITLE
Gatling performance tests instructions

### ISSUE THREAD

**Issue by danilomendonca** [apache/incubator-openwhisk#4188]
## Steps to reproduce the issue:

1.   run any of the performance tests with gatling following the instructions under tests/performance 

- e.g., [variables] ./gradlew gatlingRun-LatencySimulation

## Provide the expected results and outputs:

```
normal execution of the performance test
```

## Provide the actual results and outputs:

```
Exception in thread "main" java.lang.IllegalArgumentException: The requested class 'LatencySimulation' can not be found in the classpath or does not extends Simulation.
```

## Fix

```
update the performance tests README.md; at each test run example, the complete path to the test class should be included:

- ./gradlew gatlingRun-org.apache.openwhisk.ApiV1Simulation
- ./gradlew gatlingRun-org.apache.openwhisk.LatencySimulation
- ./gradlew gatlingRun-org.apache.openwhisk.BlockingInvokeOneActionSimulation

```

**Comment by chetanmeh** [comment]
@danilomendonca Thanks for the reporting it. This is most likely due to recent change in package names #4073. Would you be able to create a PR to update the docs?

**Comment by danilomendonca** [comment]
@chetanmeh done :)

Cheers
Danilo
