### ISSUE TITLE
unable to invoke action by docker 

### ISSUE THREAD

**Issue by axiqia** [apache/incubator-openwhisk#4197]
## Environment details:

* local deployment, Ubuntu 16.04.5 LTS
* Docker version 18.09.0, build 4d60db4

I can use `dockerSkeleton` to invoke docker actions following [here](https://github.com/apache/incubator-openwhisk/blob/master/docs/actions-docker.md). But when I try to invoke an action based on my own docker image, there is something wrong.

## Steps to reproduce the issue:

1.  ` $ cat hello.py        `
```
def main():
    greeting = "Hello " + "!"
    print(greeting)
    return {"greeting": greeting}

if __name__ == "__main__":
    main()
```

2.   `zip exec.zip hello.py`
3.   `wsk action create hello exec.zip --docker axiqia/ubuntu:python3action`
4.  `wsk action invoke hello -r `
`ok: invoked /_/hello, but the request has not yet finished, with id 119aefadbfbb4c049aefadbfbb7c04d8`

6. ` wsk activation get 119aefadbfbb4c049aefadbfbb7c04d8 `   
``` 
error: Unable to get activation '119aefadbfbb4c049aefadbfbb7c04d8': The requested resource does not exist. (code d9eb7cb32652189f3fd630f9c74831c9)
```

Thank you for help me!

**Comment by rabbah** [comment]
Did you push your image to dockerhub?

**Comment by rabbah** [comment]
Never mind I see it tagged properly.

**Comment by rabbah** [comment]
@axiqia is this a vanilla ubuntu image? If you use your own image, you need to implement this openwhisk proxy. See for details: https://github.com/apache/incubator-openwhisk/blob/master/docs/actions-new.md

**Comment by axiqia** [comment]
@rabbah got it. I'll try it and report later.
BTW, the `python3action` runtime is built from `alpine`， and I need to use `pyaudio` which depends on `libasound-dev`, but I check the package [here]( https://pkgs.alpinelinux.org/packages?name=libasound-dev&branch=edge), it seems that the package is not supported by alpine, so I try to invoke the action by docker image `ubuntu`, is this the right way to do?

**Comment by rabbah** [comment]
certainly you can do that - you can take the python runtime's dockerfile and just change the base image and some of the commands to get the desired outcome.

**Comment by axiqia** [comment]
@rabbah ok, thank you so much.

**Comment by axiqia** [comment]
@rabbah 
I use pythonAction [here](https://github.com/apache/incubator-openwhisk-runtime-python/blob/master/core/pythonAction/Dockerfile) to build a docker image, and try to pass a zip file to invoke a action, but there is something wrong.
1. `wget https://raw.githubusercontent.com/apache/incubator-openwhisk-runtime-python/master/core/pythonAction/Dockerfile`
2.  `wget https://raw.githubusercontent.com/apache/incubator-openwhisk-runtime-python/master/core/pythonAction/pythonrunner.py`
3. `buildAndPush.sh axiqia/python3`
4. `cat exec.py `
```
def main(args):
    name = args.get("name", "stranger")
    greeting = "Hello " + name + "!"
    print(greeting)
    return {"greeting": greeting}
```
5. `zip exec.zip exec`
6. `wsk action create example exec.zip --docker axiqia/python3`
7.  `wsk action invoke --result example  --param name World` 
```
{
    "error": "The action failed to generate or locate a binary. See logs for details."
}
```

**Comment by axiqia** [comment]
> The `dockerskeleton` base image is useful for actions that run scripts (e.g., bash, perl, python) and compiled binaries or, more generally, any native executable. It provides a proxy service (using Flask, a Python web microframework) that implements the required `/init` and `/run` routes to interact with the OpenWhisk invoker service. The implementation of these routes is encapsulated in a class named `ActionRunner` which provides a basic framework for receiving code from an invoker, preparing it for execution, and then running the code when required.

An implementation of the runner for Python actions is available [here](https://github.com/apache/incubator-openwhisk-runtime-python/blob/master/core/pythonAction/pythonrunner.py). 

```
class PythonRunner(ActionRunner):

    def __init__(self):
        ActionRunner.__init__(self, '/action/__main__.py')
        self.fn = None
        self.mainFn = 'main'
        self.global_context = {}
```

**So the python scripts much be named as `__main__.py`.**
