### ISSUE TITLE
move cli into new repo openwhisk-cli

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#420]

**Comment by csantanapr** [comment]
This one will be implemented once we have a stable go CLI in tools/go-cli/ released and tested. Right now the focus is to replace the current python cli with go cli in the same repo and do a clean swap.

**Comment by csantanapr** [comment]
Closing this as the go-cli is very core component to the openwhisk runtime, It's not just another client to the API
- currently used for CI/CD
- unit and integration testing
So it should be in sync  and same hash/repo with runtime to have a tight dependency

closing.
We can revisit if in the future there is a need to take parts of the go-cli as libraries can be share to create a plugin to another CLI (i.e. CF CLI)

**Comment by rabbah** [comment]
I think we should reconsider this:

1. cut down build time - the CLI now is much more just a binary we can install (pin a version we need)
2. we need to boost our API based testing which the CLI system tests allow us to continue to cheat on
3. allows others to work on the CLI independent of the main repo (ie if I only want to develop the CLI, I don't need the overhead of the rest of the system)

**Comment by psuter** [comment]
Either [GitHub Releases](https://help.github.com/articles/about-releases/) or [Bintray](https://bintray.com/) are good candidates for hosting binaries of open-source projects.

**Comment by csantanapr** [comment]
@rabbah Your suggesting that we start creating a go cli binary with a semantic version?
With the current v1 of the API we can start with a 1.0.0, when v2 of the whisk api starts showing up we can have version 2.0.0 of the API.

We can use git tags for version and releases,
Use git branches 1.x, or 1.1.x 2.x, 2.2.x for release and version management

This will be another benefit of having it's own repo, but more work to maintained. So we need to agree to invest to build the automation and infrastructure to releases

@psuter I never heard of Bintray
I would say to start lets use Github releases and keep it in one place

**Comment by csantanapr** [comment]
Done 🌮 https://github.com/apache/incubator-openwhisk-cli/releases
