### ISSUE TITLE
Users disliked output of wsk list entities when no actions, rules, triggers etc. were available

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#424]
From @nauerz-ibm : 
During workshop user would have preferred seeing a different (more descriptive I assume) output when no actions, rules, triggers, etc. were available.

This happens first time users uses the system, like a new dev setup and using guest account

Current output:

```
$ wsk list
entities in namespace: default
packages
actions
triggers
rules
```

**Comment by csantanapr** [comment]
Currently it prints the Dividers with no content, maybe we can put a count or a message that tells user run this command to copy/clone your first action. myhello

**Comment by mdeuser** [comment]
i prefer showing a count over a set of potentially changing set of instructions

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #159](https://github.com/apache/incubator-openwhisk-cli/issues/159) via [**ZenHub**](https://www.zenhub.com/)
