### ISSUE TITLE
remove older runtimes

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#4246]
The runtimes manifest includes some stale/deprecated runtimes:
- nodejs (node 4)
- python (alias for python 2)
- swift 2?, 3, 3.1.1., 4.1
- php 7.1, 7.2

I propose cleaning up the manifest to remove these older runtimes, and to make node 10 the default or node actions and python 3 for python actions.

cc @akrabat @csantanapr

**Comment by TPei** [comment]
From a development perspective, this would mean adapting the runtime.json, swagger, docs and test/dat files? I feel this might be somewhat beginner-friendly, so I'd like to express an interest in working on that :)

**Comment by rabbah** [comment]
Sorry @TPei I didn't see your note - you'll see that PR fails tests because there's actually some dependence on the actual manifest used for deployment and what the tests are assuming. It turns out we have to add a separate manifest for the test. I'm happy to close my PR if you would like to take this one.
