### ISSUE TITLE
Is openwhisk production ready?

### ISSUE THREAD

**Issue by mjason3** [apache/incubator-openwhisk#4302]
As it's still in incubator, I am wondered if openwhisk is production ready or not?

**Comment by rabbah** [comment]
Yes. 

OpenWhisk has been in production as ibm cloud functions since December 2016 as one example. 

Do you have specific questions? What are your concerns?

**Comment by mjason3** [comment]
Thanks @rabbah for quick reply. We are researching some severless engines to pick up one in internal platform. Glad to know it's already production ready since 2016.

**Comment by rabbah** [comment]
Happy to help - you can reach me on our slack channel http://slack.openwhisk.org.
