### ISSUE TITLE
Automatic code style checks for our code

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#431]
Originally from @markusthoemmes : 

We should enforce automatic code style checks on our code to keep it consistent and readable for everyone and to prevent styling annotations in code reviews.

Pointers to start: http://www.scalastyle.org/ they have a gradle plugin so its really a matter of choosing the styleguide.

@rabbah  proposed http://twitter.github.io/effectivescala/
@psuter  comments?

**Comment by csantanapr** [comment]
From @markusthoemmes : 
First stage will be a setup guide for scalastyle in eclipse + choosing a guide. We'll need to tweak the guide to our needs before we finally enforce it on a build level.

**Comment by rabbah** [comment]
This is done thanks to @markusthoemmes.
