### ISSUE TITLE
Lack of comprehensive performance evaluation tool

### ISSUE THREAD

**Issue by erezh16** [apache/incubator-openwhisk#4319]
For using OpenWhisk in a latency-sensitive application, I need to measure both latency and throughput of OpenWhisk actions invoked in all modes: synchronously, asynchronously, and (important) via rules. Furthermore, I would like to profile the invocations - separate rule overhead in and action overhead  (in OW) from net action time, but preferably without using Kamino, since I need just quick summary numbers for different deployments.    
Currently, there is no tool (or set of tools) in OW that can do that.

**Comment by style95** [comment]
closing as #4320 is merged
