### ISSUE TITLE
feedback on using Apache OpenWhisk name

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#4324]
Recently, an opportunity arose to provide a _virtual machine image_ as a one click deployment of OpenWhisk to appear in the market place for a cloud provider. I reviewed the trademark details (https://www.apache.org/foundation/marks/faq) and concluded that the name of the image can at best refer to OpenWhisk using the “Powered by” approach… which was too long for the formatting, so I opted for a different naming approach (that omits Apache OpenWhisk entirely in the name) and used the _Powered by_ language in the detailed description (with links to our project page).

There are two parts to describing the image.

The first is a brief description (where `XYZ` below is a place holder name of the image) for which I intend to use the following:
```
XYZ provides you with a platform for building serverless applications, not just functions.
It is [Powered by Apache OpenWhisk](https://openwhisk.apache.org), an industry-strength
platform for serverless computing that can handle enterprise-level scaling...
```

The second is a longer set of instructions in which I links to our github docs and tutorials. At the end of the instructions, I will conclude with the following:
```
More information about Apache OpenWhisk is available on the project website at
https://openwhisk.apache.org. Apache OpenWhisk and OpenWhisk, are either
registered trademarks or trademarks of The Apache Software Foundation in the
United States and other countries. All other marks mentioned may be trademarks
or registered trademarks of their respective owners.
```

Inline with one of the early suggestions I received, I linked to https://openwhisk.apache.org instead of the shorter http://openwhisk.org in the spirit of promoting the Apache brand. (Plus it's https :)

With this issue, I'm soliciting additional feedback that can help promote Apache/OpenWhisk, and also document the text as an example for future use by others.

**Comment by bdelacretaz** [comment]
Thanks for this, looks good to me! Does your image have an URL that you can include here for reference?

I added the "compliance" label to this ticket, maybe "branding" would be good as well but I'm not sure about creating yet another label.

**Comment by rabbah** [comment]
Here is the url https://marketplace.digitalocean.com/apps/nimbella-lite. 

Thanks for the feedback here and on the dev list.
