### ISSUE TITLE
FAILED - RETRYING: wait until CouchDB in this host is up and running (12 retries left).

### ISSUE THREAD

**Issue by Bobyuan1015** [apache/incubator-openwhisk#4350]
ansible-playbook -i environments/local couchdb.yml 

PLAY [db] ************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************
Friday 15 March 2019  17:54:01 +0800 (0:00:00.112)       0:00:00.112 ********** 
ok: [172.17.0.1]

TASK [couchdb : set the coordinator to the first node] ***************************************************************************************************************************************************
Friday 15 March 2019  17:54:02 +0800 (0:00:00.623)       0:00:00.736 ********** 
ok: [172.17.0.1]

TASK [couchdb : Set the volumes] *************************************************************************************************************************************************************************
Friday 15 March 2019  17:54:02 +0800 (0:00:00.069)       0:00:00.806 ********** 
ok: [172.17.0.1]

TASK [couchdb : check if db credentials are valid for CouchDB] *******************************************************************************************************************************************
Friday 15 March 2019  17:54:02 +0800 (0:00:00.068)       0:00:00.874 ********** 
skipping: [172.17.0.1]

TASK [couchdb : ensure directory for persisting db exists] ***********************************************************************************************************************************************
Friday 15 March 2019  17:54:02 +0800 (0:00:00.056)       0:00:00.931 ********** 
skipping: [172.17.0.1]

TASK [couchdb : fail if path to persist db does not exist] ***********************************************************************************************************************************************
Friday 15 March 2019  17:54:02 +0800 (0:00:00.056)       0:00:00.988 ********** 
skipping: [172.17.0.1]

TASK [couchdb : mount directory for persisting dbs] ******************************************************************************************************************************************************
Friday 15 March 2019  17:54:02 +0800 (0:00:00.057)       0:00:01.045 ********** 
skipping: [172.17.0.1]

TASK [couchdb : include_tasks] ***************************************************************************************************************************************************************************
Friday 15 March 2019  17:54:02 +0800 (0:00:00.056)       0:00:01.101 ********** 
skipping: [172.17.0.1]

TASK [couchdb : set the erlang cookie volume] ************************************************************************************************************************************************************
Friday 15 March 2019  17:54:02 +0800 (0:00:00.056)       0:00:01.157 ********** 
skipping: [172.17.0.1]

TASK [couchdb : (re)start CouchDB from 'apache/couchdb:2.3 '] ********************************************************************************************************************************************
Friday 15 March 2019  17:54:02 +0800 (0:00:00.058)       0:00:01.216 ********** 
changed: [172.17.0.1]

TASK [couchdb : wait until CouchDB in this host is up and running] ***************************************************************************************************************************************
Friday 15 March 2019  17:54:15 +0800 (0:00:12.533)       0:00:13.750 ********** 
FAILED - RETRYING: wait until CouchDB in this host is up and running (12 retries left).
FAILED - RETRYING: wait until CouchDB in this host is up and running (11 retries left).
FAILED - RETRYING: wait until CouchDB in this host is up and running (10 retries left).
FAILED - RETRYING: wait until CouchDB in this host is up and running (9 retries left).

cat db_local.ini 
[db_creds]
db_provider=CouchDB
db_username=whisk_admin
db_password=some_passw0rd
db_protocol=http
db_host=172.17.0.1
db_port=5984

[controller]
db_username=whisk_local_controller0
db_password=some_controller_passw0rd

[invoker]
db_username=whisk_local_invoker0
db_password=some_invoker_passw0rd

 sudo docker ps -a

CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                   PORTS                                                                    NAMES
f3ab188428bc        apache/couchdb:2.3   "tini -- /docker-ent…"   5 seconds ago       Up 3 seconds             0.0.0.0:4369->4369/tcp, 0.0.0.0:5984->5984/tcp, 0.0.0.0:9100->9100/tcp   couchdb

**Comment by style95** [comment]
@Bobyuan1015 If you are trying to deploy OpenWhisk on Mac, you may need this.

```
sudo ifconfig lo0 alias 172.17.0.1/24
```

**Comment by Bobyuan1015** [comment]
> @Bobyuan1015 If you are trying to deploy OpenWhisk on Mac, you may need this.
> 
> ```
> sudo ifconfig lo0 alias 172.17.0.1/24
> ```

I setup this on my ubuntu 16.04 and ubuntu 18.04 both, the same error occurs.

**Comment by Bobyuan1015** [comment]
> @Bobyuan1015 If you are trying to deploy OpenWhisk on Mac, you may need this.
> 
> ```
> sudo ifconfig lo0 alias 172.17.0.1/24
> ```

Any tips if I setup openwhisk of this way on ubuntu16.04. And have you checked of building this openwhisk on mac, Does it success?

**Comment by style95** [comment]
Generally, a host can access containers with container IP in ubuntu. So the above step is not required in ubuntu.
Could you share couchdb logs(`docker logs couchdb`)?
