### ISSUE TITLE
wsk cli does not pass annotations for rules

### ISSUE THREAD

**Issue by erezh16** [apache/incubator-openwhisk#4354]
## Environment details:

* vagrant

## Steps to reproduce the issue:

1. wsk trigger create testTrigger  
2. wsk rule create testRule testTrigger /whisk.system/utils/echo -a testAnn '{"key":"value"}' -v

## Provide the expected results and outputs:
Output request *should* contain the annotation testAnn

## Provide the actual results and outputs:
Output request does not contain the annotation testAnn 
Response also does not contain the annotation testAnn

## Additional information you deem important:
* Seems like a stable issue

**Comment by rabbah** [comment]
This is a CLI bug - the request body does not post the annotations.

**Comment by rabbah** [comment]
Issue moved to [apache/incubator-openwhisk-cli #426](https://github.com/apache/incubator-openwhisk-cli/issues/426) via [**ZenHub**](https://www.zenhub.com/)
