### ISSUE TITLE
openwhisk/python3action downloads pandas always fail. 

### ISSUE THREAD

**Issue by Bobyuan1015** [apache/incubator-openwhisk#4401]
bob@bob:~/work/openwhisk/pythonsample$ docker run --rm -v "$PWD:/tmp" openwhisk/python3action bash   -c "cd tmp && virtualenv virtualenv && source virtualenv/bin/activate && pip install -r requirements.txt"
Using base prefix '/usr/local'
New python executable in /tmp/virtualenv/bin/python
Installing setuptools, pip, wheel...done.
Collecting numpy (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cf/8d/6345b4f32b37945fedc1e027e83970005fc9c699068d2f566b82826515f2/numpy-1.16.2.zip (5.1MB)
Collecting Cython (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/36/da/fcb979fc8cb486a67a013d6aefefbb95a3e19e67e49dff8a35e014046c5e/Cython-0.29.6.tar.gz (2.0MB)
Collecting pandas (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/b2/4c/b6f966ac91c5670ba4ef0b0b5613b5379e3c7abdfad4e7b89a87d73bae13/pandas-0.24.2.tar.gz (11.8MB)
Collecting python-dateutil>=2.5.0 (from pandas->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
Collecting pytz>=2011k (from pandas->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl (510kB)
Collecting six>=1.5 (from python-dateutil>=2.5.0->pandas->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Building wheels for collected packages: numpy, Cython, pandas
  Building wheel for numpy (setup.py): started
  Building wheel for numpy (setup.py): still running...
  Building wheel for numpy (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/8c/a8/49/e458f0fdbc4fe3759be6b9371e172b3f0e82c09f5a750e977e
  Building wheel for Cython (setup.py): started
  Building wheel for Cython (setup.py): still running...
  Building wheel for Cython (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f6/99/56/24db8d1f1c4f903b8f59d81a3813749e64e4a83bfdeff58108
  Building wheel for pandas (setup.py): started
  Building wheel for pandas (setup.py): still running...
  Building wheel for pandas (setup.py): still running...
  Building wheel for pandas (setup.py): still running...
  Building wheel for pandas (setup.py): still running...

**Comment by rabbah** [comment]
I think ibm has published a docker image for python with pandas already installed, might be of interest to you - @csantanapr ?

**Comment by csantanapr** [comment]
Try this image https://github.com/ibm-functions/runtime-python/blob/master/python3.7/requirements.txt#L23

We have it published as `docker pull ibmfunctions/action-python-v3.7:1.8.0`

**Comment by csantanapr** [comment]
If you use IBM Cloud Functions pandas and other ML libs are included just do `wsk action create foo foo.py --kind python:3.7`

**Comment by Bobyuan1015** [comment]
> If you use IBM Cloud Functions pandas and other ML libs are included just do `wsk action create foo foo.py --kind python:3.7`
I don't use ibm cloud function. local openwhisk + couchDB instead.  Any tips for this?

**Comment by rabbah** [comment]
You can still use the docker image with a local openwhisk. Any compatible docker image in dockerhub can be used actually.
