### ISSUE TITLE
wsk -i action create  body exceed 1000bytes, ask a solution for this

### ISSUE THREAD

**Issue by Bobyuan1015** [apache/incubator-openwhisk#4402]
$ wsk -i action create word --kind python:3 word.zip -v REQUEST: [PUT]	https://***.78/api/v1/namespaces/guest/actions/word?overwrite=false Req Headers {   "Authorization": [     "Basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A="   ],   "Content-Type": [     "application/json"   ],   "User-Agent": [     "OpenWhisk-CLI/1.0 (2019-03-20T20:17:38.064+0000) linux amd64"   ] } Req Body Body exceeds 1000 bytes and will be truncated

**Comment by rabbah** [comment]
if you want to see the full payload use `-d` instead of `-v`.
