### ISSUE TITLE
replace all instances of JsBoolean(true) and JsBoolean(false)

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#4419]
I counted ~60 instances of `JsBoolean(true|false)` which could be simplified to `JsTrue` and `JsFalse` respectively... the latter are singleton objects and hence avoid re-consing of the corresponding objects.

**Comment by satansk** [comment]
Hi @rabbah we could close this issue now :)

**Comment by rabbah** [comment]
Thanks for the contribution!
