### ISSUE TITLE
Review CLI subcommands for action

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#442]
Today the CLI contains the following actions subcommands

```
$ wsk action -h
usage: wsk action [-h] {create,update,invoke,get,delete,list} ...

optional arguments:
  -h, --help            show this help message and exit

available commands:
  {create,update,invoke,get,delete,list}
    create              create new action
    update              update an existing action
    invoke              invoke action
    get                 get action
    delete              delete action
    list                list all actions
```

From conversation with @domdom82  with others it looks like there is interest to modify existing ones and add new ones.

I think instead of "create" we use "push"
Create a new subcommands "init", "pull"
`wsk action init [-type | -t <type>]` will help give the user an  hello action where do get started with sample code.
 <type> will specify node, swift, python, java, docker

`wsk action push` user will use this as today to push his code to whisk, So user can use in theory `wsk action init -t nodejs && wsk action push hello action.js"

`wsk pull` will allow for user to pull down only the code, this will allow user to pull latest version of action 
make changes and then `push` it back to the server, So user can use in theory `wsk action pull hello > action.js && wsk action push hello action.js`

**Comment by mbehrendt** [comment]
re `wsk action init` -- would it make sense to generalize this one, such that not only a hard-coded code template is used for creating the action, but rather that the user can select which code template should be used (from a catalog of public actions) ? a hello action could be the default if nothing is selected. thinking this through...should the command the be rather sth like `wsk action copy` vs init?

re `wsk action push` -- would this cover both `wsk action create` and `wsk action update` (ie make both of them obsolete) ?

**Comment by domdom82** [comment]
this design has some analogy to git which I like.
on the `init` part I think there could be two use-cases of creation:
- init (in the sense of `git init`of a new repo. that would make a new action with only skeleton code)
- fork (in the sense git `clone` of an existing repo. that would make a local copy of a public action)

we could call the latter one e.g. `wsk clone`

the "cloning" of stuff would not even have to be limited to actions. I can imagine forking entire namespaces into my own one to get a whole hierarchy of actions, rules and triggers if they were flagged "public". need to discuss how that overlaps with the package concept, though.

**Comment by mbehrendt** [comment]
in the context of your example, a `wsk action clone` would just create a copy of a given action. there could also be an `wsk package clone`, but i'd consider that to be out of scope for this issue.

**Comment by csantanapr** [comment]
>re wsk action init -- would it make sense to generalize this one, such that not only a hard-coded code template is used for creating the action, but rather that the user can select which code template should be used (from a catalog of public actions) ?
Yes I agree templates are always good entry point to see a demo/tutorial, and the author just provide a template. Usually the easiest would be url like a git url or ID in an openwhisk package registry/catalog
Like `wsk init --template https://github.com/csantanapr/openwhisk.git` or `wsk init --template ow-twilio-demo`

if the starting code is already inside the system then I would use `wsk clone namespace1/package1 or wsk clone namespace1/package1/entity1`

>we could call the latter one e.g. wsk clone
Yes I like both terms don't know which one to decide `clone` or `fork`. I think `clone` makes more sense since it's just I want a copy, no intention to do SCM and contribute back.

**Comment by sjfink** [comment]
Just to be clear (at a high level for now, don't worry about details}:

 'wsk clone/init/fork' should be equivalent to a sequence of 2 commands along the lines of 'wsk action get; wsk action create'

**Comment by mbehrendt** [comment]
i agree

**Comment by rabbah** [comment]
@csantanapr with `wskdeploy` and other discussion around deploying repos, is this issue still of interest?

**Comment by csantanapr** [comment]
yes leave open as this issue is related to scaffolding with a template from a giturlsample

**Comment by rabbah** [comment]
@csantanapr is there an appropriate issue then to consolidate this with?

**Comment by rabbah** [comment]
@csantanapr is there an appropriate issue then to consolidate this with? Or should it be in the wsk deploy repo instead?

**Comment by csantanapr** [comment]
@rabbah yes I think this requirement needs to be moved to whisk deploy

@paulcastro Want to to capture the requirements from this issue and move to the whisk deploy repo?

**Comment by rabbah** [comment]
I'm going to close this as `wskdeploy` is a more general approach.
