### ISSUE TITLE
Controller does't return json with encoding header 'Content-Type=application/json; charset=utf-8'

### ISSUE THREAD

**Issue by ysjjovo** [apache/incubator-openwhisk#4433]
Controller return json using code 'complete(OK, response)',the 'Content-Type' header value is 'application/json',without charset parameter,but some client will use a default charset(ISO-8859-1) when charset parameter not given.

**Comment by rabbah** [comment]
The default encoding is utf-8 for json iirc. Which client are you using?

**Comment by ysjjovo** [comment]
> The default encoding is utf-8 for json iirc. Which client are you using?

'InputStreamReader' class will use default charset if constructor don't pass charsetName,but default charset is't 'utf-8' in windows operating system of some other language country,such as chinese edition,it's 'GBK' by default.So we should provide it explicitly.
