### ISSUE TITLE
Trigger deleted even though the feed failed during deletion

### ISSUE THREAD

**Issue by tareqmamari** [apache/incubator-openwhisk#444]
I have a trigger and a feed associated to it, after I successfully created the trigger, I wanted to delete the trigger, thus, the feed will be executed with lifecycleEvent = 'DELETE' in order to handle  deletion of event producer webhook, whenever the feed deletion life cycle is failed, the trigger will be deleted anyway which will lead to lose control on the services controlled by the feed ( resources used by the webhook).

e.g. : imagine the Github feed is successfully created , if you want to delete it ( assumption:  deletion lifecycle is implemented within github webhook feed) and the feed is failed during the deletion , the feed ( trigger ) will be deleted anyway, so I have to delete the webhook manually which is a lose of control through Openwhisk

`error: failed to delete trigger feed rtiFeed but did delete the trigger
`

Is that unwanted behaviour ?

**Comment by rabbah** [comment]
The intention when you delete the feed is to stop the trigger from firing, that is why the trigger is deleted even if the life cycle manager fails.

Your point is valid about having to delete it manually, we should make it easier to retry deleting the feed when it fails.

**Comment by tareqmamari** [comment]
should we add an additional flag to enforce deleting the trigger whenever the feed fails ?

**Comment by rabbah** [comment]
@dubeejw is this fixed now?

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #158](https://github.com/apache/incubator-openwhisk-cli/issues/158) via [**ZenHub**](https://www.zenhub.com/)
