### ISSUE TITLE
wskadmin is not python3 compatible

### ISSUE THREAD

**Issue by axiqia** [apache/incubator-openwhisk#4456]
## Steps to reproduce the issue:

`wskadmin syslog get controller0 `

## Provide the actual results and outputs:

```
Traceback (most recent call last):
  File "/home/sxue/bin/wskadmin", line 81, in main
    }[args.cmd](args, props)
  File "/home/sxue/bin/wskadmin", line 202, in syslogCmd
    return getLogsCmd(args, props)
  File "/home/sxue/bin/wskadmin", line 702, in getLogsCmd
    joined = ''.join(logs)
TypeError: sequence item 0: expected str instance, bytes found
```

## Additional information you deem important:
https://github.com/apache/incubator-openwhisk/blob/5a2bf810dc5fda2f0d184c022e5931ac65de9721/tools/admin/wskadmin#L690
In python 2, it return a `type 'str'`.  In python, it return a `calss 'bytes'`

https://github.com/apache/incubator-openwhisk/blob/5a2bf810dc5fda2f0d184c022e5931ac65de9721/tools/admin/wskadmin#L708
In Python 2, `zip` returned a list. In Python 3, `zip` returns an iterable object.

**Comment by rabbah** [comment]
Thanks @axiqia for reporting this - are you interested in submitting a patch?

**Comment by rabbah** [comment]
Also found there's a difference in how argparse works in python 3 - where the `cmd` subparser isn't required as it is in python2 and leads to an indexing error. `cmd` is `None`, should report `usage` info.

**Comment by axiqia** [comment]
@rabbah  I'd like to ). Can we introduce new packages, such as six or future?
I have test with future in my branch.
The realtionship between six and future is [here](https://python-future.org/faq.html#what-is-the-relationship-between-future-and-six).

**Comment by rabbah** [comment]
Great @axiqia!

My preference would be to avoid six/future - for the two cases you reported, I'd think you can `byte.decode('utf-8')` and wrap the iterable with a `list` to bring up the code to python3 level.

Since python 2 is retiring, being entirely on python 3 is 👍
