### ISSUE TITLE
Passing parameters to trigger when deleting it

### ISSUE THREAD

**Issue by tareqmamari** [apache/incubator-openwhisk#446]
As the trigger delete command will invoke the feed with 'DELETE' lifecycle parameter, I couldn't  pass additional parameters such as the credentials needed in order to delete the resources ( services ) used by the feed.

Is there any alternatives where can I pass additional parameters to the feed in the trigger delete command ?

Thanks

**Comment by rabbah** [comment]
This is related to #471. As a work around, you can run the feed directly. Did you try that?

**Comment by tareqmamari** [comment]
Only the package parameters of the feed are passed.

> As a work around, you can run the feed directly. Did you try that?
Yes I did and it works well

**Comment by csantanapr** [comment]
closing as authkey is passed on all lifecycle feed invokes
