### ISSUE TITLE
Installing Distributed openwhisk

### ISSUE THREAD

**Issue by alibanaei** [apache/incubator-openwhisk#4470]
Why there is no documentation to install openwhisk in a distributed way
I found some links but they are all 404 :(
I have two servers with ubuntu 14.04
how can I install openwhisk on them?
Does it need two controllers?
Should I use the local deployment again?
What should I install on the master machine and what else on the slaves?
your documentation is so weak on this issue

**Comment by rabbah** [comment]
@alibanaei old links that you found were to unsupported and rotted docs. Can you share the links if they originate from our github so we can fix them?

If you're using VMs, you can deploy to multiple VMs by changing the IPs in the host file as in https://github.com/apache/incubator-openwhisk/blob/master/ansible/environments/jenkins/openwhisk-vm1-he-de.j2.ini and use ansible to deploy.

**Comment by alibanaei** [comment]
Thanks a lot
It's the link I found in some problems in Stackoverflow 
https://github.com/apache/incubator-openwhisk/blob/master/ansible/README_DISTRIBUTED.md

But I appreciate if you complete the documentation for distributed deploying as this link
https://github.com/apache/incubator-openwhisk/blob/master/tools/ubuntu-setup/README.md
@rabbah
