### ISSUE TITLE
Is there any periodical heartbeat checking between controller and multiple invokers? 

### ISSUE THREAD

**Issue by YangZhou1997** [apache/incubator-openwhisk#4473]
I have seen OW removes the consul components long before. So how does OW controller monitor the status of invokers? 

I do see there are several /whisk.system/invokerHealthTestAction0 actions running in the starting phase of each invoker. But it seems no further checking functions afterward (maybe I miss some of the code in controller side). 

Just curious about that; any comments are highly appreciated

**Comment by markusthoemmes** [comment]
The invokers continuously send pings via Kafka which are read and analyzed by the controllers.

**Comment by YangZhou1997** [comment]
Thanks for the comments! 
One puzzle I remained is how to create a new topic and specify the topic parameters in Kafka. 

I went through the controller source code and find msgProvider.ensureTopic() in KafkaMessagingProvider.scala creates topics in Kafka. But I find it hard to figure out how loadConfigOrThrow() in KafkaMessagingProvider.scala is implemented. Does it read the configuration file from zookeeper or locally? 

The thing is that: when I tried to create a new topic (ie, new topic name) using msgProvider.ensureTopic(), the logs in controller show that the configuration mapping for the new topic is not found and crashes the controller.

**Comment by markusthoemmes** [comment]
@YangZhou1997 `loadConfigOrThrow` is local configuration reading for our Scala components. See https://github.com/pureconfig/pureconfig for reference.

The default config can be found here: https://github.com/apache/incubator-openwhisk/blob/master/common/scala/src/main/resources/application.conf

**Comment by dgrove-oss** [comment]
Closing as answered by Markus.
