### ISSUE TITLE
Unable to connect to controller0 while running openwhisk.yml (local deployment), Connection refused!

### ISSUE THREAD

**Issue by alibanaei** [apache/incubator-openwhisk#4485]
I have an issue like https://github.com/apache/incubator-openwhisk/issues/4303
when I run ansible-playbook openwhisk.yml
but I got this Error in the controller log file
I asked there but got no answer
What should I do?

---------------------------------------------------------------------
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
Error: Password file not found: /home/owuser/jmxremote.password
sun.management.AgentConfigurationError
at sun.management.jmxremote.ConnectorBootstrap.checkPasswordFile(ConnectorBootstrap.java:563)
at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:426)
at sun.management.Agent.startAgent(Agent.java:262)
at sun.management.Agent.startAgent(Agent.java:452)
----------------------------------------------------------------------

and when I use "wskdev controller", it didn't create the log file

**Comment by style95** [comment]
It seems it could not find the password file for `jmxremote`.

Isn't there the file in your setup?

Outside of the controller container: `${OPENWHISK_CONF_DIR}/${controllerN}/`
or
Inside of the controller container: `/home/owuser/`

That file is supposed to be generated based on the ansible template while deploying controllers.
https://github.com/apache/incubator-openwhisk/blob/master/ansible/roles/controller/tasks/deploy.yml#L46

**Comment by alibanaei** [comment]
Actually these files exist   "/config/wskconf/controller/controller0"  directory
 - controller-openwhisk-keystore.p12
 - controller-openwhisk-server-cert.pem
 - controller-openwhisk-server-key.pem
 - jmxremote.access
 - jmxremote.password

and the status of "controller container" is "Restarting (1) 14 seconds ago"
It's just restarting again and again
And Config directory has 0777 permission
Is there anything that I should do inside of the controller container or somewhere else?

**Comment by style95** [comment]
Is the volume properly mapped for controller0?
And what is the file permission of the files?

**Comment by alibanaei** [comment]
Could you please explain more detail?
I didn't find any problem with volume and permission.
I've installed OpenWhisk on two different systems before, but I didn't have this problem
Why it's looking for "jmxremote.password" in "home/owuser" directory?
Shouldn't it look for in "Config Directory"?

**Comment by style95** [comment]
Yes. That's right.
But the controller process will look for the file from `/home/owsuer`.
https://github.com/apache/incubator-openwhisk/blob/master/ansible/group_vars/all#L114

And "Config directory" is mapped into `/home/owuser` directory in a container.

**Comment by style95** [comment]
It's copied at bootup time.
https://github.com/apache/incubator-openwhisk/blob/master/common/scala/copyJMXFiles.sh#L21

**Comment by alibanaei** [comment]
Thank you for all your help 
Well I checked everything, the config file is ok and the jmx files exist with true permission
but it can not map it into the container, maybe the owuser is not created
and it can't lunch the container properly

is it ok if I change this [commit](https://github.com/apache/incubator-openwhisk/commit/f7afa71b1156ea193fc1df4bfcdf39fdb64a50c5) to the root?

------------------------------------------------------------------------------------------------------
Docker PS:
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                          PORTS                                                                    NAMES

d7c6191efcbe        whisk/controller:latest       "/bin/sh -c 'exec /i…"   3 hours ago         Restarting (1) 10 seconds ago                                                                            controller0

25dfed4727f4        wurstmeister/kafka:0.11.0.1   "start-kafka.sh"         3 hours ago         Up 3 hours                      0.0.0.0:9072->9072/tcp, 0.0.0.0:9093->9093/tcp                           kafka0

a0021756460a        zookeeper:3.4                 "/docker-entrypoint.…"   3 hours ago         Up 3 hours                      0.0.0.0:2181->2181/tcp, 0.0.0.0:2888->2888/tcp, 0.0.0.0:3888->3888/tcp   zookeeper0
------------------------------------------------------------------------------------------------

**Comment by alibanaei** [comment]
Thank you for all your help
I reinstalled docker and it's worked
