### ISSUE TITLE
国外文凭办理精英国际文凭俱乐部办理国外文凭,澳洲文凭办理,英国文凭办理,加拿大文凭办理,美国文凭办理

### ISSUE THREAD

**Issue by ghvfsdasdu** [apache/incubator-openwhisk#4544]
## Environment details:

* local deployment, vagrant, native ubuntu, Mac OS, Bluemix, ...   
* version of docker, vagrant, ubuntu, ...

## Steps to reproduce the issue:

1.   
2.   
3.   

## Provide the expected results and outputs:

```
output comes here
```

## Provide the actual results and outputs:

```
output comes here
```

## Additional information you deem important:
* issue happens only occasionally or under certain circumstances   
* changes you did or observed in the environment
[国外文凭办理](https://www.diplomaclub.net)[精英国际文凭俱乐部](https://www.diplomaclub.net/gwdiploma)办理国外文凭,澳洲文凭办理,英国文凭办理,加拿大文凭办理,美国文凭办理[www.diplomaclub.net](https://www.diplomaclub.net)

**Comment by houshengbo** [comment]
@ghvfsdasdu 禁止发广告，否则禁言！
No commercials!!!
