### ISSUE TITLE
make quick-start doesn't work

### ISSUE THREAD

**Issue by SamChb72** [apache/incubator-openwhisk#4549]
## Environment details:

* local deployment native ubuntu 
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-52-generic x86_64)

* version of docker, vagrant, ubuntu, ...
Docker version 18.09.7, build 2d0083d

## Steps to reproduce the issue:

1.   make quick-start

## Provide the expected results and outputs:

```
make should compile
```

## Provide the actual results and outputs:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134    0   134    0     0    558      0 --:--:-- --:--:-- --:--:--   558
100 14.6M  100 14.6M    0     0  2244k      0  0:00:06  0:00:06 --:--:-- 2328k
Unpacking tarball.
downloading the CLI tool ... 
downloading cli for linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626    0   626    0     0   2608      0 --:--:-- --:--:-- --:--:--  2608
100 3853k  100 3853k    0     0  1522k      0  0:00:02  0:00:02 --:--:-- 2348k
Using default tag: latest
Error response from daemon: manifest for openwhisk/controller:latest not found
Makefile:114: recipe for target 'docker-pull-lean' failed
make: *** [docker-pull-lean] Error 1
```

## Additional information you deem important:
* issue happens only occasionally or under certain circumstances   
* changes you did or observed in the environment

**Comment by rabbah** [comment]
Thanks @SamChb72 - I opened https://github.com/apache/incubator-openwhisk-devtools/pull/270 to address.

**Comment by rabbah** [comment]
@SamChb72 please update devtools and try again.
