### ISSUE TITLE
make failes with `Error response from daemon: manifest for openwhisk/controller:latest not found`

### ISSUE THREAD

**Issue by axelrose** [apache/incubator-openwhisk#4551]
The current `incubator-openwhisk-devtools/docker-compose/Makefile` doesn't specify the docker image version and therefore uses the default `latest` version.

But since there seems to be no longer an `latest` image the build failes consequentially with 
```Error response from daemon: manifest for openwhisk/controller:latest not found```

As a workaround I can continue with this change in Makefile.
```
.PHONY: docker-pull-lean
docker-pull-lean:
	docker pull $(DOCKER_IMAGE_PREFIX)/controller:nightly
	docker pull $(DOCKER_IMAGE_PREFIX)/nodejs6action:nightly
	docker pull $(DOCKER_IMAGE_PREFIX)/dockerskeleton:nightly
```

[edit] the addition of ':nightly' is needed at various other places in the Makefile and in docker-compose.yml

**Comment by rabbah** [comment]
Thanks for reporting this. This Pr should address it https://github.com/apache/incubator-openwhisk-devtools/pull/270.

**Comment by axelrose** [comment]
It's corrected in latest revision. Thanks for the quick reaction!
