### ISSUE TITLE
Feed should be able to store state info

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#471]
From reporter:
The github/webhook action creates a webhook if params.lifecycleEvent == CREATE. The response from Github is the ID of the webhook created there as well as the url pointing to it. Currently, there is no established way to store such information in order to be able to delete it later. A solution could be that we store the url in annotations but I'm not sure that is the right way to go forward.

From @rabbah : 
 I think it may be relevant here. a feed creation could return values to store in the trigger so that on the next life cycle event, those values are sent as parameters with the request. This might solve the problem here if I understood it. If the values contain sensitive information, then they can be encrypted by the feed so they are treated as opaque values. A further refinement on this is to allow the feed to specify information it wants to receive back on the next life cycle event but also parameters to add to the trigger firing.

**Comment by rabbah** [comment]
Rethinking this: the feed has the trigger name and the API key. It can decorate the trigger any way it pleases. @csantanapr if you agree is this an issue at all then?
