### ISSUE TITLE
Avoid sequences to fail silently in case of compile errors within actions

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#474]
From @nauerz-ibm 
Sequences fail silently if there are compile errors within an action of the sequence.

@sjfink : This behavior was at least observed before InterConnect; close if the behavior has meanwhile be improved.

From @rabbah : 
we need unit tests for these kinds of bugs - this is a good way of starting to fix them.

**Comment by ioana-blue** [comment]
I think with the new implementation the sequence will not fail silently. I think the sequence will fail with the error returned by the "faulty" action, but if any "good" actions precede the faulty one, they will be executed. We need a test for this.

**Comment by rabbah** [comment]
A lot has changed with sequences.
