### ISSUE TITLE
Trigger update command doesn't run the feed

### ISSUE THREAD

**Issue by tareqmamari** [apache/incubator-openwhisk#481]
I am trying to update a trigger, but unfortunately the feed not executed

**Comment by sjfink** [comment]
could you post a sequence of commands that demonstrates the problem?

**Comment by rabbah** [comment]
A trigger update does not run a feed - only the trigger create does.

**Comment by sjfink** [comment]
What is the correct behavior for trigger update when tied to a feed?

I would expect it to DELETE and CREATE the feed.    Comments?

**Comment by tareqmamari** [comment]
As update doesn't execute the feed, how it can be helpful ? 

**what I have done :**
$ wsk trigger create RTIFeed --feed /namespace/iotrti/webh -p condition 'schema.value>1' 
ok: created trigger feed RTIFeed

$ wsk activation list
a11c18d9eae148179160b91c9d4ec455             webh

$ wsk trigger update RTIFeed -p condition 'schema.value>2'
ok: updated trigger RTIFeed

$ wsk activation list
a11c18d9eae148179160b91c9d4ec455             webh

from the activation list, the feed has not been executed when I used the update command !

**Comment by bjustin-ibm** [comment]
👍 on this from me as well.

Without really understanding the guts of how triggers work, I fully expected `wsk trigger update` to just work. In my scenario, I was trying to change the `cron` parameter of an Alarm trigger.  I suppose that could mean running `DELETE` and `CREATE` as @sjfink suggests.

**Comment by csantanapr** [comment]
This is now fixed, CLI will invoke feed action on update.
