### ISSUE TITLE
Provide /info API for ops/running system metadata

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#547]
Based on feedback from @mbehrendt 

/info
can provide software versions and other related endpoints
This is useful particularly to know thru the API the version of openwhisk that it's running.
In the current case it can be a commit hash and git source combination

Other's have similar /info like [CF](https://apidocs.cloudfoundry.org/237/info/get_info.html) and [Bluemix](http://api.ng.bluemix.net/v2/info)

For example
GET <openwhisk-endpoint>/v1/info

```
"name": "openwhisk",
"support": "https://github.com/openwhisk/openwhisk/issues",
"version": 1,
"description": "OpenWhisk",
"authorization_endpoint": "http://localhost:8080/uaa",
"token_endpoint": "http://localhost:8080/uaa",
"min_cli_version": null,
"min_recommended_cli_version": null,
"api_version": "1.0.0",
```

openwhisk operators can add extend with their own property

```
"acmecorp":{
    "build_date": "2016-05-24T09:54:44-05:00",
    "build_id: "17988",
   "openwhisk_source":"https://github.com/openwhisk/openwhisk#3b8c969399a9aa637e1c1a483415236bc80088ca"     
},
```

openwhisk should provide an easy way for operator's to create a file with json metadata to be merged

cc @jeremiaswerner

**Comment by nwspeete-ibm** [comment]
https://github.com/openwhisk/openwhisk/pull/1333 WIP

**Comment by rabbah** [comment]
We have `/` and `/api/v1` both returning deployment info.
