### ISSUE TITLE
Add ability to list only feeds with CLI

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#575]
A feed is an action with a feed=true annotation.
We can enhance the `wsk action list` to filter for feeds like `wsk action list --feed`

Another alternative is to treat feed as first class objects, and have a `feed` command like  `wsk feed list`

Making a the new command:

```
$ wsk action -h
usage: wsk feed [-h] {create,update,get,delete,list} ...

optional arguments:
  -h, --help            show this help message and exit

available commands:
  {create,update,invoke,get,delete,list}
    create              create new action
    update              update an existing action
    get                 get action
    delete              delete action
    list                list all actions
```

cc @mbehrendt

**Comment by mbehrendt** [comment]
to list feeds, a developer using whisk should *never* have to know that feeds are implemented as actions (actions are just impl choices). an event provider creating feeds has to know that, but not a regular user.

i'd suggest to either expose feeds as a first class entity or allow listing them with a parameter to `wsk package list`, eg `wsk package list -feeds`

**Comment by csantanapr** [comment]
Hum `wsk package list` feels wrong, this command it's about listing only packages, `wsk package get $name` or `wsk package get $name --summary` it's about list the package content.

This will get you the summary of the specified package like:
```
$ wsk package get myGit --summary
package /csantana@us.ibm.com_dev/myGit
 feed   /csantana@us.ibm.com_dev/myGit/webhook: Creates a webhook on github to be notified on selected changes
```
What about `wsk list` listing feeds?

Today it `wsk list` prints a summary for `packages` `actions` `triggers` and `rules` but it doesn't list `feeds`

for example the `feed` `/csantana@us.ibm.com_dev/myGit/webhook`
Can be listed very easily with `wsk list` like this:

```
$ wsk list
```
entities in namespace: csantana@us.ibm.com_dev
**packages**
/csantana@us.ibm.com_dev/myGit                                    private binding
**actions**
/csantana@us.ibm.com_dev/echo                                     private
**triggers**
/csantana@us.ibm.com_dev/myGitTrigger                             private
**rules**
/csantana@us.ibm.com_dev/ifGitThenEcho                            private
**feeds**
/csantana@us.ibm.com_dev/myGit/webhook                                   private

**Comment by markusthoemmes** [comment]
If `wsk list` lists feeds, I as a user expect to be able to do something like `wsk feed get` as I can do that with all the other entities. That'ld strenghten @mbehrendt 's point of having feeds as first-class entities, at least on CLI level.

**Comment by csantanapr** [comment]
I'm in agreement that it should be first class citizen and on top of that also be listed in `wsk list`

The bigger question is should the REST API supports them as first class citizens not just the CLI?

**Comment by rabbah** [comment]
no.

**Comment by csantanapr** [comment]
I our emoji voting 😄  in https://github.com/openwhisk/openwhisk/issues/575#issuecomment-224343620 seems to indicate that making them look like first class  will be handle client side (i.e. CLI, UI, etc..)

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #157](https://github.com/apache/incubator-openwhisk-cli/issues/157) via [**ZenHub**](https://www.zenhub.com/)
