### ISSUE TITLE
Discussion on how to handle swift libdispatch dependency for Swift

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#608]
This issue is related to the build break incident #600 and the #602 hotfix.

From @psuter https://github.com/openwhisk/openwhisk/pull/602#issuecomment-224913951

> We should consider depending on fixed commits in their history, I think. Pulling from the latest is a recipe for disaster as we've seen when they break it, and also for surprises when a sterilized build jumps over many versions at once due to Docker caching.
> 
> On the downside, it's more work for us to port their improvements, which are still frequent at this early stage of development for Swift on Linux.

**Comment by rabbah** [comment]
@paulcastro @csantanapr is this still valid?

**Comment by dgrove-oss** [comment]
I think this can be closed.  libdispatch is now included in the standard Swift binary releases on Linux so there should be no need for special handling.
