### ISSUE TITLE
Provide more flexibility with kind versioning

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#618]
We support the --kind on acton creation --kind <runtime>:<version>
Today we have nodejs 0.12.14 and 6.2.1

An user can use --kind nodejs:6 and it will use 6.2.1 or use --kind nodejs and it will use 0.12.14

As we add more nodejs environment in the future (i.e. 6.3.0, or 6.5.1, etc..)

We should allow user specify the <version> in flexible way using semantic versioning
Let's say that the following versions are available: 0.12.14, 6.2.1, 6.3.2, 7.0.1
User can specify:
 "6" -> will use 6.3.0
 "6.2" -> will use 6.2.1
 "6.3.0" -> will use 6.3.2
 "7" -> will use 7.0.1
" " -> will be the default of the system today, 0.12.14 but soon 6.2.1
You get the picture :-)

We could look into supporting ranges for the version, or specify the version in a package.json:engines in the future.

cc @sjfink @jasonpet @bjustin-ibm

**Comment by rabbah** [comment]
I think we should opt for less magic - that said, pr #1974 will make it possible to add kinds via a deployment manifest, and provides a canonical place to resolve versions in the [`ExecManifest`](https://github.com/openwhisk/openwhisk/blob/master/common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala#L107).

**Comment by rabbah** [comment]
@csantanapr we're all setup for this. Close?

**Comment by csantanapr** [comment]
closing, less magic
