### ISSUE TITLE
Delete default parameters for actions and packages (and annotations too)

### ISSUE THREAD

**Issue by kolien** [apache/incubator-openwhisk#76]
Using the command line interface, is it possible to delete default parameters for actions and packages once they have been defined?

**Comment by rabbah** [comment]
Use `update` to define new prameters. These _replace_ existing ones.

**Comment by kolien** [comment]
A I understand it, this will replace existing parameters with new ones, but not delete them.

**Comment by rabbah** [comment]
That's true, from the CLI, you can replace but not delete. If you made a direct API call, you could delete and replace the parameters.

**Comment by sjfink** [comment]
Proposal : add a -dp flag to wsk action update which means "delete parameter".

Comments?

**Comment by rabbah** [comment]
@dubeejw @mdeuser FYI.

**Comment by ioana-blue** [comment]
Somewhat related to this: updating parameters is not additive, an update to the action code doesn't seem to remove the default param values.

**Comment by rabbah** [comment]
when you update an action with new code, and don't specify any parameters, the POST looks like this `{ exec: ...}` and not `{exec: ..., params: []}`. This is allow you to update exec but not remove annotations or parameters that are already attached to the action. The way to remove the parameters through the CLI will require a solution as suggested by @sjfink above.

**Comment by rabbah** [comment]
To allow incremental updates (add/delete) individual parameters and annotations, we need an API change. This may be best done as part of the "v2" of the API; we can treat parameters and annotations as subresources of the action as in `/api/v2/actions/ns/pkg/name/parameters`.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #161](https://github.com/apache/incubator-openwhisk-cli/issues/161) via [**ZenHub**](https://www.zenhub.com/)
