### ISSUE TITLE
Use redis as a distributed cache and dataplane

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk#788]
In-Memory caches of existing components (controller, invoker) need to be replaced by a distributed cache to support more sophisticated deployment topologies.

A dataplane is needed to be able to support larger payloads for actions and triggers, because these are currently limited by Kafka. We can use redis here aswell. Kafka is then used purely for handling controlplane messages.

First steps will include:
- [ ] Deploy a single redis co-located to the controller
- [ ] Implement dataplane vs. controlplane seperation

**Comment by psuter** [comment]
The separation into control and data planes seems largely orthogonal to the technological choices?

If the goal is sending large messages, doesn't it make more sense to configure Kafka in such a way that it can send large messages (possibly in chunks), or to use a messaging library that supports that?

It's not clear to me that a design where we emulate messages using a distributed cache as a store will be better. I don't see how it can positively affect latency, for instance.

I assume there are other, related, goals (such as having a consistent cache for the database, or keeping large payloads "off-heap" in the controller and/or the invokers while no containers are available). It would be good to list them explicitly.

**Comment by markusthoemmes** [comment]
Not applicable anymore. Control vs. dataplane discussion should move to a new issue.
