### ISSUE TITLE
Evaluate latency characteristics of a distributed cache

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk#899]
We currently use in-memory caching in the controller which kinda blocks scaleout. We're going to evaluate latency characteristics of the in-mem cache vs. a distributed cache (e.g. redis) vs. no cache at all to decide wether it's feasible to use a distributed cache in our usage scenarios.

**Comment by style95** [comment]
It would be great to consider distributed in-memory cache such as [Hazelcast](https://hazelcast.org/)

**Comment by markusthoemmes** [comment]
Not applicable anymore, we implemented distributed cache-invalidation.
