### ISSUE TITLE
wsk package refresh doesn't work

### ISSUE THREAD

**Issue by nheidloff** [apache/incubator-openwhisk#91]
I tried to follow the instructions https://new-console.ng.bluemix.net/docs/openwhisk/openwhisk_catalog.html#openwhisk_catalog_cloudant to use Cloudant. However wsk package refresh doesn't work. As a workaround I followed the steps in "Setting up a Cloudant database outside Bluemix".

```
Niklass-MBP:whisk nheidloff$ wsk property set --namespace niklas_heidloff@de.ibm.com_dev
ok: namespace set to niklas_heidloff@de.ibm.com_dev
Niklass-MBP:whisk nheidloff$ wsk package refresh
error: Malformed request, did you specify a bluemix namespace?
error: Malformed request, did you specify a bluemix namespace?
Niklass-MBP:whisk nheidloff$
```

**Comment by markusthoemmes** [comment]
Thank you for reporting this issue. The bug is actually not in the open source code base, but in bluemix-specific code. We’ll keep you updated on when a fix is rolled out so you can verify. Stay tuned!

**Comment by skaegi** [comment]
I'm unfortunately hitting this too -- many months later -- while going through the getting started doc. 

I actually want to understand the auto-binding (or perhaps service keys)  behaviour that's happening here so I can use it in my own packages. Is that part the bluemix-specific bit?

**Comment by markusthoemmes** [comment]
Hi @skaegi,
yes, currently that's Bluemix specific code and you're right, that the auto-binding behaviour is not yet documented.

For this issue respectively the only "workaround" is to use an Org/Space combination in Bluemix where there are no `_` present in either organization or space name.

Auto binding in a nutshell:
Check the [script to install the weather package](https://github.com/openwhisk/openwhisk/blob/master/catalog/installWeather.sh#L15). It provides a parameter `bluemixServiceName` which is the service_name used in CloudFoundry (`weatherinsights`) in this case.
That value is actually the `label` attribute of said service in CloudFoundry, which can be obtained using the [CF Services API](https://apidocs.cloudfoundry.org/241/services/list_all_services.html) against Bluemix. In this case, call `GET https://api.ng.bluemix.net/v2/services` and search for the service you need.

I hope that clarifies things a little bit, if not let us know!

**Comment by csantanapr** [comment]
@markusthoemmes is this still an issue or close?

**Comment by rabbah** [comment]
Closing - package refresh should be removed from Apache OpenWhisk as it has meaning.
