### ISSUE TITLE
Create a new withExternalConfigFile pattern for property test cases 

### ISSUE THREAD

**Issue by mdeuser** [apache/incubator-openwhisk#944]
Refactor test cases that make use of a separate property file to leverage a new withConfigFile pattern (similar to withAssetCleaner) to reduce the number of times we end up repeating create file, set env map, and delete file on error. This reduces the changes of forgetting a finally also.

**Comment by csantanapr** [comment]
Issue moved to [apache/incubator-openwhisk-cli #155](https://github.com/apache/incubator-openwhisk-cli/issues/155) via [**ZenHub**](https://www.zenhub.com/)
