### ISSUE TITLE
When a trigger gets fired be able to find out what happened

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#966]
## Steps to reproduce the issue:
1.   create a trigger let's say "stockTrigger"
2.   create an action let's say "processStocks"
3.   create a rule let's say "rule_stock_process"
4.   Fire the trigger `wsk trigger fire stockTrigger '{"IBM":200}'`
5.   Got an activation id for the trigger fired
   `ok: triggered stockTrigger with id 0664eece37574a1288514dddcc3730ee`
## Provide the expected results and outputs:

Using trigger activation id `0664eece37574a1288514dddcc3730ee`
I should be able to find out all the rules that got activated (rule activations)
For each rule activation I should be able to find out the actions that got invoke (actions activations)
For each action activation I should be able to get the results and the logs.

Even if I can't get the rule activations, the net goal will be able to retrieve all the results and the logs for all activations, and the activations details (i.e. time spend, time ran, etc..)
## Provide the actual results and outputs:

No way to be able to achieve this with CLI or API
## Additional information you deem important:

This use case is important as a developer and operator of an app, I should be able to find out the net consequences when an event get's fired into the system, both for functionality but also for auditing and the net "cost" of a single event fired.

**Comment by csantanapr** [comment]
I think this is the reason that samples, and folks tend to call an action directly, rather than take advantage of triggers and rules, if a client app is develop and it's interface to the backend if emitting (firing) events/triggers then the client app will not be able to retrieve the results for the trigger that got fired. 

The benefit of using a trigger is the abstraction via rule, so client side doesn't need to know the name of the action, and the rule controls the abstraction.

**Comment by rabbah** [comment]
Related to #512.

Currently when a trigger matches a rule, the `caused` property of the rule activation will be the trigger's activation id. However, when the activator was re-architected, we lost the causality tracking between the rule and the action - so that the `caused` property in the action activation is empty (always).

**Comment by rabbah** [comment]
The commits 9ededdf82210682726f8800b2c02e68e3234efdf and b20778f37e052893818c3c39f0307783d7e5024a provide activation ids for the actions to permit tracking. Further enhancements to populate the action activation with a caused field will be possible when the posts are done internally. But we have enough to satisfy the request in this issue.

**Comment by csantanapr** [comment]
About time !!! 19 months

**Comment by csantanapr** [comment]
I don't even remember writing this issue 🤒
